### ISSUE TITLE
 Root αγ(α) needs  to be written with parentheses. Thanks.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#102]

**Comment by edouardchiricat** [comment]
Dear Sophie,
Right now we have a problem with the modification of a root already edited.
It's a recent issue: now you  trying to fix something, that issue is fixex
but there a collateral damage to another function that stops working
correctly.
Magdalena is working on it and I hope that soon we will be able to modify
αγα into αγ(α)

Édouard

**Comment by Hippodamie** [comment]
Many thanks to both. 
Excuse me for some contradictions in my requests, but there are things that become evident because of your beautiful interface. 
Another point is that we discuss some questions between colleagues of the other french team and they sometimes answer with some delay.
So, do not modify today the title of Structure. We still do not all agree about the title of the column and neither do we about the new label Participle.

I come back to you today only if you have questions and if we are totally OK with Structure and Participle. 

I was thinking if it could be a good thing to  create an autocompleting menu with already many titles of the References column. For this job, you could help you also with the references we had begun to list, that are on the document on Google docs. They are, I know, classified there by name and not by references. It is in order to quote references always exactly the same way.

Good work.
Best regards,
Sophie

**Comment by edouardchiricat** [comment]
Dear Sophie,
The autocomletion already works at that level: once eg. HPN is input in the
reference field, it will show up in an autocompletion list each time you
tipe H in the linguistic references fiels.

Édouard

**Comment by tuurma** [comment]
Fixed
