### ISSUE TITLE
To spare space in Lexis & References columns, delete s. vv. & s. n.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#104]
More simply write:
DELG ἀγα-, ζῆλος.

Οnom Thrac 1 Ἁβρόζελμις

**Comment by tuurma** [comment]
This is mostly for @edouardchiricat and other collaborators entering the data. It makes sense perhaps for you to create a document describing your editorial policy that would include this rule? Closing the issue here as it is not directly relevant to our application.

**Comment by Hippodamie** [comment]
OK; thanks, Magdalena.
