### ISSUE TITLE
Adding an optional descriptive label in Lexis (#36), for example "Possessive". In the last line.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#105]
PRESENTATION/VISUALIZATION of the fullest Lexis box (rare with so many informations):

Cf. Αἴνετος.
ὡς πάντα σφι ἀγαθὰ 
ὁ Τρηχίνιος ξεῖνος ἀγγέλλοι.
Ηdt. 7.226.8. 
ἄγγελος γὰρ ἀγαθὸς συμπορεύσεται αὐτῷ.
Sept. Tobias 5.22.1. 
Cf. Thgn 163.
DELG s.vv. ἀγαθός, ἄγγελος (Logeion) 
CEG 2 (1997)&11 (2006), s. vv. ἀγα-, ἀγαθός 
Beekes, EDG, s. vv.
Possessive.

The different descriptive labels will be : Possessive, Determinative, Verbal, Hypostatic (maybe more to be added during the work), and we will sometimes not write anything. Could be written : (Possessive) if it is clearer. But in a special line.

**Comment by tuurma** [comment]
Can I ask what would this mean? Looks like some kind of typology for the name? We could add a drop-down list with options you listed somewhere in the main form (eg. in the first line, next to Latin form, plenty of space to fit another box). Would at most one selection from the list be sufficient or do you foresee selecting 2 categories at the same time?
Thinking about the proper form control for it but also about the underlying TEI structure.
