### ISSUE TITLE
It is now impossible to add new entries or modify existing ones. We're out of bussiness !!!!

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#106]
If you open a new entry, you input all the informations and hit Save, there is a message 'Failed to save data' and the entry is not on the Visualisation page.
Same error message when you try to modify something

**Comment by tuurma** [comment]
Guess it was connected with #103, because now added a new entry without trouble.

**Comment by edouardchiricat** [comment]
It still doesn't work for me.

Édouard

**Comment by tuurma** [comment]
The file naming policy is to use Latin transliteration for file names. Roughly 80% of names contain macrons, which since recent update of eXist leads to trouble on saving, here's a test case:
```
let $data := <test/>
let $name := 'Aganōr'
return 
    doc(xmldb:store('/db/apps/lgpn-data/data/ling/names', concat($name , ".xml"), $data))
```
which throws 'malformed input or input contains unmappable characters' error. @wolfgangmm can you help?

**Comment by tuurma** [comment]
looks like Unix configuration issue
the trick is to do export LC_ALL="en_US.UTF-8" before starting the shell

**Comment by edouardchiricat** [comment]
Dear Magdalena,
Something very, very strange:
Immediately after I saw your message, I wanted to open the entry Aganōr.
error message: Failed to open data. I checked other names with macron and
made sure the the modifications can be saved. So, OK.
But when I wanted to go back to Aganōr, I realised thet it simply
dissapeared!!!

Édouard

**Comment by tuurma** [comment]
Poor Aganor, will check :)

**Comment by tuurma** [comment]
Sorry, my fault, used his name for testing and accidentally substituted the file. Now restored.

**Comment by edouardchiricat** [comment]
Thank you, Magda!

Édouard

**Comment by Hippodamie** [comment]
Aganor rescued : ouf !!!
