### ISSUE TITLE
Changes in column Structure (1). Multi-connection beween R1, R2 & structure labels

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#112]
It does not work with only one label per Root. I tried to make it coherent to make it easier for Magdalena. And Edouard asked me previoulsy to be sure, I remember. But we are wrong if we work in this way.
The structure must be the structure of the name and not the structure of the roots.

We need for example R(1 & 2) αιν (Ag-ainetos) be connected with 3 labels : V (to come back), N & Adj.
And to be able to Search : αιν combined with Adj ; αιν combined with V ; αιν combined with N. And αιν combined with Αdj + V + N.
In Ag-ainetos, R2 αιν will be connected with Adj.
In Ainesi-damos, R1 αιν will be connected with V(erb)
In Xén-ainos, R2 αιν will be connected with N. 

The column has to be called Structure, nothing more. But the next column : Roots semantics/Sens des radicaux.

**Comment by tuurma** [comment]
Do I understand it right that we are basically reverting to initial design, with possibility to select function for every root in a particular name?

**Comment by Hippodamie** [comment]
Yes, Magdalena.
For exple, the same root αιν will have sometimes the function of Adj, sometimes of V and sometimes of N.

**Comment by Hippodamie** [comment]
Yes, Magdalena. Sorry for that.
Have a good day.
Best regards,
Sophie

**Comment by edouardchiricat** [comment]
Yes, Magdalena,
This is what I told you yesterday morning by 'unlink root from its
structural value in the root edit interface'.
WIth best wishes,
Edouard


Édouard

**Comment by edouardchiricat** [comment]
But I saw yesterday evening that you already did it!
Many thanks indeed.

Édouard
