### ISSUE TITLE
category marker for hypotheses

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#114]
We would like that after, for example Adv+Adj, we could add between parentheses, only for the 2 Roots names and not for all of them, 1 (and only 1) of the 4 different labels :
P(ossessive)
D(eterminative)
H(ypotactic)
A(syntactic)

It would then look like: Adv + Adj (P), for example.

**Comment by tuurma** [comment]
Ok, so basically this is #105, but moved to another column, do I understand it right?

**Comment by Hippodamie** [comment]
Yes , exactly : delete my #105 request. Put the same information with abbreviations like (P) in the Structrue column. 
Thanks,
Sophie

**Comment by Hippodamie** [comment]
Coming back to this request of a week ago and explaining the scheme.
We would like that after, for example Adv+Adj, we could add between parentheses, only for the 2 Roots names and not for all of them, 1 (and only 1) of the 4 different labels :
P(ossessive)
D(eterminative)
H(ypostatic)
A(syntactic)

Connections would work in the following way:
(P)ossessive = N,Adj, Adv, Pro + N (I mean 4 possibilities of couples)
D(eterminative =V,N,Adj, Adv, Pro + N,Adj, Adv, Pro (each of the 5 could be connected with each of the 4 following)
H(ypostatic) = Adv + N    or   Adv +Adj.
A(syntactic) = V,N,Adj, Adv, Pro + N,Adj, Adv, Pro (each of the 5 could be connected with each of the 4 following).
Same scheme to build for D and A. Is it impossible ? The difference for us is that for A, R1 + R2 does not mean as a clause or as a phrase, whereas for D, it means.

**Comment by Hippodamie** [comment]
Improved version (finished).
Scheme would be the following:
(P)ossessive = N,Adj, Adv, Pro + N (I mean 4 possibilities of couples)
D(eterminative =V,N,Adj, Adv, Pro + N,Adj, Pro (each of the 5 could be connected with each of the 3 following)
H(ypostatic) = Adv + N.
A(syntactic) = V,N,Adj, Adv, Pro + N,Adj, Adv, Pro (each of the 5 could be connected with each of the 4 following).

How many hours do you need to input that ? Or is it possible to input it in another milestone ?

**Comment by Hippodamie** [comment]
I saw a problem about Prefix in connection with Structure again, thanks to Epagathos.

For a next step:
Scheme should be the following:
(P)ossessive = N,Adj, Adv, Pref + N (I mean 4 different couples)
D(eterminative =V,N,Adj, Adv, Pref + N, Adj, Pro (each of the 6 could be connected with each of the 3 following)
H(ypostatic) = Pref + N.
A(syntactic) = V,N, Adj, Adv, Pref, Pro + N, Adj, Pro (each of the 6 could be connected with each of the 3 following).

**Comment by tuurma** [comment]
agreed to add a select box for every hypothesis in the Segmentation & root interpretation section with following single choice options

* Possessive
* Determinative
* Hypostatic
* Asyntactic
* Abbreviated Compound
* Nickname

**Comment by tuurma** [comment]
closing as we've agreed a different labelling system
