### ISSUE TITLE
Changes in column Structure (4): consequence on request "Possessive" (#105)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#115]
Delete request #105.

**Comment by tuurma** [comment]
Hi Sophie, if I understand right you want to cancel #105? If so, the best way is to open that issue and use the 'Close' button or 'Close and comment' if you want to add explanation.
Anyway it's a bit unclear to me should I do something with this one or not? Please explain or close it as appropriate :)
