### ISSUE TITLE
Correction needed : not ανδρ but αν(δ)ρ, see Aganor

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#117]

**Comment by tuurma** [comment]
Can I ask you to track issues related to the content of the database, not to the application itself (like the one here) in a separate repository? One of you @Hippodamie or @edouardchiricat can open new repository under your account and you can track these issues there. I'm happy to help setting this up.
Mixing data and application related stuff here means that I and all my colleagues at eXist have our mailboxes full of notifications which are not necessarily relevant to our work. Thank you for your understanding.
