### ISSUE TITLE
Semantics : ponctuation between 2,3 English/FRench meanings: substitute <,> for <;>

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#118]

**Comment by tuurma** [comment]
Please consider example of Agapyrrhos/Ἀγαπύρρος
`great; very+flamboyant, blazing red, reddish`
where the first root has two meanings `great` and `very` while the other only one meaning that nevertheless is described by 3 words `flamboyant, blazing red, reddish`
We have thus 3 kinds of separators: 
- `+` separates meanings of different roots, 
- `,` separates descriptions of single meaning and 
- `;` separates different meanings of a single root. 
If we follow your  request we will loose visual clue for the readers that allows them to distinguish between cases 2 and 3. Please consider this issue and let me know what I should do.

**Comment by Hippodamie** [comment]
If i do not do any mistake (Edouard, tell us), flamboyant is French and has nothing to do here !
Just keep, please: blazing red, reddish ; and write: great, very. Only commas every time. No more < ; >
So it is more simple than you thought, except if Edouard do not agree.
As we speak of Roots and not of words/lexems in this case, we will most often keep the most generic meaning(s) and not go further in descriptions of a single meaning. Here we distingusih color and color of the hair, which is a border-line case.
But even in the triple case of will, counsel, Council, commas are enough. No other hierarchization than the order, from the most generic to the most specific.

**Comment by tuurma** [comment]
ok, putting flamboyant there is my doing (as it is an English word as well, so I chose it as a label when entering this name)
Anyway, this case still shows the issue, as meaning of `πυρρ` is given as single meaning described as `blazing red, reddish` while `βο̄λ` has three separate meanings `will`, `counsel`, `Council` listed. Perhaps this is a rare case, but we still should handle it consistently.
On the other hand choice of separator is a minute change that can be done anytime so perhaps it's not worth thinking about it too much :)

**Comment by edouardchiricat** [comment]
Dear Magdalena and Sophie
For that root, you proposed the following equivalences:
blazing red = flamboyant
reddish = roux
But yes, I think it should be in English great, very + blazing red, reddish
In the word file, I used the  ( ; ) to separate the Engl and Fr. meanings
of a root and / as a boundary between two roots. The comma (,) used to
separate two French or two English meanings of a root.

Édouard

**Comment by edouardchiricat** [comment]
Indeed, Magdalena, you entered this name for testing purposes.

Édouard

**Comment by tuurma** [comment]
Thanks Edouard for explanations, fixed this particular example and changed the separator to `,` as requested

**Comment by Hippodamie** [comment]
OK, Magdalena, thanks !
