### ISSUE TITLE
Be careful : Prefix + R2 & Prefix + R1 + R2 but no Prefix + R1

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#121]
Example :  Ἄντ-οχ-ος Antochos
Pref: αντ  + R2 εχ(ε) (+ Suff4: -os). No R1. When Prefix & only one R, then R = R2.

But Ευ-άρχ-ιππ-ος = Pref + R1 + R2 (+ Suff4)

**Comment by tuurma** [comment]
Sorry, but I don't understand the practical consequences for our app?

**Comment by Hippodamie** [comment]
If we create an Advanced Search combining 2 criteria like: Pref. + R.
The other important 2-criteria will be of course 2 different R in any order.

When do you plan to work on the Search abilities ?

**Comment by tuurma** [comment]
I don't think this is an issue in practice, as for searching we have already discussed ways to make it general, not tied to exact position of a root, but I will keep it in mind. Closing for now as it's something for the LGPN app anyway.
