### ISSUE TITLE
add structural labels (N, V, Adv etc) for prefixes

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#127]

**Comment by tuurma** [comment]
Could you please describe what the issue is?

**Comment by Hippodamie** [comment]
Is it a problem for you, Magdalena, to have a two elements compound, with not 2 R but a Pref + R2 linked to 2 Structure labels like Adv + N ? Did you also planned for this situation ?

**Comment by tuurma** [comment]
Ok, I understand. It requires some changes to the main input form (extending 'prefix' section). Nothing terrible, but surely we don't have it covered in current form design.

**Comment by Hippodamie** [comment]
Thanks : I think that we will have thought in those few days at the main sources of troubles possible for the future Edition work, and rather quickly actually. It is a good thing that we had studied with Edouard enough names before.

What about issue #112 & 114  ? Not too much trouble for you, I hope ?

Best and very many thanks again,
Sophie

**Comment by tuurma** [comment]
not applicable anymore with #288 implemented
