### ISSUE TITLE
Error in date range

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#134]
For ῾Αβρωνίδης, the date range should be -357|-100, not -357|-200. The second century BC goes until -100.

**Comment by tuurma** [comment]
I believe this is not an error in retrieving data, but rather on the old website dates were rounded up to centuries or so. I propose to revisit this as we get back to recreating old website functionality and advanced search.

**Comment by tuurma** [comment]
This is a result of person entries impossible to date, thus having very broad date ranges. Since looking for a period of usage for the name I'm looking for the earliest and latest possible date attested for a name, this is where -999/+999 comes from.
