### ISSUE TITLE
A bug : a modification of data saved in the English interface, but not in the French

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#140]
Dear Magdalena,

I tried to modify for Agathagetos, in Structure, the second information : not Adv. but Adj. The first time I typed Pro and not Adj. I corrected. The modification is now ok in English (Adj + Adj), but not in French: Adj + Pro. And I cleared the window but nothing happened.

Thanks for your help.
Best,
Sophie

**Comment by edouardchiricat** [comment]
Accessing the site in French, I have (Adj + Adj). Sometimes one has to refresh several times before the lastest modifications are fetched.
This ticket should be closed.
