### ISSUE TITLE
Ordering of dialects labels in the visualization: not the same order as in Edit 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#142]
Please, we would like dialects being ordered in the visualization column not in the same order of the Edit interface (easier to find), but in an order choosen by the scholar (chronological), depending of each name.
For example, Koinai will always come after the other when they are several (or be alone), but all the other labels could come in any order. That means that positions 1,2,3,4,5 must be available for every label.
We need a maximum of 5 different labels/name to be ordered, from 1 to 5. If they are more than 5, we do not write anything. The most often, they will be only 2 or 3 per name.
I hope it is not too difficult and too long to make. 

Best,
Sophie

**Comment by edouardchiricat** [comment]
I would say it is practically impossible. What do you think, Magdalena?

**Comment by tuurma** [comment]
It would be a significant complication for editing interface, I'm afraid beyond what we can achieve in the time we have left for the current milestone.

**Comment by Hippodamie** [comment]
I understand.
Would it be possible to do it later ? And in which delay ?

Many thanks, Magdalena,
Sophie

**Comment by tuurma** [comment]
Do you have an idea how the input procedure could look like? If you could come up with a sketch of the required input elements perhaps?

**Comment by Hippodamie** [comment]
I still think about it. I come back to you as soon as possible. 

But I discovered that they are some bugs in Period : see Agathymos. It shows -375/-31, but if you look at the ancien Database you see : from 350BC to 143 BC. Why is it different?
Some -999/999 also to notice.
 
Thanks,
Sophie

**Comment by Hippodamie** [comment]
Too complicated for our work : I delete the request.
Thanks, you helped me to think about it.

**Comment by Hippodamie** [comment]
Finally, I ask only to put Koinai at the end of the list of the Dialects labels so that it comes always the last of the list in the visualization column.
Many thanks.
That's it.
Sophie

**Comment by Hippodamie** [comment]
And last but not least : just as for Koinai, move also Latin, after Koinai.
So, the list will end with : thessalian, koinai, Latin.

To Edouard also : I would have liked a label as Thereo-Cyrenean, but I do not know how to create it in  English. It would sound : théro-cyrénéen in French.
Could we transform the current "cyrénéen" in the new label and put it in its alphabetic place just before "thessalian" ?

Many thanks.
Best,
Sophie
