### ISSUE TITLE
Problem : Agamestor without macron is to delete (2 lines Agamestor with & without macron)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#144]
Hi, Magdalena.
Thanks.
Question : could we delete the entry ourselves by Edit ?

**Comment by tuurma** [comment]
I will open new issue to have 'delete' button

**Comment by edouardchiricat** [comment]
Dear Magdalena,
There is already such an issue opened by me two or three days ago.

Édouard
