### ISSUE TITLE
Request for the alphabetic order in Transliteration: all the initial <h> being (H) written.......

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#146]
We would like to see written (H)abreas, (H)abros, exactly as we have asked for the Roots (h)αβρ.

And that (H) does not be considered for the alphabetic order so that we have, for example:

Abba
(H)abreas
Agariste
Agathidas
(H)agetas
Autagathidas
Damainetos, etc.

Is it possible ?
Many thanks.
Sophie

**Comment by tuurma** [comment]
We would need to provide another input field for that, to store the form with parentheses. I understand that whatever part of the word will be in parentheses, this part should be ignored when sorting.

**Comment by Hippodamie** [comment]
Yes, exactly !

**Comment by tuurma** [comment]
7d3b988911be7e7086c8c5b106304161f19a17e9 should have taken care of that
