### ISSUE TITLE
add option to delete entries

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#148]

**Comment by tuurma** [comment]
Confirmation box is rather ugly and I will work on it some more if time allows. Please be aware that once you delete an entry it is final.

**Comment by Hippodamie** [comment]
Please, Magdalena, 

Could you give me an account ?
Many thanks,
Sophie

**Comment by Hippodamie** [comment]
PLease, cher Edouard, could you explain :
1°delete = tout ce qui concerne le nom disparaît ?
2°Pouvons-nous, par ailleurs, réécrire une case, si elle est mal remplie (par exemple, si on tape en grec, là où il faut du latin et vice versa) ?
3° A quoi servent les poubelles, à droite ?

Pourrais-tu, STP, faire le ménage des Cf. inutiles qui traînent ?

Merci d’avance.
Bien cordialement,
Sophie

**Comment by tuurma** [comment]
1. whole name entry is deleted
2. yes, you can just switch the erroneously entered data; if the contents of Greek/Latin box is altered this will result in new name entry being created and the wrong one can be just deleted afterwards
3. not sure what you mean? little 'bin' icons on the delete button? please reopen if anything still needs an explanation
