### ISSUE TITLE
Epagathos : Prefix + Adj. Possible to input Prefix in the Structure column ?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#149]
When names are made of Prefix + Root, it means a compound of 2 elements, in which Prefix has the same function as a Root1.
That is why we should be able to put in the column Structure : Prefix + N (or Adj or Adv or Pro).

They are a few cases where we will have Pref (only ευ),  Root1 & Root 2 (Eu-arch-ippos).
It would be perfect then to be able to put in Structure : Pref+ V(or N or Adj. or Adv) + N (or Adj. or Adv). 
But this request is not so important as the former.

My last change in #114 is due to this new problem.

But it is not the most urgent case to solve, Magdalena.
Many thanks for all the hudge work done this week.
Have a good week-end.
Best regards,
Sophie

**Comment by tuurma** [comment]
basically the same as #127, closing this one
