### ISSUE TITLE
EUREKA for Ep-agathos ! I found it alone ! Just tell me next week  if it seems correct for you

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#150]
Since:
1° Prefixes modify also the meaning (the ideas they convey could be summarized as:
+, —, >, <) and for example Ep-agathos means Hyper-good (good +);
2° Prefixes come sometimes before 2 Roots, but most often before one Root only;

I tried to enter επ(ι) (with exactly the form it has in the Prefixes List) as a Root1, and then αγαθ as a Root2.
I described it as an Adv ; and gave 3 different meanings.

And it works.

Question : do you think there will not be any bug with Greek forms being present in the Prefixes List AND also present and described as Roots with their meanings ?

You prepared and made your work wonderfully, Magdalena, if I can make this important change without bugs !!!

**Comment by tuurma** [comment]
Apologies for the delayed reply on this. You can enter your data like that, sure, though it blurs the distinction between prefixes and roots. I cannot possibly judge if it makes sense or not to treat meaning-bearing prefixes as some special case of roots. A practical consequence is: when searching for επ(ι) as a prefix, you won't be able to find entries where it was entered as a root and the other way around, and it may be potentially confusing for the users to find the same morpheme on the list of roots *and* on the list of morphemes (but perhaps that's ok). On top of that, for rare, (but existing if I understood you right?) cases of 2-root names with a prefix like that, you don't have a space to put it. Therefore I'd recommend an approach discussed in #127, which gives us a way to assign a structural information to a prefix, and, possibly, extend that to linking with morphemes and their meaning in the same way that roots are linked.
The change here is mainly in the input form as prefixes are valid morphemes, so the data representation of those and their meanings stays the same.

Let me know what you think.

**Comment by tuurma** [comment]
closing this as we have agreed on a different representation for preroots
