### ISSUE TITLE
Bugs to modify the meanings of Roots κρι(ν) and αρχ

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#151]
The names bugging are Agatho-kritos, Agath-archos & Arch-agathos.

Thanks for your help.

But I revised all the columns, except Lexis, and it works well.

I would like Edouard to explain me next week how to use the adding meanings function.

**Comment by edouardchiricat** [comment]
I adressed this issue for Sophie in  #163
