### ISSUE TITLE
Browse/edit/delete meanings

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#152]
Maybe add those functionalities in the adding meanings.

But this page is great : many, many thanks for that !

Best,
Sophie

**Comment by tuurma** [comment]
Quick solution to modify meaning for now is to edit its corresponding translations on any name with that meaning. It won't allow to delete unnecessary meaning, nevertheless it is not too much of a problem as we can always clean up unused meanings afterwards automatically.
