### ISSUE TITLE
Sometimes a modification on a Root does not seem to work automatically in both R1&R2 positions

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#153]
In connection with the previous issue on bugs on 3 Roots.
Sometimes, it worked doing the meaning modification in both positions , thus in 2 different names, successively. 

Thanks,
Sophie

**Comment by tuurma** [comment]
Haven't heard anything more on this, I suspect this is a question of refreshing the Visualization table. Closing.
