### ISSUE TITLE
A strange thing in the Edit Meaning window...

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#154]
It seemed to me one or two times looking at the EDit Meaning special window that, though they were meanings in the Visualisation, nothing was written in the cases of the Meaning.

But I do not remember for which name it happened.

Next time, I tell you exactly the name.

**Comment by tuurma** [comment]
As it was not confirmed so far, closing. Feel free to reopen with example of faulty behaviour if you encounter this issue again.
