### ISSUE TITLE
Problem trying to delete the entry Agatharion ... Help !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#159]
I did not succeed trying to delete it. 
Deleting, I saw strangly data in the meanings window that where connecteδ to hαβρ and not to αγαθ.

Is it possible to delete a name entry as a whole ?
In this special case, Agatharion does not exist, but Agatharin, yes.
I would like to totally delete Agatharion.

**Comment by tuurma** [comment]
There are entries for Agatharin, Agathariōn and Agatharion now, should I delete Agatharion? Working on deleting entries anyway, so it will soon be something you can easily do yourselves.

**Comment by Hippodamie** [comment]
Τhe only one to keep, please, Magdalena, is : Agatharin.
Best regards,
Sophie

**Comment by tuurma** [comment]
Thanks Sophie, done.
