### ISSUE TITLE
Other bug on αρχ : trying to enter a new meaning: be first/être le premier, before "command"

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#163]
For both names Agath-archos & Arch-agathos.

I save but it is not be saved as show visualization and as I can see coming back to Edit.

Thanks for your help !

Best

**Comment by Hippodamie** [comment]
Already #151. Sorry !

**Comment by edouardchiricat** [comment]
I explained Sophie that this is not a bug, and she has to fill the box 'Label" without spaces: be_first.
Issue to be closed.

**Comment by tuurma** [comment]
Brilliant @edouardchiricat, thank you!
