### ISSUE TITLE
LGPN-ling doesn't pick-up gender, att. and chronological information from the prosopographic database for many names

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#166]
Eg. Ἁβραγόρα, ῾Αβρέας, Ἁβραγόρας, Ἁβροτέλης, Ἁβρόμαχος, Ἁβροκόμας etc.

**Comment by tuurma** [comment]
same as #221, will close this one as a discussion of the issue is already there
