### ISSUE TITLE
To improve #36 : about Cf.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#168]
I took the Presentation below from #36, to show you the 2 Cf : one of them is maybe too much and difficult to encode 2 identic labels in two different places (?).
So, if it could be clearer, I propose:
-to keep the first Cf. (Αἴνετος);
-to put an &:  & Thgn 163 (when we want to refer but not to quote).

Anyway: Thanks, Edouard, to encode the Lexis column always in exactly this order : first coming the reference to another personal name or to another proper name (as a god epiclesis like Abaios, with sometimes a link), if there is one. 
And then, the quotation if there is one.
Order of informations in this multi-informations column must be systematical. If it is not the case, we will be oblige to delete and rewrite anytime, which will cause bugs. 

Many thanks, Magdalena and Edouard.
Best,
Sophie

PRESENTATION/VISUALIZATION of the fullest Lexis box (rare with so many informations):
To have a narrower column, is it possible to have not only 1 line for the quotation, but more superposed, and 1 different information per line, as:
Cf. Αἴνετος.
ὡς πάντα σφι ἀγαθὰ 
ὁ Τρηχίνιος ξεῖνος ἀγγέλλοι.
Ηdt. 7.226.8. 
ἄγγελος γὰρ ἀγαθὸς συμπορεύσεται αὐτῷ.
Sept. Tobias 5.22.1. 
Cf. Thgn 163.
DELG s.vv. ἀγαθός, ἄγγελος (Logeion) 
CEG 2 (1997)&11 (2006), s. vv. ἀγα-, ἀγαθός 
Beekes, EDG, s. vv.

**Comment by tuurma** [comment]
I'm not sure I fully understand this, as a general remark though: all changes to display here are quite trivial so we can easily make them a bit later, once I can have a chat in person with Edouard perhaps. Second: we can add labels like Cf or & preceding an entry automatically, so I'd strongly advise NOT to put them in 'reference' box as I noticed is sometimes the case now (see screenshot attached). We just need precise rules when I should generate such labels and when not, and reference box should contain strictly name/siglum of the resource only

![screenshot 150](https://cloud.githubusercontent.com/assets/449468/13250359/797ebbbe-da21-11e5-98b7-db715011f772.png)

**Comment by Hippodamie** [comment]
Perfect : you are right : thanks for explaining.

**Comment by Hippodamie** [comment]
PLease, have a chat with Edouard on the subject. I just told him.
I gave you the exact position of Cf. and now &, as we need them, in #36.
Many thanks.
Best,
Sophie

**Comment by Hippodamie** [comment]
Please, Magdalena,

Not to disturb you another time : could you please send me their login so that I send it to each of them at the very moment when I can manage with their feed back ?
Or if it is too much work for you at the moment, it can wait.

Many thanks,
Sophie

**Comment by Hippodamie** [comment]
Dear both,

> Source
> Abaios
> DELG
> Lorsqu'il n'y a pas de source, Abaios arrive en-tête.
> En ce moment la convention introduite par Magdalena est que lorsque une source est citée, le programme assigne à la première référence lexicographique un "Cf. ».


This scheme is for me perfect : we just need things would follow always in the same order and each of them being clearly identified.
If there is :
(Source)
Cf. Abaios
DELG

, it goes well, I think.


Is it possible for us to put the parenthesis ( (analog. Ἀγαθ-έας, -εια) at the end of DELG reference (we will need sometimes to add details as a short explanation).  Could you try it, Edouard ?

Thanks.
Best,
S.

**Comment by Hippodamie** [comment]
Just to be sure !

**Comment by tuurma** [comment]
Yes, you can put anything in the 'details' box, including parentheses.

**Comment by Hippodamie** [comment]
Great !
Many very thanks, dear Magdalena !

Do you think
Best,
Sophie
