### ISSUE TITLE
What about different access codes for different types of collaborators ?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#169]

**Comment by Hippodamie** [comment]
+Could I, please, have an access for a colleague of the team in Paris: I would like she be able to read (and comment) but not to edit ?
How will it work ?
Because, it will happen at different moment that I will need to give to read to many other persons.

+And another point is that I will need soon access for other scholars to edit themselves. And scholars will change along the time, because the hudge work has to be shared.

+ And everytime I will then enter corrections after discussing with them and deciding what we keep or change.

**Comment by tuurma** [comment]
Dear Sophie, the requirement to have different editing options is a new requirement and not trivial, either. What do you mean exactly saying that some users need to be able to 'comment'? So far, we have two levels of access: read only and editing privileges. In our data structures there is also no special place reserved for comments.

**Comment by Hippodamie** [comment]
Comment, I meant, in another document, do not worry with that : we just need in the interface « read » different of « edit ».
Best,
Sophie.

**Comment by tuurma** [comment]
Ok
