### ISSUE TITLE
Aischrybion. A Suffix 2 is missing : (V)β/π/φ please to add at the head of the list (#147)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#170]
Please, to finalize Aischrybion, for which there is a second (low) analysis, we need the addition of the missing Suffix 2: (V)β/π/φ.

If you already did it, sorry !

No Edit interface visible at this time.
Best,
Sophie

**Comment by tuurma** [comment]
suffix already available, closing

![screenshot 148](https://cloud.githubusercontent.com/assets/449468/13249959/1e71ba8e-da1f-11e5-9e37-15b9bd9eabf6.png)
