### ISSUE TITLE
returning to the last edited name after save

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#171]
something else that makes the work particularily difficult: 
A name is input in the search case and you have displaid only that name; if you refresh, instead of showing you just that name, the search box is empty and the program gives you the entire list, (more exacty the fist page)!
In the same way, if you go to a name on the 5th page, you modify something in it and then you do the refresh in order to visualize the modifications, it sends you on the first page and you have to go again to the 5th page to see the result of the changes you made. 
Could you do something about this, too?

**Comment by tuurma** [comment]
Dear @edouardchiricat, thanks for this observation! As for the solutions, one idea is to have default ordering not by Greek name but by the time of last update - this would give us most recent names always on top and sorting by Greek would still be only a click away. What do you think?

**Comment by edouardchiricat** [comment]
OK, is this solves also the problem no. 1

Édouard

**Comment by Hippodamie** [comment]
Wonderful, this default order !

**Comment by edouardchiricat** [comment]
Sort by last modified wold be better, it has to work also with the names
that are only modified.

Édouard

**Comment by tuurma** [comment]
This is now in place, let me know how it works for you. I used the data we are storing in TEI so far, which is the day only (within the day names are sorted alphabetically). If you'd like to have better granularity for the chronological ordering do let me know.

**Comment by Hippodamie** [comment]
I would really prefer sort being by last new edited name and not by last modification, since the idea of the work is the following :

one person and only one edit, another one and only one evise and modify if necessary. And only sometimes a third person will maybe come to modify again.

The most of the time, the important thing will be for the revisor to quickly identify which are the new names to discuss and improve by modifying or adding or deleting. Revisors will be no more than 1 (me) or 2.
Editors could be from 2 to 4 working at the same time.

Best,
S.

**Comment by edouardchiricat** [comment]
In this case, you will really need better granularity for the chronological
ordering..

Édouard

**Comment by edouardchiricat** [comment]
Or not a day looks fine to me as granularity....

Édouard

**Comment by tuurma** [comment]
I think from general perspective a day should be good enough, so I would stick to storing this data in TEI. For editors' convenience I might use sorting based on the precise time of last modification, so you'd have most recent entry on top of the list by default.
Sophie's use case is slightly different and concentrates on reviewer's point of view, I will open separate issue for it and close this one.

**Comment by tuurma** [comment]
I will close this one as soon as I push the fix for more precise ordering, that is.

**Comment by Hippodamie** [comment]
Ok, of course.
Best,
S.
