### ISSUE TITLE
browse/delete roots

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#173]

**Comment by edouardchiricat** [comment]
Dear Magdalena,
I understand that this function is now implemented? (Hurray!) How does it
work?
Édouard

**Comment by tuurma** [comment]
There is a new option available in the menu bar at the top of the page called Roots/Radicaux (available for logged in users only)
It leads to a list of all roots entered. Roots that are not used in any name have Delete button available for them to delete those. See στρα/στρα(τ)/στρατ case (screenshot below)

![screenshot 151](https://cloud.githubusercontent.com/assets/449468/13350761/f5907648-dc79-11e5-8dd2-a81afcc9f49f.png)

**Comment by edouardchiricat** [comment]
Magdalena, it's wonderful! We needed this function BADLY!
Thank you sooo much!

Édouard

**Comment by Hippodamie** [comment]
Cher Edouard, bonjour.

Pourrais-tu m’expliquer, s’il te plaît, si une racine était à changer dans sa forme (je ne parle pas que de parenthèses à introduire mais aussi, par exemple, d’une consonne ou d’unen voyelle à supprimer), si on change cette forme dans la fenêtre suivante (root) :




OU dans la fenêtre des meanings (root) ?


OU dans les deux successivement, et dans quel ordre on procède ?

Bon après-midi.
Bien à toi,
Sophie

**Comment by Hippodamie** [comment]
Cher Edouard, bonjour.

Pourrais-tu m’expliquer, s’il te plaît, si une racine était à changer dans sa forme (je ne parle pas que de parenthèses à introduire mais aussi, par exemple, d’une consonne ou d’unen voyelle à supprimer), si on change cette forme dans la fenêtre suivante (root) :




OU dans la fenêtre des meanings (root) ?


OU dans les deux successivement, et dans quel ordre on procède ?

Bon après-midi.
Bien à toi,
Sophie

**Comment by Hippodamie** [comment]
Désolée pour le bug précédent !

**Comment by edouardchiricat** [comment]
Chère Sophie,
Je ne comprend pas ton message. Peux-tu être plus explicite?
Et si on doit avoir une conversation, peux-tu m'écrire à mon adresse
e-mail, car si l'on passe par Github, tous les membres d'EXIST reçoivent
une notification automatique sur une chose qui ne les intéresse pas, mais
consomme leur temps.
Édouard
