### ISSUE TITLE
Bug on all the names in Abai- Meaning Abaios has disappeared after I changed the form of R

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#180]
I had to change Αβαι into Αβ(αι). 
I did it for all the names with this root because it did not seem to do it automatically.

After, I tried to look at the meaning window, to connect Abaios Meaning with the new form of the Root: but there was a bug (cases were missing).

In the visualization, Meaning "Abaios" has now disappeared.

I am totally sorry if I made a mistake.

I do not change anything tomorrow.

Best,
Sophie

**Comment by tuurma** [comment]
Dear Sophie, we have agreed that the 'label' box in the input form will never contain parentheses, you can input those in the 'root' box. So changing the label box you effectively added new root. I've fixed the entry in roots list, but will need to apply the fix for all the names which you changed. I'm travelling today so can only do so tomorrow or you can do it yourself, making sure to search for the root form *without parentheses* ie Αβαι and it will appear as Αβ(αι) in the Visualization (see Abaios how it works)

**Comment by edouardchiricat** [comment]
I can take care of this.
Édouard

**Comment by edouardchiricat** [comment]
Actually, it's done automatically. All the roots show now as Αβ(αι)!

Édouard

**Comment by edouardchiricat** [comment]
I also input the meanings, now it's OK.

Édouard

**Comment by tuurma** [comment]
Thanks, Édouard, I cleaned up duplicates in meanings, now everything in order closing this one.
Rule of thumb is to avoid parentheses in root labels

**Comment by Hippodamie** [comment]
Many, many thanks, Magdalena.
I keep your rule beside me, not to forget !


Question: actually, I suppose that if I would like some people just read the data, they do not need any Loging and I juste have to give them the http adress ?
Is it OK for you if I do it at any time ?
Or does the fact that too many people look at it maybe everytime be able to disturb your own work ?

Many thanks inadvance for your answer,
Best,
Sophie

**Comment by tuurma** [comment]
Hi Sophie,

you can share the link to the website at anytime, it will be no disturbance
for our work (unless you perhaps have it published on the first page of Le
Monde and millions of people start flowing in). As much as I wish us all to
become rock star famous, this is rather unlikely, so no need to worry about
too much load on the server :)

**Comment by Hippodamie** [comment]
Not yet for « la une du Monde »  !

Another question : what about #114:
We would like that after, for example Adv+Adj, we could add between parentheses, only for the 2 Roots names and not for all of them, 1 (and only 1) of the 4 different labels :
P(ossessive)
D(eterminative)
H(ypostatic)
A(syntactic)
It would then look like: Adv + Adj (P), for example.

When could it be done ? Is it very time-consuming for you ?

Best, thank you !
Sophie
