### ISSUE TITLE
Can we edit in the Lexis "References" box anything: Greek, Mycenaean, Sanskrit, Armenian form

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#183]
Can we write in any alphabet in this box ?
Like: av. xvarǝnaŋvhant- (and even if they are actually 2 words as here av. +  xvarǝnaŋvhant-)???

Thanks!
Sophie

**Comment by tuurma** [comment]
Any Unicode character should work.

**Comment by Hippodamie** [comment]
Great ! Thanks!

**Comment by tuurma** [comment]
Let me know if you run into display issues, for obscure scripts we might
need special fonts, but normally it should just work.
