### ISSUE TITLE
Please add a new box for teh 'Reference' field: Author

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#184]
Dear Magdalena, 
Following our discussion, we agreed that there shoud be two boxes for the references: One for the author, another for the title. Only the title box should be in italics. The author box - in plain text.

**Comment by edouardchiricat** [comment]
Dear Magdalena,
I see that you closed this issue.
But I cannot see the new box.
With best wishes,
Édouard

**Comment by edouardchiricat** [comment]
The new box is functional only for the names we will input from now on. It is extremely important to have it added also for the names we have already input.

**Comment by Hippodamie** [comment]
Dear Magdalena, hi !

Could you please tell me how is called in English what Edouard and I call « Visualization interface » vs Edit Interface ? Whats is the right name for it ? Is « interface » the right English word ?

Many thanks.
Best,
Sophie
