### ISSUE TITLE
How to avoid the uggly coma at the beginning of a line in Lexis ?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#185]
Like:
CEG2 (1997)&11 (2006), ἀγα-
, ἀγαθός

**Comment by tuurma** [comment]
Cannot reproduce this. Chances are, though, there has been an extra space before the comma? Normally lines should not break if the comma immediately follows a word.
![screenshot 161](https://cloud.githubusercontent.com/assets/449468/14120280/07da5fce-f5ea-11e5-96f8-4a5af918e62c.png)
