### ISSUE TITLE
Thanks, Magdalena for Autagathidas ! What about #114: (P), (D), (H) & (A) labels added ?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#188]
Addition in the column Structure.
Optional, to describe more what means (historically) the Adj + N structure for compounds, for example.

When would it be possible, in which step ?

Many thanks,
Sophie

**Comment by tuurma** [comment]
closing this one as it already has a corresponding issue describing it in detail
