### ISSUE TITLE
Change in table headings: Stucture Semantics Lexis References

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#19]
Instead of the last 4 headings, please put 
Structure Sémantique Lexis Bibliographie
Structure Semantics Lexis References

**Comment by tuurma** [comment]
Done, will be visible on showcases after update (tomorrow at the latest)
![screenshot 119](https://cloud.githubusercontent.com/assets/449468/12625572/400bd1f0-c52c-11e5-8604-1d4ece320038.png)
