### ISSUE TITLE
BIG BUG After deleting a name, I input it again and then it systematically dissapears, no matter how many times I input it again.

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#192]

**Comment by edouardchiricat** [comment]
I had to open a new window and retype the address, then log in and input the name.
Otherwise, if I remain in the same window, by simply refreshing the window I get the message: "Deleting Βατιάς" and the name is gone.

**Comment by tuurma** [comment]
Thanks for clarifying the circumstances, I was about to ask if this is how it happens :-)

**Comment by edouardchiricat** [comment]
This can't stay like that, imagine if I hadn't check the name after
re-inputting it!

Édouard
