### ISSUE TITLE
Please: not only CSV format but also xml for data saving.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#193]
Like in lgpn2, where we can download the data through different formats, xml, json, kml, csv, rdf, could you make it possible to give us access to xml for all the data: so, 2 formats: CSV & xml ?

Because Huma-Num in France, a public structure for saving the data to whom we are obliged to give them as scholars, asks for xml to save them.

Many thanks.
Have a good day.
Best,
Sophie

**Comment by tuurma** [comment]
copy of #218
