### ISSUE TITLE
Curious bug: French visualization but English meanings, twice today !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#194]
When I refreshed, it came in French ! But first time in English, though we are in the French version with french titles of columns !

Best,
Sophie

**Comment by tuurma** [comment]
Does the issue persist? If so, can I have a screenshot, please, including the browser's address bar?

**Comment by tuurma** [comment]
closing as haven't heard or encountered the problem for a long time
