### ISSUE TITLE
BUG Wrong dialect on visualisation page

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#197]
In Ἀγάλλης, I have ticked the box Nort Doric in the input interface, but in the Visualisation interface it appears as South Doric

**Comment by edouardchiricat** [comment]
ticking North Doric in the input interface is systematically translated into South Doric on the Visualisation page !!!

**Comment by tuurma** [comment]
apologies, had misspelled long name for North Doric, fixed now
