### ISSUE TITLE
#114improved: important to add and to be searchable. (A)syntactic called now (I)rrational. Thanks.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#201]
To add after the Name Structure informations, between parentheses.
Scheme should be the following:
(P)ossessive = N,Adj, Adv + N (I mean 3 different couples)
(D)eterminative =V,N,Adj, Adv, Pro + N, Adj, Pro (each of the 5 could be connected with each of the 3 following)
(H)ypostatic = Adv + N.
(I)rrational = V,N, Adj, Adv, Pro + N, Adj, Pro (each of the 5 could be connected with each of the 3 following).

For example, we would like to read in the column Structure: Adj+N (P) or N+N (D) or V+N (D) or Adv+N (H) etc.
Some names will have this supplementary label (not all the 2 Roots names, but only the 2Roots Names).

**Comment by Hippodamie** [comment]
Note that the structure Adv + N can be as well, depending of the name:
Possessive, Determinative, Hypostatic or Irrational.
And the same could be said of other couples. It is totally normal. And very important for the historical linguistics and comparatism between languages, typology thus.

Best,
S.

**Comment by tuurma** [comment]
closing this as #114 is the base one for this issue
