### ISSUE TITLE
SERVER DOWN !!!

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#203]
http://admin.exist-db.org:41233/exist/apps/lgpn-ling/index.html?lang=en

**Comment by tuurma** [comment]
thank you, we're investigating this and will get back to you asap

**Comment by edouardchiricat** [comment]
The problem apparently solved by itself about ten minutes ago.
But Thank you.

Édouard

**Comment by tuurma** [comment]
hmm, I get connection refused but perhaps it's local network blocking this port
