### ISSUE TITLE
Just wanted to thank you so much for the Search window with its wonderfully useful truncation function !!!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#205]
Could we have it too in the Advanced Search interface, in the first box, as in the ancient interface?
Actually, as I told Robert Parker and Richard Catling, we need it all of us !

Best,
Sophie

**Comment by tuurma** [comment]
Yes, functionality of the old website will be reproduced in this regard.

**Comment by tuurma** [comment]
Closing as it's a duplicate of #187 and only indirectly connected with ling. Will put an issue on LGPN tracker.
