### ISSUE TITLE
Login: too often asking for Login when I modify (it happened yesterday). Would like to have it open for hours... Best, thanks, Sophie

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#206]

**Comment by edouardchiricat** [comment]
This becomes more and more annoying and, especially, time consuming. 
Now, I have to log-in every three minutes or so!
Could you please find a fix to this bug, Magdalena?

**Comment by edouardchiricat** [comment]
Something very strange: after logging-in, the URL changes into: 
http://admin.exist-db.org:41233/exist/apps/lgpn-ling/index.html?loginStatus=failed
Why loginStatus=failed when I have just logged-in?
