### ISSUE TITLE
filenames

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#208]
When two distinct Greek names (with two different accents) have the same transliteration in latin alphabet, impossible to keep both. When adding the second name, the previous one is deleted.
This is a very important bug and HAS TO BE DEALT with quite quickly, because we have many situations of this type.

**Comment by edouardchiricat** [comment]
Example: Ἀγγελῆς and Ἀγγέλης. Both are transliterated Angelēs. I had to put a 2 next to the transliteration of Ἀγγέλης in order not to overwrite Ἀγγελῆς.

**Comment by tuurma** [comment]
We need to change naming scheme for files, make it follow the Greek form rather than Latin transliteration as it obviously leads to this trouble.

**Comment by edouardchiricat** [comment]
Please do...

**Comment by tuurma** [comment]
deal with cases as described above as well as separate entries for exact same names
