### ISSUE TITLE
Additional to #114&201: more information about Simple Names in column Structure

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#209]
As we need parentheses to explain the formation of compound, as explained in #201, we need also parentheses connected to mono-Roots names.
The label we would like to have between the parentheses will be only one: (AbbrevC).
It could be connected to a monoRoot name being described as: N, Adj or V or Adv, and only these 4 labels.
And not all simple names being N, adj or V or Adv will need this supplementary (AbbrevC) label. The label will be thus optional. Some names will have just in Structure: N or Adj or V or Adv.

**Comment by tuurma** [comment]
special case for #114, closing this one
