### ISSUE TITLE
XML export (in a format suitable for generating latex output for print)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#218]
XML is the best way to edit a printed book.
I show you how the lines of analyses will look in the future book (generally, no more than 1 line by name, except when quotation or hudge bibliography:

Ἀγαθο-βούλ-α 2f., dorien micras. 3a, « bon + vouloir, conseil »: βουλῇ τ'ἀγαθῇ καὶ κακῷ δαίμονι μοχθίζουσι Thgn. 163.
Ἀγάθ-α 5f., béotien 2a. Frauen 1. OGS 3, 95.
Ἀγαθ-ίας 66m., arcadien 4a. HPN9.  
Ἀγαθ-ῖνος 74m., théro-cyr. 5a. OGS 2, 526.
Ἀγαθθ-ώ 1f. béotien 4/3a. Ou de Ἀγά-θ(υμος) (vid. s.v. ἄγᾱν et θῡ̄μός) ?

Have a nice week.
Best,
Sophie

**Comment by edouardchiricat** [comment]
Dear Sophie,
If you want to edit your book directly from xml, the procedure is rather
complicated and time consuming. Magdalena will have to write a stylesheet
which will convert the informations from the xml into pdf. As far as I know
it's not an easy task.
Magdalena, what do you think?
With best wishes,
Édouard

**Comment by tuurma** [comment]
Fine typesetting is, as Édouard rightly mentions, not a straightforward job. In this case, though, it seems not too bad and we can probably get it into LaTeX via TEI Processing Model. Key, as always, is to have precise requirements.
If we try to generalize a bit from examples provided by @Hippodamie, the structure seems to be roughly:
1. constituents of the name separated with hyphen
space
2. number of attestations followed by gender represented by m./f.
comma & space
3. short version of dialect
space
4. ??? period perhaps? in examples e.g. 3a or 2a
comma, space
5. list of meanings, joined with + and wrapped in « »
6. : followed by a quote and reference (if present)
7. other references

As usual, devil is in the details and I would need precise prescription for more complex cases, especially like this one
> Ἀγαθθ-ώ 1f. béotien 4/3a. Ou de Ἀγά-θ(υμος) (vid. s.v. ἄγᾱν et θῡ̄μός) ?

There seems to be a need for grouping of meanings together (in examples only the first name starting with Ἀγάθ have the meaning explained), rules for that need to be formed as well.

**Comment by Hippodamie** [comment]
Yes, you are right: we will have a bit later to precise the different types of lines that could be. I answer below for the special case.

But anyway, in France they need to have the data in XML files. That is why I ask to have the export also in XML format. 

Best,
Sophie


> Le 29 mars 2016 à 20:55, Magdalena Turska <notifications@github.com> a écrit :
> 
> Fine typesetting is, as Édouard rightly mentions, not a straightforward job. In this case, though, it seems not too bad and we can probably get it into LaTeX via TEI Processing Model. Key, as always, is to have precise requirements.
> If we try to generalize a bit from examples provided by @Hippodamie <https://github.com/Hippodamie>, the structure seems to be roughly:
> 1. constituents of the name separated with hyphen
> space
> 2. number of attestations followed by gender represented by m./f.
> comma & space
> 3. short version of dialect
> space
> 4. ??? period perhaps YES? in examples e.g. 3a or 2a
> comma, space 
> 5. list of meanings, joined with + and wrapped in « »
> 6. : followed by a quote and reference (if present)
> 7. other references
> 
> 
RIGHT
> As usual, devil is in the details and I would need precise prescription for more complex cases, especially like this one
> 
> Ἀγαθθ-ώ 1f. béotien 4/3a. Ou de Ἀγά-θ(υμος) (vid. s.v. ἄγᾱν et θῡ̄μός) ?
> 
> 
Here you have the case of 2 hypotheses: the high certainty comes first, then the low (they could be sometimes 3 hyp. with 2 low).
Ou = Or
« de" could be also symbolized by < (= coming from): it means here that Ἀγαθθώ could be analyzed not only as a derived form of αγαθ but also as the abbreviated form of the following compound made of 2 Roots, from which the first is different from αγαθ, since it is αγα. The first parentheses show what is the second element abbreviated. Actually, we should rather put after : vid. s. v. ἄγᾱν et θῡ̄μός. vid. s. v. = see the two other lemma of the alphabetic dictionnary.

**Comment by tuurma** [comment]
The way to proceed is for @Hippodamie to come up with a bunch of test cases - representative of scenarios which we may encounter and try to sort it into chunks to see if they fit our recipe.

Tentative list is:

1. high hypothesis: constituents of the name separated with hyphen
 space
 2. number of attestations followed by gender represented by m./f.
 comma & space
 3. short version of dialect
 space
 4. period
 comma, space
 5. in case alternative hypotheses are present, their hyphen-separated constituents should be listed after `or <=`
 5. list of meanings, joined with + and wrapped in « »
 6. : followed by a quote and reference (if present)
 7. other references

* 6 and 7 need to be elaborated *
