### ISSUE TITLE
A question: why the columns "number of occurrences" & "Periode" are not automatically completed when I edit a new name?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#221]

**Comment by tuurma** [comment]
Aren't they? Could you provide an example of an entry where that happens?

**Comment by tuurma** [comment]
I can confirm that this happens and as far as I can see, the problem lies in using different forms for inputting accents, in this case Βαβύριος vs Βαβύριος (not sure if the distinction is visible here). I will let you know once I have a fix.

**Comment by tuurma** [comment]
Now all Unicode input is automatically converted to NFC form, which should prevent this trouble popping up in the future. For the names already input it may be necessary to open&save the name for the normalization to occur atm. I will run a script that does it in a couple of days, so no real need to do that unless it's particularly annoying.

**Comment by tuurma** [comment]
![screenshot 173](https://cloud.githubusercontent.com/assets/449468/14498709/4f6cade2-0193-11e6-8fda-f9a537f71077.png)
