### ISSUE TITLE
Changing suffix ώ(ι) into (ι)ώ(ι) and placing it just before -ίων

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#222]
The place of -(ι)άς should also be change; please place it immediately after (V)ία/η.

**Comment by Hippodamie** [comment]
Dear Magdalena,

Many thanks for -(ι)ώ(ι) and its good place.
Could you, please, also move the new (ι)άς, which would be at its good place just after (V)ίᾱ/η and before (V)ίᾱ/ης ?

Many very thanks for NAME STRUCTURE !!!

Have a nice sunday !
Best,
Sophie

**Comment by tuurma** [comment]
No problem, done that
