### ISSUE TITLE
Thanks for βα(β) but new bug on Βαβυρίας, second hypothesis and whole edition page...

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#225]
The bug is such that any time I login, I am blocked on the page Βαβυρίας, where I am telled that the meanings cannot be reloaded.
I think I forgot the first time I changed the form of the root, to do it also for the second hypothesis.

Thanks for your help.
Best,
Sophie

**Comment by tuurma** [comment]
I did encounter something similar under circumstances where I was logged out (for whatever reason), but had the list of names still open. Trying to edit a name then resulted in 'Login required to edit data' alert. Logging in from there results in the kind of trouble you describe.
Workaround for now would be to click on 'Recherche' menu option **before** trying to log in again and then proceeding normally.

I'm still trying to nail down what causes this logging out.
