### ISSUE TITLE
new dialects

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#227]
@hippodamie

> Could we, please, add:
> Panhellenic (after Pamphylian).
> The 8 following labels at the end of the list:
> Greco-Anatolian
> Greco-Egyptian
> Greco-Etruscan
> Greco-Iranian
> Greco-Latin
> Greco-Phrygian
> Greco-Semitic
> Greco-Thracian.
> 
> Deleting Latin itself.

first mentioned on #211

**Comment by tuurma** [comment]
@hippodamie

> Here below are the French translations added.
> Could you please add also the new label:         Greek?/Grec?
> Many thanks.

Unfortunately French translations didn't get pasted. Do you mind putting those here?

**Comment by Hippodamie** [comment]
Could we, please, add:
Panhellenic (after Pamphylian).
The 8 following labels at the end of the list, but modification of the spelling, sorry for that, read every time Graeco-    Anatolian, etc. (not Greco !):
Greco-Anatolian
Greco-Egyptian
Greco-Etruscan
Greco-Iranian
Greco-Latin
Greco-Phrygian
Greco-Semitic
Greco-Thracian.
Deleting Latin itself.
Thanks,
Sophie

**Comment by Hippodamie** [comment]
In FRench:

-panhellénique
-gréco-anatolien
-gréco-égyptien
-gréco-étrusque
-gréco-iranien
-gréco-latin
-gréco-phrygien
-gréco-sémitique
-gréco-thrace
-grec?

The end !
Best,
Sophie

**Comment by Hippodamie** [comment]
Sorry: I've forgotten in English at the end:
Greek?

**Comment by tuurma** [comment]
Is Greek/grec supposed to be a substitute for Koinai or is that supposed to stay?

**Comment by tuurma** [comment]
Updated the list, please reopen if something's out of place.

**Comment by Hippodamie** [comment]
The new label is with ?:


English: Greek?
French: Grec?


It should comme at the end of the others labels.
Koinai must stay, of course!
Best,
Sophie

**Comment by tuurma** [comment]
That's how I did it, so should be ok. Thanks for quick response.
