### ISSUE TITLE
Methods&aims scientific document explaining our research for Magdalena

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#230]
Methods of research ; vision for the Advanced Search window ; vision of the lines of the future book (New-Bechtel): our ideal: 1 name per line in the future book. The aim: lines of the book the closest possible to the current lines of LGPN-Ling visualisation online.

[Methods&aims LGPN-Ling.docx](https://github.com/eXistSolutions/LGPN-ling/files/215582/Methods.aims.LGPN-Ling.docx)

**Comment by tuurma** [comment]
Thanks, Sophie!

**Comment by Hippodamie** [comment]
It is just for you.
I have now to extract from it the shorter and more readable presentation document to put on your "On LGPN-Ling", as short guidelines for any people coming to visit !
Thanks for your today work !
Best,
Sophie

**Comment by tuurma** [comment]
Great idea to put something into 'On LGPN-Ling' soon! Thanks for the interesting read, it always helps to know why we do this in the first place ;-)

**Comment by Hippodamie** [comment]
Soon is not so sure: because of the application, I am very late and busy ! Would like to!
