### ISSUE TITLE
Horrible bug when trying to save an entry

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#231]
Dear Magdalena,
There is a problem I cannot live with any more.
Each time I want to save an entry, after having input all the information, I have a message 'failed to save data'. Sometimes the third or fourth try is successful, but now I've been trying to save an entry for five minutes!
I know that Sophie is also annoyed by this. Can you do something to solve this bug?
Thank you in advance,
Édouard

**Comment by edouardchiricat** [comment]
I definitely cannot save Hagnodēmos!

**Comment by edouardchiricat** [comment]
What can I do?

**Comment by edouardchiricat** [comment]
I've just tried to modify something and now it's impossible to save!

**Comment by tuurma** [comment]
This is definitely something else then just being logged out of the blue, looking at Hagnodēmos and some other entries from today, they seem to have wrong document permissions set, lacking write privilege for the group. This is most probably the reason for not being able to save at all.

**Comment by tuurma** [comment]
![screenshot 174](https://cloud.githubusercontent.com/assets/449468/14500908/d5aaf08c-019b-11e6-9199-becba3525366.png)

**Comment by edouardchiricat** [comment]
And why does this happen?
And why the other entries from today, that seem to have wrong document
permissions set, have been saved?

Édouard

**Comment by edouardchiricat** [comment]
Well, I gave up and tried to go back to the visualization page. There, a
window asking me to login! I log-in and I am automatically sent back to
Hagnodēmos! It is a vicious circle I cannot escape. Please do something🤕

Édouard

**Comment by tuurma** [comment]
Apologies, Edouard, I don't have answers yet.
I have further observations though.
Trying to change permissions from eXide results in this error:

> exerr:ERROR Resource or collection '/db/apps/lgpn-ling-data/data/names/Hagnodōros.xml' does not exist. [at line 291, column 49, source: /db/apps/eXide/modules/collections.xql] In function: local:get-property-map(xs:string) [316:63:/db/apps/eXide/modules/collections.xql] 

Which is clearly not the case, as the content of the document can still be retrieved. I suspect again normalization issues - this time in filename. Bear with me some more as I look into it.

![screenshot 175](https://cloud.githubusercontent.com/assets/449468/14501042/68fb44ae-019c-11e6-9e13-e90a88a82a87.png)

**Comment by edouardchiricat** [comment]
I opened a new window, I accessed the name, I made the modifications and
after hitting ten times the button 'save' it finally saved the entry ...
By the way, I do not have access to the interface you copy me in.

Édouard

**Comment by tuurma** [comment]
Glad you did it, but I'm still puzzled :-(
I post eXide screenshots for my colleagues whom I asked for advice, you don't necessarily need to be bothered about it (unless you want to).
