### ISSUE TITLE
I cannot save anymore data (quote & lexicographic) for Babyrios neither Babyrias, Help ! ...

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#235]
And after having tried to save without any success, I cannot go out of the edition page to come back to visualisation. I have to reload LGPN-Ling.

Thanks for your help.

I must say that I spent the whole day just trying to modify the 3 names in Βαβυρ. I cannot lose anymore such a time. It is really discouraging. Could you, please, Magdalena, give us short guidelines, just telling us what we must absolutely avoid to do?
I asked Edouard for guidelines. He did it but problems occur still very often.

Research means changing your mind as you study new names. The answer cannot be sure before having studied lots of close names. We should be able to change data without any problem. Everytime we have to modify several data for the same name, we are stopped by bugs.

Thanks in advance for your help and making things for us easier, please.
Best,
Sophie

**Comment by tuurma** [comment]
Apologies for that once again, I think the issues with saving are now largely a thing of the past.
