### ISSUE TITLE
Many thanks, Magdalena: all is done with Babyrias, Babyrios & Babyros, waouh!!!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#236]
Sorry if you found me quite desperate yesterday: the struggle against the machine the whole day...
Anyway, the machine is done to edit but does not like very much we correct !

Good week-end.
Best,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

I'm working on nailing what's wrong with the save, as you know, sometimes
it works but more often it doesn't, it's very hard to determine precisely
in which circumstances it happens. Apologies for many inconveniences it
causes.

**Comment by Hippodamie** [comment]
Dear Magdalena,

By now I suffer on Aischrybes and Aischrybas again, because, low hypothesis is missing for Aischrybes, and I try to input it (no ways), and for both I have to put the Bibliography in another order just as in Aischrybion.

Courage !
But I worked well at the beginning of the afternoon !
Best,
S.
