### ISSUE TITLE
Agestos: tried to input a 3rd low hypothesis. But meanings is not visible.... Help !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#241]
3rd hypothesis = a new Root.
When I came back to the Edit window, after choosing the good form of the Root in the list (στᾱ), I input the new Constituent form. I chose στ which was already there in the list as linked to another root, which is στρατ.

Is it because of that: no meaning comes.

Thanks for your help.
Best,
Sophie

**Comment by tuurma** [comment]
Hi,
what I did there was basically to take it out and select it again, after which meanings reloaded ok. Sorry for that, I think this is perhaps connected again to how you input accents - either as combining marks or as a whole character combined. I will change the script that looks up morphemes to take that into account but tomorrow, if that's all right with you, it's Sunday after all ;-)

**Comment by Hippodamie** [comment]
Sorry, Magdalena,

When I put remarks on Githubs, it is just not to forget, not to deal with on Sunday !!!
Do not look at your emails on Sunday !!!
Have a nice day (here a little sunny but fresh)! I leave now.
Best and sorry for that,
Sophie

**Comment by tuurma** [comment]
Have a good day, it's so sunny here today, makes you almost forget it's
Britain ;-)
