### ISSUE TITLE
To fix and to make me able to work on and to save this afternoon, please !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#242]
Dear Magdalena,

I would like, please, to be able to work on, save and end the following problematic entries (I will work the whole afternoon):
Aglaphon, Aglao- or Aglo-phantos, Aglophanes, Agathophanes, names in Babyr- and Aischrubas & Aischybes, where I cannot put any low hypothesis as in Aischrybion, which is perfect. I would like to see back the meanings of all the names in Angel-.
It will be often only very small modifications, as Bibliographic, but the problem is that I never can save... and have always to log in again and sometimes am blocked always in the probelmatic edition window, as in a circle!!!
Thanks for your help.
I would like to put all the edited names in order during Edouard vacations. It is very important, since experts (fundings application)) can look at the names at every time.

Have a good day (here sunny!).
Best,
Sophie

**Comment by edouardchiricat** [comment]
Chère Sophie,
Je regarde rarement mes e-mails, et je viens de voir que tu as des
problèmes.
Il m'est arrivé, à moi aussi, d'être pris dans le cercle dont tu parles.
Il y a une solution (la seule) d'en échapper:
Il faut fermer toutes les fenêtres LGPN-ling, en ouvrir une nouvelle, en
copiant dans la barre d'adresses l'URL du site, i.e.
http://admin.exist-db.org:41233/exist/apps/lgpn-ling/index.html. On est
alors dans l'interface de visualisation.
Ensuite, on peut accéder à nouveau aux noms que l'on veut éditer, comme
d'habitude.
Bien cordialement,
Édouard

**Comment by Hippodamie** [comment]
Cher EDouard,

Grand merci: c’est parfois DESESPERANT. Car, éditer, ça marche assez bien, si on fait bien du premier coup, en ayant tout bien préparé. Mais CORRIGER, AJOUTER, comme je dois faire par définition et comme je devrais faire à chaque nouvelle avancée ou publication, c’est souvent, et dès que je touche au radical, l’échec garanti. J’ai perdu tout vendredi à bloquer nom après nom..., et m’y remets cet après-midi...

Masi tu es en VACANCES: alors, ne regarde plus tes mails, STP !!!
Profite bien de ton repos. Je m’arrête moi-même, en principe d’ici quelques jours. C’est pour cela que je voudrais corriger tout, en profitant de ton absence (ce ne sont pas tes erreurs que je corrige, mais souvent des progrès que j’essaie d’introduire, en prenant mieux le temps de réfléchir).

Bonnes vacances, Edouard.
Bien à toi, et merci,
Sophie.

**Comment by edouardchiricat** [comment]
Chère Sophie,
Entendu.
Bonnes vacances à toi aussi.
Édouard

**Comment by tuurma** [comment]
I think this is now fixed, but please reopen if not.
