### ISSUE TITLE
Magdalena: it works !  Wonderful ! Thanks for what you did! Could you please make re-appear Angel- meanings ?          

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#243]
I would like to be able to type them: but no cases anymore !

It should: English: messenger
                             (convey a) message

French: messager
             (annoncer la) nouvelle.

Could you fix the sub morphem window for all the names in Angel-?

Many thanks in advance.
Best,
Sophie

**Comment by tuurma** [comment]
Fixed now!
