### ISSUE TITLE
Impossible to delete the lines with the spelling F instead of PH. ( names in -fanes, -fantos)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#245]
I would like to delete Aglofantos & Aglofanes because I changed their Latin spelling in Aglophantos, Aglophanes.
But it is impossible.

And maybe it is the reason why I cannot add a reference in Aglophanes.
Thanks for your help.
Good night.
Best,
Sophie

**Comment by tuurma** [comment]
Deleted both without problems. I suspect you might have been logged out and perhaps for that reason you encountered trouble deleting those names.

**Comment by Hippodamie** [comment]
Thanks, but how could I delete if logged out ?
Have a good night!
Best,
Sophie
