### ISSUE TITLE
Failed to load data for Agaios, where I have to move  the reference in Lexis

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#249]
Many thanks for your help.
Best,
Sophie

**Comment by edouardchiricat** [comment]
I think the problem comes from the fact that there are two (identical) entries for Agaios. I have tried to delete one, but the result is a system crash. I think that this problem should be fixed.
This is what is displayed: 
An error has occurred

An error has been generated by the application.

err:XPTY0004 checking function parameter 1 in call xmldb:remove(untyped-value-check[xs:string, util:collection-name($entry)], untyped-value-check[xs:string, util:document-name($entry)]): checking function parameter 1 in call util:collection-name($entry): XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: util:collection-name($node-or-path-string as item()?) xs:string?. Expected cardinality: zero or one, got 2. [at line 69, column 68, source: /db/apps/lgpn-ling/modules/app.xql]
In function:
	app:delete-entry(xs:string?) [59:26:/db/apps/lgpn-ling/modules/app.xql]
	app:delete-name(node(), map, xs:string?) [219:18:/db/apps/lgpn-ling/modules/app.xql]
	templates:call-with-args(function, function*, element(), map) [208:13:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process-output(element(), map, item()*, element()) [205:9:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call-by-introspection(element(), map, map, function) [187:28:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call(item(), element(), map) [135:36:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [28:13:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	intl:translate(node(), map, xs:string?, xs:string?) [221:18:/db/apps/lgpn-ling/modules/i18n-templates.xql]
	templates:call-with-args(function, function*, element(), map) [208:13:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process-output(element(), map, item()*, element()) [205:9:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call-by-introspection(element(), map, map, function) [187:28:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call(item(), element(), map) [143:37:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [277:13:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [146:81:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [462:17:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process-output(element(), map, item()*) [270:9:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process-output(element(), map, item()*, element()) [205:9:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call-by-introspection(element(), map, map, function) [187:28:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:call(item(), element(), map) [135:36:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [131:51:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:process(node()*, map) [88:9:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]
	templates:apply(node()+, function, map?, map?) [48:5:/home/wolfgang/eXist/webapp/WEB-INF/data/expathrepo/shared-0.4.0/content/templates.xql]

**Comment by tuurma** [comment]
this is now fixed
