### ISSUE TITLE
Modify the headings' order in the first columns

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#25]
EN: Latin Greek Gender Dialects Period
Fr: Latin Grec Genre Dialectes Période

**Comment by tuurma** [comment]
Done. Please note that Genre/Period columns are just placeholders for now, pending union with prosopographical database
![screenshot 120](https://cloud.githubusercontent.com/assets/449468/12625931/e6eec4cc-c52d-11e5-822d-d9efbd815c35.png)
