### ISSUE TITLE
Hi, Magdalena: a request. Could I please have an xml version of all our current data for security saving? Many thanks. Have a nice day! Best, Sophie

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#250]

**Comment by tuurma** [comment]
Sure, where would you like it placed? We have daily backups scheduled, just to put your mind at ease :-)

**Comment by Hippodamie** [comment]
1° Would it be possible to have, as the CSV export you put in the top left corner, an xml export, just as in lgpn2, see infra , where clicking in it you just can copy the data in a Word document? Here is the xml extract. This kind of line exactly looks like what I need to print the future book.
 
LGPN 2016-4-30 15:38:56 LGPN 
Derived from postgreSQL database retrieval

 Ἀκουσαγόρας Melos f.iv BC s. Στρόμβις  XII (3) 1176Ἀκουσαγόρας Cyrene 3AD f. Ἀπολλώνιος  XX 741 a, 13

And to have all data xml all together just as in the visualisation if you ask « all » names visible.


2° Another thing: I will give you soon an address to have another place to stock the data as we are obliged in France (Huma-Num). But I have before to ask them for login and password.

Have a nice week-end.
Best,
Sophie

**Comment by tuurma** [comment]
We have briefly discussed 1° in #218, so let's keep that discussion there. I'll open another one for the Huma-Num export.
