### ISSUE TITLE
"Cf." label before DELG in Lexis column (...)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#253]
We do not need to have this cf. since DELG is enough for everybody to make clear that it is something different of the previous quotations.
And another thing is that we have sometimes to write cf. in the quotations themselves when the link with the name is not direct and when the quotation is an indirect evidence to help undertstand the name (for example Mycenaean evidences). But in this case we do not need of course that CF is automatically input, and neither do we before DELG.
CF has an important meaning in itself so it is a problem if it appears automatically. 

Thanks for your help.
Best regards and have a nice week,
Sophie

**Comment by tuurma** [comment]
For clarification: do you want me to get rid of automatically inserted cf. altogether? Or do we try and come up with another way of signalling where it is necessary and where not. As I think we discussed before I would strongly advise *against* putting Cf. literally in the Reference box, as it will affect searches and autocompletes in the future.

**Comment by Hippodamie** [comment]
Ηι, Magdalena,

If you mean Searches for the future user of the database, i must say we do not need to make search possible from the Lexis and References boxes, from those only 2 boxes.

For autocompletion for us, editors, I understand the problem, but the important for us is to have a very logic syntaxis easy to understand for the user: for example, for Agestos, Cf. HPN 308 comes first because it is our way to understand the name, against the way Bechtel, HPN 12, understood himself and listed the name. « Cf." means we do not find the item itself but something else to compare, which helps bettter to understand the name. 
It could also happen that we need to put « contra » (sometimes after cf.) because there was a discussion between scholars about the name and we want to let know which hypothesis we consider better or in the opposite consider as impossible. We also try to explain shortly in the parenthesis what is the subject.
This micro-syntaxis could be used often in the References box, less often in the Lexis box. But the automatically Cf. before DELG is really not necessary after a quotation, because it is clear by the abbreviation DELG or EDG or CEG itself that here begins something which is at another level.
Another solution if you do not want we write cf. etc., would be to have an optional cf., contra, not, pace Box (with a cross to put on one of them if we need, as you did for Noun Verb Adv. etc.) to add or not to add before each possible reference.

Best,
Sophie

**Comment by Hippodamie** [comment]
Hi again,

I do not find anymore your message about the subject, but will try to answer on it.

We could do without any specific search with « prefix » as a criterion. The search by the sole criterion « adverb » will make possible to find all of them together, and after, looking at one especially, to type one of them by entering the 3 or 4 letters corresponding to its kind of root in the autocompleted roots list. By the way, a specific search by each of the structure labels is of course as necessary as searches combining both: Rx, y or z + V or Adv etc. and combining a third criterion which is the position.

But a better possibility could be to make able the user to chose the specific search « prefixes » as combined searches:
 1° R1+Adv ; 2° R2+Adv 3° Preroot+Adv ; 4° Preroot+N ; 5° Preroot+V. [the + meaning =].
Just to add in your current Advanced search window after Prefix, at the same line « position », as you did for root and constituent.

But, the important question now is to make us able to edit everytime in this box « preroot ». Sure, 3-Roots names are rare. The most of the time we will have only in this box: ευ or α or (h)α (but by caution keep all the list unchanged), but it will happen (no more maybe than 100 times for all the 35,000 names, I guess!) that we have to edit something else like for example θεο or another root in connection with names of gods or maybe even a verb.

So, could you please make us possible to better edit this box? Or just add to the current list a line « other ». But in this case, the preroot will not be searchable connected to the R1 & R2, for example for θεο, which will be found also as a R1 & R2.

If I changed my mind months ago on the subject, it is because I thought it was a pity if we were not able to give the meaning also of the prefixes. We need it as well as for the other roots.

Just think about all of that and tell me what is your opinion. But the best way, I guess, would be to build a special second subwindow for the Preroot, exactly made as the current you built for the R1, R2.

I hope it is clear enough. Just ask if necessary.

I will be in Oxford next 28th of June: could we work all together with Edouard in his office this day or part of the day, and maybe talk on the subject, if it is easier ? Tell me.

Best regards,
Sophie

**Comment by tuurma** [comment]
add a checkbox for the lexis column to mark if it should be preceded with `cf.` in the output

**Comment by tuurma** [comment]
related to #429
