### ISSUE TITLE
Βαβυραταδας disappeared, I do not understand why. Have you kept any trace of it, so as to restore it ?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#257]
Many thanks,
Best,
Sophie

**Comment by Hippodamie** [comment]
I meant Βαβυρτάδας, sorry !

**Comment by tuurma** [comment]
Mhm, any idea when did you saw him last?

**Comment by Hippodamie** [comment]
It was around the famous week-end when I struggled to save even on Sunday and disturbed you because of it. I have worked on these names between the 15 and the 19 of April.

Thanks for your help.
Best,

Sophie
