### ISSUE TITLE
Agorakrinēs, Krinagoras: please make appear The root κρῑν of these names in Visualisation

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#265]
There are instances where certain roots do not appear any more in Visualisation, even if they are correctly input.
Is it still because the macron?

**Comment by tuurma** [comment]
This happened because no Unicode normalization was applied when saving the morphemes. I will apply a permanent fix shortly.

**Comment by tuurma** [comment]
This happened because no Unicode normalization was applied when saving the morphemes. I will apply a permanent fix shortly.
