### ISSUE TITLE
The script replaces ῞Α by Ἄ

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#270]

**Comment by tuurma** [comment]
thanks for spotting that!

**Comment by tuurma** [comment]
can you please check if it's ok now?

**Comment by edouardchiricat** [comment]
Now it's fine. Does the script modify things already input? I checked the column Greek and it's fine, but I cannot do it for the citations in the column Lexis.

**Comment by edouardchiricat** [comment]
...thank God, I meant...

**Comment by Hippodamie** [comment]
Dear Magdalena,

Could you please give login and password to Enrique Nieto ?
enrique.nieto.1977@gmail.com

Many thanks in advance.
Best,
Sophie
