### ISSUE TITLE
Problem with searching a root beginning with a letter with diacritics

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#271]
Dear Magdalena,
There is another big problem. 
When one searches for a root in the input interface, the letters with diacritics are not taken into account. 
For example, if one tapes δα, δᾱμ is not listed as an existing root. You can imagine that somebody who doesn't know that will input δᾱμ once again. 
A bigger problem are the roots which begin with diacritics. For example, ᾱ̆φεν is impossible to find by taping α. 
It's very important to fix this. I hope it is possible.
Best wishes,
Edouard

**Comment by tuurma** [comment]
I've put in a fix, let me know if it's as you expected?

**Comment by edouardchiricat** [comment]
Dear Magdalena,
Many, many thanks for solving this important problem.
Things look fine now, but please allow me to do a little bit more testing.
Best wishes,
Édouard

**Comment by edouardchiricat** [comment]
Dear Magdalena, the problem is not entirely solved yet. 
I type δο et δōρ doesn't appear in the options list.
Equally, could you please let the system ignore the initial aspiration h and display roots like hαγ even if one types just αγ ?
Thank you
