### ISSUE TITLE
Put in bold letters the following:

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#28]
-the Greek form of the name
-the Radical 1
-the Radical 2
-the Suff.1
-the DELG references (i.e. the Greek word following s.v.v. or s.v.)

**Comment by tuurma** [comment]
done for the Greek form and Radicals/Suff, extracting last one into separate issue
![screenshot 121](https://cloud.githubusercontent.com/assets/449468/12626340/2683a344-c530-11e5-8aed-7b4990600d74.png)
