### ISSUE TITLE
Adrano/Andrano-doros, another doublet with no access to delete one of them

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#286]
Dear Magdalena,

No access to any of those to names.
Andranodoros is to delete BUT its bibliography has to be put with the right form of the name, which is : Adranodoros.

Could you, please, make the change or allow us to re-edit Adranodoros ?

Many thanks.
Best,
Sophie

**Comment by tuurma** [comment]
I did not encounter trouble with that. Since the correct version was with Andranodoros, I first deleted the other one, then renamed Andranodoros to correct Adranodoros, saved (which re-created Adranodoros as separate entry) and finally deleted no longer necessary Andranodoros record.

**Comment by Hippodamie** [comment]
Many thanks, dear Magdalena.

And what about the Structure change ? Did you understand my answers and requests ? May you do the change ? How long will it take ? And when could you do it ? ...Because we are waiting for it before editing new names...

Have nice holidays if it is the case for the next few days.
With best wishes,
Sophie
