### ISSUE TITLE
new design for Segmentation & root interpretation section

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#288]
@hippodamie Dear Sophie, how do you like this version of the form
![screenshot 285](https://cloud.githubusercontent.com/assets/449468/20262656/086fb026-aa5b-11e6-8b45-f368bde9cc17.png)

and a view with drop down list open

![screenshot 286](https://cloud.githubusercontent.com/assets/449468/20262680/1c9bfa0a-aa5b-11e6-8dc2-98ae9875ddb0.png)

I think it reflects our email discussion, not sure about placement of **Irr** though, as I don't know if it is a characteristic of a single compound or rather the whole name? In the latter case I'd move it to the top line, next to 'Structuration & Semantics of the Complex names' drop down. Let me know what you think before I finish implementing the details.

**Comment by tuurma** [comment]
I've found your note on Irr, saying
> Irr = irrational = the compound name makes no sense. 2 ideas/notions have been just put together but they do not make any phrase. Another label could have been « Aphrasal » but I prefer to keep with Irrational, which was created by a great onomatologist specialist of ancient Greek names, Olivier Masson.

so I take it needs to be considered as characterizing the name as a whole and therefore belongs to the top line 


![screenshot 287](https://cloud.githubusercontent.com/assets/449468/20263149/485450dc-aa5d-11e6-8670-5c5f3126bf33.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

We have finished the lists of the suffixes of the 4 levels in the frame of the Proceedings of our previous conference SAGA.
Could you please put the last suffixes to add to the lists of the Edit window?

Here are the items:
No new S4 item.

— S3 list, add:
ίων (at the end, after ιχ)
ων  (at the end, after ίων )

— S2 list, add.:
(ϝ)εσσ (between (ϝ)εν(τ) and ιππ)
ων  (between (V)νν et ιαν): Current order to change in such a way that we finally have: αιν, (V)νν, ων, ιαν, (V)ν(δ), (V)ν(θ).

— S1 list, please:
1.Change -ον into: (έ)ον,  AND:  (V)τᾱ/ης into: τᾱ/ης
2. Μerge, please: έᾱς/είᾱς and έης/ῆς into: έᾱς/είᾱς/έης/ῆς.

3. Add.:
ην  (between εύς and ήν)
τᾱ/η  (between ς and (V)τᾱ/ης)  
τις (between τηρ and τος)
τος  (between τις and τωρ)                   We will have thus: τᾱ/η, τᾱ/ης, τηρ,  τις, τος, τωρ, υς.
ά̄(ϝ)ων  (between ων and ωρ).

The end !
Many, thanks again.
With best wishes,
Sophie
