### ISSUE TITLE
Hi, Magdalena. How are you ? 2 bugs. Could you help to repare ?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#290]
We cannot work on 2 sub-form windows. Those of the Roots: βιλ(λ) and βρουκ. Cannot add the meanings. No boxes visible anymore... 

Thanks in advance for your help.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
Fixed, I think, thanks for letting me know.
