### ISSUE TITLE
Theudagoras: the place of N(oun)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#294]
Look at the Structure column, where Noun comes after Z: we have N-V N (Z(Noun)YX,);
we should have: N-N-V N (ZYX).
And Noun has not to be written in full.

Thanks for your help.
Best,
Sophie

**Comment by tuurma** [comment]
Many thanks for pointing this one out, I've made a mistake and a. put the wrong value in the list for prefix functions and b. bound it with the wrong attribute in case of prefixes. Fix coming in a minute.

**Comment by tuurma** [comment]
Already fixed on a server, luckily we only had it in case of Theudagoras, so no harm done.
