### ISSUE TITLE
Androlas: the place of AbbrC

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#295]
Hi, Magdalena,

Look at Androlas Structure: currently N-N(XY(AbbrC)<YX,).
We should actually rather have: N-N (XY<YX AbbrC) [with a space before AbbrC].
So, is it that we should have put AbbrC rather at the top, near Irr ??? Or ALSO at the top ???
Since with: XY/YX Irr  there should be also a space before Irr.

We could have before AbbrC:
a. XY AbbrC
b. YX AbbrC
c. X AbbrC
d. Y AbbrC
e. XY/YX AbbrC
f. XY/YX Irr AbbrC
g. YX>XY AbbrC   etc. (all the items of the pop-up list).

Thanks for your help.
Best,
Sophie

**Comment by tuurma** [comment]
ok, no problem and no need to change anything in the form, will adjust the display in a moment
related #293

**Comment by Hippodamie** [comment]
Answer to your email:

OK, you are right. We would better need for Androlas, not the current with parentheses: 
N-N(XY(AbbrC)<YX) 
BUT rather: N-N (XYAbbrC<YX)

So:
a. no parentheses anymore around AbbrC
b. a space between the functions labels and the first parenthesis
c. no space anymore before AbbrC.

What do you think?

MANY thanks for the comma and Noun gone away!
Best,
Sophie

**Comment by Hippodamie** [comment]
Actually, it could be clearer to have the things between parentheses under the functions labels, I mean in another line, just under the former.

**Comment by tuurma** [comment]
I think now it looks as requested. Let me know how you like it :-)
