### ISSUE TITLE
In the search results, pur 'previous 1 2 3 next' at the top right, too

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#30]
when we read all the list of the results after searching for e. g. Πολύξενος, we have at the bottom right : previous 1 2 3 next. Could you put the same also at the top right of the list of the names: it would be more user friendly to have both

**Comment by tuurma** [comment]
already in place, pasting a screenshot
![screenshot 118](https://cloud.githubusercontent.com/assets/449468/12625114/308aa69a-c52a-11e5-9f18-f2e2c4622a73.png)
