### ISSUE TITLE
Hi, dear Magdalena ! How are you ? Abanthis

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#305]
A problem on Abanthis. No more saving is possible and no modification ...

Could you, please, help ?

Many thanks in advance.

I am almost finishing the About LGPN-Ling, but only in French at first. Hope I will give it to you (in French) in a few days.

Best wishes,
Sophie

**Comment by tuurma** [comment]
Sure, I'm a bit tied-up at the moment but I will try to have a look tonight or tomorrow.

**Comment by Hippodamie** [comment]
Many thanks, but take it easy, please !!!
Best,
Sophie

**Comment by tuurma** [comment]
At first glance everything worked for me, but then I noticed that suffix -is is not showing in the drop down box, even though it is present in the data and shows in visualization and after playing with that I can't save the document anymore - as you report. I will need to investigate what is going on there but can only get back to it in the evening. My apologies for the inconvenience.

**Comment by Hippodamie** [comment]
Ok, thanks, I am waiting : no access for me at the window right now. Just see the xml page.
Have a nice day.
Best,
Sophie
