### ISSUE TITLE
Hi, Magdalena ! How are you? Hope you are all well. A modification of the Dialect(s) label

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#307]
Could you please change the Dialect(s) label at the top of the column in the visualization window into:

Dialectal/Areal,
Bilingual                             French: Dialectal/aréal, 
                                                       bilingue

Many thanks in advance.
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Dear Sophie, for spatial economy's sake we have tried to keep labels rather brief.

I would also appreciate clarification (strange spacing here confuses things a bit), do you mean:

English label:
>Dialectal/Areal, Bilingual

French label:
>Dialectal/aréal, bilingue

**Comment by Hippodamie** [comment]
Dear Magdalena,

Yes !
Could you please also (finally) change Preroots into Prefixes in both English and French?

With alla thanks and best wishes,
Sophie
