### ISSUE TITLE
Hi again, Magdalena ! Problem on visualization of Pre-root Label N & Z: Theudagoras

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#308]
Dear Magdalena,

Could you please, help ?
It is edited but we do not see it in the visualization.
Many thanks.
Have a great day !
With all best wishes,

Sophie

**Comment by tuurma** [comment]
Sure, will look into it. Thanks for letting me know.
17 lut 2017 12:19 "Hippodamie" <notifications@github.com> napisał(a):
