### ISSUE TITLE
replace 'covering semanticFields' by 'semantics'

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#31]
In the search interface, replace 'covering semanticFields' by 'semantics'

**Comment by tuurma** [comment]
should the French version stay 'champs sémantiques' or should I turn it into 'sémantique'?

**Comment by edouardchiricat** [comment]
Dear Magdalena,
Please change that too into 'sémantique'.
Thank you for integrating the requests into the interface!
All best,
Édouard
