### ISSUE TITLE
Capitalization of roots

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#311]
I tried to fix an error edited on the label of the Root, which was written: Aba-i-d as a label with dashes...
Impossible. I tried so many times that the access to LGPN-Ling is now out.

Could you please fix this Label as it should be and make the access possible for me ?
And make the loading normal? 

Many thanks in advance,
best wishes,
Sophie

**Comment by tuurma** [comment]
Sure, looking into it now.

2017-03-03 14:59 GMT+00:00 Hippodamie <notifications@github.com>:

**Comment by Hippodamie** [comment]
Μany thanks: I understood why I was wrong: not typed Abaid with the capital; thus could not find in the box menu.
Sorry for that, Magdalena !
Best,
Sophie

**Comment by tuurma** [comment]
Two remarks:

- it is, as you noticed important to stick to the same spelling
- on the other hand, morphemes, I believe, should *not* be capitalized, so I'd go for 'αβαιδ' there...

I notice page loads for over 2mins, which is of course unacceptable, I wonder why and will aim to fix that as soon as possible.

**Comment by Hippodamie** [comment]
Please, I don’t understand « morphems ». Isn’t it Root?
In the subwindow, we have Labels and Roots.
A  question: where could we put capitals, since we would like to for names made already of other names (and not of words or words roots in the lexicon)? As for example Hermes the god, see Hermandridas.
If not in the Root, would we put capitals for the sole Label and/or for the Constituent?

**Comment by tuurma** [comment]
To answer your question: I believe roots should be in general lower case except when they are a proper name in themselves as Hermes
