### ISSUE TITLE
spaces in morpheme identifiers

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#314]
And no entrance possible in the Morphems sub-window for hᾱγε̄̆μ which I have to modify.

Thanks for your help.
Have a nice day.
Best,
Sophie

**Comment by tuurma** [comment]
Fixed now, there was a problem again with extra space after hᾱγε̄̆μ

2017-03-22 10:16 GMT+00:00 Hippodamie <notifications@github.com>:

**Comment by tuurma** [comment]
Performing a sanity check to see if this same problem affects other morphemes, I found that

4 morpheme labels (identifiers) contain a space which should not happen. These are:
```xml
<category xmlns="http://www.tei-c.org/ns/1.0" baseForm="μᾱτερ " ana="#mother #Mother_Goddess">
<catDesc>μᾱ-τ(ε)ρ</catDesc>
</category>

<category xmlns="http://www.tei-c.org/ns/1.0" baseForm="οιτ 2" ana="#destiny">
<catDesc>οιτ</catDesc>
</category>

<category xmlns="http://www.tei-c.org/ns/1.0" baseForm="κτᾱσ " ana="#procure_for_oneself #acquire">
<catDesc>κτᾱ-σ</catDesc>
</category>

<category xmlns="http://www.tei-c.org/ns/1.0" baseForm="αργ 2" ana="#Argos">
<catDesc>αργ</catDesc>
</category>
```

These morphemes are used in 36 name entries. I will fix them tomorrow if that's ok.

```xquery
for $i in collection('/db/apps/lgpn-ling-data/data/taxonomies')//tei:category[contains(@baseForm, ' ')]
return ($i)

for $i in collection('/db/apps/lgpn-ling-data/data/names')//tei:m[contains(@baseForm, ' ')]
return ($i, $i/ancestor::tei:entry//tei:orth)
```

**Comment by Hippodamie** [comment]
Sorry for that: you can fix it, many thanks !
Problems with Login for me this afternoon, no access to the ddb.

**Comment by Hippodamie** [comment]
Dear Magdalena,

I have still to be able to save modifications in edit of Hagetorinos and all the names in Agemon… And failure to save everytime  !!!
Help !
It is very time-consuming !
Thanks for your help !
Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

Sorry to disturb a sunday !
Just to tell you that we worry about around 30 names edited yesterday and totally disappeared on LGPN-Ling (not even counted in the around 3200 names edited).
Until you tell us, I think we will not edit any other name.
Have a good sunday.
Best,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

here's the list of names edited yesterday (Mar 25th). What time did the
missing edits happen? Could you give me an example of one of the missing
names?

Theaidētos 2017-03-25T10:05:58.449+01:00
Aiglōn 2017-03-25T08:49:11.446+01:00
Agon 2017-03-25T08:45:31.313+01:00
Harmotta 2017-03-25T08:17:14.365+01:00
Hagētoridas 2017-03-25T08:22:44.996+01:00

Best,

Magdalena


2017-03-26 11:44 GMT+01:00 Hippodamie <notifications@github.com>:

**Comment by Hippodamie** [comment]
Dear Magdalena

Missing names begins with Autokrata edited on Friday 24, the last one saved on saturday night is Aphêgoumenos. Αutokrata is still there, but not the latter et the other in between.
Thanks for your help. But could wait until tomorrow morning.
Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

Just to let you know that nobody is able to work today. Only 3 names edited and saved his morning.
Give us please news when you can.
Best,
Sophie
