### ISSUE TITLE
A list of 4 bugs.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#316]
Hi, Magdalena,

Revising the morphems list this afternoon, here are some bugs:
1. no access to the morphem window for (h)εανο, where meanings are still missing. It never opens.

2. Ἀφηγούμενος. Morphem: (h)αγε̄̆-ο-μεν is twice AND meaning are laso repeated twice. Failure to save also.

3. (h)ᾱγε̄-το̄̆ρ: the same meaning repeated twice. No way to fix it.

4.(h)ᾱφαιστ: twice AND meaning are laso repeated twice. Failure to fix it.

Many thanks in advance for your help.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
2, 3 and 4 all had two entries in morpheme list, with slightly differing labels (see screenshot below).

Could you possibly give me a name where 1 occurs? Can't find this morpheme anywhere.

![image](https://cloud.githubusercontent.com/assets/449468/25207408/40e61c20-2566-11e7-8285-eb262c6a9652.png)

**Comment by Hippodamie** [comment]
Ηι, Magdalena.
The only name is Ἀφηγούμενος
Many thanks for your help.
Best,
Sophie

**Comment by Hippodamie** [comment]
For (h)εανο, the only name is Agreanos, with 2 hypotheses of analysis. In the second one, there is a new Root (h)εανο, where I cannot enter to add the meaning.

Thanks for your help.
Have a great week!
Best,
Sophie

**Comment by Hippodamie** [comment]
If I did not already answer for Ἀφηγούμενος, I must say that the only label I would like to keep is:

Label: hᾱγε̆-ο-μεν   Root: (h)ᾱγε̆-ο-μεν 

Many thanks for your help.
Best,
Sophie

**Comment by tuurma** [comment]
Right, now I found the (h)εανο, thanks for providing the name where to search.
The other thing was already fixed on Friday/Saturday I think. Please reopen if it still persists.

**Comment by Hippodamie** [comment]
Dear Magdalena,

How is the weather in Athens, how many degrees? Here we freeze !
Many thanks four our poor hεανο and the others, χθο̄̆ν etc. ! 

A remark: it seems that you changed the dash between the Pref., R1, R2 Meanings into a +. It is actually impossible because our compound names does not work at all syntactically as juxtaposed (which could be symbolized by a +) (or only very rare names among them, some of the XY/YX), but they are compounded, which means that there is a syntactical link between the elements (they form a phrase or a clause). Thus, I propose that you change the new + into a new dash, not the short dash as in an English translation as in old-fashioned, but a larger dash, the long dash maybe, so that each dash be quite different in visualization.

What do you think? The dash let understand the link without presupposition about the kind of syntactical link. It is quite neutral. Exactly what we need.

Could you please also add the Dialectal/Linguistic labels I told you:

— Indigenous
— Non Greek
— Latin
— Greek-Ital.
— Greek-Celt.

Of course, more urgent for you: to have time after your classes to wander through Athens and enjoy !
With all best wishes,
Sophie

**Comment by tuurma** [comment]
Hi,

I don't think we still have '+' anywhere? I changed '-' (hyphens) into longer m-dashes, let me know if that's what you had in mind?

![image](https://cloud.githubusercontent.com/assets/449468/25389209/de6f3b38-29c7-11e7-9839-8b37b28c089b.png)

**Comment by Hippodamie** [comment]
It looks quite well, except the fact that there is no space before the m-dash, which does not look pretty, but it is a detail.
Thanks !
Best,
Sophie
