### ISSUE TITLE
French version of About LGPN-Ling and visualization of French Roots meanings

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#317]
Dear Magdalena,

It is very important for the fundings application to the French Agence nationale de la recherche that the whole text of ‘Sur LGPN-Ling’ be in French.
I sent you 2 pdf in each version, but only the Introduction and the beginning of Avertissement (Forewords) are in French, everything else in the French version is actually in English, as in the English version.

Another fact that I cannot explain is that now we do not visualize anymore the French translation of meanings in the Roots meanings column.

Could you please help ?

Many thanks in advance.
Best,
Sophie

**Comment by tuurma** [comment]
Sorry, I have added full French version few days ago but must have accidentally revert to the former state. I will work a bit to make both French and English look neater today, but it takes quite a lot of time.

**Comment by Hippodamie** [comment]
Dear Magdalena,

Help ! G. Genevrois is not able to work : difficult access to the Edition of new names and not saving possible... and difficulties again for the function Search: asking for Login many times and a window with Ajax reference as I sent you appears… !
Help !

Many thanks,
Best,


Sophie

**Comment by tuurma** [comment]
Dear Sophie,

problems with saving and asking for login are very much related issues. I'll see what I can do and let you know as soon as possible.

**Comment by Hippodamie** [comment]
Dear Magdalena,

Thank you for your help.
Best,
Sophie
