### ISSUE TITLE
Ηι, Magdalena: impossible to delete the following morphem (see screenshut). Best ! S.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#320]
![capture d ecran 2017-04-29 a 21 24 23](https://cloud.githubusercontent.com/assets/16923546/25558219/68c92db8-2d22-11e7-9382-39b29fb7736b.png)

**Comment by tuurma** [comment]
As far as I can see at the moment, there are 4 names using this morpheme, so deleting is blocked. Could you please confirm if it is still a valid issue for you, or was it some momentary hiccup?

**Comment by Hippodamie** [comment]
Dear Magdalena,

Before I have time to answer about #320, 2 things I would like to be improved.

There is a real problem for me (and not forGenevrois, fortunately): not only I am everytime asked to Login going from edition to list of morphems and back and often when I try to modify in the EDition window, BUT I am very often confronted to a failure of saving. And each time I ask Genevrois to try to do what I would have done by myself if I had be able to do it, he is successful ! What is good for our work but make us lose lots of hours, because I have to explain and to copy for him what I wanted to insert.

So really I spend, I would say, almost 1 or 2 hours in a day losing time with those problems (=things I cannot finalize by myself)). That is why I spoke the other time of « desperating » .

Could you please give me as easy edition conditions as to Genevrois, Chuat or Nieto ?

Many thansk in advance.
Have a nice day.
All best,
Sophie

**Comment by tuurma** [comment]
Can we arrange for a Skype call, so we could investigate what causes
trouble for you? I have to admit that some of the last issues you
registered I were not able to reproduce (and as you say your collaborators
also), so I suspect that something in your particular setup causes
difficulties.

**Comment by Hippodamie** [comment]
Hi, Magdalena,

I do not have any Skype address anymore, but will try to get one.
What is yours ?
Would you be available for that tomorrow morning, I mean Wednesday, around 9 a. m. (your time, if you are in Oxford). The hour is up to you. Or later in the day. But I won’t be available after 4 p. m. 

Thanks in advance.
Best,
Sophie
