### ISSUE TITLE
Why shall I ever Login when I go from Search to Morphems and the other way? Best. S.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#322]

**Comment by Hippodamie** [comment]
Ι must add that every time I try to go from the Edition of the names to the Morphems list, I transit always by the About LGPN-Ling page.

**Comment by tuurma** [comment]
As demonstrated during screen-sharing session earlier today, trying to open the editor for a name results in  need to log in; immediately after the name is loaded but not the meanings for morphemes and, likely as a result of that failure, it is impossible to save the name.

This scenario seems to persist on Sophie's workstation but does not surface for myself, when logged in as Sophie, nor for any other user of LGPN-Ling.

As a test, Sophie will try to work from a different computer and see if she can reproduce the issue.

**Comment by Hippodamie** [comment]
Hi Magdalena,

It seems that it worked almost normally in my son’s computer (a Mac too, but with a more recent system Sierra, I am stil on Yosemite).

What I will do this afternoon is to load a new version of Safari.

Then, if necessary, try to update my system, what I never do.

So I come back maybe tomorrow to tell you how it works.

Many thanks for your help.
Best,
Sophie
