### ISSUE TITLE
Hi, Magdalena. Bugs happenend since the 30th. Strange visualization for the names:

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#326]
Ἀγαλίδας Agalidas
Ἀγώι Agōι
Ἐπαγήλας Epagēlas
Ἀθαύμαντος Athaumantos.

Could you, please restore them in their usual visualization?
Many thanks.
Best,
Sophie

**Comment by tuurma** [comment]
Fixed after update

![image](https://user-images.githubusercontent.com/449468/34155386-66be9bf8-e4b9-11e7-92fe-9f9deb81a6e2.png)

**Comment by Hippodamie** [comment]
MANY, many thanks, Magdalena !
