### ISSUE TITLE
Hi, Magdalena ! Visualisation bug appeared when I deleted the high hypothesis of Aristas2

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#328]
Help !
Best,
Sophie

**Comment by Hippodamie** [comment]
I explain to you that I tried to delete the radical στα since it was its unique example and I think it does not exist.
I tried it twice. It told me deleted.
But it does not seem to have been really, since it is still visible, but with a zero.
Best,
Sophie

**Comment by tuurma** [comment]
Could you please clarify which radical you wanted to delete?

![image](https://user-images.githubusercontent.com/449468/31878420-5365c290-b7da-11e7-9803-96d6a59f9295.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

Thanks for your message. I cannot find the name associated to that στᾰ Root, here in orange, the first one. I would like to know what it is before I answer to which one is to delete. Could you find it yourself ?
Many thanks in advance.
Have a good day.
with all best wishes,
Sophie

**Comment by tuurma** [comment]
It appears on Antistatēs / Ἀντιστάτης

**Comment by Hippodamie** [comment]
ΟΚ! Thanks ! So, the only one to delete is the zero markedbelow:  στᾱ-ντ standing (up).
Many thanks in advance;
best,
Sophie

**Comment by tuurma** [comment]
The superfluous root I have deleted and I can't see any problems with visualization of Aristas2 nor other names (see #327) thus closing this issue.

**Comment by Hippodamie** [comment]
Dear Magdalena,

We still have 2 Hagēmōn, both dated 03-28 : one is to delete.
Could you please do it ?
Many thanks for what you did.
Best,
Sophie
