### ISSUE TITLE
Entry form: GPR/Fict. categorizations

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#332]
/estimate 4h

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/33884237-32828da6-df3f-11e7-8674-b1ad9bd22eab.png)

```xml
                  <gramGrp type="classification">
                    <gram type="fictitious"></gram>
                    <gram type="GPR"></gram>
                  </gramGrp>
```

**Comment by tuurma** [comment]
Requires adding `@type='segmentation'` to other instances of `gramGrp` and following adjustments to the xforms bindings.

**Comment by tuurma** [comment]
https://github.com/eXistSolutions/LGPN-ling/issues/330#issuecomment-351062365

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/33889553-ba10a210-df50-11e7-906a-1bdaa4c8a19b.png)

**Comment by Hippodamie** [comment]
This precise order you propose could be better kept.

For the next element, remember, I changed its label (linked name)) into : Significant relative name ; in the box: e.g. son or e.g. father ; next box: the Greek form.

Thanks for what you already did. Good work.
I am back around 9.
Best,
Sophie
