### ISSUE TITLE
Entry form: Linked LGPN name (s./f. of)

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#334]
/estimate 4h

**Comment by tuurma** [comment]
Label: Significant relative name

**Comment by tuurma** [comment]
sketch in https://github.com/eXistSolutions/LGPN-ling/issues/332#issuecomment-351058389

**Comment by tuurma** [comment]
Proposed TEI structure utilizing `<re>` element http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-re.html
```xml
<entry ...>
   ...
  <re><form><lbl>son</lbl><orth>Ἀγκυλίων</orth></form></re>
</entry>
```

**Comment by tuurma** [comment]
Hidden by default

![image](https://user-images.githubusercontent.com/449468/33942571-a9a7126c-e016-11e7-9aa5-d14bf13761fb.png)

Can be added via + button

![image](https://user-images.githubusercontent.com/449468/33942639-d1a4799e-e016-11e7-8613-bdaf1d2c51f3.png)

**Comment by Hippodamie** [comment]
Yes,  Magdalena,I think it is correct.
Different of  (morphological) « variants », which are supposed to have exactly or nearly the same meaning.
Thanks !

**Comment by Hippodamie** [comment]
Wonderful ! Since, actually, we will not add it very often. So it is a good point not to have it always visible
Best and many thanks,
Sophie
