### ISSUE TITLE
Entry form: Most ancient dialect

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#336]
/estimate 4h

**Comment by tuurma** [comment]
![dialects](https://user-images.githubusercontent.com/449468/33950304-5e25a978-e02c-11e7-9099-6bb10df85c5a.jpg)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/33952499-41880f9e-e032-11e7-8156-4e3032dda9bb.png)

**Comment by Hippodamie** [comment]
Perfect !!!

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/33989892-6af2e1e6-e0c9-11e7-9236-188a7ff9f219.png)

**Comment by Hippodamie** [comment]
I think it looks perfect !
