### ISSUE TITLE
Entry form: Name variants

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#337]
/estimate 8h

**Comment by tuurma** [comment]
related to #333 

currently we have several forms of a name: Greek, Latin transliteration and a form which may contain parenthesized parts (H)

![image](https://user-images.githubusercontent.com/449468/32392135-99fc8376-c0d4-11e7-87de-f59b3aa7f62a.png)

```xml
          <entry xml:id="Ἁβροτέρα">
              <form type="lemma">
                  <orth type="greek">Ἁβροτέρα</orth>
                  <orth type="latin">(H)abrotera</orth>
                  <orth type="variant">Habrotera</orth>
...
            </form>
...
      </entry>
```

**Comment by tuurma** [comment]
The design for name variants has been simplified (as per Sophie's email of Nov 30th)

![image](https://user-images.githubusercontent.com/449468/33880128-e7e3555e-df30-11e7-8a61-4ae080ae2c1f.png)

**Comment by Hippodamie** [comment]
Hi, Magdalena.
Yes, I confirm.
Best,
Sophie (not anymore available until toonight)

**Comment by tuurma** [comment]
Entry form will allow adding as many name variants as is required

![image](https://user-images.githubusercontent.com/449468/33881812-46b37604-df36-11e7-84f6-df66d53dde0f.png)

**Comment by tuurma** [comment]
There is no name variant by default, may be added via + button as required 

![image](https://user-images.githubusercontent.com/449468/33881969-d587eab8-df36-11e7-9817-1834d90056ea.png)

**Comment by tuurma** [comment]
@hippodamie shall I move the `gender` field to the left, preceding the variant form itself?

**Comment by Hippodamie** [comment]
Yes, please.
All perfect before this email, except that detail.
