### ISSUE TITLE
Taxonomies: adjust suffixes

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#343]
@hippodamie could you kindly remind us which suffix lists need adjusting?

**Comment by Hippodamie** [comment]
Dear Magdalena,

Thanks for your message.
Here is the answer:


Addditional suffixes labels ορ correctionσ:
Suffixes 1 Box
Correction of:    /ή (ligne 4) into:           ά̄/ή
Αddition of: 
– ῶς (at the end of the list)
– ής (under ης without accent)

Suffixes 2 Bοx: Αddition of:        ᾱ(ϝ)ων (between (V)νν and ων)

Suffixes 3 Box: 
Delete accent on /ι/ of  ίων
Add:
ε̄̆(ϝ) (between ιδ and (V)κ)
ᾱ(ϝ)ων (between ιχ and ων)
(V)κ (before (V)λλ) 
(V)ν (before (V)ν(ν))
(V)(ν)τ (after (V)ν(ν))
(ϝ)εντ (after (V)(ν)τ).

Many thanks in advance.
With all best wishes,
Sophie
