### ISSUE TITLE
Help: an entry has disappeared after I had worked in it: name Ancharenos/Ἀγχαρηνός.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#345]
Dear Magdalena,

Could you, please, make it appear again?
I cannot understand why it happened : I saved and remarked after the entry was not visible anymore.

Many thanks in advance,
best,
Sophie

**Comment by tuurma** [comment]
Hi, the entry is still there under http://admin.exist-db.org:41233/exist/apps/lgpn-ling/editor.xhtml?id=Anchar%C4%93nos but I can confirm it can't be found with search in the visualization table. I will be travelling to Canada all day tomorrow but will try to fix the problem as soon as possible.

**Comment by Hippodamie** [comment]
Good new, thank you, Magdalena : have a good journey and a good time overthere (I remember where you go, Victoria).
But very strange matter...
Many thanks to have take the time to answer though busy before leaving.
With all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

Now, I think I guess why it disappeared: it is because I have deleted the segmentation and root interpretation.
And this name has indeed, by the fact, to be deleted, but I could not do it anymore, since I did not see it anymore.
The name is not Greek, but Latin : that is why it has not to be in the database. Thanks to you, I can now note the bibliographical arguments.

So, to fix it, could you please, really delete it ?
Many thanks.

With all best wishes,
Sophie

**Comment by tuurma** [comment]
No problem, deleted the name.
