### ISSUE TITLE
Ηι, Magdalena !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#347]
After I deleted the segmentation part of the name Agrimios and edited again to add a new Root (αγρι-μ), the Greek and Transliterated form of the name disappeared in the Visualization window.
Look at the screenshot.
Could you, please, make them
![capture d ecran 2017-12-04 a 08 20 18](https://user-images.githubusercontent.com/16923546/33540735-ad606e18-d8cc-11e7-9586-086ff810af98.png)

 visible again ?
Many thanks.
Best,
Sophie

**Comment by tuurma** [comment]
They're back

![image](https://user-images.githubusercontent.com/449468/34155137-769b4040-e4b8-11e7-9821-b0411b6b86af.png)

**Comment by Hippodamie** [comment]
Many thanks !
