### ISSUE TITLE
A quite ancient bug: no search possible of the Αγαθ/Agath names.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#348]
Could you, please, make it possible ?
Best,
Sophie

**Comment by tuurma** [comment]
I think it's fixed now

![image](https://user-images.githubusercontent.com/449468/34155217-bfbba1de-e4b8-11e7-9ba5-42997ce75219.png)

with 113 entries starting with Αγαθ found

![image](https://user-images.githubusercontent.com/449468/34155257-e1c41298-e4b8-11e7-8f6b-1201426dad71.png)

**Comment by Hippodamie** [comment]
YES !!!!
