### ISSUE TITLE
Entry form: align preroot treatment regarding abbreviated compounds with Root

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#350]
Dear Magdalena,

I have totally forgotten we need a AbbrC box also for the Preroot level.
Since a name like Amphias is an AbbrC but the amphi- element is a Preroot. Since the box does not exist, we are currently obliged to edit amphi as if it was a Root1, which is false.

Thanks to add it too. We will pay for that too.
Did you already begin to work for LGPN-Ling today?
Is everything OK for your work or do you need more explanations?
Just let me know.
Best,
Sophie

**Comment by tuurma** [comment]
@Hippodamie I have added the Abbr checkbox and linked compound as in Root1/2 sections

![image](https://user-images.githubusercontent.com/449468/34054161-f9116e7e-e1c9-11e7-972f-a153ce9f2698.png)

**Comment by Hippodamie** [comment]
Thanks but… not forget we need to be able to put an optional asterisk in front of the linked compound AND an obligatory ‘e.g.’ before the Greek linked compound:
The whole meaning is:       Abbr. (of) e.g. (= exempli gratia = for example) [linked compound]. The e.g. must always appear, maybe even in the Edition window, but for sure in the visualization.

The information ‘linked compound’ is only indicative, never totally sure.
Best,
S.

**Comment by tuurma** [comment]
Is there a problem just to precede the name in the linked compound box with an asterisk? Otherwise we could have an extra box with `*` standing for a whole class of names

**Comment by Hippodamie** [comment]
The asterisk is for names which could exist but are not yet attested. So actually, I must say that we need an optional asterisk box.

**Comment by tuurma** [comment]
* for preroots

![image](https://user-images.githubusercontent.com/449468/34082333-40f5ec72-e35c-11e7-9405-aaf3d31b9ffe.png)

and roots

![image](https://user-images.githubusercontent.com/449468/34082334-540eac22-e35c-11e7-8f0c-97ed551da160.png)

**Comment by Hippodamie** [comment]
Hi, Magdalena ! It looks perfect. Many thanks,
best,
Sophie
