### ISSUE TITLE
Hi, Magdalena: there is a bug in the name Amasos visualization

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#351]
Dear Magdalena,

Could you, please, fix the following bug of mine?
Thanks for your help.
Have a good week-end.
![capture d ecran 2017-12-08 a 19 01 25](https://user-images.githubusercontent.com/16923546/33779001-662bcfd8-dc4b-11e7-93a0-dd03fec1355b.png)

with all best wishes,
Sophie

**Comment by tuurma** [comment]
Fixed with the app update
