### ISSUE TITLE
Entry form: make all references bound to a particular segmentation

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#354]
cf discussion in https://github.com/eXistSolutions/LGPN-ling/issues/338#issuecomment-352076224 and below

summary:

all lexical and onomastical references are to be bound to a particular segmentation hypotesis

reconsideration of existing TEI structure and conversion of existing records will be required

**Comment by tuurma** [comment]
conversion still missing and thorough testing required

**Comment by tuurma** [comment]
some problems when adding new bibl. entries for multi-hypothesis records

**Comment by Hippodamie** [comment]
Dear Magdalena,

Thank you very much for for your messages.
Please, let me know. I am the whole day until 9. in front of the computer, not looking everytime because I have to prepare my conference, but looking often !
Good work: I hope you will find a solution today.
With all best wishes,
Sophie
