### ISSUE TITLE
Entry form: uncertainty marker for dialects

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#355]
cf #342

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/34153155-635ad5c4-e4b1-11e7-88c4-2d23e1c58e29.png)

**Comment by tuurma** [comment]
@hippodamie would you like it also for dialects in name variants? I assume yes

![image](https://user-images.githubusercontent.com/449468/34153386-23719942-e4b2-11e7-99f1-4331e0da7880.png)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/34153463-6b3dfa54-e4b2-11e7-94dc-7279ddc97bb9.png)

**Comment by tuurma** [comment]
Adjusted and compacted Name variants section slightly

![image](https://user-images.githubusercontent.com/449468/34153679-3004b5ee-e4b3-11e7-9a93-962d1c501798.png)

**Comment by Hippodamie** [comment]
Hi, Magdalena !
I saw you got rid of the quote box in Onomastics Modern references : wondeful, hope it did not waste too much time of your time.
Perfect for that, thanks !
Sophie
