### ISSUE TITLE
A request: Last change of titles for Dialects. Change into Dialectal area/Bilingual

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#358]
Dear Magdalena,

Could it be, please, easily changed into Dialectal area/Bilingual ?

And the same at the Variants level, for the currently Dialect box.

Sorry for that. I reported the change in many work documents weeks ago, but forgot to tell you those last days, because we were busy with many other subjects.

Best,
Sophie

**Comment by Hippodamie** [comment]
Places are perfect.
Wording to change : not Dialectal area/Bilingual BUT: Dialectal/Areal/Bilingual
Thank you !
Best,
Sophie

**Comment by plutonik-a** [comment]
@Hippodamie Ok, noted, will change the wording to "Dialectal/Areal/Bilingual".

**Comment by plutonik-a** [comment]
Done with https://github.com/eXistSolutions/LGPN-ling/commit/02dacf60247b23b6cdc264cd44eebada618e2ebf

Test url: http://admin.existsolutions.com:55221/exist/apps/lgpn-ling/editor.xhtml

<img width="665" alt="bildschirmfoto 2018-04-27 um 11 56 28" src="https://user-images.githubusercontent.com/1157669/39357319-d719e7d6-4a12-11e8-91e7-7678e4c33812.png">

<img width="633" alt="bildschirmfoto 2018-04-27 um 11 56 52" src="https://user-images.githubusercontent.com/1157669/39357330-e176ccee-4a12-11e8-8fd8-9295f28cba23.png">

**Comment by Hippodamie** [comment]
Wonderful ! Better is the first with « Chek if uncertain ».

**Comment by plutonik-a** [comment]
@Hippodamie 
> Better is the first with « Chek if uncertain ».

What does this mean? Do you want to change the wording of the second screenshot also to "check, if uncertain" instead of a question mark?

**Comment by Hippodamie** [comment]
OK, I misunderstood, sorry !

I answer again.
In your Dialects schema, do you think it is necessayry to repeat Dialectal/Areal/Bilingual, after the first time ? Maybe nothing to write the second and third time.
AND for Uncertain, maybe rather write:
the first time:
Uncertain
and the ? after the cross/box.

And for th second time, not write again UNcertain, but just have the ? after the cross/box.

To avoid unnecessary repetitions.

**Comment by tuurma** [comment]
@plutonik-a @Hippodamie 

If I may, I'd suggest that all boxes that we use to mark uncertainty are consistently labelled. In majority of cases we use just `?` instead of help text `(check if uncertain)`, so I'd stick to that.

![image](https://user-images.githubusercontent.com/449468/39759032-c92c5e48-52d1-11e8-8aa7-917fea014121.png)

**Comment by Hippodamie** [comment]
Hi, Alexandra : yes, of course, you are right !
Best,
Sophie
