### ISSUE TITLE
Example (not real) of the fullest Lexis box we could have  + Logeion link + Visualization

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#36]
Below is the example in the order of the lines we would like, with the best presentation/visualization.
It will happen that the first Source would be another name (with a link possible to the line of LGPN-Ling for this name?).
Then, 3 sources with their references, the last one not quoted.
Then 3 lexicographic references : DELG, CEG & Beekes, EDG.
Be careful: sometimes  Beekes, EDG (which is online but expensive access) will be the only reference (without DELG).

PRESENTATION/VISUALIZATION of the fullest Lexis box (rare with so many informations):
To have a narrower column, is it possible to have not only 1 line for the quotation, but more superposed, and 1 different information per line, as:
Cf. Αἴνετος.
ὡς πάντα σφι ἀγαθὰ 
ὁ Τρηχίνιος ξεῖνος ἀγγέλλοι.
Ηdt. 7.226.8. 
ἄγγελος γὰρ ἀγαθὸς συμπορεύσεται αὐτῷ.
Sept. Tobias 5.22.1. 
Cf. Thgn 163.
DELG s.vv. ἀγαθός, ἄγγελος (Logeion) 
CEG 2 (1997)&11 (2006), s. vv. ἀγα-, ἀγαθός 
Beekes, EDG, s. vv.

QUESTION about Logeion links:
1)Since DELG is not online right now but Logeion is: could it be possible to put the Logeion link on both ἀγαθός, ἄγγελος and write the line as (the parenthesis will mean "link is to Logeion". The 2 greek words + Logeion will be in blue, meaning linked): 
DELG s.vv. ἀγαθός, ἄγγελος (Logeion).CEG 2 (1997)&11 (2006), s. vv. ἀγα-, ἀγαθός. Beekes, EDG, s. vv.

2) If Beekes comes first or alone, then:
Beekes, EDG, s. vv. ἀγαθός, ἄγγελος (Logeion).

3) Other special case, with 4 Logeion links (ἀγαθός, ἀγα, ἄγαμαι & ἀγητός) if possible:
DELG s.vv. ἀγαθός, ἀγα-: cf. ἄγαμαι, hom. ἀγητός: ἄγη+τος? (Logeion).

Best, Magdalena, with many, many thanks.

**Comment by tuurma** [comment]
subject already raised with #34
