### ISSUE TITLE
Create front-end development environment

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/LGPN-ling#360]
* create minified CSS and JS with a build automation
* update with latest development packages
* create database upload automation for local development

**Comment by Hippodamie** [comment]
Wonderful, because we would like to be sure we save our datas very soon, since we are at work and do not have already the  visualization corresponding to the updated app !
Many thanks,
best,
Sophie

**Comment by tuurma** [comment]
@Hippodamie sorry to disappoint you but this is about the input form :-) But we will work on the visualization side too, don't worry.

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/LGPN-ling/pull/365
