### ISSUE TITLE
Visualization: dialects

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#362]
cf #357
@hippodamie please describe the intended content for this column

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/34454444-00b65970-ed6c-11e7-8cf6-3f7a3cf51127.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

Thank you for your work, but...
we should have the other (grey) Greek names exactly under the first one (in black).
The gender, in the Gender column, just like for the first name above ; the dialect, in the Dialects column. One information by column and by line.
A last point : ‘etc.’ is clear enough. Not necessary to have ’et cetera’.
Many thanks in advance.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/34481438-771746ae-efb2-11e7-8508-ffb390af1b7f.png)

**Comment by tuurma** [comment]
Already installed on the server

![image](https://user-images.githubusercontent.com/449468/34481984-81936556-efb5-11e7-9154-4859938f6c0e.png)

**Comment by Hippodamie** [comment]
Wonderful, Magdalena !
Thank you very much !!!
I come back in the afternoon on GitHub with small Visualization troubles.
with all best wishes,
Sophie
