### ISSUE TITLE
Visualization: references

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#363]
cf #357
@hippodamie please describe the intended content for two columns with references

**Comment by tuurma** [comment]
Dear Sophie,

could you let us know if you are happy with how Lexis and Onomastique columns are displayed now?

![image](https://user-images.githubusercontent.com/449468/39761778-45d324fc-52d9-11e8-9584-7046ce8609ca.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

1. We would like not to see the commas.

2. We do not need Details be in italics. 

3. We would like only Reference be in italics.

4. We sometimes need to begin with Cf. or Contra or Pace or even Voir aussi [see also]. We do not know really where to put those logical connectors. When there is an author name, we write it before, in the author box, when there is only a Ref, like HPN, OGS, we put it before it, in the Ref box. I guess there will be a problem to make the catalog of the Ref and authors...

That’s it.

**Comment by tuurma** [comment]
Thanks Sophie. Your points 1, 2 and 3 are very clear and we'll take care of them. 4 as you rightly feel needs discussion because we need to keep them out of author/ref boxes. I will start a separate issue for that.

**Comment by Hippodamie** [comment]
Very well, thanks !
Best,
Sophie

**Comment by tuurma** [comment]
Results of applying fixes for pp. 1-3

![image](https://user-images.githubusercontent.com/449468/39776485-51db2c7c-5301-11e8-9108-065b5f7da219.png)

**Comment by Hippodamie** [comment]
Very well !
