### ISSUE TITLE
Visualization: structure

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#364]
cf #357
@hippodamie please describe the intended content for this column

**Comment by Hippodamie** [comment]
Dear Magdalena,

for your work of next week : 
I put all 3 needed sketches in the same Word document (= pdf) 
[Sketches new visualization Janu2018.docx](https://github.com/eXistSolutions/LGPN-ling/files/1584339/Sketches.new.visualization.Janu2018.docx)
[Sketches new visualization Janu2018.pdf](https://github.com/eXistSolutions/LGPN-ling/files/1584340/Sketches.new.visualization.Janu2018.pdf)

I think it is clear and you will understand very well and quickly.
I will not be connected at all (no connected Iphone) next week. But I am sure you will do well without me! I am totally confident.

**Comment by Hippodamie** [comment]
Hi, again,

an additional (not very important) mention, forgotten in the file above:
N.B.6 : the Gender information for variants could be missing (thus not visible), if it is the same as for the master-name, as is the case for Theogenes and its variants, see A.
Thanks,
best,
Sophie

**Comment by tuurma** [comment]
Structure example for Areiphos

![image](https://user-images.githubusercontent.com/449468/34453931-866c9820-ed5f-11e7-8d97-a5a632ea1ed3.png)

and corresponding entry form

![image](https://user-images.githubusercontent.com/449468/34453924-5fee1b7e-ed5f-11e7-9be1-2c8f049bec77.png)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/34454041-66f38596-ed62-11e7-8402-8c55d71e6449.png)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/34454100-71a845b6-ed63-11e7-83da-cc613a1f8874.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

I wish you a HAPPY NEW YEAR and all the best for your life and for the children new life !

I answer to each emails.
Many thanks for having fixed LGPN-Ling for Gerard.
We do not need to search for the linked name.
 (…)

**Comment by Hippodamie** [comment]
Perfect : thanks a lot, Magdalena !
