### ISSUE TITLE
Quote box for content informations currently between () in the Details boxes ? Rather than to keep those informations in that Detail box?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#367]
Dear Magdalena,

Ie seems that you were perhaps right to put quote boxes (as you did and as I asked you to delete) even in the Modern references. I just realised it, looking at the same boxes in Lexis references, with some explanations in parentheses, which are like quotations of the modern authors.

Before asking you perhaps to put again the quote boxes in Modern references in Onomastics (is it a very quick and small work for you?), I would like to ask you a question.

In the TEI process, could/should we put theses types of informations in quote boxes ? (it is not an exact quotation of the modern author [we have real quotations of the ancient authors in the quote box of our Sources level], BUT it it rather a synthesis WE make of HIS arguments)

For the web (not for the printed book, () are enough for the book), should we better put the informations we used to put between () in the detail box (after the pages numbers), in another box, perhaps called quote ?

Please, could you answer before the week-end, since Gerard Genevrois will be at work the whole week-end…

AND another linked question: would it be easy for you to make the conversion yourself, like automatically : everything between parentheses moved from Details in another (Quote) box ?

many thanks in advance,

with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
I found the answer myself ! We keep the parentheses, which are only useful for LGPN-LIng and not to be shared with other projects (I mean, their content only by itself).

But we do not need thus Quote boxes in Lexis Modern References. Could you, please, make them disappear? Thank you very much.

With all best wishes,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

I think that any information which you might want to treat separately
should ideally be in its own box. We could rename 'quote' as 'note'. I
don't think using parenthesis is a foolproof method, since you may want to
use it for other purposes too. Thus I would suggest leaving the 'quote'
boxes and just giving them a different label. It is very dquick andd easy
to do.

Magdalena

PS Apologies for the late reply, I was already travelling for Christmas

**Comment by Hippodamie** [comment]
Dear Mgdalena,

But in this case, we should have them be put again in Onomastics Modern references too, as you had put them at the beginning...
But the other point is that they should come at the same place as currently between their parentheses, I mean AFTER Details. And have, yes, the name of Notes.
And as the conversion work is hudge for us, would it not be possible to convert automatically all that is between parentheses into the new Notes boxes? It would be especially necessary in Onomastics, where there are almost always parentheses for each modern reference...

They were bugs, yesterday and today. Gerad had to stop. But I did not want to disturb you on Christmas days.

But as I am not connected from the 26 to the 31, I put the sketches already. Hope it will be ok for you.

I wish you a very happy Christmas and would like you not too work those days, but relax and enjoy.
With all best wishes,
Sophie
