### ISSUE TITLE
A complex Bibliography box example, with a commentary in parentheses

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#37]
3 references, the 3rd one (NIL) being more complex : commentary between () ; 2 etymological hypotheses ordered as high, then low, both possibles ("or" & ?). 1 different information per line for this complex reference. The content/commentary of NIL is summarized between ().

_HPN_ 7+11
Ferrary, _Onomatologos_, p. 36.
_NIL_, s.v. _meg- 
(_mgh2-dhó-, Pinault, _MSS_38, p. 166) 
or_ LIV2_, s. v. *geh2dh- ?

Many thanks, Magdalena. I have to think now about (again) the 2 columns Structure and Semantics, which still does not work well.
I come back to you on this subject as soon as possible.
Best,
Sophie

**Comment by tuurma** [comment]
mentioned in #34, closing this one
