### ISSUE TITLE
To improve visualization, not to repeat the same information

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#371]
Dear Magdalena,

I take as an example Arsinoe again.
Here is the screenshot.
[Document8.docx](https://github.com/eXistSolutions/LGPN-ling/files/1598294/Document8.docx)

In the red circle are the 3 informations lots that we do not need visible when there are more than 1 hypothesis.
The question is nonetheless, if you make them not visible anymore, how to make clear the difference between the morphological variant of the name (Arsinoa) and the low analysis hypothesis of the name? Since both are currently in grey.

I think the better way would be: 
a. not to repeat twice the Arsinoa formal variant, which would be enough if only visible at the end, AFTER the 2 hypotheses.
b. to let in black the low analysis, all columns, since it happens that both hypotheses are in the same level of certainty. So grey is not good. Brey only for the formal variants, as currently.

A remark: the way you present the linked compound to the XY AbrC names, in smaller is a success! Many thanks!

Many thanks for all.
Good night,
Sophie

**Comment by tuurma** [comment]
closed with #357
