### ISSUE TITLE
Dialects labels order : different order in Edition and in Visualization: is it normal?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#372]
AND no ? visualized, see for example Atoklea, variant, sub Aristokles.

Thanks,
Sophie

**Comment by tuurma** [comment]
@Hippodamie could you please confirm

Name variants for Aristokles are as follows:

```
Ἀριστοκλέης
Ἀριστοκλέας
Ἀριστοκλεῖς
Ἀρισστοκλῆς
Ἀστοκλέας
Ἀσστοκλέας
Ἀστοκλείας
Ἀστοκλίας
Ἀριστόκλεια
Ἀριστοκλέα
Ἀριστόκλια
Ἀτοκλέα
```

with visualization 
![image](https://user-images.githubusercontent.com/449468/34525934-f641c672-f0a0-11e7-93a0-bc4fb6b341c3.png)

I can't notice any discrepancies in ordering though confirm missing ? marker for Ἀτοκλέα
![image](https://user-images.githubusercontent.com/449468/34525974-2b17cbee-f0a1-11e7-96c7-e66803b670a4.png)

**Comment by tuurma** [comment]
fixed the uncertainty markers, please reopen if you still observe ordering problems

![image](https://user-images.githubusercontent.com/449468/34526521-f82dee6e-f0a2-11e7-9461-81e42f5af9d8.png)

**Comment by Hippodamie** [comment]
Yes, I confirm.
