### ISSUE TITLE
Still to visualize

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#373]
1. GPR is not visible, see for example Argyros.

2. Significant relative names, see Asias.

3. Polysemic, see Arsinoe.

4. The second element of complex lables as XY/YX, see Archiereus.

Good night.
With all best wishes and many thanks for your work,
Sophie

**Comment by tuurma** [comment]
@Hippodamie could you please remind me where polysemic ? marker should go in the visualization?

**Comment by tuurma** [comment]
4 
![image](https://user-images.githubusercontent.com/449468/34525405-1d5c3f00-f09f-11e7-9b13-5693b36fdd41.png)

**Comment by tuurma** [comment]
2 for the time being I've put it under transliterated version

![image](https://user-images.githubusercontent.com/449468/34525456-503de87e-f09f-11e7-8ff3-dd65e6e63c72.png)

**Comment by tuurma** [comment]
1
![image](https://user-images.githubusercontent.com/449468/34525496-6d385ba8-f09f-11e7-803d-44bb1991916d.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

It was for the book, but I wonder if it will be useful. It is redundant since it only means that we have more than one hypothesis.
I think it could be deleted, actually.

Many thanks for all !
I come back for GPR in another email.

**Comment by Hippodamie** [comment]
Dear Magdalena,

1.e.g. is missing, just as for XYAbbr
					e.g. Ἀρσινόη.

2. We would like to have it between parentheses:
(e.g. s. Ἂσανδρος)

3. We would like to have it under the Greek form of the name. If there is also a {Ἀβγ...} mention, we would like to have the () mention under the {}.

4. It is totally necessary that we have exactly the same system of mentions as in the lgpn Database.
Thus, not ‘son’, ‘father’ BUT
f. or s. (which actually means in the other db: ‘father of’ or ‘son of’) or d. or m. 

Many thanks again,
I go to GPR…

**Comment by Hippodamie** [comment]
Not too pretty : could you please add a space between GPR and Argyros…
Many thanks for your work !
With all best wishes,
Sophie

**Comment by tuurma** [comment]
GPR (added space)
![image](https://user-images.githubusercontent.com/449468/39762044-f37c72fc-52d9-11e8-8e41-adfebe8ec3d5.png)

Significant relative
![image](https://user-images.githubusercontent.com/449468/39762208-5829f62a-52da-11e8-8d10-571b45df676a.png)

Second element of complex labels
![image](https://user-images.githubusercontent.com/449468/39762313-8f6d8fca-52da-11e8-87f5-ed6ed398d98d.png)

**Comment by tuurma** [comment]
@Hippodamie 

Dear Sophie could you let us know if you're happy with the above and what else (if anything) is necessary for polysemic names such as Arsinoe?

**Comment by Hippodamie** [comment]
Great ! Thank you !

**Comment by tuurma** [comment]
In general we need to distinguish between different views we can have on names. Current visualization table is intended for overview/proofing for editors. As a reference for general public we should also have a separate page for each name, where we can rearrange the display not bound by the table structure. Third view will of course be for the future book.

As this issue regards only adjustments necessary for the visualization table to reflect structural changes we made, I would like to close this issue.
