### ISSUE TITLE
?,  for Dialects labellization

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#374]
Dear Magdalena,

No way to make appear the ? after, for example, Greek as a dialectal label, see Arnestes.
Could you, please, help ?
Best,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/39099825-d5bd54da-4680-11e8-93c4-0fe89c849e90.png)

**Comment by Hippodamie** [comment]
WOnderful, thank you, Magdalena !
