### ISSUE TITLE
Same references repeated in both Lexis and Onomastics visualizations

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#376]
Could you, please, help?

See for example Arsinoe and Ariôn.

Best,

Sophie

**Comment by tuurma** [comment]
I cannot reproduce, visualization seems okay

Arsinoe: high hypothesis

![image](https://user-images.githubusercontent.com/449468/39099698-092a6828-467f-11e8-9d5b-46b1eda62c8d.png)

low hypothesis:

![image](https://user-images.githubusercontent.com/449468/39099705-25963aa0-467f-11e8-89c6-38b76c463158.png)

**Comment by Hippodamie** [comment]
Yes, it is now ok !
