### ISSUE TITLE
Ηelp, Magdalena: a disaster on Semandros, I just modified (N V label) ! All repeated in the first case of visualization. Thanks, S.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#378]

**Comment by tuurma** [comment]
Investigating this. Symptoms are exactly the same as the range index
corruption we have encountered before.

**Comment by Hippodamie** [comment]
Yes… exactly the same.
What did I do : there were 2 POS labels (V and N, if I remember well), and I took off the V label…
Good night,
best and many thanks anyway, because, for Gerard it went well today,
Sophie
