### ISSUE TITLE
Hi, Magdalena : bugs this morning with (H)adrianos, Semandros (already yesterday)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#379]
![capture d ecran 2018-01-12 a 08 47 37](https://user-images.githubusercontent.com/16923546/34864545-10ffdb72-f775-11e7-808f-fc4c0a20c251.png)

Same bugs as before you had to patch.
Curiously, there was a bug on Theudagoras (I went several times on its Edition window yesterday and changed a POS label = Adj this morning), which was solved by reopen and saving again.

I tried to reopen and save again several for Semandros and Hadrianos too, and all the infomrations went successively in the first and in the second case/box. I mean the form of the bug changed, but bug remained for those two names.

I must say that I will have to reopen lots of windows, like Gerard, as soon as I have time, and even on week-end, I think.

Have a good day,
best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

Here is a screenshot.
There are for a long time some problems of duplication (sometimes Abbr, sometime AbbrC) and sometimes it is visible BUT not in the edition window, and cannot be deleted in the visualization.
Could you, please, fix it?
Here for Akestos, no Abbr appears in the EDition window !
Many thanks in advance.
Best,
Sophie

**Comment by tuurma** [comment]
Could you please paste the screenshot again, I can't see it?

**Comment by Hippodamie** [comment]
I do not see any bug anymore. I think you can delete it.
I remember I have to deal with a small list you gave yesterday.
I do it very soon
