### ISSUE TITLE
Structure, Semantics columns, the end !!! Only replace Verb by Participle. Visualization: Adj Adv 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#38]
Dear Magdalena and EDouard,

No change for these columns titles.

The only thing to change in the EDit interface is:
to replace Verb by Participle (Participle will work for all these Roots that convey an idea which is at the same time nominal, verbal and adjectival).
The Abbreviations in the Visualization will be:
P, N, Adj Pro Adv
Sometimes we will have 2 at the same time as: Adv P
We could have then in a box (maximum): Adj N + Adv P.
Visualization:
Adj Adv (no Adj. Adv. anymore).

Many thanks
Best,
Sophie

**Comment by tuurma** [comment]
Could I ask to keep titles as short as possible to get the gist of an issue and more elaborate description in the comments below? In this case 'Structure, Semantics columns, the end' is not relevant, leaving just 'replace Verb with Participle' would be much clearer.

**Comment by Hippodamie** [comment]
ΟΚ ̣

**Comment by tuurma** [comment]
Perfect, thank you!

**Comment by Hippodamie** [comment]
Thanks, Magdalena !
