### ISSUE TITLE
New title for morphems both at the head of the list and as title as the sub-form AND column title

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#388]
Hi, dear Magdalena,

Could you please (or Alexandra) change the name of morphems into:

1. List of lexemes

and as the title of the sub form:

2. LGPN-Ling lexemes and meanings sub-form

3. Visualization title of the current Base/Root column:    Eng:. Lexemes        Fr.: Lexèmes
Exit: Bases/Roots

Many thanks,
have a good week-end,
best,
Sophie

**Comment by Hippodamie** [comment]
I more exactly mean:

2. LGPN-Ling lexemes sub-form

3. We will have thus for each of the 3 first columns of the Segmentation:
Préfixe     Lexème1        Lexème2
Prefix       Lexem1          Lexem2

That's it, now !
Best,
Sophie

**Comment by Hippodamie** [comment]
No, it does not work for Visualization, sorry !
So I am OK with 1 and 2 of the previous post, but for 3, Visualization, please:

We keep exactly the same as currently!
Because if we put 'lexems' in Visualization, it would be confusing with the lexems in Lexis.
Actually, the special lexems we create in the sub-form and which are listed should be called something like ‘onomatems’.
But lexems is good for the Edition (back office).
Best,
Sophie

**Comment by tuurma** [comment]
@plutonik-a 

* [  ] menu entry
* [  ] morphemes heading
* [  ] subform heading

1. menu entry to be changed into `List of lexemes`
![image](https://user-images.githubusercontent.com/449468/38735408-023dba40-3f29-11e8-8465-8e94e1cf3cd4.png)

2. morphemes heading  to be changed into `List of lexemes`
http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/morphemes.html

![image](https://user-images.githubusercontent.com/449468/38735454-22c5a822-3f29-11e8-883a-98db8b03c624.png)

3. subform heading to be changed to ` LGPN-Ling lexemes and meanings sub-form`

![image](https://user-images.githubusercontent.com/449468/38735787-27e5e3ca-3f2a-11e8-93fd-88b169ee0889.png)

**Comment by plutonik-a** [comment]
<img width="959" alt="01-menu-entry-388" src="https://user-images.githubusercontent.com/1157669/38744484-349dadc4-3f42-11e8-9175-ed1a9913f150.png">


<img width="670" alt="02-list-of-lexemes-header-388" src="https://user-images.githubusercontent.com/1157669/38744485-34be3468-3f42-11e8-90c2-509893608356.png">

**Comment by Hippodamie** [comment]
Wonderful, Alexandra: many thanks !
Best wishes,
Sophie
