### ISSUE TITLE
Ηι, Magdalena ! Could you please, help me for 2 urgent distinct things...

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#389]
Dear Magdalena,

I hope you are well.
1. We really urgently need: 2 new Suffix 1 labels: Ø and morphological lenghthening/allongement morphologique.

2. Could you please do not forget to fix Theudagoras and Arsinoe visual lines... for my forthcoming presentation?

Less urgent but necessary for the estimate to be payed of the whole:
when will you have time to make the following tasks of the estimate:

	1.	Data export into CSV
	2.	Review and change tracking functionality
 Or do you have to wait until you have fixed the index corruption?

I must say, I will have to make changes in nearly all the editions in the following weeks, because we decide to change the form of the Root and because of this change, the Suffix 1 will often be change into Ø. Consituants will change also... and sometimes we will have to modify the V, N etc. labels.
So lots of changes in view...
Matilde will begin to work everyday from February the 1st to do the same type of work as Gerard : pu together some current entries.

Have a nice week-end (here, first time it does not rain since... 5 weeks !),
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Νοt "morphological lenghthening/allongement morphologique", but vowel lenghthening/allongement vocalique.

Many thanks in advance.
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Please, Magdalena, postpone the Suffixes addition, not necessary for a while.
But CSV export is really urgent.
Is tracking a risk for slowness ?

Best,
S.

**Comment by tuurma** [comment]
@Hippodamie could you please confirm what is the status of Suffix adjustments?

**Comment by Hippodamie** [comment]
Dear Magdalena,

Not needed anymore. Replaced by the NEW S1 list I sent you 1 hour ago. To substitute the current S1 list.
Many, many thanks for what you did.
I post on GitHUb problems Gerard told me about.
all best,
Sophie
