### ISSUE TITLE
Apologies for a mistake at the top of the edition window

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#390]
Dear Magdalena,

Sublemma should not take place at the top. 
Actually, we need 3 sublemmas of the same shape, one for each Prefix/Root/Base.

Currently, as we just have worked on the lemmas list of the lexicon words beginning with α-, it is not a problem, but it cannot stay as it is.
I am totally sorry about that.
Apologies.

Have a good week-end,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Sorry for the delay, let's get back to this question soon. My advice would be to create tentative summaries for listings in the *book* format where sublemmas come into play.

**Comment by Hippodamie** [comment]
Do not understand exactly ‘tentative summaries for listings’...
