### ISSUE TITLE
3 Additional functional labels

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#392]
Dear Magdalena,

How are you ? 
We would need 3 more functional labels:

Participle/Participe, abbrev.: Part
Agent Noun/Nom d'agent, abbr. Engl. AgtN/ French NAgt
Action Noun/Nom d'action, abbr. E ActN/ French NAct.

Th order in the edition window would be thus:
V; Part; AgtN; ActN; N; Adj; Pro; Adv.

When could you do it?
with all best wishes,
Sophie

P.S.:LGPN-Ling works perfectly: THANKS a lot !
P.S.2:  could you please send me the bill of your work? Thanks in advance.
P.S.3: I am re-writing About LGPN-Ling. It is possible I send you a few other requests this week.

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/36842220-3982d2a6-1d4b-11e8-86d5-8c6a6b96cd35.png)
