### ISSUE TITLE
Editor: significant relative options

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#394]
Would it be long for you to add ‘woman’ to the mini-list ‘son, daughter, mother, father’? Actually, we discovered yesterday that ‘woman’ is missing and useful. I do not think ‘man’ would be needed. But it could be add also, to be sure.

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/36841305-33d89776-1d48-11e8-90fa-a4514e8e60c3.png)

**Comment by Hippodamie** [comment]
Wonderful ! Thanks you to the fairy !
