### ISSUE TITLE
New list Suffixes 1+ Genitives: a correction on the line -τις, τίς

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#396]
Dear Magdalena,

Here the list again.
Ready, now.
With all best wishes and thanks,
Sophie
[Liste S1 + génitifs février (bis, τις)2018.docx](https://github.com/eXistSolutions/LGPN-ling/files/1771356/Liste.S1.genitifs.fevrier.bis.2018.docx)

**Comment by Hippodamie** [comment]
No other changes in the other Suffixes lists. Only S1.
with all best wishes.
Sophie

**Comment by tuurma** [comment]
Do I understand you correctly that you will still select just one suffix from the dropdown, just it will list both Nom and Gen forms together without editors specifying which one is used in the name?

**Comment by Hippodamie** [comment]
No, maybe not.
I sent you the document yesterday, but had missed the double -τις/-τίς, which is needed.
Thus, you can delete the former version  and keep only the corrected version I posted on GitHub #396 [...février (bis, τισ)2018].

The aim is to add to each of the current Nominative Suffixes 1 their corresponding Genitive, so that we see both automatically.
I suppose it means you will have to add to each of the existing Nominatives in the current S1 list, the information ‘linked Genitive’ or something like that. Be careful: I asked to delete some suffixes and add some others. 
The aim is to see from now both, in the same visualization column. The Nominative form and just under it, the Genitive form. I explain the precise visualization on the document.

Do you understand better?
Thanks for your work.
Good night,

best,
Sophie

**Comment by Hippodamie** [comment]
Actually maybe you did understand well! The Dialect characterization is supposed to help to find his way through the several Genitive forms.
