### ISSUE TITLE
Problems in Roots deletion: does not seem to work!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#397]
Dear Magdalena,

When I try to delete roots (and I have a lot), one time it looks as if it had been done, but next refreshing, it looks as if not !
One time, I read 1522 entries, the other 1591.
Could you please help?
I need to delete all needed very quickly, if possible.
Many thanks for your help,
best
Sophie

**Comment by Hippodamie** [comment]
And ε̄σ- impossible to delete for some days.
Best,
S.

**Comment by Hippodamie** [comment]
Same for ϝρατα.

**Comment by tuurma** [comment]
I think I can see your issue

Searching for `ε̄σ`

![image](https://user-images.githubusercontent.com/449468/36866013-72a44dbc-1d91-11e8-9c8c-1f85b7d18abd.png)

Deleting and searching again

![image](https://user-images.githubusercontent.com/449468/36866114-ae77f4ec-1d91-11e8-9e9f-8ac2098dc348.png)

Note the extra whitespace in `baseForm` which led to problems

```xml
    <category baseForm="hε̄σ  " ana="#send #throw #let_go">
        <catDesc>(h)ε̄σ</catDesc>
    </category>
```

I have run through all other baseForms affected and fixed these.

For `ϝρατα` though deletion worked for me, just required refreshing the browser window.

**Comment by Hippodamie** [comment]
OK, Magdalena: many thanks for the white space information. Hope I will remember it.
Can I delete 10 by 10, as I tried, and not only 1 by 1? Because, I have a lot to delete.
Best,
Sophie
