### ISSUE TITLE
Forgotten 1 functional label: Verbal Adjective. So sorry, Magdalena !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#398]
Dear Magdalena,

Could you, please, add between Verb and Participle:
Verbal Adjective (French: adjectif verbal). English abbreviation: VAdj

Please, excuse-me for that. I am currently re-writing ‘About’, that I will ask you to put online in 1 month or before, with its English translation. By re-writing the 8., I discovered I did not ask you for the last label.

So much work, I try to work too fast.
with all my apologies,
best,
Sophie

**Comment by tuurma** [comment]
Had to shorten some of the labels to make them all fit

![image](https://user-images.githubusercontent.com/449468/36864031-c4eb83de-1d8b-11e8-8fb0-5c8ee9d18f1d.png)

**Comment by Hippodamie** [comment]
THANK YOU so much, Magdalena !
Perfect,
best,
S.
