### ISSUE TITLE
Hi, Magdalena, Suffixes1 Genitive list to postpone ! You are right...

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#401]
Dear Magdalena,

Many thanks for your always so pertinent short questions !
I realize (after night!) that you are right: not maybe the best solution to give several genitive forms each time we meet the nominative.

I have to think about it. Other way: only the most recurrent form of each genitive. And maybe give the full table as a page in the new About we currently re-write.

So, we wait for a while...
have a nice day,
best,
Sophie

**Comment by tuurma** [comment]
related to #396

As a rule of thumb: we can define in one place (ie suffix list) all Gen forms for a given Nom suffix. Which is easily done and likely should be done. When choosing a suffix from the dropdown list what happens is we are linking to the full record about the suffix. 

In this approach, we can't point to any particular Gen form as would be attested in the context of the particular name. Not sure it is relevant at all, but glad you do find my questions useful. I'm looking from the data modelling perspective, where fundamental rule is to avoid redundancy and thus inconsistency.

**Comment by Hippodamie** [comment]
OK, I deal with that later, of course. I am about to give anyway the table in the new About version.

How do you call in TEI marking the name which is used now as a main entry vs the others which are its variants?
Head-name, master-name, main name, main entry ?

Thanks in advance,
best,
Sophie
