### ISSUE TITLE
Φίλαργος· no acces to the subform. Does not open

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#402]
Dear Magdalena,

Would like to open the subform of Philargos and Argophilos:
to change αργ2 (maybe a white space?) into αργο    αργ(ο) Meaning: Argos, the city.

Could you please fix it, do ti or make possible for me to edit again?

These are the only occurrences of αργ2.
We do not need αργ2 as the label, but αργο.

Thanks for your help.
Best,
S.

**Comment by tuurma** [comment]
Changed the label `αργ 2` into `αργο`,  afterwards it was not a problem to change the names anymore.
