### ISSUE TITLE
Same problem for Aθηνοίτης: R = οιτ 2 (with a white space), 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#403]
Cannot change the Root since the subform does not open, cannot change anything, substituting another R for example. The box is blocked with οιτ 2.

What can I do ? The 4 occurrences should now be changed into οιτο    οιτ(ο), meaning unchanged.
Could you, please, do it?

**Comment by Hippodamie** [comment]
The 3 others occurrences are of course what you found yourself:
Ἀλκοίτας
῎Ανδροιτο
Ἀγροίτας.

Μαny thanks for Αγανω. Here, I can do it, it seems.
Thanks for your help for the former, or tell me what I could do.
Best,
Sophie

**Comment by tuurma** [comment]
Changed the label `οιτ 2` to `οιτο`, now it will be possible to use the new one in names.

```xml
    <category baseForm="οιτο" ana="#destiny">
        <catDesc>οιτ(ο)</catDesc>
    </category>
```

**Comment by Hippodamie** [comment]
Many thanks !
Have a good week-end,
best,
Sophie

**Comment by Hippodamie** [comment]
Thanks!
I must remember to review all of them again.
