### ISSUE TITLE
Hi, Magdalena: a technical question: how many Gigaoctets or so on currently? I am asked

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#406]
Dear Magdalena,

I am asked about the current size of LGPN-Ling and at the end with 35000 names studied ?

Thanks in advance for you answer,

with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Other question:
the programmation language ?
Thanks,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

LGPN-Ling system is a complex system, composed of:

* its data, represented as XML documents encoded with TEI,
* application code, composed of XQuery modules, HTML page templates, JavaScript client-side code, CSS stylesheets and auxiliary application specific data in XML
* eXist-db serving as data base management system, web server and application framework.

I could elaborate further on these aspects but it would make most sense if I knew how would you like to use it? E.g. we'd phrase things differently for technical audience than for funding application etc.

**Comment by Hippodamie** [comment]
Dear Magdalena,

it was not so important, I gave a kind of answer since they were in a hurry, and it seems it was enough. We keep these questions for another time, when ANR will ask (I guess next January, I will have a report to give: they will only need Gigaoctets or such general kind of answers, ranged according to the very 3 points you mention. To get an idea of the size of the project. It won’t be for funding application but for control of our fundings).

When do you plan to give a version to our LGPN-Ling for hosting by Huma-Num? Because that point is quite urgent. I mean I would like it to be done before summer or just at its end. Next september will be the deadline. 

Best,
Sophie
