### ISSUE TITLE
Here is the new Soft Nom + Genitive Suffix 1 list !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#407]
Dear Magdalena,

Here is the soft list.
The complete will be put on line inside the About LGPN-Ling new forthcoming version.
Could you, please, fix it ?
Or do you have any further question?

many thanks in advance,
with all best wishes,
Sophie
[Soft S1 list with Genitive to set online.docx](https://github.com/eXistSolutions/LGPN-ling/files/1789517/Soft.S1.list.with.Genitive.to.set.online.docx)

**Comment by tuurma** [comment]
Dear Sophie, sorry to get back to it so late but it's very difficult for us to understand sometimes what you mean. I tried to split all the tasks resulting from this request into separate issues. Could you help us please with getting the list in the format that is not ambiguous and tedious to process? I've extracted it into #421. Many thanks!

**Comment by tuurma** [comment]
same as #420 so closing this one
