### ISSUE TITLE
Athenoites: no access to the subform of the wrong οιτ 2

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#408]
Dear Magdalena,

Could you, please, fix this entry, to which we have no access?
Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Sure, no problem. Please note, that typing in the search box under the morpheme, you can always select another one from the list, which is all that is necessary to adjust a name.

![image](https://user-images.githubusercontent.com/449468/37144863-9af2d760-22bf-11e8-906d-4aa54ff83fb4.png)

**Comment by Hippodamie** [comment]
Of course, but nothing changed when I did it just for this name
