### ISSUE TITLE
Export: A copy of the data in GitLab

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#410]
A question: would it be possible to have a copy of the whole ? Actually to have several copies made every day. As you can understand, because of the hudge amount of work, especially from Gerard, I feel as unresponsable not to be able to have myself an everyday copy of our work.
It is also linked to the question of another copy of the interface hosted in the French TGIR Huma-Num.

**Comment by tuurma** [comment]
As part of the solution of providing HUMA-NUM with up to date copy of LGPN-Ling data, we could set up automated syncing with GitLab repo, from which HUMA-NUM could pull. No conflicts should arise as the workflow is one-way: from master eXist instance to the repo.
