### ISSUE TITLE
What appears to us as a presentation bug: the repetition of variants for each analysis hypothesis

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#413]
Another thing, this time we do not at all need:

for mulltiple hypotheses names (most often 2 or 3), we do not need to see repeated the variants for each hypothesis, see e.g. Alkandros.

Variants should come at the top, just under the lemma name or entry name, and then the 2 or more hypotheses, without the variants repeated for each of them.

The variants of the entry name of course have exactly the same Roots/Meanings/Structure analysis as it. 

Could you please, modify the current presentation/hierarchization?

Many thanks in advance.

Have a nice day,
best,
Sophie

**Comment by tuurma** [comment]
Current behaviour

![image](https://user-images.githubusercontent.com/449468/39099488-3674419e-467c-11e8-9cc8-f8f0fb511ee8.png)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/39099578-7e844050-467d-11e8-8721-25d513725643.png)

**Comment by Hippodamie** [comment]
We would like not to see what is on the screen shot: unnecessary ! 
We would like to keep the richest informations given at first (above), and could you please make not visible anymore the same which is repeated below, as you see on the screenshot?

**Comment by Hippodamie** [comment]
Better, but actually the best would be to have that below but in another order:
Alkandros
Alkandros
and then
Alkandre

BUT what would be perfect would be not to rewrite Alkandros and its Greek equivalent.

What I mean is :

Alkandros Ἄλκανδρος  first segmentation ;
then, second segmentation without repetition of the names ;
finally Ἀλκάνδρη.

Could you do it, please ?

Best,
Sophie

**Comment by tuurma** [comment]
Is that what you mean? To move name variants below last hypothesis?

![image](https://user-images.githubusercontent.com/449468/39100079-869ab4ca-4684-11e8-8fd2-5e8225a73d77.png)

**Comment by Hippodamie** [comment]
exactly

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/39111095-154e5a60-46d4-11e8-9d54-56ab0feab007.png)
