### ISSUE TITLE
Νames labellized as Abbr (sic) without any mark in the edition window ?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#414]
Hi, Magdalena,
How are you? When is your coming back on LGPN-Ling ?

Just to let you know we have names like Anthaion, Anthianos, Anthias etc., which are visualized as Abbr, but we did not put any mark about it in the Edition window!

What to do? We cannot delete these labels by ourselves. Could you please help?

Many thanks,
Have a happy Easter (with chocolate eggs for the children!),
Sophie

**Comment by tuurma** [comment]
Confirmed
e.g. http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/editor.xhtml?id=Anthyllis

![image](https://user-images.githubusercontent.com/449468/39098987-05115208-4673-11e8-9eb0-ef898965b5bd.png)

while TEI shows

```xml
                <gramGrp ana="" cert="high" subtype="" type="segmentation">
                    <m ana="" baseForm="" cert="" corresp="" function="" n="1" subtype="" type="prefix"/>
                    <m ana="Abbr" baseForm="ανθεσ" cert="" corresp="" function="N" n="1" subtype="" type="radical">ανθ</m>
                    <m ana="" baseForm="" cert="" corresp="" function="" n="2" subtype="" type="radical"/>
                    <m baseForm="" n="1" subtype="flexional" type="suffix">ίς</m>
                    <m baseForm="" n="2" type="suffix">(V)λ(λ)</m>
```

NB :  `<m ana="Abbr" baseForm="ανθεσ" cert="" corresp="" function="N" n="1" subtype="" type="radical">ανθ</m>`

Workaround is to check the Abbr box, save, uncheck, save again and then visualization returns to normal. Still unsure what is the underlying cause...
