### ISSUE TITLE
A bug on "significant relative name" at the top

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#416]
Hi, Magdalena, Hi Alexandra,

There is a recent bug on this function above.

It happened for Enrique Nieto, and seemed to be ok for us before, so it is a quite new bug, since Enrique began to work only on Monday.

We just see in Visualization "son" and not the Greek name he typed after.
And for example on   Chrysanthidas, "son" is 3 times repeated in Visualization.

Could you please fix it ?

Many thanks in advance,

with all best wishes,
Sophie

**Comment by tuurma** [comment]
Thanks for letting me know, will look into it.

**Comment by Hippodamie** [comment]
Always the same bug for Enrique NIeto : son appears and we cannot do anything to close it and take it off, after opening.

Many thansk for your help.
Best,
Sophie

**Comment by tuurma** [comment]
Fixed for Chrysanthidas

![image](https://user-images.githubusercontent.com/449468/39098794-56dea07a-4670-11e8-8640-dc3581526ffe.png)

We already have the delete buttons in the redesigned form, thanks to @plutonik-a work, so it should not bother you any more once we deploy that version (hopefully later this week).

![image](https://user-images.githubusercontent.com/449468/39098817-c1554abc-4670-11e8-96cf-ffaac62ee2a4.png)

**Comment by tuurma** [comment]
It was also the case for Haplos, fixed there as well

![image](https://user-images.githubusercontent.com/449468/39098841-2a9f7a42-4671-11e8-9f19-d152b67539a0.png)

**Comment by Hippodamie** [comment]
Hi, Magdalena! 

Ok, Super, many thanks to Alexandra too !
