### ISSUE TITLE
Rework form

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#417]
dialects section: it would be ideal if the delete button fitted on the same line as single dialect entry

![image](https://user-images.githubusercontent.com/449468/38734688-ce7cd6d4-3f26-11e8-8171-630c2e1095a0.png)

**Comment by Hippodamie** [comment]
Is it in relation with # 415 ? ?

**Comment by tuurma** [comment]
name variants section: if possible, please put controls in one line to save space or otherwise condense the entries

current form
![image](https://user-images.githubusercontent.com/449468/38735929-a1c8e50c-3f2a-11e8-8d19-4791eb09c682.png)

should resemble more the production version
![image](https://user-images.githubusercontent.com/449468/38735884-80030ef2-3f2a-11e8-9855-ad02509f8ae4.png)

**Comment by plutonik-a** [comment]
<img width="1002" alt="lgpn-ling-editor-417" src="https://user-images.githubusercontent.com/1157669/38738639-f297cdce-3f32-11e8-9bba-9c3f7e313768.png">
