### ISSUE TITLE
A bug on AbbrC for (H)ekasōn.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#418]
Hi, Magdalena,

how are you ?
I had to change from a compoun name with 2 Roots and the second abbreviated, into a single Root name.
I tried to take the cross off on Abbr. and did it in the Edition window, BUT in Visualization, we still have AbbrC.

Could you please fix it ? But every time we do this special change, the same happens.
Many thanks in advance.

Have a good week-end,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Well spotted!
