### ISSUE TITLE
Inflexional visualization (formerly Suffix 1)

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#420]
resulting from #407 

Flexional morphemes require more than just the base form:

* base form
* additional information (optional)
* genitive information 

![image](https://user-images.githubusercontent.com/449468/39111927-280b480e-46d7-11e8-95d6-f6db41dde27b.png)

e.g. 

base form:   -ις 
gen: 	ιος, -ιτος, or even -ιδος, Cypr. -ιϝος, rare -ίου

base form: -(V)τᾱ/ης
gen: Att. -του, Ion., A.M. -εω etc., Beot. -τᾱο, Dor. -τᾱ

with additional info

![image](https://user-images.githubusercontent.com/449468/39112291-529293d8-46d8-11e8-84a8-87bfe749792e.png)

base: -εύς
add: late -έους (Egypt) 
gen: Att., early Ion. -έως, A.M. -έος, late Ion. -εῦς

Visualization required:

![image](https://user-images.githubusercontent.com/449468/39112188-ff990ff4-46d7-11e8-9ef6-206fe9770d1d.png)

base form: both bold and italics for -ις (additional short dash) (14 pts);
gen: italics, and in smaller size (9 pts).

**Comment by tuurma** [comment]
Hi Sophie, where would you like this information to be presented? In the visualization table in Flex1 column or the About pages?

**Comment by Hippodamie** [comment]
I gave the full version in “About”.
But I gave you a “soft” list of each nominative with its corresponding genitive(s), which was made to be visualized in the Inflect1 column.
(Note that we call it now not Flect1 anymore, but Inflect1, as was already told Alexandra for the About text).

Th "visualization required" is exactly as we would like to see it, if it looks not too bad, what is difficult for me to imagine.

Best,
Sophie

**Comment by tuurma** [comment]
Hi, thanks for clarification. That's what I thought at first but started to doubt myself last night ;-)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/39805492-4d9fab3a-5377-11e8-8bb1-3429230ab5cf.png)

**Comment by Hippodamie** [comment]
Not very clear… What to do ?… 

1. Could you, please, add a blank line between Nom and Gen forms ?

2. Try not to have Mac. at right but always at left of the Greek form, as above.

3. etc. not in bold.

4. Try to put in bold only, as in my word doc., for Att., not the others. Th bold in my list was usually for Att. or sometimes Ionic or sometimes both of those 2.

Many thanks, it is almost done, I guess ! Wonderful what you do !
S.

**Comment by tuurma** [comment]
Added blank line. Minor typesetting issues can be resolved later with Alexandra, I will have to stop here. @plutonik-a please take over when you have a moment.

**Comment by Hippodamie** [comment]
Ok : thank you, Magdalena !

**Comment by tuurma** [comment]
@Hippodamie  
3. double ων stem from the fact that there are two entries with that base. Could you choose which one should stay?

```xml
    <option>
        <former>ων</former>
        <base>ων</base>
        <add>Thess. <i>ουν</i>, Pamph. <i>ω</i></add>
        <gen><i>-ωνος</i> or even <i>-ονος</i>, Thess. <i>-ουνος</i></gen>
    </option>
    <option>
        <base>ων</base>
        <add/>
        <gen><i>-οντος</i>, hence <i>-ωντος</i></gen>
    </option>
```

**Comment by Hippodamie** [comment]
We need both. 
I must say that we would have to create the new one, which is the -ων with Gen -οντος (the second one of the 2 below, in your xml lines).
The ancient one which is to use for 99% of the names in -ων has its Genitive in -ωνος ( the first one of the 2 below, in your xml lines).

How to do the change: input, I think, the first one everywhere. BUT, when you see « Part » in Structure box, and when it is a masculine name (which is quite rare, between 10 and 20 names, I guess), you are sure that it is the second -ων which is needed.

Do you understand exactly what I mean... ?

**Comment by tuurma** [comment]
Unfortunately we need to have unique identifiers. In that case we need to separate the suffix reading from its label (identifier).

**Comment by Hippodamie** [comment]
Why not to label 1 as : ων/ωνος and the other ων/οντος or without any bar/dash ?

**Comment by Hippodamie** [comment]
Αnyway, many thanks to Alexandra and you for the Visualization of Genitive : it looks beautiful !
Best,
S.
