### ISSUE TITLE
AbbrC instead of Abbr we would like to see... No AbbrC anymore, please...

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#425]
Dear Magdalena,

For example in (H)edytea, we have AbbrC and not Abbr. AbbrC is erroneous, so we would like the label always being Abbr and never more AbbrC.

I tried to take it off, to save then to refresh, then to come back and put the lebal back, but when it came back it was still the same AbbrC we would not like to see anymore on LGPN-Ling.

Could you please fix it ?
Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
```xquery
xquery version "3.1";
declare namespace tei="http://www.tei-c.org/ns/1.0";

for $i in 
collection("/db/apps/lgpn-ling-data/data/names")//tei:m[@ana="AbbrC"]

return 
    update replace $i/@ana with 'Abbr'
```

**Comment by tuurma** [comment]
Before

![image](https://user-images.githubusercontent.com/449468/39758485-4967dc74-52d0-11e8-8e21-85fad1404888.png)

After

![image](https://user-images.githubusercontent.com/449468/39758506-59089f06-52d0-11e8-99dd-bd16eb69a84e.png)

**Comment by Hippodamie** [comment]
Great !
Many thanks, Magdalena, and for (V)τ !!
Best,
Sophie
