### ISSUE TITLE
A new Suffix 3 to modify a little ! Currently τ, into: (V)τ. Thank you

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#426]
Dear Magdalena,

We have a Suffix3 currently : τ.
We need it to be transformed into: (V)τ.

Could you please fix it ?

Many thanks in advance,
best Sophie

**Comment by tuurma** [comment]
I have adjusted Suffix 3 list. 7 names were using τ instead of (V)τ.

"Ἀρχιερατικός"
2
"Ἀλκοτάδας"
3
"Ἀμφεωτίδης"
4
"Ἀπφουτιανός"
5
"Ἀλεξιτίδης"
6
"Αἰσχητάδης"
7
"Ὀροβιτηνός"

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/39757355-dbc8a5fc-52cc-11e8-9a9c-dd1e82a106b7.png)

Names using the old version converted with:

```xquery
declare namespace tei="http://www.tei-c.org/ns/1.0";

for $i in collection("/db/apps/lgpn-ling-data/data/names")//tei:m[@n="3"][@type="suffix"][.="τ"]

return update replace $i/text() with '(V)τ'
```
