### ISSUE TITLE
A bug on  current Suff1 -ός with accent: not available to edit anymore.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#432]
Dear Magdalena and Alexandra

There were until today 2 different -ος Suff1:
ος  Gen. -ου, -ω     and
ός Gen -οῦ, -ῶ

They are still in the autocompleting list in Edition window.
But, when you introduced the Genitive linked form, it happened as if the 2 were merged into a only one ος, without the accent.

See Alexamenos. It has a final accent: Ἀλεξαμενός on ός. 

When I tried to edit the ός form, nothing appears at all in the column of the Visualization window.
So only ος is now available ; not ός anymore.

Could you, please, remedy ?
Many thanks in advance,
best,
Sophie

**Comment by tuurma** [comment]
Hi Sophie,

looks like we had in the list the wrong unicode character, fixed now

**Comment by Hippodamie** [comment]
Very well, thank you, ouf !
Best,
Sophie
