### ISSUE TITLE
Α bug on ex Suff1 = now Inflect1: ίων. Not visualized anymore. See e.g. Aristiōn

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#435]
Hi, Magdalena and Alexandra,

Suff1 disappeared ! Could you, please, fix it?
Thanks in advance for help.
with all best wishes,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/40326595-1ce3097e-5d40-11e8-8f5e-609534fedf4c.png)
