### ISSUE TITLE
Other Suffixes1 currently not visualized anymore: (V)ία, (ι)άς and εύς

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#437]
Dear Magdalena,

I hope you spent a good week-end.
So, they are currently 4 Suff1 not visualized.

Could you, please, fix it?
Could we have a Skype meeting on next Thursday, the 17th, around 10.30 or 11 in the morning?

Have a pleasant week.
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
IN fact they are a total of 5:
ων, εύς, ία/η, ιάς and ίων.

Best,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/40326530-d5848f26-5d3f-11e8-90cf-d7a44da36bf0.png)
