### ISSUE TITLE
Hi, Magdalena. Help: a bug on a Root/base happened today

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#440]
Dear Magdalena,

An awful bug came back with a Root Gerard changed the form today morning !
Help ! Could you please fix it. I must say it looks for me as if our previous (a few months before) nightmare reproduces....
Look at the screenshot...

![capture d ecran 2018-05-18 a 19 17 43](https://user-images.githubusercontent.com/16923546/40248241-90bed9f4-5acf-11e8-930e-befc98375c85.png)

Thanks for your help: could the bug be contagious? Are we supposed stop to work?
Have a nice week-end!
With all best wishes,
Sophie

PS: we will have next time a talk about prospective for the whole project and connection with LGPN etc. Sorry, I did not prepare what you really expected of our meeting.
I have to find the time to think more about the future and to talk with people and partners about it, before coming back to you.
So we will have another talk but later in the summer, if you are again available.

**Comment by tuurma** [comment]
Don't worry,  it's nothing troublesome.  I will fix it as soon as I have
Internet working - technician is supposed to come again tomorrow.
Unfortunately can't fux from my phone. Please continue working,  hope to be
able to fix visualisation tomorrow.
18 maj 2018 19:16 "Hippodamie" <notifications@github.com> napisał(a):

**Comment by Hippodamie** [comment]
Thanks for your quick answer.
Look at that in Morphems list ! Gerard wanted to modify an ancient Root and I do not know what he did but it did not work goog and he deleted and made a new R, but I do not understand really the details...

![capture d ecran 2018-05-18 a 21 35 19](https://user-images.githubusercontent.com/16923546/40254258-044b80a8-5ae3-11e8-8756-4af871c26b21.png)

Have a good week-end.
Hope it will stay isolated as a bug !
Take care and relax !
Best,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/40325932-d3c8177c-5d3d-11e8-861d-68d96523e5f5.png)
