### ISSUE TITLE
A new bug !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#441]
Hi, Magdalena,

How are you ?
Here is a new bug: look at that !

![capture d ecran 2018-05-21 a 22 40 40](https://user-images.githubusercontent.com/16923546/40328698-952d48fc-5d47-11e8-8c7c-7c310ce4403f.png)

Could you please fix it ?
Many thanks in advance.
Good night,
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
son and of are separated by the Greek name instead to have
son of and then the Greek name.

Best,
Sophie

**Comment by tuurma** [comment]
already fixed with abf29a10f93fba61e5901ee6ce9ecc1375cc9f9d but due to some hiccup reappeared on the server; now fixed again

![image](https://user-images.githubusercontent.com/449468/40499946-b55b8524-5f83-11e8-9f98-be275095fea0.png)
