### ISSUE TITLE
Hi, Magdalena ! A new label ‘Interlinguistic’ to add

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#442]
Dear Mgdalena,

How are you?
Could you, please, add Interlinguistic, in the Dialectal list, just after Lallname?
Many thanks in advance.
Have a nice day !
With all best wishes,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/40499687-f9afd578-5f82-11e8-9105-1acc527feee2.png)

**Comment by Hippodamie** [comment]
Many thanks, dear Magdalena for all you fixed an added.
Wonderful for this one ! Could you, please, make the initial /i/ of interlinguistic capitale: thus Interlinguistic?
Many thanks.
Good night !
Best,
Sophie

**Comment by tuurma** [comment]
No problem, done.

**Comment by Hippodamie** [comment]
Wonderful : I knew !
Many, many thanks for all !
With all best wishes,
Sophie
