### ISSUE TITLE
Invisible names !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#443]
Dear Magdalena,

Just to let you know: names are sometimes not searchable but they have been edited.
For example, yesterday evening, before 6 pm, I serached for Epias and Epimenôn, which were supposed to have been edited by Enrique the 21st and 22nd of May, and when I called them (in fact i called for Επιμεν, but for complete Επιας), they did not appear as if they were not there. 
But they were and this morning, after having asked to Gerard, I saw them as was normal.

Could you please fix it? Because if we edit again with the idea that Enrique had forgotten to edit a few names, it would be a pity !

Thank you in advance for your help.

With all best wishes,
Sophie

**Comment by tuurma** [comment]
Επιας / Epias both return the same single name an Επιμεν / Epimen return same 4 names. Please note that upon your request we have changed the search behaviour so that it is case sensitive, thus search for eg `επιας` (lower case) won't find the name Epias, but Asklepias etc...

**Comment by Hippodamie** [comment]
Hi, Magdalena,

I do not understand what happened. Maybe I was too tired!
If it happens again, I come back.
I go on Git-HUb to ask you for 2 additional labels in the same box as Dev you added when we had our Skype.
See you,
Sophie
