### ISSUE TITLE
2 additional labels of the same level as recent Dev

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#444]
Hi, Magdalena,

Could you please add in the Complex names Structuration box just before Dev in the list, in the alphabetical order:
Deadj. [= Deadjectival]
Denom. [= Denominal]

and then comes our Dev [= Deverbal], to replace now, please,  by Deverb. (clearer).

So, we would have the end of the list as:
/YX
Deadj.
Denom.
Deverb.

Many thanks in advance,
with all best wishes,
Sophie

P.S.: when do you think you could deploy the new version?
Next week, monday or tuesday or wednesday end of afternoon would be great, from 6 if you send an email before. Or if you prefer at night around 10 pm.

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/40655699-739381a6-6342-11e8-8a4e-45ef20c83fb9.png)

**Comment by Hippodamie** [comment]
Many thanks, Magdalena !
Best,
Sophie
