### ISSUE TITLE
Ηι, Magdalena : no access anymore on LGPN-Ling for Gerard and I. Could you please help?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#445]
Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Could you please check now?

**Comment by Hippodamie** [comment]
Dear Magdalena,

How are you ? Did you get the paiement of the bill from EPHE?
It was OK again almost as soon as I told you. Maybe you did something.
Thank you anyway.
When will the new implementation be done?

Best,
Sophie

**Comment by tuurma** [comment]
Thanks, I will close the issue then.

Yes, got confirmation, that the bill was paid, thank you! I will get back to you about server update.
