### ISSUE TITLE
sanity check on morphemes

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#446]
Dear Magdalena,

How are you? I hope everything is ok for you. When will you have vacations? I know you work a lot and teach currently in Oxford, and will have a meeting with the team.

Since yesterday night, we do not have any access to LGPN-Ling, neither Gerard nor I (and I supposed Enrique and Matilde).
Could you please fix it ?

And could you please tell me when you think you could finalize what was almost ready (what Alexandra had set online and the new look of the edition interface)?

Enrique will have vacations after the 8th of August and until the 1st September.
In August, Gerard will work as usually, but me not so much for LGPN-Ling, so our work will be a little softer after the 8th. Just to let you know in case you need to stop LGPN-Ling for a few days. All worked very well since weeks, as you could see, since I almost never came to ask for help!

In September, I would be happy if you could come back to LGPN-Ling and if we could work together to make progress the Search interface part of the job. In my own schedule/planning, September would be the best, since as soon as my weekly research seminar runs again and all that goes with it, I am often overworking and not so available to work with you.

Many thanks in advance for your help and answer.

With all best wishes,
Sophie

**Comment by tuurma** [comment]
I am sorry I was very busy through September with a long journey to Japan for the TEI conference and additional 3 days of the TEI Council meeting. We have also released new version of the TEI Publisher so that left me very little time to work on LGPN-Ling. I will be much freer in October and happy to discuss requirements for the search interface.

**Comment by tuurma** [comment]
Will close this issue since server works fine now - let's arrange a chat on Skype to discuss search interface.

**Comment by Hippodamie** [comment]
ΟΚ, Ι understand very well.
So, I will wait and let’s have a chat on Skype if possible the week of October the 15th, the Wednesday the 17th would be perfect, at your hour. Or another day, except Tuesday.


Thanks a lot for διϝος.  About agora again, I deleted it, but it comes back as if not deleted.

And I am waiting to have it REALLY deleted, since I need after to change the αγορ   αγορ  you see into : αγορα  αγορα, what I cannot do if αγορα   αγορ(ᾱ/ο) does stil exist.
Could you please help ? It is my last request !

I must also tell you that deletion of Roots is very often chaotic : I delete, the message deleted comes. And after refreshing, the Roots are still there.

Thanks for your help,
best,
Sophie

**Comment by tuurma** [comment]
Looking for agora in the list, I cannot find it any more. Could you please let me know if there is still a problem?

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/449468/45807319-87ee8300-bcc3-11e8-904b-be523759a048.png">

**Comment by tuurma** [comment]
Dear Sophie,

thanks for detailed explanation. I had a closer look and found that γλυπhμα has appeared in the list of morphemes twice, once with some trailing whitespace. I have cleaned up this one and also other base forms where unnecessary space was present, but I will need to work a bit on the editing form to prevent this happening in the future.

**Comment by Hippodamie** [comment]
Dear Magdalena,

Many thanks for γλυπμ. 
I worked on αγορα, but do not find again the last name which was still edited as αγορ   αγορ(ᾱ). If you had still a little minute, could you, please, find the missing name? I am very curious to see how it looks, since I did, I suppose, all to find it...
Many thanks in advance.
Τhat’s all !
Best,
Sophie
