### ISSUE TITLE
New version LGPN-Ling with suffixes 1 with their genitives needed

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#447]
Dear Magdalena,

Hope you are well and were happy about the seminars you gave, and guess you are working at Oxford!
Could you, please, set the new version with the suffixes 1 and their genitives ? It is urgent now since we have already more than 8500 different entries and we need to be able to distinguish names with homonymic nominatives by their genitives. 
Of course more we wait to do it, more work we will have to re-enter the edition windows of all the names for which we have to change the suffix because of its new genitive form.

I am not available for that until the 6th of August. When will you have yourself vacations?
Many thanks in advance to plan it for us,
with all best wishes,

Sophie

**Comment by tuurma** [comment]
closing since this is covered in the recently deployed version
