### ISSUE TITLE
Hi, Magdalena ! How are you ? Sorry if you are in vacations. A short help asked...

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#448]
Dear Magdalena,

How are you? I hope you are well and maybe in vacations or already came back and had a very good time.

Could you please help me ?

I have to delete a root and to replace it by another one. It is a root with a lot of occurrences. I searched for all names, but 2 are still missing and I cannot find which one they are. Is is possible for you to make quickly this search?

The 2 names missing have as their current root
αγορα           αγορ(ᾱ/ο)

For all the other I re-edited it into:
αγοραο  αγορ(ᾱ/ο).

Ι need to find these 2 names so that I could delete
αγορα           αγορ(ᾱ/ο)

(which I need to re-make into
αγορα     αγορ(ᾱ)
 for other kind of names of this large family, that's why).

Many thanks in advance for your help.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
These names are Xenagion and Timagion, could you try to edit them please? I am not entirely sure what should I change them into - I guess αγοραο αγορ(ᾱ/ο) but don't want to make a mess if I didn't understand you correctly.

http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/editor.xhtml?id=Xenagion
http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/editor.xhtml?id=Timagion

**Comment by Hippodamie** [comment]
GREAT ! I did it.

Another similar issue, see infra: we have 106 occ of διϝος ‘(of) Zeus’,    BUT only διϝο ‘(of) Zeus, daylight’ is correct. 

Would it be easy for you to merge the erroneous διϝοσ into διϝο? So that we do not have to enter in the 106 windows of διϝος to make the substitution? And we get at the end 140 διϝο and no διϝος anymore?

If you can do it easyly, many thanks for your help.

Best,
Sophie

**Comment by tuurma** [comment]
No problem, accomplished with

```xquery
declare namespace tei="http://www.tei-c.org/ns/1.0";
for $i in collection("/db/apps/lgpn-ling-data/data/names")//tei:m[@baseForm="διϝοσ"]

return 

    update replace $i/@baseForm with 'διϝο'
```

You can delete the διϝοσ now, if it's no longer needed
