### ISSUE TITLE
Logeion URL changed yesterday ! 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#450]
Dear Magdalena,

How are you ? I hope you are well.

We face a problem: Logeion has changed its URL and all the links we used for each name of LGPN-Ling became yesterday erroneous.
For example, for the word ἑλίκωψ,the ancient address was this one
http://logeion.uchicago.edu/index.html#ἑλίκωψ
It became now, shorter:
http://logeion.uchicago.edu/ἑλίκωψ

What shall we do? We will have soon around 10 000 names analyzed : there are thus around 10 000 Logeion links to modify. 

I wrote to Logeion and was answered by Helma Dik that there was just to cut < index.html# >
They understand our problems after they received many messages  and decided thus to re-enabled index.html links, but only for a while. 

Could you, please, do the substitution in the xml files, so that it is made once for all? The sequence of signs to cut is, as you see: index.html# 
Since yesterday, of course, we began to edit the Logeion links of our new names with the new URL.

Many thanks for your help.
Have a good week-end!

With all best wishes,
Sophie

**Comment by tuurma** [comment]
```xquery

xquery version "3.1";

declare namespace tei="http://www.tei-c.org/ns/1.0";
for $i in collection("/db/apps/lgpn-ling-data/data/names")//tei:bibl[@type="auxiliary"]/tei:ref[starts-with(@target, "http://logeion.uchicago.edu")]
let $t := replace($i/@target, 'index.html#', '')

return 
    update replace $i/@target with $t
```

**Comment by Hippodamie** [comment]
Many thanks, Magdalena ! Could you, please, have a look to issues 448 and 449, which could be, I guess, quite easy to deal with too…

Good night,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Only updated the data today since I had problems accessing the server yesterday night and had to configure a tunnel to get in.

**Comment by Hippodamie** [comment]
No problem.
Have a nice day,
with best wishes,
Sophie
