### ISSUE TITLE
1 name missing in αγορ 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#451]
Dear Magdalena,

Could you, please, find the last name in  αγορ   αγορᾱ which I still cannot find, so that I can delete the Root? (which has become αγορᾱ   αγορ(ᾱ)  21 occ.)

Many thanks in advance.

Difficult for us not to be able currently to have a list of all names built with one Root.

Have a nice day and week-end,
with all best wishes,
Sophie

![capture d ecran 2018-09-21 a 09 24 13](https://user-images.githubusercontent.com/16923546/45866344-c1d18f00-bd80-11e8-8f3b-4ee0cd011af8.png)

**Comment by tuurma** [comment]
It's Astagos http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/editor.xhtml?id=Astagos

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/449468/45866901-63a5ab80-bd82-11e8-8108-5bb4c6d0cdcc.png">

**Comment by tuurma** [comment]
Addded an issue for new search features #452

**Comment by Hippodamie** [comment]
MANY THANKS FOR ALL !
Never would I have thought to Astagos, which is scientifically/onomastically very interresting...
Best !!!
Sophie
