### ISSUE TITLE
Search: discuss new search mechanism

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#452]
* allowing fine tuning of case/diacritic sensitivity
* allowing direct search for particular grammatical feature (eg root)
* ...

tentatively scheduled for the week of Oct 15th

**Comment by Hippodamie** [comment]
Do you mean, which would be wonderful, that if I turn the arrow after (or before) a root on the visualization screen, I could have listed all for example αγορ(ᾱ) names ???

**Comment by tuurma** [comment]
Ah, actually this is very good idea too, to make parts of the visualisation table links to related queries.

**Comment by Hippodamie** [comment]
thanks !
Wonderful what you tell about the new connection !
