### ISSUE TITLE
Permanent URLs 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#453]
http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/editor.xhtml?id=Astagos

Do you think we could, one day, have, as they did at Logeion,  a more clean and simple URL, we too?

Best,
S.

**Comment by tuurma** [comment]
Yes, this is what I work on already in connection with the ISicily project, and we are thinking about something like http://lgpn.ox.ac.uk/api/names/Astagos Details are not entirely set in stone, but we should have first version running in about 2 weeks

**Comment by Hippodamie** [comment]
what does mean api ?

**Comment by tuurma** [comment]
API stands for Application Programming Interface and means a way to access a resource (such as an online database) for other applications to use. Thinking how LGPN and LGPN-Ling are obvious candidates for authority resources to use in other projects (such as ISicily) we want to allow other applications access to query and link to LGPN and LGPN-Ling. Happy to explain in detail when we talk on Skype!

**Comment by Hippodamie** [comment]
Great! I will make a list of all we have to discuss, I mean what is the most urgent to deal with (but the logical/digital order of urgence you have to tell me).
As you know I will ask you again an estimate since we need to use a part of fundings I have necessarily before next March 2019.

Last point: why  Alexandra did not set online the new version of INtroduction to LGPN-LIng which was ready? We still only have the ancient version.

Best,
Sophie
