### ISSUE TITLE
Frequent message about the impossibility to save while editing

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#454]
Hi, Magdalena,

Forgotten to tell you: we have too quickly messages about the impossibility to save when we are editing. We have thus to leave the page without saving and to re-open it again, to save finally what we wanted to save.

It happens since weeks.

Could you, please, make longer the time to edit one page, so that we do not have to leave it and come back 2 or 3 times while editing? And also make possible 2 people are able to save at exactly the same minute (if it is the problem)?

I suppose it could happen especially when we are 3 or 4 people on LL at the same time... But it is very often the case we are at least 2. Even in week-ends, as you know.

Thanks  a lot for your help for that too.
Good week-end,
best,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

it it not a problem if several people work simultaneously, as long as they do not edit the same name.

The problem with session expiring is quite tricky and troubles LGPN team as well, I have tried to set the sessions never to expire but somehow this setting is not respected by the forms engine. Sorry I do not have quick solution for it but be assured we are aware of the problem and trying to solve it.

**Comment by Hippodamie** [comment]
Many thansk,

good week-end !
Best,
Sophie
