### ISSUE TITLE
Search does not work anymore.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#457]
Dear Magdalena,

we cannot work anymore.
Could you please help?
Did it happen because of the long comments I wrote in 1 or 2 entries this afternoon (e.g. Drepalas)?
Or is it because of the number of names edited (almost 10 000)?

Thanks for your help.
best,
Sophie

**Comment by tuurma** [comment]
Hi, could you please let me know what were the search terms that failed? I checked yesterday evening and this morning too, so things seem to be in order but sometimes it's a particular query which throws an error.

**Comment by Hippodamie** [comment]
Dear Magdalena,

Everything is ok again this morning. It was as blocked yesterday night and had become extraordinarily slow (in the afternoon) before being blocked. It was very slow to save and refresh and search. No more !
Maybe were they working on the servor?

Sorry to have disturb you.

I profit to tell you again about the new version of the introduction, which was not set online. It is confusing for us not to have access to the new version. So it is quite urgent ot do it.

Have a nice day,
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Please, Magdalena, do we have  to download the Version 4.4.0?
Best,
S.
