### ISSUE TITLE
Additional Areal/Dialectal labels

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#459]
Dear Magdalena,

could you, please, add in the list:
Egypt, Palestine, Syria and Aegean?

See the ordering.
Many thanks,
best,
Sophie

[Areal_Dialectal_Bilingual labels.docx](https://github.com/eXistSolutions/LGPN-ling/files/2436990/Areal_Dialectal_Bilingual.labels.docx)

**Comment by Hippodamie** [comment]
Dear Magdalena,

2 more labels: Arabia and Cyrenaica.
See file.
best,
S.
[Areal_Dialectal_Bilingual labels.docx](https://github.com/eXistSolutions/LGPN-ling/files/2442681/Areal_Dialectal_Bilingual.labels.docx)

**Comment by tuurma** [comment]
Will do tomorrow!

**Comment by Hippodamie** [comment]
Have a good evening !
Thank you !
Best,
S.
