### ISSUE TITLE
Renaming columns' titles

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#460]
Dear Magdalena,

Here is what we would like for those titles.
Have a nice day and a good week,
with all best wishes,
Sophie
[Renaming columns' titles.xlsx](https://github.com/eXistSolutions/LGPN-ling/files/2455098/Renaming.columns.titles.xlsx)

**Comment by Hippodamie** [comment]
Dear Magdalena,

Do you think you could do it soon?
Many thanks in advance,
best,
Sophie

**Comment by Hippodamie** [comment]
Renaming is not ready.
Will be reworked very soon.
Always the Inflex 1 matter !
Best,
Sophie

**Comment by Hippodamie** [comment]
Hi, Magdalena,

here is the new version of Renaming column'headings
It is not so urgent as the change you were ready to proceed yesterday evening.
Thanks for it.
[Renaming columns' titles Oct2018.xlsx](https://github.com/eXistSolutions/LGPN-ling/files/2530631/Renaming.columns.titles.Oct2018.xlsx)

Best,
Sophie

**Comment by tuurma** [comment]
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/449468/48632079-4c6cee00-e9c0-11e8-9df0-79cb505abc71.png">

**Comment by Hippodamie** [comment]
Do you understand well ? Hyper-title like Anthroponymic suffixes, then the details of the different columns under it, with the precise title of each column.
Sometimes the only title takes 2 lines space like Geo-dialect. whereas in other cases the above line has the hyper-title and the below line the precise title. To let see the difference, I have set it in bold and larger size, whereas precise title is in smaller and normal (not bold).

Last thing which would be great: could you please delete all the lexems to delete? So that I do not have to do it page by page. I am late with that because it works so slowly. But note that now the search works fast !!! So nice. Only difficulty: when it tells us no saving possible just go out and we lose all the data we had put … and even sometimes when begining to edit. It depends. 

Thanks for the wonderful last improvements (dash and cleaning of Suff1 column).
Good work,
best,
Sophie

**Comment by tuurma** [comment]
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/449468/48636297-cbffba80-e9ca-11e8-8167-ee451e36f9bf.png">

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/449468/48636333-e33ea800-e9ca-11e8-990f-26db55ff8efd.png">

**Comment by Hippodamie** [comment]
Very well: would it be possible to have a kind of hierarchization like Name in bigger than Inflect Type or using the bold and not bold to better visualize?

**Comment by tuurma** [comment]
Yes, will do so.

**Comment by tuurma** [comment]
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/449468/48773722-82fc7e80-ecc8-11e8-9be2-673bfa044369.png">

**Comment by Hippodamie** [comment]
Hi, Magdalena : it looks better ! But that would be still greater if we could have:
for ex. ‘Nom’ under the grey line, I mean closer of Type flex: the space looks each time too much between the bold and the not bold title.
 Same for the others double titles: but bold and not bold look are good and of course to keep. 
Maybe also make ‘Nom’ more visible than all the others, a little bigger size ( or all in capitals like NAME / NOM)? What do you think?

with all best wishes and thanks,
good evening!
Sophie
