### ISSUE TITLE
Our roots... where are they ???

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#465]
Hi, dear Magdalena,

Discovered your new LGPN-Ling EDitor, which looks great. Hope it will be appreciated by Enrique and Gerard who edit the most. Hope the subwindow for new roots will be as convenient as the previous one.

Question1 : where are the roots of the names? All seems currently empty, which looks terrible !

Question 2: the same bug as when you tested at first on the Suffix1 of a name like Eucleon (and there are a lot with -ων). Look at the screenshot [ων   ων twice! ]. 

We had actually, from the begining, 2 different ων suffixes, which differ only by their Genitives.
The most current one is the Eucleon type, with all those different Genitive variants.
<img width="1107" alt="capture d ecran 2018-10-21 a 21 05 29" src="https://user-images.githubusercontent.com/16923546/47271143-eda98580-d575-11e8-91de-640b19adc083.png">

But the other, which is very rare but happens (see Geron1), has its Genitive only in -οντος.
<img width="1103" alt="capture d ecran 2018-10-21 a 21 14 05" src="https://user-images.githubusercontent.com/16923546/47271166-306b5d80-d576-11e8-8ff3-643665a80461.png">
We should have thus for Geron1: ων  -οντος

You have both ων in the list I gave you and you gave me to check when you had set it in Xml.
 
Another thing is that dash should be only before the greek letters at the begining of the line and not at the end of the previous line.

I also saw thing which does not seem to be achieved (about uncertainty of variants, no boxes at the moment).

The big question fro tomorrow morning for Enrique is: where are the roots? And can we edit tomorrow or not yet? I mean, have you still to work on it?

Good night and SO MANY thanks for what you did,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
inflectional suffixes are addressed in #471 and missing roots were just a caching problem so closing
