### ISSUE TITLE
French version of the introduction

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#467]
Dear Magdalena,

I would like to thank you for the new up-dated system: the appearance looks beautiful (not only Editor but also list of names). Please keep it as it is ! I do not know if it the police used or the size or the kind of not bold?
Please convey thanks to everybody, especially Alexandra for Editor and English version. What about the French version?

A small bug: Logeion link does not seem to be active, look at Editor of the following name (edited today)
<img width="1094" alt="capture d ecran 2018-10-22 a 14 39 38" src="https://user-images.githubusercontent.com/16923546/47292773-59d4c980-d608-11e8-8445-810c77f90905.png">

Thanks for your help,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
@plutonik-a could you please remind us what is the status of the French version of the introduction? Could it be it is not pushed to the repo?

**Comment by plutonik-a** [comment]
@tuurma It hasn't been implemented yet.
