### ISSUE TITLE
Size of Greek forms in Lexis and Onomastics

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#469]
Hi, Magdalena,

Appearance again: I think it is not necessary and does not look as well to have the Greek forms in taller size than the rest. I think it should be better in the same size as Latin forms.

What do you think?

Thanks for your advice,
with best wishes,
Sophie

**Comment by tuurma** [comment]
Please could you explain what you mean? Screenshot might be helpful.

Greek form is shown in bold in visualisation but same size as Latin

<img width="283" alt="image" src="https://user-images.githubusercontent.com/449468/47444182-32236400-d7b6-11e8-8bd7-1fae02e3b746.png">

While in Lexis / Onomastics columns there is no highlighting of Greek whatsoever

<img width="189" alt="image" src="https://user-images.githubusercontent.com/449468/47444228-50895f80-d7b6-11e8-948c-4f3ba6a4b61b.png">

**Comment by Hippodamie** [comment]
> 2018 à 18:01, Magdalena Turska <notifications@github.com> a écrit :
> 
> Please could you explain what you mean? Screenshot might be helpful.
> 
> Greek form is shown in bold in visualisation but same size as Latin
> 
> 
no, it is ok for that.
>  <https://user-images.githubusercontent.com/449468/47444182-32236400-d7b6-11e8-8bd7-1fae02e3b746.png>
> While in Lexis / Onomastics columns there is no highlighting of Greek whatsoever:
> 
> 
I mean things like that:
you see Αth. 9.401 c-d looks smaller than the Greek letters; 
LSJ in italics looks smaller than the Greek σύαγρος
‘taureau sauvage’ looks smaller than βόαγρος. We would prefer Greek and Latin letters all of the same size.
It is the same problem in the Onomastics column.
Best,
Sophie

**Comment by tuurma** [comment]
Could I have a screenshot please, it's very hard to understand for me where the problem occurs, also might be a browser specific rendering issue.

**Comment by Hippodamie** [comment]
I just sent it to you, did you get it?

**Comment by tuurma** [comment]
Unfortunately not, I think attaching to an email doesn't work. Could you try using GitHub website instead (just follow the link *view it on GitHub* at the bottom)

**Comment by Hippodamie** [comment]
Here, at the bottom, I put it again, here:
> I mean things like that:
> you see Αth. 9.401 c-d looks smaller than the Greek letters; 
> LSJ in italics looks smaller than the Greek σύαγρος
> ‘taureau sauvage’ looks smaller than βόαγρος. We would prefer Greek and Latin letters all of the same size.
> It is the same problem in the Onomastics column.
> Best,
> Sophie



> Début du message réexpédié :
> 
> De: MinonSophie <s.minon@orange.fr>
> Objet: Rép : [eXistSolutions/LGPN-ling] Size of Greek forms in Lexis and Onomastics (#469)
> Date: 24 octobre 2018 18:15:46 UTC+2
> À: eXistSolutions/LGPN-ling <reply@reply.github.com>
>

**Comment by Hippodamie** [comment]
I mean things like that:
you see Αth. 9.401 c-d looks smaller than the Greek letters; 
LSJ in italics looks smaller than the Greek σύαγρος
‘taureau sauvage’ looks smaller than βόαγρος. We would prefer Greek and Latin letters all of the same size.
It is the same problem in the Onomastics column.
Best,
Sophie
![capture d ecran 2018-10-24 a 18 07 36](https://user-images.githubusercontent.com/16923546/47448061-59326380-d7bf-11e8-8219-2217ba6543e4.png)

**Comment by tuurma** [comment]
Thanks. The difference is not quite as strong on Safari. I'll see what I can do, likely we'd need to choose fonts which display Greek and Latin comparably sized. 

<img width="1479" alt="image" src="https://user-images.githubusercontent.com/449468/47448666-e2966580-d7c0-11e8-8b6a-b18549543775.png">

and Chrome

<img width="298" alt="image" src="https://user-images.githubusercontent.com/449468/47448751-24bfa700-d7c1-11e8-9474-a8827daf9bd6.png">

**Comment by Hippodamie** [comment]
You are right. I understand. Many thanks. Be sure that  they really have all the signs we need, the macron and the digamma (ϝ), when you change.
Best,
Sophie

**Comment by tuurma** [comment]
@plutonik-a Alex, could you advise on the font to use, so that mixed Greek/Latin passages look roughly the same?

**Comment by Hippodamie** [comment]
Thanks for that,
best,
Sophie

**Comment by plutonik-a** [comment]
@tuurma 
I thought, font IFAO-Grec Unicode will display Latin and Greek characters alike, but I assume, as I the font folder is entirely missing in this repo, it might also be missing on the production server so the a different font will be displayed. Judging from the screenshot, that might be most likely the case.

If this shouldn't be the case here and IFAO-Grec Unicode is correctly in use, I would suggest to use a font-switch in xquery. Depending on character range, you will be able to assign a specific font family. In a next step you control the font-specific font-sizes via css.

**Comment by plutonik-a** [comment]
@tuurma 
This is the reference for the missing Greek font: https://github.com/eXistSolutions/LGPN-ling/blob/e7f91257ab7de873ae01490149d6501614f6bbbf/resources/css/less/style.less#L11
