### ISSUE TITLE
About Lexemes title at the top menu and in the subform

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#470]
Dear Magdalena,

I apologize since I think I did the mistake.
The new ‘Lexemes’ title does not work.
We should have instead: Bases/Roots at the top and in the subform.
In French: Bases/radicaux.

Could you, please, change it?
Many thanks in advance.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
Here? And where else?

<img width="664" alt="image" src="https://user-images.githubusercontent.com/449468/47446749-2b97eb00-d7bc-11e8-99a6-3b58506a2f82.png">

**Comment by Hippodamie** [comment]
Yes and there instead ‘Lexemes’
