### ISSUE TITLE
Βug ων   ων   cf. issue #465 (explanation and how to solve it)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#471]
Dear Magdalena,

Here is an example of the bug and what we currently read.
![capture d ecran 2018-10-23 a 16 26 40](https://user-images.githubusercontent.com/16923546/47367779-aa1f5a80-d6e0-11e8-9e6e-7ddca6fef857.png)

Actually, the 2 different ων have been mixed in one.
We should have:

a. ων, Thess. ουν, Pamph ω
(then below the genitives:) -ωνος or even -ονος, Thess. -ουνος

b. ων
(below:) -οντος, hence -ωντος

The best solution:
change all the -ων names into a.
We will change the rare b. type after you change the whole, one by one (it will not take too much time: you could help us by giving the list of the names which base ends with  (οντ).

Did you understand what I propose? Is it easy for you?

Thanks for your help.
Best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

Yes, ok,  and the rarer ων_ , please, in the menu-list, insert it UNDER the simple ων. Another solution could be ων1   vs    ων2; and in the menu maybe, if possible to have it in italics or smalle size, just to be sure to distinguish them quickly.

Thanks for all,
best,
Sophie

P.S.: will be without connection from 10.30 to  2.30 pm.

**Comment by tuurma** [comment]
Still working on styling of variant b. entries

<img width="910" alt="image" src="https://user-images.githubusercontent.com/449468/47438583-0e0e5580-d7ab-11e8-90f5-d4293d0f478d.png">

All existing entries will assume version a. ων, please change names which require version b.

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/449468/47440829-46179780-d7af-11e8-8365-aba6cc2dc0ec.png">

**Comment by Hippodamie** [comment]
Ι saw you did it !!! Μany, many thanks !!!
Geron1 has the other ων.
Is it easy for you to find all the bases ending in (οντ) and make the substitution?
For the style, could you please do smaller size and italics or is it not clean? For the bizarre quadrat with ? after it should look actually as you see in the list for Alcmeon: an alpha with the macron + accent.

Could I ask someting for better hierarchization in the Editor? Difficult for us to find our way, since it is a very long page.
Could you set in italics Linked Sources (under Onomastics) and in italics too Lexical or Lexicographic Significant Sources (under Lexical Connections).
Some titles are too much and could be deleted, I think, like:
a. Under Name in context: Classification need not to be there: to delete
b. Under Dialects: Uncertain has not to be written.
c. Under Preroot: Preroot (prefix) has to be deleted. But the Preroot title itself should be actually ‘Prefix’.
d. Under Onomastics, under Modern references, Modern reference is not necessary to repeat and repeat: reference is enough.

Thanks for all,
best,
Sophie

**Comment by tuurma** [comment]
Extracting your requests regarding labels to a separate issue

**Comment by tuurma** [comment]
Do I understand correctly you'd like all entries where *Inflexional morpheme 1* is οντ to be changed into ων?

**Comment by Hippodamie** [comment]
Not at all ! Sorry if not clear.
Look at Geron1


What is needed is: to have as a Inflex1  ων_  – as I wrote it (Genitive: -οντος, hence -ωντος) –, for all names that, like Geron1, have their base (1 or 2) ending in (οντ) like you see γερ(οντ).

Thanks,
best,
Sophie

**Comment by tuurma** [comment]
Below is a list of baseForms ending in οντ. Shall I add Infl1 to all of these with ων_?

ακμαζοντ

λεϝοντ

αρεθοντ

κρειοντ

ιοντ

φαϝοντ

αρχοντ

βλεποντ

φεροντ

γεροντ

μεδοντ

μενοντ

αρκεοντ

ακοντ

αϝιοντ

ευφραινοντ

λιποντ

βαλλοντ

αγοντ

αχεροντ

αυγαζοντ

θυοντ

αλεϝοντ

σαϝοοντ

ευτυχεοντ

βρεμοντ

εθελοντ

βρυοντ

ϝανατσσοντ

**Comment by Hippodamie** [comment]
Wonderful: are they all there, for sure?
You can go !
Many, many thanks,
best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

one more to your list:
πρεπ-(οντ).
Many thanks.
Best,
Sophie

**Comment by tuurma** [comment]
Dear Sophie @Hippodamie 

Do you mind checking this list http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/tools/ontSuf1.xq one more time and letting me know what shall I do for cases where there already are Infl1 entries different than ων_?

**Comment by Hippodamie** [comment]
Dear Magdalena,

all has been already fixed by Gerard, I think. Eeverything seems OK withe the expected ων_ suffix. He used your previous list to fix it.

**Comment by Hippodamie** [comment]
Good night ang thank you very much !
Best wishes,
Sophie
