### ISSUE TITLE
Return to list of names without saving / Cancel doesn't work

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#474]
Dear Magdalena,

Sorry to come again !
When I leave the Editor window, previously, with the  return arrow, I found again the list of names.
Now on Chrome, when I use the return arrow after saving the Edition, it refreshes always, which is time-consuming.
Is it a possibility not to have this inconvenient?
That is why I asked you yesterday if it was possible to transform the function at the bottom ‘Return to the list without saving’ into ‘Return to the list of names (even after saving)’?
Anyway, it seems this function does not work.

And what does exactly mean at the bottom ‘cancel form’ (I do not dare to try if it deletes the edition)?

Thanks for your answer,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Cancel means do not save your current edits (*not* deleting a whole entry, just dropping any changes since you last saved) and return to the list of names. I can confirm it doesn't work.

**Comment by Hippodamie** [comment]
Thanks !

**Comment by Hippodamie** [comment]
Dear Magdalena,

could you please give Login and password to Florian Reveilhac? Sorry to disturb you, but it is quite urgent, now. We have 3 days work together planned next week… and I would like him to see the EDitor and all before we begin.

Many thanks in advance for your help.
Have wonderful vacations,
best,
Sophie

Here is Florian’s address:
Florian Réveilhac <florian.reveilhac@gmail.com>
