### ISSUE TITLE
Non securized connection on Firefox and Chrome

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#475]
Dear Magdalena,

here is the message on both browser.
Could you, please, fix it?

Many thanks,
best,
Sophie

**Comment by tuurma** [comment]
Sorry, I think a screenshot is missing. Is the problem like here?

<img width="700" alt="image" src="https://user-images.githubusercontent.com/449468/47444530-f210b100-d7b6-11e8-9161-a9269197ce4d.png">

**Comment by Hippodamie** [comment]
Yes !
