### ISSUE TITLE
A spelling mistake

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#478]
Dear Magdalena,

Could you please, make a correction spelling in Greek. There is a iota missing, to add in: εω to correct into ίεω.
Here it is:
![capture d ecran 2018-10-24 a 21 40 06](https://user-images.githubusercontent.com/16923546/47456924-0d3ee900-d7d6-11e8-9b02-8a0c835f258d.png)
In this column:
![capture51](https://user-images.githubusercontent.com/16923546/47456949-19c34180-d7d6-11e8-916a-3a22cc13a5dd.png)

Many thanks in advance,
good night !
with best wishes,
Sophie

**Comment by tuurma** [comment]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/449468/47514025-bdb4f780-d87f-11e8-8a22-1b2cde3dc9a7.png">

**Comment by Hippodamie** [comment]
Wonderful ! thank you again!
