### ISSUE TITLE
morphemes: add text value

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#48]
as morphemes have 2 ways for display - with/without parentheses around optional fragments we need a place to provide both versions

**Comment by tuurma** [comment]
from @hippodamie "Is it OK to have parentheses ?, without which we can do our linguistic analysis, because we will have them very often, also in Roots...
as (h)υβ (with sometimes this Latin letter in the parenthesis) ; κρι(ν) ; (ϝ)ανακ(τ) ; αν(δ)ρ; Suff. (V)λ(λ) etc."

**Comment by tuurma** [comment]
so, in case of roots, current TEI representation should be
`<category xml:id="hυβ" ana="#hump">(h)υβ</category>`
to accommodate the need above.
Consequences for the autocomplete fields and visualization are that @xml:id (formerly @baseForm) should be used as value on entry/m(orphemes) and string value as label

for completeness current representation (to be changed) is:
`<category baseForm="hυβ" ana="#hump"/>`

**Comment by Hippodamie** [comment]
Hope it is not too much trouble for you !
Thanks, Magdalena,

Sophie

**Comment by Hippodamie** [comment]
I answer to that comment:
"as morphemes have 2 ways for display - with/without parentheses around optional fragments we need a place to provide both versions".
No 2 ways: we will always use the only forms κρι(ν) ; (ϝ)ανακ(τ) ; αν(δ)ρ; Suff. (V)λ(λ) with their parentheses as R1, R2 & Pref  & Suffixes. Only the forms in the box Constituent will be without parentheses.

**Comment by tuurma** [comment]
Well, yes, you are right, the displayed form will be always the one with parentheses. The need for the second form comes more from XML and TEI requirements, where categories need to have xml:id attribute and this attribute cannot contain parentheses.

**Comment by tuurma** [comment]
Current TEI structure (note still uses @baseForm as some Greek Unicode characters cannot be used in xml:id's. This is temporary solution pending fix to eXist.)

`<category baseForm="huβ" ana="#hump">
    <catDesc>(h)uβ</catDesc>
</category>`

**Comment by Hippodamie** [comment]
Wonderful !
Best,
Sophie
