### ISSUE TITLE
Βug on Fictitious + GPR

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#480]
Hi, Magdalena,

Not sure to have put it on Git-HUb.
It seems that by default Fictitious and GPR at the top are checked off.
Could you, please, fix it, since we will have trouble with the names where it was checked off before up-dating and the others?
Many thanks in advance,
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Many thanks for both messages.
OK for tonight.  I will not be on it after 7 pm, and tell the others. Thank you in advance.
Good work on LGPN. Thanks for them because it is quite urgent for them especially !
With all best wishes,
Sophie

**Comment by Hippodamie** [comment]
It is the most urgent point for us because we do not know what to do when we edit a new name and when both boxes are already checked off (x). Could we and should we remove it when we begin to edit a name?

Thanks for your quick answer to that question.
Best,
Sophie

**Comment by tuurma** [comment]
Should be fixed now, do you mind checking?

**Comment by Hippodamie** [comment]
YES !!!! THANKS !
