### ISSUE TITLE
Automatic opening or not opening of 2 headings in the EDitor.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#482]
Dear Magdalena,

What would be more convenient would be some (not so frequently used than the others) headings would not be opened when we open a new edition page.

I especially mean:
Lexical or Lexicographic significant sources AND
in Onomastics Linked sources.

This request is directly connected with another one, which number is #477.

Thanks for your work.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
Please note that in new edition both Lex. significant sources and Ono. linked sources are currently collapsed by default. I could also collapse other references at first, so you only add the ones that are needed.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/449468/47516220-39fe0980-d885-11e8-83d9-3e522479c030.png">

**Comment by Hippodamie** [comment]
It seems it is perfect like that. Sorry, if I missed it before and complained for nothing in fact !
Many thanks.
Have a good evening.
I close LL for tonight now.
Best thanks and wishes,
Sophie
