### ISSUE TITLE
Place of the Search case: to far away at right as it seems now

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#483]
Dear Magdalena,

I do not know if it is new, but I remark this morning that Search case is just above update, and the page is so wide for us that we have to make it move from left to right each time we have to search a name or its begining.

Was'nt this Search case before just above Onomastics? In that place, it was more convenient since we had the case always directly visible. It takes time to have to move the page...

Could you please remove it as it was previously?
Thanks a lot.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
Could you please let me know what browser manifests this behaviour? Search box should be positioned in the right hand corner of the viewport, on smaller screens it should be adjusted as well

<img width="777" alt="image" src="https://user-images.githubusercontent.com/449468/47676829-ddb92380-dbbd-11e8-963b-c7350db2729e.png">

**Comment by Hippodamie** [comment]
It happened on Chrome just after your new up-dating, but does not happen anymore, it seems !
So it is ok, thank you !
Best,
Sophie
