### ISSUE TITLE
Bug (unnecessary reduplication) on Suffix1 μᾰ

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#487]
Dear Magdalena,

here is the Inflex1 bug.
Could you, please, fix it: only one time is the Genitive forme needed.

Many thanks in advance,
best,
Sophie

![capture d ecran 2018-10-27 a 18 29 04](https://user-images.githubusercontent.com/16923546/47606645-57aea880-da16-11e8-9ac8-32ab671e3e80.png)

**Comment by tuurma** [comment]
Fixed duplicate entry for (μ)α but meanwhile the Infl1 for Egema has been changed

<img width="962" alt="image" src="https://user-images.githubusercontent.com/449468/47663825-0f21f700-db9e-11e8-90da-1cae0072f39f.png">

**Comment by Hippodamie** [comment]
No, it is OK, there are 2: you have fixed it on μᾰ !
We have also to deal with these 2 bizarre entries !

**Comment by tuurma** [comment]
Please explain what remains to be done?

**Comment by Hippodamie** [comment]
Νothing: it seems you fixed it.
