### ISSUE TITLE
Suff1/Inflectional type

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#488]
Dear Magdalena,

How are you? A request difficult to explain: 
to transfer the informations of Inflect1 (currently Nominative+Genitive) under the Greek Name. And keep in the current Inflect1 (with a new name: Suff.1) only the nominative form (like in the previous version).

We would need the inflectional information (Nominative + Genitive) take place under the Greek form of The name, in smaller size, in the same column.
Eudaimocles  Εὐδαιμοκλῆς would have thus the Inflect information under its Greek form, like that
                       ης
                      early -εος,
                     Att. -ους
                     etc.

You would have to transfer the current informations of the names which are in column Inflect.1 in the column Greek Name, under each of them. And to substitue for all the names in the current Inflect1 the ancient nominative like they still are listed in the Menu list in the Editor.

We would have thus:
 Εὐδαιμοκλῆς                             (bla bla bla....) and Suff.1: ης.
        ης
        early -εος,
        Att. -ους
            etc.

What will change for us is that sometimes the Suff.1 case will be empty. Because actually it will give the following different information: which suffix 1 is merely anthroponymic (because some of them are lexical and anthroponymic). So we will have to empty, I guess, like half-part of  all the around 11000 cases.

Which would be great would be that we have in the **Editor** to give the information only one time with the current Inflectional morphem1 list, and when we arrive in Suffixes 4, 3, 2, we would just check a little case in front of Suff.1, if and only if the Inflectional morphem is also a Suff1. And by checking it, it would appear in the Suff.1 column only the nominative form.

What do you think about it? Is it possible? And how much time?
If you could give me a quick answer until tonight it would be great.
But I am aware you are busy for LGPN.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
Do I understand it right that effectively, on the data entry side, you'd need dropdown lists for Suff.1-2-3-4 plus additionally a dropdown for Infl1?

Then on the visualization side we'd display information for Infl1 not in a separate column, but just under the name in Greek name column?

**Comment by Hippodamie** [comment]
Yes, exactly, for the latter. 
But not exactly for your first sentence, since we would need only one dropdown list, the one with Nominative + Genitive; for the other information (corresponding Nominative), no dropdown list: just a case to check if and only if Inflect = Suff1.  Because, in any case, the Nominative form will be the same under the Greek name and in the Suff1 column. The only difference is that it could appear or not, in its special Suff1 column.
The aim is that if we check, then the Nominative appears in the Suff1 column. And if we do not check, the column keeps empty.

Is that clear enough?
Many thanks for your quickness,
best 
Sophie

**Comment by tuurma** [comment]
Like this?

<img width="685" alt="image" src="https://user-images.githubusercontent.com/449468/47666590-409dc100-dba4-11e8-80eb-3ed85b3383d6.png">

In this case, it would be enough to add an attribute for Infl1 field.

**Comment by Hippodamie** [comment]
Yes. But the name will change: now: Inflectional type and the other Suff1, yes.

**Comment by tuurma** [comment]
Okay, I understand. It doesn't look too complicated, so I'd estimate around 3h of work, to establish corresponding TEI structure, adjust the form and visualisation etc.

**Comment by Hippodamie** [comment]
Many thanks !

**Comment by tuurma** [comment]
Shall I proceed and implement it then?

**Comment by Hippodamie** [comment]
Τhank you to propose but I am not available to ‘help’ you if necessary tonight.
And tomorrow, not available the whole day.
So, could you please wait a little? 
I will be available again from tomorrow, at the end of the afternoon.
Goodnight,
best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

in case you have still time to proceed and implement tonight, I am ready to be available (only not available for dinner between 7 or 7.30 and 8.30 pm).
Tomorrow is also possible.
I finally will not be available from thursday to friday night: I will be without connection.
We would like of course this change be made as soon as possible since we have to apply the new pattern for all new names we edit.
Thanks for all,
best,
Sophie

I re-send in the devoted # the new version of renaming columns.

**Comment by Hippodamie** [comment]
Dear Magdalena,

I comment your scheme with the yellow arrow above, to add an information you need.
About the NEW case/square Suff1 to check in the Editor. When you will proceed to the change I asked for, 2 options are possible: 
1. keep in the column re-named Suff1 each nominative corresponding to the Nominative/Genitive couple you will now set under the Greek Name, and give us thus in the Editor the new case/square Suff1, for all the names edited, **already checked**. 
2. the other choice would be to give the column Suff1 empty and the little square not checked.

Of course, we would need the option 1. Each name will have thus its Nominative in the column and the square would be already checked. For names that do not need a Suffix1, we will thus have to un-check the square, to empty the place in the column.

And when editing new names, we will choose a suffix in the current INflectional morphem1 list, and it will be visible under the name and if it is a Suff1, we will check the square Suff1, and the Nominative of the same suffix will be visible in column Suff1.

I think you have all informations necessary to proceed.
With all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Ιn direct connection with the previous comment:
Could you please use the option1 for all the around 11 000 names, BUT
use the option2 (square Suff1 not checked = column Suff1 empty) for all the names begining with Eu- in their translated form (like Eutychous, Eucharitos etc) [they are around 1100]?

Thanks in advance,
with best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

for me, this point is now ready for you to proceed. And one of the most urgent for us.
Best,
Sophie

**Comment by Hippodamie** [comment]
Hi, Magdalena,

to summarize I just take above that:
1. to transfer the informations of Inflect1 (currently Nominative+Genitive) under the Greek Name. And keep in the current Inflect1 (with a new name: Suff.1) _only the nominative form_ (like in the previous version).
2. in the Editor, to add what you already gave schema (the little square to check).
3. to set the little square already checked for all names (= Nominative present in Suff1 column), except the around 1100 names beginning with Εu- Greek ευ, simple ευ + complex ευ= ,  every Eu- name: for them, little square not checked = nothing at all in Suff1 column.
4. Change the columns titles like in the last Excel I sent: for example Inflex1 becomes Suff.1 and Greek will become Name [with as a smaller sub-title: Inflect. Type]. That, for the English version.

Thanks for what you do for us.
All best,
Sophie

**Comment by tuurma** [comment]
```xquery
for $i in collection('/db/apps/lgpn-ling-data/data/names')//tei:m[@subtype='flexional']
return 
    update replace $i/@subtype with 'suff'
```

**Comment by tuurma** [comment]
Still working on it, but pasting how the editor part is looking like now 

<img width="782" alt="image" src="https://user-images.githubusercontent.com/449468/48558049-92568300-e8e8-11e8-92e5-04cfa23cab4e.png">

**Comment by tuurma** [comment]
@Hippodamie 
Dear Sophie could you please confirm this is the expected visualisation (Ekephylos has Suff box checked while Euderkes doesn't)

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/449468/48559626-41488e00-e8ec-11e8-814c-66e3861e1a01.png">

**Comment by tuurma** [comment]
Convert Eu* names 

```xquery
for $i in collection('/db/apps/lgpn-ling-data/data/names')//tei:orth[ft:query(., 'eu*')][@type='latin']/ancestor::tei:entry//tei:m[@type="suffix"][@n="1"]
return 
(:    $i:)
    update replace $i/@subtype with ''
```

**Comment by Hippodamie** [comment]
Hi, Magdalena,

perfect, except rename, please, Inflect (no 1 anymore); and rename Suff1 in teh EDitor Suffix 1 (like the 3 others). Suff. 1in the visualization only.

**Comment by tuurma** [comment]
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/449468/48560944-33e0d300-e8ef-11e8-9ec5-01f0716edb85.png">

**Comment by tuurma** [comment]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/449468/48561098-8ae6a800-e8ef-11e8-819f-90111aedd11e.png">

**Comment by tuurma** [comment]
I will change visualisation column names in the next step. For now converted the data, adjusted the editor and visualisation table contents.

**Comment by Hippodamie** [comment]
Dear Magdalena,

not exactly, but almost done, very well:

1. the aim is that Inflex1 should have only the nominative form, like in the ancien version, so for Ekephylos, only ος but not Gen. -ου, -ω.

2.  Euderkes is almost perfect (with the empty INflex, especially), BUT not visually clean/clear. 
I mean, could you, please, make the ης which comes first under the Greek name, maybe smaller but still bold? As you see, the flexional nominative ης is like a repetition of the end of the name itself, which is expected and normal. But I think keep the italic+bold for ης. What do you think ? Or please, let me see 3 simulations of possible presentations of this inflectional informations. Or put ησ rather just at right, so that it is just under the end of the name itself? I do not see very well how to do for the best visual. Could you please help?

**Comment by Hippodamie** [comment]
2. again : or italics and not bold for ης ??

**Comment by Hippodamie** [comment]
GREAT THANKS !
