### ISSUE TITLE
Additional Suffix 2: δ

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#489]
Dear Magdalena,

could you please add δ to the list Suffixes2?
range it before αδ, second line?

Many thanks,
best
Sophie

**Comment by tuurma** [comment]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/449468/47667066-58c21000-dba5-11e8-93d0-59c219633890.png">

**Comment by Hippodamie** [comment]
Many thanks !
