### ISSUE TITLE
The most important now: parentheses in Prefix, R1, R2, Suff. 1, 2, 3, 4.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#49]
Is it OK to have parentheses ?, without which we can do our linguistic analysis, because we will have them very often, also in Roots...
as (h)υβ (with sometimes this Latin letter in the parenthesis) ; κρι(ν) ; (ϝ)ανακ(τ) ; αν(δ)ρ; Suff. (V)λ(λ) etc. 

Best, Magdalena.

**Comment by tuurma** [comment]
same as #43, closing this one and moving comment above there
