### ISSUE TITLE
Additional inflectional morphem 1 current list

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#490]
Please, Magdalena, could you add at the end of the list: ?, which is currently missing.

Many thanks in advance,
best wishes,
Sophie

**Comment by tuurma** [comment]
<img width="824" alt="image" src="https://user-images.githubusercontent.com/449468/47667024-45af4000-dba5-11e8-83e6-75efb2372a4d.png">

**Comment by Hippodamie** [comment]
Wonderful !
Many thanks !The underscore ων_ looks awful: could you please change it into ων2; Sorry for that.
