### ISSUE TITLE
suff1 list ᾱ(ϝ)ων

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#491]
Dear Sophie @hippodamie Should the funny looking entry in Infl1 list ?-(ϝ)ων in fact read as ᾱ(ϝ)ων?

**Comment by tuurma** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/449468/47674735-4b625100-dbb8-11e8-8186-8998855ea425.png">

**Comment by Hippodamie** [comment]
Thank yuo, Magdalena.
