### ISSUE TITLE
Message ‘your sessions expired, you have to quit’

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#492]
Dear Magdalena,

Enrique, Gerard and Jean-Claude complain about the very unconvenient  fact that they have too often the above message when they edit. They have to save several times during the edition, to be sure not to be obliged to quit before it is done and to have thus to rewrite everything.

It happens especially when several people are at work, which is very often the case (we are almost 2 everytime except on Tuesdays, and sometimes 3 or 4 and 5 or 6 from next March)...

Is it possible to fix it?

Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
I am aware of this problem, alas it is very tricky to fix, and I have been trying various approaches already. I do have it on my list and try to find a solution. Apologies for the inconvenience, I know this is mightily frustrating.
