### ISSUE TITLE
Not clean appearance in dropdown lists: please, to clean !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#493]
Dear Magdalena,

could you please clean the Greek in the dropdown lists, which is not easy to read at the moment: the repeated Greek form in each line is like sticked all together without any blank between each form of each couple of forms.

Many thanks in advance,
with all best wishes,
Sophie 
![capture d ecran 2018-10-31 a 14 47 55](https://user-images.githubusercontent.com/16923546/47792244-e7589d80-dd1b-11e8-9432-a1dfc660536c.png)

**Comment by tuurma** [comment]
ΝΒ may require reloading the page with Shift+Reload

<img width="393" alt="image" src="https://user-images.githubusercontent.com/449468/48156020-a5f06100-e2cc-11e8-9779-b6a50f09856b.png">

**Comment by Hippodamie** [comment]
Μany thanks, Magdalena.
The priority for us is to be able to use the Search function in Greek again.
Could you please fix it?
Thanks for what you did.
Good night,
Sophie
