### ISSUE TITLE
Α new Complex Structuration label: delocutive

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#495]
Dear Magdalena,

Could you please add Deloc. between Deadj and Denom.?

Many thanks,

Good break !
Best,
Sophie

**Comment by Hippodamie** [comment]
Actually, we will need (I confirm it next week):
not only delocutive but also
clausal
conversion
phrasal
Alphabetic order in the list.

Best,
Sophie

**Comment by Hippodamie** [comment]
It is ok: I confirm it is ready to proceed.
Many thanks in advance,
best,
Sophie

**Comment by tuurma** [comment]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/449468/48153650-10060780-e2c7-11e8-8884-bd5a90a515fe.png">

**Comment by Hippodamie** [comment]
Great ! Many thanks !
