### ISSUE TITLE
Lexemes deletion: does not work. Could you fix it?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#496]
Dear Magdalena,

Deletion of the currently so-called lexemes, which are actually bases, does not seem to work, since I try to do it. Deleted is written after. But when I refresh, bases are still there and indicated as being to delete.

1. Could you, please, fix it?
2. Could you, please, also automatically delete all bases waiting to be deleted?

Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Just checked with δατσμ and couple others and everything seems to work fine. Please reopen if you experience the problem again.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/449468/50018872-f98f5200-ffd0-11e8-9787-7371191ee385.png">
