### ISSUE TITLE
A bug we generated: could you please help to fix it?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#497]
Dear Magdalena,

Look at that
![capture d ecran 2018-11-03 a 11 46 55](https://user-images.githubusercontent.com/16923546/47951234-16f6e800-df5e-11e8-96e7-2a11fb01a2a9.png)

Here is the name:
![capture d ecran 2018-11-03 a 11 48 17](https://user-images.githubusercontent.com/16923546/47951243-3aba2e00-df5e-11e8-9a85-1ed840715f80.png)

Could you please fix it? I cannot, sorry for that.
Many thanks in advance,
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
We will have now (and have already a little) new complex bases of 3 types:
1. with = in the middle like ευ=τυχ
2. with +, like επι+τυχ
3. with # like αγαθ(ᾱ)#ᾱμερ(ᾱ)

Here is my question1:
are those signs ‘authorized’ or do they possibly generate bugs?

For all 3 types, we continue to edit the left corresponding form of the base like:
ευ_τυχ
επι_τυχ
αγαθᾱ_ᾱμερ(ᾱ).

Question 2 linked:
Is it possible like that from your point of view? 

Question3:
I suppose that we will be able in the future Search interface to query for the names in =, the names in +, the names in #, even if we edit them all in the left case/box as x_y. Could you, please, confirm it?

Thank you for all,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Here's a list of duplicates. Cleaning these up.

"hελλᾱνικο - 2"

"αγαθᾱ_τυχᾱ - 4"

"αρϝᾱ - 2"

"ευ_ρυθμιᾱ - 5"

"πῡρο - 2"

**Comment by tuurma** [comment]
Answering your question on combining things with _+#: it is possible to include these signs but I strongly suspect it is not a good idea to combine different roots with, I assume, different meanings in single base form. You would need to explain rationale behind this idea more clearly, I'm afraid.

**Comment by tuurma** [comment]
for the future reference

```query
xquery version "3.1";
declare namespace tei="http://www.tei-c.org/ns/1.0";

let $m := '/db/apps/lgpn-ling-data/data/taxonomies/morphemes.xml'

return 

for $morph in doc($m)//tei:category
    let $base := $morph/@baseForm
group by $base
order by $base

return if (count($morph) > 1) then $base || ' - ' || count($morph) else ()

```

**Comment by Hippodamie** [comment]
Yes of course, thank you !
