### ISSUE TITLE
Restoration of Search function is of course the priority. Thanks for your help.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#499]

**Comment by tuurma** [comment]
Yes, I'm on it.

**Comment by tuurma** [comment]
I will have to update the server to a new version of exist. Will try to do it on Friday evening.

**Comment by tuurma** [comment]
Leading wildcard queries introduced with cf27eb830fbe14e090ce6a9a9c183be3e89fdd39 
Updating the server to the current eXist 4.x.x develop fixed the problem with polytonic Greek searches

I have also introduced a change in behaviour, queries are only sent when hitting Enter, to prevent sending a new query with every keystroke

<img width="1627" alt="image" src="https://user-images.githubusercontent.com/449468/48342664-99735c00-e670-11e8-8a46-138745e371b8.png">

**Comment by Hippodamie** [comment]
WONDERFUL, Magdalena. 

THANKS A LOT !!!

Do I understand well that:
– Enter has always to be pressed after any *search?
– * is to use always.
– Can we use both at the same time like *φαν* without make problem?

We have also to find with you a new way to have 2 copies on 2 different servors. That is why a quick memo on Git-Hub services could help both teams… How would they charge, for example, monthly or yearly, asked right now Richard? And the problem is for lgpn-ling that TGIR Huma-Num hostes for free, BUT would ike we take their url with Huma-NUm at the end.
What do you advise to do? Since we would like Robert and I the 2 projects keep being hosted in the future at classics-ac-ox-uk. Could lgpn-ling have a 2 different url at the same time? But we need securization not only of the datas but also of the applications, not to know again restoration of a less performant version of the application (with Search not working as well as before!).

Many, many thanks,
best wishes,
Sophie

P.S.: when do you plan to do the 2 other things I asked for Renaming columns and TRansfer of Suff1 below Greek Name? Please tell me, even if it is delayed, so that I can organize my own planning.

**Comment by tuurma** [comment]
1. Enter has to be pressed **always**, regardless if the query contains * or not
2. No need to put * at the end - it is always assumed by the application
3. Initial * needs to be entered **only** if you want matches with your query string in the middle or at the end

I will aim to work for Ling Thursday or Friday.

**Comment by Hippodamie** [comment]
Ok, Magdalena,
I think I have it.
It is perfect for me on Thursday or Friday: I plan to be available. 

With all best wishes and thanks,
Sophie
