### ISSUE TITLE
Macron needed for omicron & epsilon: to pick in Police IFAOgrec UNicode on the Web

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#50]
See Ἀγαθό-δωρος, for example : R2 = δο̄ρ
I cannot do it with epsilon & macron : it does not appear here.
I attach a R2 of a name like Ἀγα-μήδης.  
![capture d ecran 2016-01-29 a 09 07 15](https://cloud.githubusercontent.com/assets/16923546/12670355/1031bc3c-c668-11e5-9604-29c1cdf78a34.png)

**Comment by tuurma** [comment]
same as #20, close the other one as it only mentions trouble with o

**Comment by tuurma** [comment]
Arial Unicode MS solve the issue for omicron and macron entered as omicron + combining diacritic macron; combined character in private area only

**Comment by tuurma** [comment]
from Edouard's email, reopening
"I finally understand the problem with this character. 
The combination that works right now in our environment is not a glyph combining an omicron with a Greek macron. It's simply the letter omicron with a latin macron on top. I found this by inserting the character here: 

​Not only this is not the cannonic way of expressing the combination, but I suspect that this could cause problems for the users who, looking for a specific root, will type in, as I do, the combination as required by the APA association and their fonts, standard adopted now in almost every Greek font, including IFAO Greek Unicode. 
To me, this looks like a problem and a use which is not very orthodox, opening the way to potential problems (beyond the user issue explained above, there will be the problem of compatibility with other databases and others, that we cannot even imagine now)
Best wishes,
Édouard"

**Comment by edouardchiricat** [comment]
The correct unicode value for the glyph omicron + Greek macron is U+E1C3 (This is one character, not a combination of two characters, as it is the case with omicron (U+03BF) with latin macron on top (U+0304).
