### ISSUE TITLE
ων_  not anymore in the Suff1 droplist, but again we have: ων and then ων(without underscore)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#500]
Dear Magdalena,

here a missing thing.
The undescore ων_ was the ων with Genitive -οντος.

Thanks for you help,
best,
Sophie

**Comment by Hippodamie** [comment]
We had
ων
ων_
Τhe second is the less frequent.

**Comment by tuurma** [comment]
Sorry, must have missed it somehow. Now fixed.
