### ISSUE TITLE
Datas securization

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#501]
Dear Magdalena,

I hope you are well and not too tired by the unpleasant event.

If you are at work for LGPN-Ling the 2 next days, here are my requests and the priority range.

Of course, we need at first the restoration of all functionalities of the application as they were before the crash. I already give you notices of the small points missing.

Then, the most urgent task are: Renaming columns and #488.

Just after comes the better securization of the application itself and its datas.
My request is the following:
to have application and datas duplicated as you proposed months ago (the master base at Oxford, the slave base at French TGIR Huma-Num), with synchronization of both made at least twice a day like in Oxford.

I already have a free stockage place at TGIR Huma-Num (I had to, part of the requisits for the fundings), where I put copies I take of the datas, letter by letter, which is a really time-consuming task and almost impossible to realize regularly.

Here is a screenshot of how this stockage-space looks like.
Could you please make a priority of proceeding to the installation of a slave-version of LGPN-Ling in TGIR Huma-Num in synchronized interconnection with Oxford ?
 
<img width="1223" alt="capture d ecran 2018-11-07 a 11 39 59" src="https://user-images.githubusercontent.com/16923546/48126592-ce9f3900-e281-11e8-9ee9-28e3d13f37cc.png">

It is definitely for me a condition of security. We cannot continue working without it. The aim is of course to keep the master-app at Oxford, where LGPN-Ling will stay with LGPN in the future and share the same domain name according to Robert Parker and I.

Tell me please if you can work at it those next days.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
I've sent an email to contacts at Huma-Num today

> Dear Stephane and Gerald, dear Sophie.

> The LGPN-Ling project is required to keep its data available at HUma-Num repository, but since in its origins it is sharing the database instance on the Oxford server with a related project, Lexicon of Greek Personal Names (LGPN). Applications used for editing are sharing some resources thus it would be unfeasible to transfer LGPN-Ling completely to a different hosting site. Nevertheless, it makes perfect sense to make sure that current copy of all LGPN-Ling data and application code is hosted elsewhere. For this purpose I'd suggest we use a git repository for which we could set up database triggers so all the updates are virtually immediately available in the git repo. On the Huma-Num part it would be required to configure daily pulls from the repository to always have a recent copy.

> Please let me know if you like the solution sketched above and how can we proceed with this.

**Comment by Hippodamie** [comment]
Many thanks, dear Magdalena: it seems perfect.
Good evening,
with all best wishes,
Sophie
