### ISSUE TITLE
Significant relative names: e. g. additional

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#502]
Dear Magdalena,

Could you please add to the significant relative name the mention 
e. g.
so that we could read on the screen:
**e.g. father** of Eumoiros (or so on).

I mean e.g. should take place just before father or son etc. (in this order exactly).

Many thanks in advance,
with best wishes,
Sophie

**Comment by tuurma** [comment]
<img width="158" alt="image" src="https://user-images.githubusercontent.com/449468/48153178-ec8e8d00-e2c5-11e8-866f-831ae4049e82.png">

**Comment by Hippodamie** [comment]
Perfect  ! Thanks !
