### ISSUE TITLE
Eutrēsios: the root we cannot open

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#503]
Hi, Magdalena,

a problem on this name, whose root is without access: the sub-form does not open.

Could yo please fix it?

Many thanks in advance,
with alla best wishes,

Sophie
<img width="942" alt="capture d ecran 2018-11-07 a 18 35 12" src="https://user-images.githubusercontent.com/16923546/48149189-c95ee000-e2bb-11e8-9397-647cf8222035.png">

**Comment by tuurma** [comment]
fixed

<img width="856" alt="image" src="https://user-images.githubusercontent.com/449468/48152643-b6044280-e2c4-11e8-95d0-e9e4d9757893.png">
