### ISSUE TITLE
Next urgent task. Greek alphabetical Ordering of the lexems in the drop-down lists. The same for the personal names themselves

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#509]
Dear Magdalena,

This is a task urgently needed since when we call a lexem, especially the shortest forms like ευ, ν_, α, etc., we spend a lot of time searching it in the list and never know where in the list it will appear. Sometimes we cannot find it and it happens we type it again, which is not good.

Ordering will mean have our lexems lists in the exact Greek alphabetical order. Letter by letter, like ν_ before να, then ναβ, ναγ, etc, νεβ, νεγ and so on.

Could you ask your machine, from Greek dictionaries datas, to put the lexems in the same order as in modern Greek, which is the same?

The only small trouble afer that will be the initial ϝ, which it is easy for me to give you the exact position in the alphabet: it is after ε (epsilon) and before the ordinary next one (ζ, capital: Z).
 
Another small trouble would be the initial (h). But in Greek, it does not matter. I mean that α or (h)α must be in the list among initial α lexems. So, we will list together αγ and (h)αγ and have to decide which one we set before the other. We would prefer at first αγ and just after the almost homonymic (h)αγ.

The same of course is true for the personal names themselves in the whole DB LL: we should be able to call for the whole 11400 in their exact alphabetical order.

Here is the next task I would like to ask you to do. It is of course not only for the preparation of the Searching interface, but also for our everyday work not only of Edition but also of Revision: it is a condition of improvement of the scientific work we now urgently need.

After, I think you could take a break with LL for a while.

But I do not know how to thank you of the improvement of the performances we observe now, since the crash!

with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
The urgence is because when we search especially for a letter alone like very often α alone or επ or ευ (1, 2 letters sequences), we never are able to find them in the lists.

Could you, please, at least put those 1, 2 letters sequences at the top of the list, to find them quickly?

Thanks a lot,
best,
Sophie

**Comment by tuurma** [comment]
I have adjusted the order and also made the Lexemes page load faster. Didn't manage to make initial h ignored, will try to work on it next.

**Comment by tuurma** [comment]
Sorry, my mistake, the ordering I've introduced is not working with data tables... Will work on it more.

**Comment by tuurma** [comment]
I've disabled pagination, so that all lexemes are shown in a long list. Please let me know if this display is more helpful than before. You can search with Ctrl+F, using the browser mechanism.

**Comment by tuurma** [comment]
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/449468/50013898-b8904100-ffc2-11e8-95e6-e51fa5bc0039.png">

**Comment by Hippodamie** [comment]
Dear Magdalena,

for us, the previous display was good: the only point was the slowness. And the improving of the alpjhabetic ordering of lexems and Greek names. I look at that as soon as I can.
But sorry, I must leave now.
With all best wishes and thanks,
Sophie
