### ISSUE TITLE
A small complement of task in relation with the bases in -(εσ): take off the parentheses

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#510]
Dear Magdalena,

Sorry not to have asked in the same time: could you please take off the parentheses () for all the bases currently ending with -(εσ)?

Many thanks in advance.

Then, it will be totally clean.

With all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Thus, they would end in: -εσ
That's it !
best,
S.

**Comment by tuurma** [comment]
Here's the list, could you please check if these are entries you'd like changed?

-- | --
(h)ᾱ̆κ-(εσ) | hακεσ
(h)αλλ-(εσ) | hαλλεσ
(h)αμ(α)ρτ-(εσ) | hαμαρτ
(h)εδ-(εσ) | hεδεσ
(h)ελ(εσ) | hελεσ
(h)ερκ-(εσ) | hερκεσ
(ϝ)(h)ᾰδ-(εσ) | ϝhᾰδεσ
(ϝ)(h)ε̄θ-(εσ) | ϝhε̄θεσ
(ϝ)αρδ-(εσ) | ϝαρδεσ
(ϝ)ειδ-(εσ) | ϝειδ
(ϝ)ειδ-(εσ) | ϝειδεσ
(ϝ)εικ-(εσ) | ϝεικεσ
(ϝ)επ-(εσ) | ϝεπεσ
(ϝ)ετ-(εσ) | ϝετ
hε̄ρ(ᾱ/ο)=κλε(ϝ)-(εσ) | hε̄ρα_κλεϝεσ
α-λᾱθ-(εσ) | α_λᾱθεσ
α(ν)/ν=σφαλ-(εσ) | α(ν)/ν_σφαλ
α(ν)/ν=σφαλ-(εσ) | αν_σφαλ
αισχ-(εσ) | αισχ
ακριβ-(εσ) | ακριβ
ᾱ̆λεγ-(εσ) | ᾱ̆λεγεσ
αλθ-(εσ) | αλθεσ
αλκ-(εσ) | αλκεσ
ανθ-(εσ) | ανθεσ
αντι=φαν-(εσ) | αντιφανεσ
ᾱ̆ρ-(εσ) | ᾱρεσ
αρκ-(εσ) | αρκ
ᾱ̆φ(ε)ν-(εσ) | ᾱ̆φεν
βαρ-(εσ) | βαρεσ
δαπ-σ-(ιλ)-(εσ) | δαπσιλεσ
δεικ-(εσ) | δεικεσ
δε̄ν(σ)-(εσ) | δενσεσ
δι(ϝ)(ε)(ι)=τρεφ(εσ) | διϝειτρεφεσ
δια+γεν-(εσ) | δια_γενεσ
δρῡ+πετ-(εσ) | δρῡ_πετεσ
δυσ=ᾱρ-(εσ) | δυσ_ᾱρεσ
δυσ=μαρ-(εσ) | δυσ_μαρεσ
εκ=φαν-(εσ) | εκφανεσ
εμ+φερ-(εσ) | εμ_φερεσ
εμ=φαν-(εσ) | εμφανεσ
εν=δελεχ-(εσ) | εν_δελεχεσ
εν=τρεχ-(εσ) | εντρεχεσ
εντ(εσ) | εντεσ
επ=ᾱν-(εσ) | επ_ᾱνεσ
επι+(ϝ)εικ-(εσ) | επι_ϝεικεσ
επι+γ(ε)ν-(εσ) | επι_γενεσ
επι+τρεφ-(εσ) | επιτρεφεσ
επι=τᾱδ-(εσ) | επι_τᾱδεσ
επι=φαν-(εσ) | επιφανεσ
ευ=(ϝ)ειδ-(εσ) | ευ_ϝειδεσ
ευ=ᾱρ-(εσ) | ευ_ᾱρες
ευ=γεν-(εσ) | ευ_γενεσ
ευ=κλεϝ-(εσ) | ευ_κλεϝεσ
ευ=κρῑ-ν-(εσ) | ευκρῑνεσ
ευ=λαβ-(εσ) | ευ_λαβεσ
ευ=μᾱκ-(εσ) | ευ_μᾱκεσ
ευ=μαρ-(εσ) | ευ_μαρεσ
ευ=παλ-(εσ) | ευ_παλεσ
ευ=πετ-(εσ) | ευπετεσ
ευ=πτο-(εσ) | ευ_πτο-εσ
ευ=σθεν-(εσ) | ευσθενεσ
ευ=στα-θ-(εσ) | ευ_σταθεσ
ευ=τελ-(εσ) | ευτελεσ
ευ=τριβ-(εσ) | ευ_τριβεσ
θ(α/ε)ρσ-(εσ) | θαερσεσ
θαλ-(εσ) | θαλ
θεο=δ(ϝ)ει-(εσ) | θεο_δϝειεσ
θερ(εσ) | θερεσ
θυρ-ᾱ(ι)=γ(ε)ν-(εσ) | θυρᾱι_γενεσ
ιθα(ι)=γεν(εσ) | ιθαι_γενεσ
κᾱδ(εσ) | κᾱδ
κερδ-(εσ) | κερδεσ
κλε(ϝ)-(εσ) | κλεϝ
κρ(α)τ-(εσ) | κρατ
κριν-(εσ) | κρινεσ
κῡδ-(εσ) | κῡδεσ
λαβ-(εσ) | λαβεσ
λᾱ̆χ-(εσ) | λᾱ̆χεσ
μᾱ̆θ-(εσ) | μᾱ̆θεσ
με̄-δ-(εσ) | με̄δεσ
με̄̆-δ(εσ) | με̄̆δ
μεδ-(εσ) | μεδ
μελ-(εσ) | μελ
μετ(α) =γ(ε)ν-(εσ) | μετ(α)_γ(ε)ν-(εσ)
οφελ-(εσ) | οφελεσ
π(ε)ιθ-(εσ) | πειθεσ
πᾱ̆γ-(εσ) | πᾱ̆γ
παθ-(εσ) | παθεσ
περι+γ(ε)ν-(εσ) | περι_γενεσ
πετ-(εσ) | πετεσ
πο(τ)(ι)=γ(ε)ν-(εσ) | πο(τ)(ι)_γενεσ
πολυ=(ϝ)ειδ-(εσ) | πολυ_ϝειδεσ
σακ(εσ) | σακεσ
σεβ-(εσ) | σεβεσ
σθεν-(εσ) | σθεν
σκελ(εσ) | σκελ
στα-θ-(εσ) | σταθεσ
συ-(εσ) | συεσ
σφαλ-(εσ) | σφαλ
ταγ-(εσ) | ταγεσ
τελ-(εσ) | τελ
τε̄ρ-(εσ) | τε̄ρεσ
τερπ(εσ) | τερπεσ
τυπ-(εσ) | τυπεσ
φαϝ-(εσ) | φαϝ
φαϝ-(εσ) | φαϝεσ
φαν-(εσ) | φανεσ
φᾱρ(ϝ)-(εσ) | φᾱρϝεσ
φειδ-(εσ) | φειδεσ
φερ-(εσ) | φερεσ
φραδ-(εσ) | φραδεσ
χαρ-(εσ) | χαρεσ
ψευδ-(εσ) | ψευδ

**Comment by Hippodamie** [comment]
Dear Magdalena,

thanks for all.
Finally, not so sure we will take them off. It will take time to answer. And I am not available until Wednesday now.
So ti will have to wait a little.
Have a good week-end,
best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

finally I cancel my request for that. But I thank you a lot for the list you made, which is very useful for us and made possible for us to decide finally we did not have to ask you to cut the parentheses.
With all best wishes for the holidays,
Sophie
