### ISSUE TITLE
The appearance of the implementation fo the new columns titles

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#511]
Dear Magdalena,

It currently looks awful !  Would it be possible, please, to make disappear the grey lines which make like not pretty boxes instead of the beautiful/clean apparance we had before...
When you presented it yesterday, I thought the lines were like a work/schema for you.

And, as I told you, the undertitles in smaller size than the uppertitles, if possible!

But may be it is only your work progressing.

Thanks for what you did anyway.
Best,
Sophie

**Comment by Hippodamie** [comment]
Hi, Magadalena,

another problem with that: it takes places like 2 lines of names analysis, and very often we need to see together on the same window the most names possible.

So, would it be possible to gain place at the top, for example, by making the grey vertical lines not so high and diminish the space available between Show 50 entries and Name (which is the upper line)?

Many thanks,
wuth all best wishes,
Sophie

**Comment by tuurma** [comment]
Sorry, I have removed vertical borders. In the end I did not increase size for headings as it consumes even more space, but removed bold styling on the subtitles.

We can think some more about saving space in the visualisation table but maybe after we are done with the functional requests?
