### ISSUE TITLE
Priority range of next tasks

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#513]
Dear Magdalena,

Here is the priority range I would like you deal with the tasks.
Actually, the most urgent is #501: datas and application securization. What would you propose?

After comes 474.
Thereafter:
506
510
509.
Here you are!
But if you have not much time, please think about what to propose us about securization.
A copy of datas and application on HUma-NUm would be the best solution, since they have the memory capacities and for free.

Thanks in advance.
Best wishes,
good night!
Sophie

**Comment by tuurma** [comment]
some are already closed, the ones still opened I just marked as priority so closing this one
