### ISSUE TITLE
Α Suffix 1 to slightly modify: change, please, ε(ι)ᾰ/είη       into:     (V)(ι)ᾰ/(V)ίη. Thank you!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#517]
Dear Magdalena,

Could you, please, make the little modification in one Suff1 as you see in the title?

Many thanks.

Good evening,

best wishes,
Sophie

**Comment by tuurma** [comment]
replaced 60 entries

for $i in collection('/db/apps/lgpn-ling-data/data/names')//tei:m[@type='suffix'][.='ε(ι)ᾰ/είη']
return update replace $i/text() with '(V)(ι)ᾰ/(V)ίη'

**Comment by Hippodamie** [comment]
Many thanks!
