### ISSUE TITLE
Coming back to the previous status about the respective order of XY labels and Comlex structuration labels! 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#519]
Dear Magdalena,

I do not find the older issue, but maybe you remember I asked you previously to change the order of XY vs Complex structural labels (visualizing Complex before XY labels and not anymore XY before Complex) . And you did it. But it was a mistake, because now we see non sense things like you see below, I mean /YX    XY 
<YX    XY, which of course does not make sense.  

<img width="1180" alt="capture d ecran 2019-01-05 a 10 32 52" src="https://user-images.githubusercontent.com/16923546/50722802-f15c9b00-10d4-11e9-8e28-bd5f67d2a8d0.png">

Could you please restore the previous order, so that we indeed have: XY/YX and XY<YX etc., exactly as it was before?

It is, like #518, the other priority, because it looks quite confusing right now.

Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/449468/50772328-ab970280-128d-11e9-960a-5d8484dfb15b.png">

**Comment by Hippodamie** [comment]
Ouf !!! It looks quite better like that!
Many thanks,
best wishes,
Sophie
