### ISSUE TITLE
A request: the list of names with only the Attic dialectal label

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#520]
Dear Magdalena,

could you, please, give us the list of all the names already edited which only have as their dialectal label ‘Attic’? We will have to check them all.

Thanks a lot.

Best wishes,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

there are 1780 names where 'Attic' occurs as dialectal label and 882 where it is the only dialectal label.

To see the list of the latter (only Attic) please use the list at http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/import/attic.xq

**Comment by Hippodamie** [comment]
Dear Magdalena,

many, many thanks. 
Could I ask you for a so little thing: a coma is missing in the title of the column in French ‘Aires géo-dialect., interlinguistiques’, juste after the dot. 
Could you please add it, since it looks quite absurd!
Many thanks in advance,
with all best wishes,
Sophie
