### ISSUE TITLE
Interrogation dots ? To make them re-appear

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#521]
Dear Magdalena,

how are you?
Could you, please, make all the existing ? again visible?
For example, see the Editor for the name Eurylos. When we cross the little boxes, we would like to have the information visible

Many thanks for your help,
have a nice day,
best wishes,
Sophie
![capture d ecran 2019-01-09 a 12 02 16](https://user-images.githubusercontent.com/16923546/50895377-3f8bda00-1406-11e9-8835-37d642fbbdb0.png)

**Comment by tuurma** [comment]
I wasn't entirely sure how to visualise the 'Linking of the form...' Please let me know if you're happy how it looks like

<img width="540" alt="image" src="https://user-images.githubusercontent.com/449468/51737508-10739a80-208d-11e9-8070-5b7ba04b1bd4.png">

**Comment by Hippodamie** [comment]
It is perfect!
Thanks!
Best,
S.
