### ISSUE TITLE
 ‘Deadv.’ missing, among new complex structuration label, in the list

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#522]
Dear Magdalena,

could you, please, add it? IT is missing.
Please, between Deadj and Deloc.

Many thanks,
with all best wishes,
Sophie

![capture d ecran 2019-01-09 a 18 15 20](https://user-images.githubusercontent.com/16923546/50916036-62d07c80-143a-11e9-89a1-1a25dd5d5bb2.png)

**Comment by tuurma** [comment]
<img width="237" alt="image" src="https://user-images.githubusercontent.com/449468/51626784-9d5d0d80-1f40-11e9-9bd4-b20cd3e8d19d.png">
