### ISSUE TITLE
Planning and budgeting 2019 and Searching interface

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#526]
Dear Magdalena,

thanks you for the news, which are quite good, congratulations for all (and the children improving their skying!)

Questions before thinking about the interface:

1. what is the best solution:
a. begining to build the searching interface before the end of the edition of the whole stock of the names?
b. or rather waiting for the end of the edition before building it?

Best solution means:
 for you, the more logical solution and more economical in time spent (same for me, actually).

2. What is the approximate total cost you plan for: the building of the Search interface and making it working and available in free access for people on the web? I exactly mean the perfect completion of the work. I would like a little detailed estimate about the main issues of this complete work. Could you please give it?

3. How do you see LGPN-Ling Search interface, with your experience of other projects (but, maybe, ours is the only one with 2 heads)? Our own Search interface and LGPN own Search interface (= 2 different), with a connection between both, cliking on the Greek form of the name in both?

I put the same issue on Git-Hub, to find it easily.

Best wishes,
thanks for all,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

Could you please make an Estimate for the cost of the building of the whole Search Interface, with the different steps of your work?

We of course need the Estimate to ask for provision and prepare payment.

The address of facturation will change now, so you will have to write at the top:
Sophie MINON
Projet ANR/LGPN-Ling
Laboratoire ANHIMA, UMR8210
aux bons soins de
Isabelle BART et 
Emmanuel Proust
2, rue Vivienne
75002 Paris

Many thanks in advance,
best,
Sophie

**Comment by tuurma** [comment]
Estimates sent out today and we agreed to discuss in detail first half of August and implement in September.
