### ISSUE TITLE
Items repeated in the pop-up list of Suffixes 1

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#527]
Dear Magdalena,

how are you? Hope you all do well.
Just to ask you to correct, if possible the indue repetition of items I discover in the pop-up Suffixes 1 list.
Look at the screen-shot.
<img width="404" alt="Capture d’écran 2019-03-16 à 13 54 51" src="https://user-images.githubusercontent.com/16923546/54475589-18c99580-47f3-11e9-9e10-e04a8165e1b4.png">

Could you please remove the 2 at the top and just keep the last 3 = 
ιώ(ι)
ίων
ον

Thanks for your help,
with all best wishes,
have a good week-end,
Sophie

**Comment by tuurma** [comment]
<img width="186" alt="image" src="https://user-images.githubusercontent.com/449468/59938457-4d359900-9455-11e9-85c6-a1a47d9729f2.png">
