### ISSUE TITLE
hιππο Root

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#528]
Dear Magdalena,

how are you? Did you solve the problem on the servor?

Could I ask you for a small help?

We currently have edited in the Sub-Form,
at left hιππ and at right: hιππ(ο).
We would like to have at left too the omicron, so: hιππο instead of hιππ.

Βut they are I guess something like 379 different names edited. And Gerard will finish the family this week-end.

Could you make it automatically, next Tuesday?

Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
There are 429 occurrences of hιππ root form. Converted to hιππο with

```xquery
for $i in collection('/db/apps/lgpn-ling-data/data/names')//tei:m/@baseForm[.='hιππ']
return
    update replace $i with 'hιππο'
```

**Comment by tuurma** [comment]
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/449468/54907959-13510700-4ee7-11e9-9934-dff18ee66e91.png">

**Comment by Hippodamie** [comment]
Dear Magdalena,

many thanks for all!
I ask Violeta ot do the jo you ask for because I am not available until Wednesday.
But Violeta should be able to do it today.
Have a good day
With all best wishes,
Sophie

But these lexems are OK, as it seem to me. No job to do on them.
