### ISSUE TITLE
hᾱγεσι

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#530]
Dear Magdalena,

we try to homogeneize some other roots forms and have a problem with hᾱγεσι:
we cannot find 2 personal names with the ancient left form hᾱγεσ, that we now transform into hᾱγεσι.
We didi it for 75 occ. but 2 are left.

Could you please help us to find both?

Many thanks,

![Capture d’écran 2019-03-21 à 14 29 06](https://user-images.githubusercontent.com/16923546/54755533-6759a400-4be6-11e9-86a3-51b85f12f042.png)

with best wishes,
Sophie

**Comment by tuurma** [comment]
These are: Hagēhistratos and Hagēhilas

<img width="955" alt="image" src="https://user-images.githubusercontent.com/449468/54905582-ad15b580-4ee1-11e9-9180-a014e1ee4bd0.png">
