### ISSUE TITLE
Still more problems with identical ID: could you please help?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#531]
Dear Magdalena,

I do not understand what happens.
Look at that, on twice wanaktsi2, whereas they were supposed to be distinguished as on the Googledoc document
<img width="655" alt="Capture d’écran 2019-04-04 à 14 24 48" src="https://user-images.githubusercontent.com/16923546/55555211-08ffeb80-56e5-11e9-866c-0b4eff9607aa.png">
<img width="952" alt="Capture d’écran 2019-04-04 à 14 24 14" src="https://user-images.githubusercontent.com/16923546/55555220-0d2c0900-56e5-11e9-89c3-4e1adabc4e31.png">
Could you please help? The best solution is to make as on the Googledoc in red, and I will after you give the right base to the right name (there are only 
<img width="693" alt="Capture d’écran 2019-04-04 à 14 18 01" src="https://user-images.githubusercontent.com/16923546/55555653-0e116a80-56e6-11e9-8a2d-5f1ea031c7db.png">
a few with the meaning ‘Wanakes’.
Because we are as in the fog now that the 2 identical ID make the bases mixted.

For another problem of confusion between the ανν of the negation and the ανν meaning ‘grand mother’, I made a new basis: αννι αν(ν)-(ι) for ‘grandmother’. All the others are for the other base, the negation.

Could you please deal with those, because it is so confusing right now.

Many thanks in advance,
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

I tried to begin myself το re-work both and to re-distribute the names between the 2 bases.
But it does not work very well.

And I do not find in the lexems list the new base ϝανακτσι (ϝ)ανακ(τ)-σ(ι) I tried to create.
And the other ϝανακτσι2 is twice visualized.

I think the best way for you to help would be to only keep the currently names in ϝανακτσι2 meaning Wanakes Dioskouroi, and to transfer all the others into the other base: ϝανακτσι (ϝ)ανακ(τ)-σ(ι) be lord, be master.

Could you please make a priority? Because it is currently a miss.

Thank you so much.
With all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

here is the job.

Re-distribution has been done between names in ϝανακτσι verbal and names in ϝανακτσι2 Disokouroi.
<img width="734" alt="Capture d’écran 2019-04-04 à 15 52 47" src="https://user-images.githubusercontent.com/16923546/55560826-5da96380-56f1-11e9-9873-8551f417cad9.png">

The only thing I ask you to do, because I cannot is to make the currently duplicated ϝανακτσι2 being alone.

Could you please do it?
And the same for negative ανν?

Many thanks in advance,
best wishes,
Sophie

**Comment by tuurma** [comment]
sorry, I was in meetings in town all day

<img width="887" alt="image" src="https://user-images.githubusercontent.com/449468/55580710-7595dd00-571b-11e9-861c-372f412c5c51.png">

<img width="853" alt="image" src="https://user-images.githubusercontent.com/449468/55580744-87778000-571b-11e9-905f-9206b3046994.png">

**Comment by Hippodamie** [comment]
Dear Magdalena,

so many thanks: ouf!!!
Could I make you remember of 3 other small things waiting like:

2 other similar bugs:
Look at αινο twice (do not take care of αινιστο). Ι created thus αινιο instead of the αινο of Ainos city of Thrace. There was only 1 name/occurrence: Mister Ainios.

1. So could you please keep only αινο 56 praise and delete the other αινο Ainos, city of Thrace?


2. Almost the same for θε̄ρᾱ. I had to create θε̄ρᾱ2 for the city of Thera, different from θε̄ρᾱ hunting, hunter.


Could you please delete the second one: θε̄ρᾱ  θε̄ρᾱ  47    Τhera, and keep only the first with its 47 occurrences?


3. Impossible for us to find the last guy who had a root in κλεϝεσ, since we have try to re-made all of them into now κλεϝεσι.

The other last 9 (for which our job has been done) are:

Κλεισ-αγόρας (1+) Dor. E., Ion. cycl. 4a-hell.
Κλησι-μβρότα f. (1) Dor. S. 7a (m. Κλεισίμβροτος Dor. E.).
Κλεισι-μβροτίδας (1+) Dor. E. 3a-1a.
Κλεισ-ανθίδας (1+) Dor. E. 2a.
Κλήσ-αρχος (1+) Dor. O. 6a-3a.
Κλεισί-θεμις (1+) Dor. E. 2a-1a.
Κλεήσ-ιππος (1+) Dor. S., Th.-Cyr. arch.-2a (Κλήσιππος Dor. ; Κλείσιππος Dor. E. ; Κλεύσιππος Béot.).
Κλεισ-ιππίδας (1+) Dor. E., Éol. E. 4a-2a.
Κλεησι-σήρα f. (1) Dor. S. 7a (f. Κλησιθήρα Mac.). Cf. Buck, GD § 64 (laconien σ pour θ).

Could you please find this guy for us?

Many thanks in advance for all,
have a nice end of week (here fresh, but wonderfully sunny and springly)
with all best wishes,
Sophie
