### ISSUE TITLE
A last name in κλεϝεσ wanted!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#532]
Dear Magdalena,

How are you? 

Impossible for us to find the last guy who had a root in κλεϝεσ, since we have try to re-made all of them into now κλεϝεσι.Capture d’écran 2019-03-31 à 15.25.45

The other last 9 (for which our job has been done) are:

Κλεισ-αγόρας (1+) Dor. E., Ion. cycl. 4a-hell.
Κλησι-μβρότα f. (1) Dor. S. 7a (m. Κλεισίμβροτος Dor. E.).
Κλεισι-μβροτίδας (1+) Dor. E. 3a-1a.
Κλεισ-ανθίδας (1+) Dor. E. 2a.
Κλήσ-αρχος (1+) Dor. O. 6a-3a.
Κλεισί-θεμις (1+) Dor. E. 2a-1a.
Κλεήσ-ιππος (1+) Dor. S., Th.-Cyr. arch.-2a (Κλήσιππος Dor. ; Κλείσιππος Dor. E. ; Κλεύσιππος Béot.).
Κλεισ-ιππίδας (1+) Dor. E., Éol. E. 4a-2a.
Κλεησι-σήρα f. (1) Dor. S. 7a (f. Κλησιθήρα Mac.). Cf. Buck, GD § 64 (laconien σ pour θ).

Could you please find this name for us?

Many thanks in advance.

With all best wishes,
Sophie

**Comment by tuurma** [comment]
http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/editor.xhtml?id=Thynoklidas

**Comment by Hippodamie** [comment]
Hi, dear Magdalena,

done and deleted!
Best,
S.
