### ISSUE TITLE
 Α last personal name in Base αργ(ε/ι) wanted!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#533]
Dear Magdalena

Same problem: Impossible for us to find the last name who had a root in αργ(ε/ι), since we have try to re-made all of them into now αργι.

The other last 18 (for which our job has been done) are:

῎Αργας (1+) Crét. 3-2a. 
῎Αργος (1) Gr. occ.
῎Αργων (1) Thess. 3a
῎Αρκα-πος ? (1) Mac. 5a.
Ἀργαῖος (10+) Mac. etc. 7a-2p.
Ἀργᾶς (1) Att. 4a.
Ἀργει-λίας (1+) Béot. 3a
Ἀργέ-λαος (1) Béot. 3a.
Ἀργιάδας (1) A.M. 1a-1p.
Ἀργίδης (1) Att. 6a.
Ἀργι-κλίδας (1) Béot. 3a. 
Ἀργι-λεωνίς f. (1) Dor. S. 5a
Ἀργι-λίδας (1) Béot. 3a.
Ἀργί-λιος (1+) Béot., Dor. NO., Thr.-Pont 4-2a.
Ἄργι-φος ? (1) Dor. NO. 3/2a 
Ἀργίων (1) Béot. 3a.
Ἀργύλος (1) Pélop. 3p.
Ἀργώνδας (1) Béot. 5a

![Capture d’écran 2019-04-11 à 10 26 22](https://user-images.githubusercontent.com/16923546/55941986-b45bf380-5c43-11e9-90d1-9b8bcb62e96b.png)

Could you please find this name for us?
Many thanks in advance.

With all best wishes,
Sophie

**Comment by tuurma** [comment]
http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/editor.xhtml?id=Argiklidas

**Comment by Hippodamie** [comment]
No, it does not seem it is the good one, look at this:
<img width="700" alt="Capture d’écran 2019-04-24 à 18 37 11" src="https://user-images.githubusercontent.com/16923546/56676813-66bd9d00-66bf-11e9-808d-d515146b0d36.png">
And we have still, the one with αργ left:
![Capture d’écran 2019-04-24 à 18 39 05](https://user-images.githubusercontent.com/16923546/56676914-98366880-66bf-11e9-9cf1-ad58bf331fc6.png)
Thanks in advance for what you can do.
Best,
Sophie

**Comment by tuurma** [comment]
Sorry, it was http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/editor.xhtml?id=Argikidas just one letter difference ;-) I've updated it

before 

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/449468/56679248-e26e1880-66c4-11e9-8b8d-e33e9d7ebf07.png">

after

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/449468/56679497-79d36b80-66c5-11e9-95f3-cea099953284.png">

**Comment by Hippodamie** [comment]
Thanks for all, dear Magdalena.
With all best wishes,
Sophie
