### ISSUE TITLE
Similar issue:  a last name with an αρ-σ(ι) Base : wanted! 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#534]
Dear Magdalena,

Impossible for us to find the last name who had a root in αρ-σ(ι), since we have try to re-made all of them into now αρσι.

The other last 16 (for which our job has been done) are:

Ἀρρι-δαῖος ? (10+) Mac. 5a-4p
Ἀρρί-λεως (1+) Att. 4a.
Ἀρρί-φρων (1) Att. 5a.
Ἀρριφῶν
Ἀρρι-χεύς ? (1+) Eub. 6-3a.
Ἄρρων (1) Att. 4a
Ἀρσάς f. (1) Crét. Imp.
Ἀρσέας (1) Mac. 4a
Ἀρσίας (1+) Béot., Crét. 6-2a.
Ἀρσί-λοχος (1) Béot. 5a.
Ἀρσί-νη f. (1+) Ion. cycl., Dor. E., A.M. 2a-byz.
Ἀρσι-ννώ f. (1+) Thess. 3-2a.
Ἀρσι-νόη ? f. (10+) Mac., A.M. etc. 4a-4p
Ἀρσίφρων
Ἀρσι-φρώνδας ? (1) Béot. 3a.
Ἀρσοῦς f. (1) Koin.

 Could you please find this name for us?
Many thanks in advance.

With all best wishes,
Sophie

**Comment by tuurma** [comment]
http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/editor.xhtml?id=Arsinidas

**Comment by Hippodamie** [comment]
But, dear Magdalena, the name Ἀρσινίδας does not exist (?)
![Capture d’écran 2019-04-24 à 18 47 53](https://user-images.githubusercontent.com/16923546/56677422-cec0b300-66c0-11e9-8891-72a41fbe52cf.png)

**Comment by tuurma** [comment]
Checking... please bear with me

**Comment by tuurma** [comment]
Do you mind trying again? This name (and few others) had a bit outdated structure.

**Comment by Hippodamie** [comment]
Here is the problem, as you can see:
![Capture d’écran 2019-04-24 à 19 14 07](https://user-images.githubusercontent.com/16923546/56679079-873c2600-66c4-11e9-9dc5-e4bf86dba68d.png)

There remains 1 name with αρσ as Root/Base ID, whereas for all the 15 others, we changed αρσ into αρσι, which is what we want.

Could you find the only 1 name which has still αρσ as its ID? As soon as we have it, we change its αρσ in αρσι and then will be able to delete the bad αρσ.

Do you understand better?
Thanks for your help.
Best,
Sophie

**Comment by tuurma** [comment]
Updated Arsinidas and it looks ok now:

before

<img width="868" alt="image" src="https://user-images.githubusercontent.com/449468/56679675-f1a19600-66c5-11e9-8fc2-fd8d44919432.png">

after

<img width="869" alt="image" src="https://user-images.githubusercontent.com/449468/56679725-0f6efb00-66c6-11e9-9d13-1f4511674b99.png">

**Comment by Hippodamie** [comment]
Dear Magdalena,

I do not understand.
But where was  Arsinidas, since it was not on LGPN-Ling?
Best,
Sophie

**Comment by Hippodamie** [comment]
Αnother point is I cannot edit in Arsinidas and there are some informations to add.

Could you please help?
Many thanks,
best,
Sophie

**Comment by tuurma** [comment]
There certainly was an entry for Arsinidas though I can confirm that it is gone now - someone must have deleted it

**Comment by Hippodamie** [comment]
Yes, it was maybe wrongly edited, because the right name is in fact Arsenidas.
So the issue can be closed.
Good week-end,
best,
Sophie
