### ISSUE TITLE
2 bugs to correct: on αινο and θε̄ρᾱ

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#535]
Dear Magdalena,

it seems that 2 other bugs (same ID for 2 bases) does still exist. I hope they will be the lasts.

Look at αινο twice (do not take care of αινιστο). Ι created thus αινιο instead of the αινο of Ainos city of Thrace. There was only 1 name/occurrence: Mister Ainios.

So could you please keep only αινο 56 praise and delete the other αινο Ainos, city of Thrace?Capture d’écran 2019-03-31 à 10.39.23

Almost the same for θε̄ρᾱ. I had to create θε̄ρᾱ2 for the city of Thera, different from θε̄ρᾱ hunting, hunter.
Capture d’écran 2019-03-31 à 10.47.11

Could you please delete the second one: θε̄ρᾱ  θε̄ρᾱ  47    Τhera, and keep only the first with its 47 occurrences?

Many thanks in advance,
with all best wishes and all apologies,
Sophie

**Comment by tuurma** [comment]
No problem, sorry about the delay!

**Comment by Hippodamie** [comment]
Μany thanks!
Looks better!
Best,
S.
