### ISSUE TITLE
Impossible Lexemes deletions

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#536]
Dear Magdalena,

here are the deletions I would like to do since many months and never can! I do ti but they ever re-appear.

Could you please delete them?

Many thanks,
with all best wishes,
Sophie
![Capture d’écran 2019-04-24 à 18 57 33](https://user-images.githubusercontent.com/16923546/56678215-6e327580-66c2-11e9-8680-8cb42a032e13.png)
![Capture d’écran 2019-04-24 à 18 54 53](https://user-images.githubusercontent.com/16923546/56678219-712d6600-66c2-11e9-91e1-87b2410d1719.png)
![Capture d’écran 2019-04-24 à 18 55 08](https://user-images.githubusercontent.com/16923546/56678225-74c0ed00-66c2-11e9-99ac-5134b36a6c11.png)

**Comment by tuurma** [comment]
Deleted the first two (δια_φανεσ and δια_φερο̄̆νισα) and deleting the rest should work now

**Comment by tuurma** [comment]
for future reference, small script to update 

```xquery
for $c in 
 collection('/db/apps/lgpn-ling-data/data/names')//tei:m[contains(@baseForm, ' ')]
 let $bF := normalize-space($c/@baseForm)
 return
(:     ($c, $bF):)
     update replace $c/@baseForm with $bF
```
