### ISSUE TITLE
A name to find

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#537]
Dear Magdalena,

Could you, please, find the only name made of this root (see screenshot)?
Because I think it could be made with another Root and I would like to delete this one.

Many thanks for your help.

With all best wishes,
Sophie

![Capture d’écran 2019-04-24 à 23 01 57](https://user-images.githubusercontent.com/16923546/56693293-608de780-66e4-11e9-8467-cf1211b3e045.png)

**Comment by tuurma** [comment]
It's http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/editor.xhtml?id=Arktōria
