### ISSUE TITLE
About Root/Base αργε/ι αγαιν

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#539]
Dear Magdalena,

We had what your screen shot show: 1 + 18.

You wrote that the name missing was Argiklidas but it was in fact in the previous llist of Violeta, which was the list of the names checked; and we were looking for another name.
Look at the list of 18 names:

῎Αργας (1+) Crét. 3-2a. 
῎Αργος (1) Gr. occ.
῎Αργων (1) Thess. 3a
῎Αρκα-πος ? (1) Mac. 5a.
Ἀργαῖος (10+) Mac. etc. 7a-2p.
Ἀργᾶς (1) Att. 4a.
Ἀργει-λίας (1+) Béot. 3a
Ἀργέ-λαος (1) Béot. 3a.
Ἀργιάδας (1) A.M. 1a-1p.
Ἀργίδης (1) Att. 6a.
Ἀργι-κλίδας (1) Béot. 3a. 
Ἀργι-λεωνίς f. (1) Dor. S. 5a
Ἀργι-λίδας (1) Béot. 3a.
Ἀργί-λιος (1+) Béot., Dor. NO., Thr.-Pont 4-2a.
Ἄργι-φος ? (1) Dor. NO. 3/2a 
Ἀργίων (1) Béot. 3a.
Ἀργύλος (1) Pélop. 3p.
Ἀργώνδας (1) Béot. 5a
You show in your screen shot: 0 + 19.

But this morning, I refresh the lexems several times and see always the following:

![Capture d’écran 2019-04-25 à 08 35 13](https://user-images.githubusercontent.com/16923546/56714464-2c8ee280-6735-11e9-97f0-295719b990b2.png)

What happens? Where is the nineteenth name gone?

Could you, please, explain?
Is it only a question of page not every time up-dated or are some names lost?

Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
I believe yesterday there was a name Argikidas (not ArgikLidas) and indeed today it is not there. Perhaps someone deleted it?

**Comment by Hippodamie** [comment]
Dear Magdalena,

we have both  Argiklidas and Argilidas, but Argikidas is not supposed to be attested. I deleted Arsinidas, which does not exist but was corrected by LGPN into Arsenidas.
Best,
Sophie

**Comment by tuurma** [comment]
Below's an excerpt from my local copy for `Argikidas`. Seems it has been a mistake to register it without L as greek version clearly states `Ἀργικλίδας`. Shall I assume then that we correctly have 18 names for αργι? Please reopen if anything is still unclear here.

```
 <entry xml:id="Argikidas">
                <form type="lemma">
                    <orth type="greek">Ἀργικλίδας</orth>
                    <orth type="latin">Argikidas</orth>
                    <orth type="h-variant">Argikidas</orth>
                </form>
                <gramGrp ana="" cert="high" type="segmentation">
                    <m ana="" baseForm="" function="" n="1" subtype="" type="prefix"/>
                    <m ana="" baseForm="αργ" cert="" function="Adj" n="1" subtype="Y" type="radical">αργι</m>
                    <m ana="" baseForm="κλεϝεσ" cert="" function="N" n="2" subtype="X" type="radical">κλ</m>
                    <m baseForm="" n="1" subtype="suff" type="suffix">ᾱ/ης</m>
                    <m baseForm="" n="2" type="suffix">ιδ</m>
                </gramGrp>
  ```

**Comment by Hippodamie** [comment]
Hi, Magdalena: I am totally overworking those days and next week so have not any time to answer.
But now I remember I corrected the error in Latin. Somebody had wrongly edited the following entries: Argikidas Greek Ἀργικλίδας. So I had to correct the Latin form and edited the right couple Argiklidas/Ἀργικλίδας; then, I deleted the other.
Thanks for all,
have a good week-end,
best,
Sophie
