### ISSUE TITLE
Changing 2 Roots ID

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#540]
Dear Magdalena,

Could I ask you for changing the ID of the 2 following Roots/bases:
![Capture d’écran 2019-04-25 à 10 00 19](https://user-images.githubusercontent.com/16923546/56719210-95c82300-6740-11e9-82ee-3d23e6fecf5f.png)

I mean: to change the current κλεϝεσν      into        κλεϝεσνο
and
the current κλεϝετ    into           κλεϝετο.

Μany thanks in advance,
have a good day,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Before

<img width="841" alt="image" src="https://user-images.githubusercontent.com/449468/56895088-3ba0c800-6a88-11e9-901f-0a696d6cf722.png">

after 

<img width="858" alt="image" src="https://user-images.githubusercontent.com/449468/56895159-7b67af80-6a88-11e9-853f-623d76eff275.png">

**Comment by Hippodamie** [comment]
Many thanks, dear Magdalena.
Have a good week!
With all best wishes,
Sophie
