### ISSUE TITLE
A new Suffix 3 in its pop-up menu: please add ιαν.               No emergency!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#541]
Dear Magdalena,

are you already in Washington DC?
Hop you had a good fly.

A last suffix 3 is missing, incredible: we discovered it through the name Zosim-ian-id-es, which is quite incredible, but nice! We thought it only existed as Suff2.

Could you, please, add it in the list?
Here is the list:
<img width="326" alt="Capture d’écran 2019-05-01 à 16 10 53" src="https://user-images.githubusercontent.com/16923546/57020895-126c6d00-6c2b-11e9-8fca-f01da41153f0.png">

The place is just between (V)μ and (V)ν.

Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
<img width="164" alt="image" src="https://user-images.githubusercontent.com/449468/57101762-31015f80-6d22-11e9-8036-f020efadd37e.png">

**Comment by Hippodamie** [comment]
Many thanks! But I told you: no emergency!
Best wishes,
Sophie
