### ISSUE TITLE
A bug on the meaning of Theo-/ θεο the name of god! Twice the same meaning

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#542]
Dear Magdalena,

Hi, how are you doing?

There is a bug we cannot fix by ourselves: could you please fix it?

We would like to have as meanings for θεο the 3 following in this exact order:
god
goddess
deity

We currently have:
goddess
goddess
deity

Many thanks in advance for your help,
with all best wishes,
Sophie

![Capture d’écran 2019-05-03 à 12 01 19](https://user-images.githubusercontent.com/16923546/57130684-8b3e0700-6d9a-11e9-8542-78cb26272514.png)

**Comment by tuurma** [comment]
Before

<img width="837" alt="image" src="https://user-images.githubusercontent.com/449468/57840098-3f428780-77c8-11e9-88c3-a488741a048b.png">

After

<img width="759" alt="image" src="https://user-images.githubusercontent.com/449468/57840130-51bcc100-77c8-11e9-9c82-d16ed0fdbbba.png">
