### ISSUE TITLE
A last name in ϝοικ ID wanted! Thanks in advance. Best, Sophie

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#543]
Dear Magdalena,

Impossible for us to find the last name who had a root in (ϝ)οικ(ο), since we have try to re-made all of them into now ϝοικο.

The other last 15 (for which our job has been done) are:

Ἀγροίκιος
Ἀγροῖκος
Ἀκροικώι
Βοικήν
Ἐλλόοικος
Ἐποικεύς
Οἰκογένης
Οἰκοδάμας
Οἰκόδομος
Οἰκοκράτης
Οἰκοσθένης
Στασίοικος
ϝάδοικος?
ϝοικίδας
ϝοίκων

Could you please find this name for us?
Many thanks in advance.
With all best wishes,

Sophie

**Comment by tuurma** [comment]
It was Ἀποκίας, now fixed 

<img width="755" alt="image" src="https://user-images.githubusercontent.com/449468/57840377-cbed4580-77c8-11e9-8f6f-0817ede9d2a6.png">


after

<img width="852" alt="image" src="https://user-images.githubusercontent.com/449468/57840429-e1fb0600-77c8-11e9-96ad-f4c8add0c732.png">

**Comment by Hippodamie** [comment]
Hi, Magdalena, how are you? How was your stay overseas?
Many thanks for θεος also!
We never could have found it by ourselves, this one!!!
