### ISSUE TITLE
A new Suffix1 is missing!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#548]
Dear Magdalena,

could you, please, add to the Suff1 List, at the end of the List, just between ωρ and ?
the new Suffi1: ώς

Many thanks in advance,
with all best wishes and thanks for the good presentation of the alhabetic letters at the top of Lexems,
Sophie

**Comment by tuurma** [comment]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/449468/58043873-a486d780-7b3e-11e9-98f9-5f927411a8f4.png">

**Comment by Hippodamie** [comment]
Many thanks!
Good evening!
Best,
Sophie

PS: il you had more time, good you please fix the bad ἀπολλο̄ν instead of απολλο̄ν we should have written : we ar not supposed to use the diacritic.
We would like to have in both side απολλο̄ν    απ(ο)λλ(ο̄ν).
Many thanks if you can do it.
