### ISSUE TITLE
The end of the Suff1 list as it is in the Table in the Introduction to LGPN-Ling seems to have suffixes now missing

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#550]
Dear Magdalena,

we have 2 more Suffixes 1 missing in the List. Look at the bottom of the Table, which has some more suffixes than in the current List. So we have lost the last of them, since months, I guess.
![Capture d’écran 2019-05-21 à 15 25 41](https://user-images.githubusercontent.com/16923546/58099450-f29de880-7bdb-11e9-89ee-597aacb5b587.png)

To summarize:
I asked you yesterday to add ώς, which is great, and should have added too its Genitive: ῶτος.
Then, I would like to have added as it was at the very beginning the 2 others missing:
we would have them after the former, thus
ώς followed by the 2 others:
ω(ϝ)ς Genitive ωϝος [NB: in fact, the * before ϝ should be deleted in the Table of the Introduction too]
ῶς and its Genitives as in the Table.

The most important are the Suffixes missing, that we need.
Many thanks in advance for your help.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
<img width="187" alt="image" src="https://user-images.githubusercontent.com/449468/59939407-29278700-9458-11e9-8353-759d6e08040c.png">
