### ISSUE TITLE
Elpizousa: no opening possible of the subform to modify

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#551]
Dear Magdalena,

how are you? I do not forget we have planned to Skype.

When will you be available?

Could it be not next week but the following, for example Wednesday the 12th?
The subject will be Building of the Searching interface: the way you see it, your advices and the order of the tasks for us and for you, indexations. The planning and schedule.

A detail: could you please give access to Elpizousa subform? It does not open.
Many thanks in advance.

Have a nice day,
with all best wishes
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

did you do something?
We were finally successful but now, impossible to delete the wrong base (among lexems).
Could you please demete it?

Many thanks in advance.
With all best wishes,
Sophie
<img width="1187" alt="Capture d’écran 2019-06-04 à 10 04 09" src="https://user-images.githubusercontent.com/16923546/58861854-9fce3180-86af-11e9-807a-720134b8f740.png">

**Comment by tuurma** [comment]
fixed manually, bit hard to say why it didn't want to delete with the button

**Comment by Hippodamie** [comment]
Many thanks for all, Magdalena!
Have a good week-end,
best,
Sophie
