### ISSUE TITLE
About the o with macron separated from the others 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#552]
Dear Magdalena,

it is an excellent idea to separate lexems beginning with ο̄, from  those beginning with o.

And the same with ᾱ different from α without macron. And we will have to do the same with ε̄ different from ε. 

Concerning the lexems beginning with vowels with the double  ̄ + ̆, they have to be kept at their current place in the list of the lexems beginning with the short vowels. What will have to be changed sometimes in the current ᾱ list.

The only question I cannot solve at the moment is the following: do we really open special lists or do we rather put all the ᾱ, for example, at the end of the same and sole α list?

I have to think a little more, and consider what will be the best choice for the Searching interface.

So, Magdalena, I wonder if I will be really ready next week to have a Skype with you. I must say, I think it is a little too early.

What is your own schedule, at what time would you prefer to work a bit for us?

I continue in an email.
Best,
Sophie

**Comment by tuurma** [comment]
My suggestion would be to put all lexems starting with a letter, regardless of its exact form, together, because this is likely what users would expect. Also searches should be somewhat 'insensitive' to the exact accents used. Thus I'd suggest moving all ο̄ forms to the end of o list.

**Comment by tuurma** [comment]
Ah, you already decided this in #553 ;-) Closing this one then.
