### ISSUE TITLE
Alphabetical order for the indexation of the lists of bases (lexems)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#553]
Dear Magdalena,

How are you? What are you currently doing?
I had finally time to do it after discussion with the colleagues.

So here is the way to range/order the bases in their lists.

So, the currently opened ο̄  and ᾱ can disappear: all α will go together, with an ordering I have written in the attached file.

Here it is.
Have a good day,
with all best wishes,
Sophie
[Alphabetical order for the indexation of the lists of bases.docx](https://github.com/eXistSolutions/LGPN-ling/files/3280060/Alphabetical.order.for.the.indexation.of.the.lists.of.bases.docx)

**Comment by tuurma** [comment]
Thanks, I will have some time for it next week.

**Comment by Hippodamie** [comment]
Perfect, dear Magdalena!
Why do you never answer to the financial questions
 Summer is coming, and if you do not fill the file I had sent you, it will take so much time that it will be impossible to pay anything before next September (all administration is closed the whole August and I am away from July, the 10th). We need the file + a (even small) Estimate.
And be aware that after the begining of November, they close their financial year and all is stopped until end of January: it is the way it works (or doesn not work very well...) in our French country.

And they even prefer to pay 4000 euros several times than 10 000 one time.

with all best wishes and thanks in advance,
Sophie

**Comment by tuurma** [comment]
Thanks for the reminder. Point is someone else usually takes care of the financial stuff, I will chase this.

**Comment by Hippodamie** [comment]
Ok, I understand!

**Comment by tuurma** [comment]
Before

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/449468/60571901-b500b380-9d74-11e9-9c85-583e9864d740.png">

After

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/449468/60571918-bfbb4880-9d74-11e9-96e7-4df56656d3ef.png">

Fragment of the `α` list:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/449468/60572125-335d5580-9d75-11e9-9558-4554af6c5bd5.png">

**Comment by Hippodamie** [comment]
Many thanks , dear Magdalena!
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

could you please put the only ο̄ occ. in the  o (59) list, in its good place, like you did for α?
Many thanks in advance,
best,
Sophie
