### ISSUE TITLE
A modification to bring by your help to the ανδρ Base

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#554]
Dear Magdalena,

We have a very important Base ανδρ man 422 names.

There is an important change to bring.
1. to move ανδρ ανδρ
into: ανδρο    ανδρ(ο)
This new one works both as a B1 and as a B2.

2. I have created the second Base connected with the 1st, which is only used as a Base2:
it is ᾱνο̄̆ρ. I already created it for the sole Ἀγαπήνωρ.

3. Here comes my question:
could you automatically make the sorting out among all the 422 names between the names with ανδρο Base and the names with the new ᾱνο̄̆ρ Base?

The most of them will keep being in ανδρο (after your 1 step).
How could you find the others for the new other Base ᾱνο̄̆ρ?
This  concerns only the second element of the name and will not necessarily end the name (we will have ending in - ανωρ/-ηνωρ; but also in the middle of the name: -α/ηνορ-     + ιδ(η/ας) or ορ -ιανος etc.
Anyway, the difference is: the presence or absence of δ in one case; the presence or absence of ο̄̆ in the other case. And the long α at the begining or not.
They are quiet few with the new Base.

Thta is all.

Could you do it too, next week?

Many thanks in advance,
with all best wishes,
Sophie (I am writing an email for other subjects)

<img width="1125" alt="Capture d’écran 2019-06-13 à 15 27 53" src="https://user-images.githubusercontent.com/16923546/59436208-7455f000-8def-11e9-813a-4b66d04d5b05.png">

**Comment by tuurma** [comment]
Starting moving all existing ανδρ / ανδρ entries to ανδρο / ανδρ(ο). There are two names registered in the new ανδρο base already

<img width="600" alt="image" src="https://user-images.githubusercontent.com/449468/59941359-4d399700-945d-11e9-921f-8c2f1f4b7348.png">

**Comment by tuurma** [comment]
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/449468/59941894-a6ee9100-945e-11e9-81ff-db7b3a45a7ba.png">

**Comment by tuurma** [comment]
@Hippodamie here's a list of distinct values for the constituent corresponding to ανδρο base. 

`ανδρ ανορ ανδρο αν ανδρε ανωρ  ανδρα ανδρι ηνορ νδρ ανν`

Does it look like we could use it to sort out between the two bases? For example looks like `ανδρ ανδρο ανδρε ανδρα ανδρι νδρ` would be good candidates for `ανδρο` while `ανορ ανωρ ηνορ` seem to fit `ᾱνο̄̆ρ`. This would leave us with only names where constituent is `αν or ανν` to investigate further.

**Comment by Hippodamie** [comment]
Hi, Magdalena: yes, I began the process with those names.

**Comment by Hippodamie** [comment]
Yes, perfect! Wonderful! You can do it.
Best,
Sophie

**Comment by tuurma** [comment]
There were 86 entries total for `ανορ,  ανωρ,  ηνορ` now moved to `ᾱνο̄̆ρ` base

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/449468/60568985-841d8000-9d6e-11e9-8fa7-6de9c7878244.png">

**Comment by tuurma** [comment]
There are still cases of `ανν, αν` forms to be manually checked. There are 57 entries in total, 12 of which as Base 2:

`Ἀγανώ Αἰσάνιος Ἀγανᾶς Εὐφρανίδας Ἀρχηνᾶς Εὐφράνιος Ἀγύρανος Ἀγανίς Ἀρχαννού Καλανεύς Θιανις Νίκανος`

**Comment by Hippodamie** [comment]
Dear Magdalena,

thanks for all! Could you please substitute ᾱνο̄̆ρ for all of these B2 too?
Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

what do you mean with 
There are still cases of ανν, αν forms to be manually checked. There are 57 entries in total => as Base 1, I suppose?
Where are they? I cannot find them. Could you please give an example?
I do not understand.
Thnaks for your help,
best,
Sophie

**Comment by tuurma** [comment]
I meant that there are 12 cases where currently as the base 2 form we have ανδρο but the constituent form is either αν or ανν. These are the names Ἀγανώ Αἰσάνιος Ἀγανᾶς Εὐφρανίδας Ἀρχηνᾶς Εὐφράνιος Ἀγύρανος Ἀγανίς Ἀρχαννού Καλανεύς Θιανις Νίκανος. Shall I change the base to ᾱνο̄̆ρ for these?

There are also cases where we have base 1 form ανδρο and constituent form αν or ανν. These are
῎Αννα Ἀναίτιος Ἀνέγκλητος ῎Ανοχις ῎Ανιππος Ἄνοχος Ἀνδέκτας ῎Ανων ῎Αννων ῎Αννυλα Ἀνδώρητος ῎Ανοκνος Ἀνώφιλος Ἀνεγκλιανή Ἀνάπτη Ἀνδοκίς Ἄνικρος Ἀνείας Ἀνήριτος Ἀνάριστος Ἀνόπτης Ἄνα Ἀνάλκης Ἀννᾶς Ἀναυχίδας Ἀναπίας Ἀνδοκίδης Ανιμος Ἄνδοκος Ἀνόδικος Ἀνοθήνης Ἀνόπτηνις Ἀνόϊστος Ἀνόϊστος Ἀνάνιος Ἀνναῖος Ἀνέγκριτος Ἀναίη Ἀναγόρης Ἄνανθος Ἀνήριστος Ἀννικῆς Ἀνοχίδης Ἄνσιλλος? Ἀνάγυλλα

**Comment by Hippodamie** [comment]
No, Violeta has done it.
Many thanks for the others: I will check.
Best,
Sophie
