### ISSUE TITLE
First ideas about the requests for the Searching interface to build. First indexations to do.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#555]
Dear Magdalena,

I put here a part of what I just have written in an email, to have tracks easy to find.

We already currently have, thanks to you:

a) all bases listed in around 23 alphabetical lists of the initial letter of the base, soon improved by you in their alphabetical ordering (user being able to browse through the list as currently and having all names per Base)

b) another thing we would like to keep for ever (!) is the ** functions (sequence letters searching), but with the c) supplementary function added:
currently we already can search for:
`*ηνωρ`= all names having something before this sequence and having this sequence inside or ending with it.
`ανδρο*` = all names begining with it.
c) What is not yet available and is as necessary as the previous:  *κλεα = all names exactly ending with it, different from *κλεα* = all names having something before and after this sequence. 
We would like to have thus 4 choices:
`κλεα`
`*κλεα`
`κλεα*`
`*κλεα*`

TO BUILD to complete the simple Searching and to begin the coupled Search (A+B) 
1. the previous c) +:
And malking possible from now on to search also by (the ranging from 1 to 15 is a priority order – from the highest to the lowest):
2. List of all Meanings: a. French b. English. 
3. List of all DELG or EDG Greek lemmas ranged by alphabetical order (Lexis) [the alphabetical order is here the usual order of the Greek 24 letters alphabet];
4. List of all Greek words with a Logeion link ranged by alphabetical order (Lexis)  [the alphabetical order is here too the usual order of the Greek alphabet].
5. List of Latin transcriptions of all the names ranged by alphabetical order[h coming first; vowels  with macrons after the corresponding vowels without it, but the usual order of Latin alphabet].

6. LIst of all Dialectal/Areal/Bilingual/Linguistic label (I need to reorder them or to send you again the file where I did it months ago)
7. All Suffix 1 -ος names               and the same for each kind of Suffix1;   idem for Suffix 2, 3 and 4, 
8. All conversions; all XY/YX.
9. All only Pro Bases and other grammatical categories (only V, only Adj. etc.)

10. All only X bases
11. All only Y bases
12. All bases being sometimes X, sometimes Y.

13. All only B1 bases
14. All only B2 bases
15. All Bases being used sometimes as B1, sometimes as B2.

**Comment by tuurma** [comment]
Dear Sophie,

points a) and b) and c) are now completed. As we agreed, we'll discuss next steps early August.

**Comment by Hippodamie** [comment]
Dear Magdalena,

OK. I look now at the question you asked with κλεα.
Many thanks for all,
best,
Sophie
