### ISSUE TITLE
Small change: could you please change the ID αγοραο into αγορᾱο? 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#557]
Dear Magdalena,

Small change: could you please change the ID αγοραο into αγορᾱο? (with a macron on the alpha?

Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/449468/65953529-6c749700-e444-11e9-9118-051e3d759bf2.png">

**Comment by Hippodamie** [comment]
Many thanks, Magdalena!
