### ISSUE TITLE
[cross-language sorting] Same type of task: reindex I- lexems list: a few items

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#559]
Dear Magdalena,

Hi.
Again:
could you please move the 3 items of the screen shot at the end of the list, since they have an ο̄ in them?
Many thanks,
have a nice week,
best,
Sophie
![Capture d’écran 2019-08-19 à 10 01 52](https://user-images.githubusercontent.com/16923546/63248968-c6404980-c268-11e9-9128-99e8ce89e8ab.png)

**Comment by Hippodamie** [comment]
The 3 will stay in the same order, at the en dof the I- list.
Thanks,
S

**Comment by tuurma** [comment]
Dear Sophie,

the problem with display of Io entries stems from error in their entry - the sign ō in this case is composed of *Latin* letter o with a macron, instead of Greek letter o. Since they look the same, it's undetectable to the eye but sorting order is affected.

**Comment by Hippodamie** [comment]
Dear Magdalena,

could you do it for the current lexems and I will tell the team to be very careful on this point.
Is it possible for you?
Thanks for all,
best,
Sophie
