### ISSUE TITLE
Reordering Dialectal labels list

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#560]
Dear Magdalena,

How are you? 
Her is the file for last fixing of the list. Thanks in advance for this work.
[Reordering Dialectal labels Aug2019.docx](https://github.com/eXistSolutions/LGPN-ling/files/3529275/Reordering.Dialectal.labels.Aug2019.docx)

Good end of week.
Have all nice vacations in Corfu, enjoy!
With all best wishes,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/65951530-844a1c00-e440-11e9-8ed5-ef01ce6cfd6d.png)

<img width="151" alt="image" src="https://user-images.githubusercontent.com/449468/65951607-acd21600-e440-11e9-811c-918fe0b55d4f.png">
