### ISSUE TITLE
Improving -999/999 bad look! 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#562]
Dear Magdalena,

it seems to me you work on Meanings! Great for us! Many thanks for that.

About -999/999: it seems it happens when we have archaic (-999) and for the 999, it seems it happens when we have thing like ?before a fork like: ?300/400AD?

Would it be possible to improve it with like arch. for -999 and for the other plan that ? is not sensitive or whatever...

Thanks for your help,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
I removed dating altogether for cases like -999/999 where all it means really is that it was not possible to make a precise judgement on dates for some of the individuals bearing the name. I think in due time we'll be able to link people to new version of LGPN Database search, so keeping this information in Ling will not be necessary altogether.
