### ISSUE TITLE
Parentheses to add to the current Suffix 1 οῦς

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#563]
Dear Magdalena,

Hi, how are you? 
Could you please put parentheses to this suffix 1: current οῦς to change into οῦ(ς)
Many thansk in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
<img width="204" alt="image" src="https://user-images.githubusercontent.com/449468/65950434-595ec880-e43e-11e9-880c-f87194077777.png">

**Comment by Hippodamie** [comment]
Thanks, Magdalena, for all!
Best,
Sophie
