### ISSUE TITLE
fix css/js issues when adding a section

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#57]
![screenshot 129](https://cloud.githubusercontent.com/assets/449468/12682035/789326e4-c6a9-11e5-81c6-1afc30501055.png)

**Comment by patczar** [comment]
Sorry, I looked at it and I don't understand it. In the first section there are div-s and in the next (dynamically added) sections there are span-s in the same places. The same XForms code is translated into different html (in repeats). I can experiment more, but maybe Joern (or somebody elso from BetterForms) would understand it more deeply.
