### ISSUE TITLE
A Suffix 1 to change a litle

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#572]
Dear Magdalena,

could you please change the S1 suffix -οῦ(ς) into: (ι)οῦ(ς)?

Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/72723095-2a509c00-3b80-11ea-8ffb-5dcbf44d9fac.png)
