### ISSUE TITLE
A bug on Menalkes: no complex structuration box in this Editor window

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#574]
Dear Magdalena,

could you please fix this entry? We do not have acces to the complex structuration box, which does not appear on the editor.

Many thanks in advance;
with all best wishes,
Sophie

**Comment by tuurma** [comment]
fixed (together with 227 similar cases) with

```xquery
 for $i in collection('/db/apps/lgpn-ling-data/data/names')//tei:gramGrp[@type='segmentation'][not(@subtype)]
return 
    update insert attribute subtype {''} into $i
```

**Comment by Hippodamie** [comment]
Thank you, Magdalena: yes, it was not the only case!
Best,
Sophie
