### ISSUE TITLE
A, additional Suffix4: (V)(ϝ)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#575]
Dear Magdalena,

I wish you a very nice end of the year and ‘reveillon’ tomorrow night!

Could you please add a second Suffixe 4:      (V)(ϝ)
Listed before ων?
Many thanks in advance,
with all best wishes already for the new year to you and all your children and family,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/71917577-a9a59f00-3180-11ea-8b11-d528f344dd17.png)

**Comment by Hippodamie** [comment]
Thank you, dear Magdalena!
A happy new year to you and your family!
With all best wishes,
Sophie
