### ISSUE TITLE
Suffix 3 to add: ισκ without accent

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#576]
Dear Magdalena,

Hi! A new suffix just for 1 name: Μενισκιανός!
Could you please add it as a Suffix3 in the list?
It would be between: (V)k and (V)(λ)λ.
Many thanks in advance,
all best,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/72722858-adbdbd80-3b7f-11ea-8373-be697cd1a2f8.png)
