### ISSUE TITLE
Suff2 to modify: δ into (V)δ

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#577]
Dear Magdalena,

how are you? 
Could you, please, change the suffix2 δ into (V)δ and move it from its current place, so that we have then the following order:
(V)β/π/φ
(V)δ
αδ
ιαδ
ιδ
Many thanks in advance!
Have a nice week-end,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Done
