### ISSUE TITLE
A bug on the list Complex Structuration and Semantics/ low hypothesis

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#578]
Dear Magdalena,

Hi! How are you? I hope you are all ok and the kids, but you especially.

Just a request:
could you please fix this list because every time we open it when there is a low hypothesis, some items are missing, as you can see: it is for the name Archedeiktes.

Many thanks for your help,
with all best wishes,
Sophie
![Capture d’écran 2020-03-18 à 18 03 30](https://user-images.githubusercontent.com/16923546/76987760-fb6a6280-6943-11ea-8e62-5bf46997268c.png)

**Comment by tuurma** [comment]
Dear Sophie, the 'empty' lines correspond to `<XY` and `<YX` options and for whatever reason are incorrectly rendered in the browser when you just add the low hypothesis. After saving and reopening the name entry all is correctly visualised again. I will try to figure out why the problem occurs only under these conditions but it may not be easy.

**Comment by Hippodamie** [comment]
Many thanks, dear Magdalena! Yes I saw, after having asked, that we in fact saw it edited, but not in the list of the Editor.

Could you please add a missing suffix 3 in its list (Florian just told me): we would need (V)θ, to put just under (V)(ϝ) and before (V)κ.

Many thanks for that too.
Take care,
best,
Sophie

**Comment by tuurma** [comment]
No problem, updated suffixes

**Comment by tuurma** [comment]
Btw, issue #523 was already reported for this problem. In a longer perspective I will want to rework the forms to avoid using betterForms as underlying technology because betterForms are no longer maintained and supported. It is still at least few months though before we will be able to do so.
