### ISSUE TITLE
prefixes & suffixes: add text value

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#58]
similar to #48; consider moving prefixes & suffixes to lgpn-data app

**Comment by Hippodamie** [comment]
Is it a question I have to answer to ? To add text values ? We do not need them for Prefixes & Suffixes.

**Comment by tuurma** [comment]
That's right @Hippodamie, thanks for pointing this out. This is irrelevant for prefixes & suffixes. Closing.
