### ISSUE TITLE
No access to Meanings

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#581]
Dear Magdalena,

Could I please have access to meanings?

Many thanks in advance,
with all best wishes,
Sophie
<img width="1123" alt="Capture d’écran 2020-04-23 à 10 44 45" src="https://user-images.githubusercontent.com/16923546/80078231-e5594e80-854e-11ea-8555-55ce3f610af6.png">

**Comment by tuurma** [comment]
Dear Sophie,

could you please help me to reproduce the error, ideally by pasting the link to the page you're trying to view? I tried to find it myself but can't so far. Is it happening for all the meanings or just one?

**Comment by Hippodamie** [comment]
Hi, Magdalena,

it happens just by clicking on Sens/ Meanings. I am on Chrome. Lexems work very well, but not Meanings (it does it also in English), see:

Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
The error was caused by the illegal `/` character in the meaning id. I changed it to underscore `_` and now all works well

```
exerr:ERROR Syntax error in Lucene query string: Cannot parse 'of_Hyrmine/Horminae': Lexical error at line 1, column 20.  Encountered: <EOF> after : "/Horminae" [at line 36, column 17]
```

![image](https://user-images.githubusercontent.com/449468/80215432-b8836500-863c-11ea-84cb-1a28788b5826.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

sorry for that!
Many thanks, best wishes,
Sophie
