### ISSUE TITLE
A small misspelling on daughter

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#582]
Dear Magdalena,

there is a small misspelling on the word ‘daughter’ (significant relative names): it is wrong on the visualization but correct in the pop-up list.
Could you, please, fix it?
See eg Menounis.

Many thanks in advance,
with all best wishes,
good week-end,
Sophie

**Comment by tuurma** [comment]
Well spotted. I fixed it in the drop-down list values and in the 118 entries where it was used.

**Comment by Hippodamie** [comment]
Dear Magdalena,

many thanks for all!
With all best wishes,
Sophie
