### ISSUE TITLE
A bug on Lexem βρυο̄σα

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#583]
Dear Magdalena,

how are you? When will you be able to come back to our previous way of life, or  what could look as quite close of our previous way of life? Here in France it is supposed to be next Monday.
Could you, please, delete for us
βρυο̄σα with ‘swelling, abounding’ meanings
and keep only the other:
βρυο̄σα with ‘bold’?
There is a bug, it seems, and we cannot at all delete it.
Thanks for your help,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
fixed
