### ISSUE TITLE
A bug on ‘feeling affection’ in Meanings

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#584]
Hi, Magdalena,

how are you? Is the lock down open now? Are your children back to school?
I hope you are all well.
We have a bug on this meaning. We corrected it into the good one = ‘feeling_affection’ but the former keeps being with lexems supposed to be linked with this meaning whereas in fact no lexem has it. We would like ‘feeling affection’ to be deleted. Only keeping the good version.
Could you please help?
Many thanks in advance.
Take care,
with all best wishes,
Sophie
![Capture d’écran 2020-05-18 à 11 45 07](https://user-images.githubusercontent.com/16923546/82198561-c7d49600-98fc-11ea-9c86-e3531b41e28e.png)

**Comment by tuurma** [comment]
fixed
