### ISSUE TITLE
A bug on ‘damaging, destroying’ meanings

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#585]
Dear Magdalena,

How are you? I hope you are all well.
Again, we cannot delete this meaning. Our aim is to keep only destroying and not the double meaning. Florian took it away from all the names but it is not possible to delete it now. We do not even see the ‘delete’ red box.

Could you please help?
Have a good holiday,
with all best wishes,
Sophie

destroying | qui détruit | destroying | hανυσαντ, περθσι, hανυσι, ϝρε̄γσι (4)
-- | -- | -- | --
damaging, destroying | qui endommage, qui détruit | damaging, destroying | hανυσαντ, περθσι, hανυσι, ϝρε̄γσι, σιντο (5) WE would like to delete this one.

**Comment by tuurma** [comment]
fixed
