### ISSUE TITLE
Νο αccess to Meanings

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#586]
Dear Magdalena,

sorry to come so late, but until tomorrow!
We have (Florian this afternoon and me now) an error message to acess to Meanings. Could you please fix it?
Many thanks in advance for your help.
Good evening.
Best wishes from
Sophie
![Capture d’écran 2020-05-28 à 21 41 01](https://user-images.githubusercontent.com/16923546/83185534-6e097280-a12b-11ea-90da-480452bc1fc2.png)

**Comment by tuurma** [comment]
No problem, fixed. Please do not use signs like / or space in identifiers - this was the source of the trouble.
