### ISSUE TITLE
A bug on Armenian

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#587]
Dear Magdalena,

I do not understand that:
only αρμενισαντ is supposed to have te meaning ‘behaving_as_an_Armenian;
and αρμενιο is supposed to mean only: ‘Armenian’.
But both lexems are listed as if they had both meanings.

Could you please fix it?
All best,
Sophie
<img width="1173" alt="Capture d’écran 2020-06-03 à 17 41 59" src="https://user-images.githubusercontent.com/16923546/83657313-fc18a980-a5c0-11ea-85b2-235285c2e617.png">

**Comment by tuurma** [comment]
I can confirm it's weird. I don't see the reason yet, just a suspicion that Lucene indexes treat - or _ signs as word boundaries perhaps. Will investigate further and let you know.

**Comment by Hippodamie** [comment]
Thank you!
