### ISSUE TITLE
An error message on Meanings

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#588]
Dear Magdalena,

access to Meanings does not work well. I got it at first, but now I only have this message.
We have a lot to do in Meanings.
Could you please fix it?
Many thanks in advance
with all best wishes,
Sophie
![Capture d’écran 2020-06-05 à 11 08 11](https://user-images.githubusercontent.com/16923546/83857960-0ac7a380-a71c-11ea-94f4-f264d836e803.png)

**Comment by tuurma** [comment]
There was a problem with definitions for ψαιστο. The id of the meaning contained spaces, `/` sign etc, which should not be used. I changed it to 'ground_kind_of_cake', not sure if it is correct, perhaps it should be just 'ground'. Please create a new meaning if so and change in the name.

![image](https://user-images.githubusercontent.com/449468/83861672-2a14ff80-a721-11ea-9a6f-b55625a973f6.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

I just wrote a warning about the subject to everybody.
Many thanks for your quick presence to fix it! I check the meanings, now,
have a nice week-end (I hope not to come back to you…),
all best,
Sophie
