### ISSUE TITLE
A meaning which cannot be deleted: 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#590]
Hi, Magdalena,

how are you?
Florian told me about a meaning with a bug: we made an error, putting a coma in the sensible left box...
So we are not able to delete the meaning by ourselves.

Could you please help?
Another question: when will you be able to work on the Searching new interface?
You remember I will be away from July the 10th and very busy in August on other subjects!

Many thanks in advance,
with all best wishes,
Sophie
![Capture d’écran 2020-06-26 à 21 42 15](https://user-images.githubusercontent.com/16923546/85894491-255ddb80-b7f5-11ea-9a75-ebea123a24e2.png)

**Comment by tuurma** [comment]
I've adjusted the meaning identifier but currently it is not used at all

![image](https://user-images.githubusercontent.com/449468/90816702-08451500-e32d-11ea-8926-589221b3cdd6.png)
