### ISSUE TITLE
A bug in 1 meaning we cannot fix by ourselves

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#593]
Dear Magdalena,
Florian told me about a meaning we would like to improve but we cannot:

protector of the rights of hospitality

the mistake was to edit it without the underscore between each word.
Could you please help us? Putting maybe yourself the missing  _ , because the meaning concerns many roots...
Many thanks in advance for your help and apologies,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
no problem, fixed now. Apologies for the delay.

**Comment by Hippodamie** [comment]
Dear Magdalena,

many thanks for all!
Have  a nice day and end of week,
with all best wishes,
Sophie
