### ISSUE TITLE
5  Documents for your work on the Searching interface (up-dated from last year)              1. Notes on design

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#594]
Dear Magdalena,

Th idea is to keep the current Parthenon composition as it is, and maybe to add as a small Logo/Vignet the following Ostrakon, (Greek letters smaller but still readable, and more in the form of a circle, I mean higher than in the current ellipse). Or keep the whole ostrakon (no more any ellipse added) and reduce the size a lot.
For the following Ostrakon, there is a variant with colors on Wikipedia, which could be better because it is in color.
![Capture d’écran 2020-08-03 à 09 20 00](https://user-images.githubusercontent.com/16923546/89192531-e154b800-d5a4-11ea-9ea2-b2a5f775ff23.png)
![DSC04006](https://user-images.githubusercontent.com/16923546/89192590-ffbab380-d5a4-11ea-9223-fc406e85770a.jpg)

**Comment by Hippodamie** [comment]
2 Document;
How I see the front page of the site.
[Search Page 1 _1st page of the site..pdf](https://github.com/eXistSolutions/LGPN-ling/files/5016499/Search.Page.1._1st.page.of.the.site.pdf)

**Comment by Hippodamie** [comment]
Document 3: The LGPN-Ling 
[Numériser 136.pdf](https://github.com/eXistSolutions/LGPN-ling/files/5016511/Numeriser.136.pdf)
Search (simple search)

**Comment by Hippodamie** [comment]
Document 4: the main catalogues.
[Numériser 137.pdf](https://github.com/eXistSolutions/LGPN-ling/files/5016527/Numeriser.137.pdf)

**Comment by Hippodamie** [comment]
Document 5 (last): Advanced 
[Numériser 138.pdf](https://github.com/eXistSolutions/LGPN-ling/files/5016546/Numeriser.138.pdf)
Lexemes Search.

**Comment by Hippodamie** [comment]
Dear Magdalena,

all is ready for you to work on it. 
I do not think it is very different of what you already understood when you did the 1st test Searching interface last summer.
But I think and hope it is useful to give you an up-dated version. 

If you have any questions, just ask me.
I will be the most of the time available tomorrow, Tuesday (but absent one hour in the afternoon), and present the whole Wednesday and the other days.

When you will read me, I hope you will have come back home without any trouble and have really enjoyed the holidays you spent with your children.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

thank you for your preparations.

During past week I've started work on new interface:
* migrated browsing to TEI Publisher 6
* defined facets and fields for basic searches and sorting (by name, Greek name, transliterated name, dial. area, lexeme (any, prefix, root, root1, root2)
* started preparing advanced search interface.

I don't have a test server yet to demonstrate but I will register a series of new issues and paste screenshots there.

**Comment by Hippodamie** [comment]
Dear Magdalena,

wonderful! Thanks a lot!
I am available when you need.
With all best wishes,
Sophie
