### ISSUE TITLE
Please help on a bug: a Lexem triplicated γᾱ-ι(ο)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#595]
Dear Magdalena,

could you please fix it? We have now 3 γᾱιο lexems. I think the editor did something wrong, and we cannot do anything to fix it. We deleted it from the personal name Gaiomachos, and there no occurrences now. But the system tells us that it cannot delete because there are references. But is shows zero references!

Thanks for your help. We would like to fix it not to forget the whole family.
I will create the new lexems as γᾱιο myself because it seems my colleague does mistakes on this point.

Sorry to disturb with this kind of problem.
With all best wishes,
Sophie
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

in fact the more simple way would be to totally delete the now 4 γᾱιο.
Good night.
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Was:

![image](https://user-images.githubusercontent.com/449468/90606237-d08c7f00-e1ff-11ea-98f9-02a2e01c5b96.png)

Now deleted:

![image](https://user-images.githubusercontent.com/449468/90606306-ef8b1100-e1ff-11ea-8e19-d06f86ff5bee.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

many thanks,
with all best wishes,
Sophie
