### ISSUE TITLE
[New Ling] logos

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#596]
Dear Sophie, I've been briefly experimenting with logo generators, perhaps you will like one of these or it will give you ideas which directions to go to

<img width="495" alt="smashing_logo_socrates2" src="https://user-images.githubusercontent.com/449468/89895779-ab36ba00-dbdc-11ea-8f3d-701f1a411992.png">
<img width="485" alt="smashing_logo_socrates" src="https://user-images.githubusercontent.com/449468/89895783-aeca4100-dbdc-11ea-86d5-4550a276e85b.png">
<img width="497" alt="smashing_logo" src="https://user-images.githubusercontent.com/449468/89895799-b1c53180-dbdc-11ea-994a-4f46ffc17de0.png">
<img width="491" alt="smashing_logo_temple" src="https://user-images.githubusercontent.com/449468/89921784-6cb1f700-dbfe-11ea-8d84-5e0c1043072e.png">

**Comment by Hippodamie** [comment]
Dear Magdalena,

sorry not to have come on Git Hub the last days. But after talking, I will have less to comment! Many thanks again for all what you understood and created!
Concerning the logo, I like the design of the letters and even the colors. But the left icon does not make sense.
I had put the example of Megaklees ostrakon in a previous issue: Would it be possible to keep the 2 names or to keep only Megaklees (making it very small) and to put it instead of the current icon at left, in like a square or a circle or an ellipse (with an as beautiful result as you can)? The aim is we have something like an ostrakon as an icon or at least that we see a Greek name inscribed in original Greek letters.
Last point: the small subtitle cannot begin only by ‘analysis’, even if LING already defines it.

**Comment by Hippodamie** [comment]
Dear Alexandra,

I hope you are well in those difficult covid times.
Please, note about Logos that I pu some indications in #597.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
Dear Sophie, we agreed to wait until we have main functionality implemented to see where we stand about the budget - designing a logo would take some hours which we may not have in the end. If you could point us to the source of the ostrakon on wikipedia, so we could see if we can use it?

**Comment by tuurma** [comment]
Here's a link to Themistocles ostrakon https://commons.wikimedia.org/w/index.php?title=Special:Search&limit=500&offset=0&ns0=1&ns6=1&ns12=1&ns14=1&ns100=1&ns106=1&search=Ostracon&advancedSearch-current={}#/media/File:3164_-_Sto%C3%A0_of_Attalus_Museum_-_Ostracism_against_Themistokles_(480s_BC)_-_Photo_by_Giovanni_Dall'Orto,_Nov_9_2009.jpg

**Comment by plutonik-a** [comment]
Just my 2 cents: What about those rounded ostraka like e.g. https://commons.wikimedia.org/wiki/File:Ostracon_of_Themistocles_-_Museum_of_the_Ancient_Agora_-_Joy_of_Museum.jpg They are quite nicely reusable as an icon.

**Comment by Hippodamie** [comment]
Yes, why not (if it is free from copyrights).
Best,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/90687476-2fd4a880-e26d-11ea-95a1-d9dbb319ec86.png)

**Comment by Hippodamie** [comment]
Hi, Magdalena,

in fact, we should have as a subtitle:
Etymological and semantic analysis of ancient greek personal names.

For the source, it was not wikipedia but a picture that I took from a book.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
Dear Sophie, to function as a logo, the image needs to be converted into much simplified graphic form and for this we need a high quality image to start with, otherwise it will become unnecessarily long (and therefore costly) process while effects may still be rather poor. Alexandra is our expert in terms of graphic design, so I would ideally leave her creative freedom in the process, just define general direction and gather some images and samples as inspiration. She designed beautiful logos for TEI Publisher and recently for e-editiones.

But, as I said, we need to be considerate of the budget so we want to finish the functional side first and see if we can splash out a little on the styling then.

**Comment by Hippodamie** [comment]
Οf course! Logo has to come after.
Best,
Sophie

**Comment by tuurma** [comment]
> About the olive-branch above: it is quite better than the others, and would be ideal if we could put the Greek letters of a name through the branch, on it. We could make the choice of a winner at Olympie and make appear his very name in Greek letters.

> I found the name: Κόροιβος, who was the first man supposed to have been a winner in the Olympic Games. For many reasons, it would be a great choice.

![image](https://user-images.githubusercontent.com/449468/90975542-617f9500-e535-11ea-9e67-2cc061d12891.png)
