### ISSUE TITLE
[Search] advanced search 

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#597]
# current status

## Search form

* [ ] adjust all autocomplete sets
* [ ] adjust select option sets
* [x] use new pb-select component (when ready) instead of paper-dropdown-menu
* [ ] make sure that form controls values are passed on form submission
* [ ] reset search button

## Search functionality

* full text search
  - create "content" field which includes all text content, attribute values and resolved attribute values (eg meanings, lexemes, functions...) for "full text" search

* browse (facet&filter search)
  - allow for multiple filter expressions

* advanced search
  - create complex search queries based on the advanced form input

## Search results
 *always* as the document list, including the full text search.

---
#initial version

![image](https://user-images.githubusercontent.com/449468/89896230-652e2600-dbdd-11ea-9938-38c977348538.png)

Dear Sophie, I've divided the form into separate tabs, each dedicated to one area

* Name 
* Period
* Area
* Lexemes
* Suffixes
* Meanings
* Lexica/Resources

Users can enter relevant criteria in any of these tabs, depending on what they are interested in.

Every tab allows for adding a number of "query lines", using the `+` button to interactively create new ones e.g. for Names we could ask for

Greek name starting with Αγα* AND transliterated name starting with Aga*

![image](https://user-images.githubusercontent.com/449468/89896658-1df46500-dbde-11ea-8ce4-ca87db76198a.png)

or

Greek name starting with Αγα* OR any name starting with Aba* OR Ana*

![image](https://user-images.githubusercontent.com/449468/89896973-9b1fda00-dbde-11ea-978a-2d3c0b8e6037.png)

In this manner, we can combine arbitrary number of conditions on the name and join these with a logical operand AND (conjunction) or OR (alternative). For names we can further fine tune the conditions by asking for any form of a name or specifically for Greek or transliterated form.

Same mechanism would apply for all other tabs: areas (dialects), suffixes, lexemes and so on. Conditions from all tabs will be eventually combined so we can ask for all names matching e.g. following conditions:

* Greek name starting with Αγα*
* West Dorian but NOT Ionian
* with lexeme κλεο in Root2 position
* with suffix ος OR ης

**Comment by tuurma** [comment]
@hippodamie

All Advanced Search tabs (tentative labels) and Names tab open. I've added a *not* option after our conversation this morning

![image](https://user-images.githubusercontent.com/449468/90128479-38a61580-dd67-11ea-9d98-83d8e24ff9ce.png)

**Comment by Hippodamie** [comment]
Thank you! I come back to ex-Lexica.

**Comment by Hippodamie** [comment]
Ok. I am ready for the titles to change on this line. I copy all the titles:
Name  Period  Linguistic areas Lexemes Suffixes    Structure   Lexica   Other.

1. Thus, as you can see: exit Lexis and again, as you did first: Lexica. Lexica means:
DELG entries
LSJ/DGEsp
Logeion entries of the current Lexis column + the Logeion entries of the current Onomastic column.

2. Structure means sub-labels:
Functions: V etc
Headedness: X  or Y
Complex structure as: XY/YX; XY < YX; YX < XY; XY > YX and YX > XY

**Comment by Hippodamie** [comment]
About Abbreviated:
in fact, we should not have it juste after X or Y (sorry as I told you this morning) but after lexems and in this menu.
Lexem1                                 Lexem 2
Abbreviated or not               Abbreviated or not.
Because, it is neither the function nor the headedness which is abbreviated but really the Lexem it self.

**Comment by Hippodamie** [comment]
Now, OTHER, at the end of the line=
the details we do not know where to put because they are heterogeneous and not so important:
I mean GPR
fictitious
gender

**Comment by Hippodamie** [comment]
At the end, I come back to what I told you, which is on my page 2bis: Converted Names.
It was like a mess in the Complex Structuration and Semantics: so we just separate the labels type XY < YX etc.
Now, we speak about the rest, which could be called: Converted Names.
Converted Names could be (in this very order):
-Clausal
-Phrasal
-Deverbal
-Denominal/Deadjectival [the current label Conver.]
-Deadverbal
-Depronominal [which should be added, because we need it].

Where to make that appear?
In fact, we should have it under Name, since they are Converted Names. Converted means ‘directly converted from the Lexicon to be used as personal names’.

**Comment by Hippodamie** [comment]
Dear Magdalena,

I think I did all what was to do after our talk.
If you need more informations, just ask.
Of course, it could happen hours before I come back, since I am trying to write something else at the same time.

**Comment by Hippodamie** [comment]
About the olive-branch above: it is quite better than the others, and would be ideal if we could put the Greek letters of a name through the branch, on it. We could make the choice of a winner at Olympie and make appear his very name in Greek letters.
I try to find one interresting/significant name in a few couples of hour. I go to search right now. 
See you,
best and many thanks,
Sophie

**Comment by Hippodamie** [comment]
I am already back: I found the name: Κόροιβος, who was the first man supposed to have been a winner in the Olympic Games. For many reasons, it would be a great choice.
Best,
Sophie

**Comment by Hippodamie** [comment]
Here is my last up-dating of Advanced.
Best,
Sophie
[Advanced.Search.updated 2021_10_07.docx](https://github.com/eXistSolutions/LGPN-ling/files/7303649/Advanced.Search.updated.2021_10_07.docx)
