### ISSUE TITLE
[Search] Lexica

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#598]
I thought that in the interest of not multiplying sections, we could combine input fields related to DELG/LJS and Onomastica/Logeion by adding a type control field to choose between DELG/LJS/Logeion or even search through any of these.

As in other cases, multiple options can be connected with logical AND or OR operators

<img width="568" alt="ling1" src="https://user-images.githubusercontent.com/449468/89898288-ba1f6b80-dbe0-11ea-992a-1b4e9161fd20.png">

**Comment by tuurma** [comment]
Changed the label to *In other resources* for the time being

![image](https://user-images.githubusercontent.com/449468/90128722-a18d8d80-dd67-11ea-8d8f-d2643cf999ad.png)

**Comment by Hippodamie** [comment]
No. Please, just call it Lexis. It means all which concerns the Lexicon, with access to items of the DELG and/or the LSJ/DGEsp and/or to Logeion
