### ISSUE TITLE
[Search] Linguistic areas

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#599]
<img width="888" alt="ling2" src="https://user-images.githubusercontent.com/449468/89899425-93facb00-dbe2-11ea-8d41-2f63a96c247d.png">

**Comment by Hippodamie** [comment]
I would prefer the label:
Linguistic areas (it means all: areal = almost geographical; dialectal; and bilingual or sometimes trilingual).

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/90982440-69f0c380-e567-11ea-9119-aacb8f6b5667.png)

Dear Sophie,

I've changed the label as requested. I also changed the type of the control - made it an autocomplete field, not a dropdown with a predefined list of options.

Rationale for this decision was:

1. list is quite long so it's easier to start typing to see only matching options
2. you can't use wildcards with dropdowns, so it would be not possible to choose `dor*` which would match all Doric areas at once

**Comment by Hippodamie** [comment]
Perfect! Many thanks,
with all best wishes,
Sophie
