### ISSUE TITLE
[New ling] visualization table 

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#600]
Browsing view comprises

* results table with summary information for each name
* collapsible facet panel called `Filters` to the left
* basic sort/filtering option directly above the table

Resembling previous version, this one allows to quickly narrow down the result table to entries matching selected facets or filters. Compared to previous versions facet filtering is much faster and user interface friendlier. Additionally, it is possible to match names by:
* any name form
* Greek name form
* transliterated name form
* dialect
* any lexeme
* prefix
* any base
* base1
* base2

All filters accept wildcards, also in leading position. All filters ignore accents.

<img width="1673" alt="ling2" src="https://user-images.githubusercontent.com/449468/89899749-07044180-dbe3-11ea-8ca9-275f5600a2e6.png">

**Comment by tuurma** [comment]
Example of a name with primary and secondary segm. hypothesis

<img width="1249" alt="ling2" src="https://user-images.githubusercontent.com/449468/89900634-47b08a80-dbe4-11ea-9e30-1287d01a1bda.png">

**Comment by tuurma** [comment]
In the interest of space, I've moved information pulled in from LGPN to the name column. This section uses icons representing number of attestations, gender and att. period.

**Comment by tuurma** [comment]
Slight difference in color between even and odd table rows to lead the eye

![image](https://user-images.githubusercontent.com/449468/90130946-976d8e00-dd6b-11ea-865a-2f29f0fe815c.png)

**Comment by tuurma** [comment]
Highlighting of the row in focus (on mouse over)

![image](https://user-images.githubusercontent.com/449468/90131388-59bd3500-dd6c-11ea-8c85-3d1607b7ece7.png)

**Comment by tuurma** [comment]
Display of information from LGPN (number of attestations, gender(s), period)

## current 

![image](https://user-images.githubusercontent.com/449468/90131733-e9fb7a00-dd6c-11ea-8416-4a4b1a39a4f8.png)

## proposed variant 1 (compact, with icons)

![image](https://user-images.githubusercontent.com/449468/90131795-07c8df00-dd6d-11ea-829c-c58e8598fb4a.png)

## proposed variant 2 (separate lines)

![image](https://user-images.githubusercontent.com/449468/90131961-42cb1280-dd6d-11ea-8c47-d9be50834119.png)

## proposed variant 3 (no icons, no labels)

![image](https://user-images.githubusercontent.com/449468/90132055-68f0b280-dd6d-11ea-9db6-eb439319285d.png)

## proposed variant 4 (text. labels)

![image](https://user-images.githubusercontent.com/449468/90132147-92114300-dd6d-11ea-9479-aa584806e8be.png)

**Comment by Hippodamie** [comment]
Variant 3 slightly remade into:
LGPN
130 [m.]
_371/999

**Comment by Hippodamie** [comment]
Another comment, concerning the top:
if we have Start, do we need Database?

About the Q function at the top at right: 
would it be possible to search through Q for e. g. the title of a monography or the name of a modern author of columns Lexis and Onomastics?

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/90134410-6beda200-dd71-11ea-8c83-1a098dd086a0.png)

**Comment by tuurma** [comment]
> if we have Start, do we need Database?

Database has two sub-options: Browse and Advanced search, but we could get rid of Start, I think.

> would it be possible to search through Q for e. g. the title of a monography or the name of a modern author of columns Lexis and Onomastics?

![image](https://user-images.githubusercontent.com/449468/90134634-bec75980-dd71-11ea-8545-47444c5d5c0a.png)

here? yes, we could use it for a full-text search, to search for occurrences of query term anywhere in a name entry

**Comment by Hippodamie** [comment]
Wonderful. Yes, I think Database could be enough.
Best,
Sophie

**Comment by tuurma** [comment]
Since we decided not to add Advanced Search but use the potential of facets, I changed the Database option into just Browse/Parcourir

**Comment by Hippodamie** [comment]
yes!
