### ISSUE TITLE
[Search] Other categorizations (e.g. gender, GPR etc)

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#603]
![image](https://user-images.githubusercontent.com/449468/90129409-e534c700-dd68-11ea-8cd3-a3c954c5be08.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

did you see that I proposed (#597) to change the top titles in the following way:
Name Period Linguistic areas Lexemes Suffixes Structure Lexica Other.

I would better like to have Structure not with those one like GPR and fictitious, which are not at all as important as Structure.

Thank you in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Sure, I updated the labels and just showing autocomplete fields in action. Still need to work on them a bit more but getting closer :-)

![image](https://user-images.githubusercontent.com/449468/90681885-6bb74000-e264-11ea-9727-063a72d8430a.png)

**Comment by Hippodamie** [comment]
Many thanks, Magdalena!
Good night,
with all best wishes,
Sophie
