### ISSUE TITLE
query field in the menu bar - full text query

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#605]
> would it be possible to search through Q for e. g. the title of a monography or the name of a modern author of columns Lexis and Onomastics?

![image](https://user-images.githubusercontent.com/449468/90134634-bec75980-dd71-11ea-8545-47444c5d5c0a.png)

here? yes, we could use it for a full-text search, to search for occurrences of query term anywhere in a name entry

**Comment by Hippodamie** [comment]
Very well!

**Comment by tuurma** [comment]
we decided later to remove it not to complicate matters
