### ISSUE TITLE
A bug on Lexeme γαινο

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#609]
Dear Magdalena,

the lexem is showed as if we had to delete it, but it is in fact used in the name Γεινιανός, we edited the lexeme, but cannot open the subwindow. 
And on the visualization, we do not se at all the lexem, but we edited it.
The editor does not work, we cannot save, nothing.

Could you please fix the bug on this entry/name?
Thank you,
best,
Sophie

**Comment by tuurma** [comment]
Dear Sophie, perhaps it was due to yesterday's problem with the server? I
did re-edit the name, re-selected the lexeme and checked that the meaning
is correctly pulled in and displayed in the form. I saved the name record
and afterwards lexeme list correctly display Γεινιανός there.

**Comment by Hippodamie** [comment]
Μαny thanks!
Best,
Sophie

PS: I do not yet received your estimate...
