### ISSUE TITLE
A bug on Lexems Σελλο

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#611]
Dear Magdalena,

I hope you are all well.
We have a bug we cannot solve, which concerns visualization among Lexems;
Here it is (σελλο): meanings do not appear.
Could you please fix it?
Many thanks in advance,
with all best wishes,
Sophie
<img width="953" alt="Capture d’écran 2020-10-09 à 10 31 38" src="https://user-images.githubusercontent.com/16923546/95560442-92e6ee00-0a19-11eb-9358-7e79553bef86.png">

**Comment by tuurma** [comment]
There was space in the meaning identifier, fixed now

![image](https://user-images.githubusercontent.com/449468/95563378-9a0ffb00-0a1d-11eb-863d-b4a3d8faf485.png)

**Comment by Hippodamie** [comment]
Sorry, dear Magdalena, but many thanks for fixing it.
Best wishes,
Sophie
