### ISSUE TITLE
A question concerning the use and search for initial capital letters

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#613]
Dear Magdalena,

I wrote you by email but come back to Git-Hub.

A question:  we would like to be able to have a special (new) search for  lexems begining with a capital letter.
Would the Search function be possible if we put the capital of the lexem only in the right box and not at left (Sub-form)?
Or do we have to do it both at left and at right?

Subsidiary question: when lexems begin with an `<h>`, is it possible to write the following vowel in capital rather than the `<h>`? I mean that the ideal would be the user types the vowel in capital even if it begins with an `<h>`.
Αnd the same is true for lexems begining with `<F>` or `<Fh>`: we would like the user types <Aλειο> and gets the analysis of the name Ἀλεῖος, even if the lexem is in fact Fᾱλειο.

The most important (and urgent for us) question is the first one.
any thanks in advance for your answer,
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Hi again, Magdalena,

if we put for every lexeme for which it is necessary the initial letter in capital in the box at right, would it be possible for you to generate automatically the change at left for all of them, thanks to only one query?

The present issue is  of course in connection with the next one about the 8 additional functional labels for nouns which are in fact themselves names. 

Thanks for your attention,
best,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

First, about Lexemes:

the form at left is only an internal identifier of the lexeme. It is inconsequential for searches, as the only form to be searched by, will be the form from the right hand box.

Therefore, you can adjust the Lexeme (right box) as necessary and all the names which are connected with its id (left box) will be automatically presented with the changed Lexeme form.

![image](https://user-images.githubusercontent.com/449468/104893155-565d5380-5973-11eb-96cc-0cbeca56a209.png)

Second, about searches:

at the moment when we search, we search for a name form and searching e.g. for 'alei*' we can retrieve names 

* Ἀλεῖος
* Ἀλείνη
* Ἀλείδας

In the new search interface we will retain the capacity to search for *names* (with or without wildcards) and have a new possibility to search for *lexemes*. This will also allow for searches with or without wildcards. So, I imagine, if you would be interested in finding the name, Aleios, it would be easiest through a name search, like we do now. On the other hand if you were interested in all names built on `(Ϝ)ᾱλ-ε(y)-(ιο)` lexeme, you would use the Lexeme tab and specify this exact form. Of course combining searches for name and lexeme form etc will be also possible. I hope this clarifies matter a bit.

![image](https://user-images.githubusercontent.com/449468/104894930-91608680-5975-11eb-854c-6da06024bf38.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

we already did it. Thank you for remembering me the function at left.
