### ISSUE TITLE
In view the Search interface finalization.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#614]
Dear Magdalena,

in view of the Search interface, do you need I give you an up-dated version of the current Editor, which is partly to revise now (for example: functions for pre-root are too many. Pre-root is only adverbial. And another important thing is that headeness does not need and never uses Z, but only X and Y)?

I give in another issue NEW functions we discovered recently that we need them and it will be really new to let people search them. It corresponds to one of the big results of the project.

See next issue...

**Comment by tuurma** [comment]
Dear Sophie,

our Lexeme search at the moment allows for these criteria to be specified:

Position (e.g. Prefix or Base), Lexeme (e.g.  (Ϝ)ᾱλ-ε(y)-(ιο)), Constituent (αλειο), Function, Headedness, Abbr. and Meaning.

With the new classification for proper nouns, we could just extend the Function to add *Proper Noun* beside *Noun* as an available category and another box for subcategories (anthroponym, toponym etc). It would be then very easy to query for it at different levels of granularity (all proper nouns or just based on hero names, for example) and combine it with criteria for names or lexemes.


![image](https://user-images.githubusercontent.com/449468/104896016-e2bd4580-5976-11eb-9769-952a49fb8dff.png)

**Comment by Hippodamie** [comment]
Wonderful!
