### ISSUE TITLE
Proper Noun Lexems and subcategories

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#615]
Dear Magdalena,

at this very late point of our research, we understand that lots of compounds personal names have one of their element/base which is not a lexem but a name.

Those name bases are of 8 main categories:
anthroponym
festival name
hero's name
month name
mountain name
river name
theonym
toponym.

Would it be possible to introduce now those 8 labels under the current Function 1 and Function 2 labels?
And our job od editors would be thus to change the Noun label into one of those 8 everytime it is necessary.

It would of course permit to search calling for example ‘anthroponym’, and then to get all the personal names of the database made themselves of an anthroponym. See e. g. one of the hypotheses of Euarchippos.

And by the way, about this Euarchippos: it would be very interresting to be able to call all lexems which have an = sign, like for αρχ(ε/ι)=ιππο for the 2nd element of this name.

Many thanks in advance for your answer,
best,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

I would perhaps suggest extending the Function options with Proper Noun for these and introduce sub-categories with options that you listed? This way we could in the end have more flexible searches.

**Comment by Hippodamie** [comment]
Dear Magdalena,

yes. Just like that.
I look your other messages and thanks for fixing the 2 lexems.

**Comment by Hippodamie** [comment]
Dear Magdalena,

it seems in fact that PropN is not visible in the facet Fonctions.
