### ISSUE TITLE
2 bugs on lexems: λυκαστο and Ασ_ανδρο

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#616]
Dear Magdalena,

we have 2 bugs we are not able to solve by ourselves.
On the lexem λυκαστο: we cannot enter in the sub-form as we need;
 and the lexem Ιd. Ασ_ανδρο, see A(1 or 2).  We re-edited it with another form of the lexem (ασ_ανδρο) but cannot delete the 2 lexems which are listed under A. We would like A list to be empty and disappear.

Could you please help?
Many thanks in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Should be both fixed now
