### ISSUE TITLE
Impossible deletion of Lexem ενεϝα

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#618]
Dear Magdalena,

could you please fix it? Here it is.
<img width="1182" alt="Capture d’écran 2021-01-21 à 22 02 51" src="https://user-images.githubusercontent.com/16923546/105411920-5344ba80-5c34-11eb-8632-886c6a076293.png">
Many thanks.
Good night,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
done

**Comment by Hippodamie** [comment]
thank you, Madgalena,
best,
Sophie
