### ISSUE TITLE
Leōbrimos : a small bug!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#619]
Dear Magdalena,

How are you? Did you receive my previous message?
Could you please fix the bug on this name? We cannot open the Lexem sub-widow and the Lexem2 is not visualized.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
I just searched for ο_βριμο in lexeme2 and re-selected it, now seems to work ok.

I will answer you next week, if that's okay? I have had a very busy couple of weeks, very sorry for silence

**Comment by Hippodamie** [comment]
Very well! Nex week will be perfect for me too.
Thank you for the guy Leobrimos!
Best,
Sophie
