### ISSUE TITLE
Doromenes

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#620]
Dear Magdalena,

hello! I hope you are well.
Here is a new bug-like we cannot delete.

We do not need a Capital in the identifiant. So we have remade it without the capital. But I do not know why but we are not able to delete it among the lexems.
Could you please delete it? 

Many thanks in advance,

<img width="1189" alt="Capture d’écran 2021-03-13 à 08 11 04" src="https://user-images.githubusercontent.com/16923546/111022550-a71d8580-83d3-11eb-8474-4d72af3cd7e8.png">

with all best wishes,
Sophie

**Comment by tuurma** [comment]
Removed, no problem. I am well, thank you. Wish you a nice weekend!

**Comment by Hippodamie** [comment]
Thank you! You too!
