### ISSUE TITLE
Feed-back (the end): Advanced Search up-dating: almost unchanged!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#623]
Hi, Magdalena,

here are my small comments about the Advanced Search as I drawed it a long time before and that you work on. 
See the word docx file.
Almost no changes, in fact!
With all best wishes,
Sophie
[Advanced Search(updating 2021April15).docx](https://github.com/eXistSolutions/LGPN-ling/files/6318540/Advanced.Search.updating.2021April15.docx)

**Comment by Hippodamie** [comment]
Hi Magdalena,

I think I understood now how to use facets also for combined searches... 
So, here is, after the mail of this morning the improvement of my thoughts about Advanced Search:
all that we need  (for Lexemes: combined, exclusion and reverse couples) seems possible combining Main Filter for exemple Lexeme+ Lexemes facets, if and only if it is possible to choose several Lexemes among facets at the same time or sometimes only one (in this special case necessarily we would need not only Top50 Lexemes but the whole choice).
Since, those last thoughts have consequences on the facets list, I give you in the same file the new list of facets and give again the new list of the Main filter, in both English and French.

I assume that it is now the end of my (sometimes contradictory) thoughts) until next thursday where we speak together.

I think that you have before Thursday only to understand what I mean in this last file. There were also the bugs I had listed in the Feed-back April file #621
[Advanced.Search.updated 2021_10_08.docx](https://github.com/eXistSolutions/LGPN-ling/files/7311983/Advanced.Search.updated.2021_10_08.docx)

Thanks you for your patience and sorry for all the changes,
have a nice week-end,
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
As a complement:
if facets list has to many items to make all of them appear every time (with my suggestion of Advanced Search made through Main Filter +facets), could it be possible to open only the categories of facets needed depending of the Filter chosen?
For example: if we choose Lexeme (for example αγορα) as a main filter, then would directly open the corresponding Dialect-Areal1, Lexemes, Constituents (with the results, like now) and the rest will only take the form of the different titles list. And if we need then to search for suffixes, we just would have to click on the title ‘Suffixes’, and the list of the 4 suffixes will appear with their results. And the same for the other items.

**Comment by Hippodamie** [comment]
A correction about Suffixes: in the file posted, I wrote #602 was perfect. But in fact, my new suggestion (all in facets) makes it not available anymore.

Best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

I hope you had a nice week-end.
I post a slightly up-dated version of the Advanced Search (today dated version).
In fact, the difference only concerns the list of facets and the Main Filter list.  I corrected Personal name into Proper Noun, which was right.
Many thanks in advance.
Do you confirm our Thursday meeting around 10.30?
With all best wishes,
Sophie
[Advanced.Search.updated 2021_10_11.docx](https://github.com/eXistSolutions/LGPN-ling/files/7320088/Advanced.Search.updated.2021_10_11.docx)

**Comment by Hippodamie** [comment]
Hi, Magdalena,

very well what you did!
I post again the only Main filter list with my view of the hierarchization: please, tell me if it is in your view correct.
Best,
Sophie
[Rewriting Main filter list_for a better hierarchization .docx](https://github.com/eXistSolutions/LGPN-ling/files/7320416/Rewriting.Main.filter.list_for.a.better.hierarchization.docx)

**Comment by Hippodamie** [comment]
Sorry: you are right: not ‘Lexical Base’ but only ‘Base’, in fact.

Please a French error in the Catalogues: nom par ‘aire’ and not par ‘l'aire’. All the rest is perfect.
Thank you

**Comment by tuurma** [comment]
Dear Sophie,

I've been working on new facets but primarily making the "hierarchical" facets (like Dialect-areal) work more intuitively. It now works well for Dialect-areal and includes all available information, also on 2nd and 3rd dialect and information from variants.

Problem is a bit more tricky for Bases-Constituents where selecting a base we obviously see other bases from compound names. I solved it by adding another level to the Constituent facet, so it always groups by a Base and then follows by the Constituent value.

![image](https://user-images.githubusercontent.com/449468/136847051-dc69ce02-0d16-4951-97b9-332470400a82.png)

Selecting base βο̄λα I can see all other bases which may accompany it also in Constituent list, but I can choose the one I want (also βο̄λα) there and see 

* β_ 
* βουλ 
* βουλο

as constituents. I think it's the best solution to avoid mixing constituents from other co-occuring bases in this facet.

![image](https://user-images.githubusercontent.com/449468/136847407-f416b468-c5ca-4587-b448-2a3bd40ceb1a.png)

**Comment by tuurma** [comment]
I've also added Suffixes and Functions as separate facets but for the time being grouped Headedness, Abbr etc under Classification. We could add as many categories as you like if this approach is useful to you.

![image](https://user-images.githubusercontent.com/449468/136847705-b30a6b06-4ac0-4450-8129-0e8956e8f904.png)

**Comment by Hippodamie** [comment]
Hi, Magdalena,

thanks a lot for the first work about Bases-Constituents, which is great!
About Functions and Classification: in fact it is a matter of advanced search only. I mean: nobody will search for those facets for Simple Names (=not compounds); but, they will only search for combined like: VN XY(Abbr), AdjN YX etc. Or they could need to search only for VN, AdjN, AdvV, AdjAgtN etc.
I will give you soon a list of the only types of facets we need for the ordinary search.
In fact, Magdalena, Advanced Search would have to be almost exclusively made for Compound Names, if we can have in the main facets the possibility to ask for combined suffixes.
That is why I thought those last days we could put all together on the same facets page if and only if we are able to ask for combined search, for example opening sub-boxes as you did by cliking on βο̄λα. For example, opening classification and having directly the possibility to click on several items at the same time: for example VN XY.
What do you think? Or do you prefer to open a special advanced search only for searches about Compound names?
thanks for your answer and for all,
best,
Sophie

**Comment by Hippodamie** [comment]
Here is a new facets scheme combining usual and advanced search.
What do you think?
Is it the best way to get the part of our search focused on Complex Names?
Note: I have to think more about the names of the 2 labels: Simple Names vs Compound Names or Not simple Names or Complex Names...
[New facets labels reordered October12.docx](https://github.com/eXistSolutions/LGPN-ling/files/7328092/New.facets.labels.reordered.October12.docx)

**Comment by tuurma** [comment]
Thank you, this would work upon the condition that each level of grouping gives us non-overlapping categories, e.g.

* Simple
* Compound
  - non-abbreviated compound (XY or YX but no Abbr)
  - truncated compound (XY or YX and Abbr)
  - simple<compound (X or Y and Abbr)

I note that in the list above there's no space for cases where we have X or Y but no Abbr.

Alternatively we could have the division like below, which gives us a "slot" for all possible cases

* Simple (no Abbr, X, Y)
* Compound
  - non-abbreviated (no Abbr)
    - double (XY or YX)
    - single (X or Y)
  - truncated (with Abbr)
    - double (XY or YX)
    - single (X or Y)
 
Below the headedness layer we would of course have functions in all cases.

**Comment by Hippodamie** [comment]
1. "I note that in the list above there's no space for cases where we have X or Y but no Abbr."
We are not supposed to have edited X or Y without Abbr? Could you show a case?

2. I think the first scheme, as you re-write it, is the only possible.

3. I added 2 schemes of Abbr (in blue) in the file I posted earlier in the morning.
[New facets labels reordered October12.docx](https://github.com/eXistSolutions/LGPN-ling/files/7328449/New.facets.labels.reordered.October12.docx)

**Comment by Hippodamie** [comment]
Hi, Magdalena,

there are also examples of N Abbr without X or Y, like for Ἀνδριτίων. It is rare but could happen!
Good night,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Hi, Sophie

I've been running some tests with the Classification facet

Step 1

![image](https://user-images.githubusercontent.com/449468/137099649-1294412d-f744-46b8-8a59-e69ec3db2217.png)

Step 2 - expand 1st option

![image](https://user-images.githubusercontent.com/449468/137099771-656858bc-a719-4de7-b824-9576fe2878a8.png)

Step 3 - expand to see Function level

![image](https://user-images.githubusercontent.com/449468/137099951-db49d9f0-0b35-44a1-b1d9-8abece798dba.png)

**Comment by tuurma** [comment]
NB The counts above are quite small because I operate on a reduced sample of ~200 names

Last case above shows non-abbreviated and abbreviated options despite selecting "non-abbreviated" because one of the names has a second hypothesis, so a single name "belongs" to both facets.

![image](https://user-images.githubusercontent.com/449468/137100869-974aea62-b211-4c9f-8beb-c04ab51c4766.png)


For similar reason the sum of XY+YX is greater than the count for non-abbr compound (95 vs 15+81=96)

![image](https://user-images.githubusercontent.com/449468/137100938-dc09e508-a8ef-408d-ab3d-eed98d62c28a.png)

**Comment by tuurma** [comment]
Alternative is the division into 

* simple
* complex
  - truncated
  - whole
  
and below headedness and functions levels as before. To me it looks somewhat clearer.

![image](https://user-images.githubusercontent.com/449468/137101711-9d8a7ee6-922b-49d6-bedc-37415b724544.png)

![image](https://user-images.githubusercontent.com/449468/137101811-301f6b8d-c92a-48c7-a5a2-0232436f6d4a.png)

![image](https://user-images.githubusercontent.com/449468/137101876-82c68280-8c29-48ea-881d-76a06f4aace8.png)

**Comment by Hippodamie** [comment]
Hi, Magdalena,

for me too this last one is clearer. It looks great!
An only correction to bring: one subcategory was forgotten: there are also Simple coming from Complex Names (XAbbr, YAbbr and even Abbr without X or Y).
Many thanks,
best,
Sophie

**Comment by Hippodamie** [comment]
By the fact, we would appreciate to get the list of all AdjV in our datas, since it is not normal and we would need to correct them.
I understood about counting and the problem of double hypotheses.
Best,
Sophie

**Comment by tuurma** [comment]
I had some issues with the Oxford server but managed to upload to ours. If you have some time to look at the facets in action.

http://apps5test.existsolutions.com/exist/apps/lgpn-ling7/index.html

Some things to note apart from counting which I explained earlier:

* non-hierarchical facets (bases & suffixes) allow for selection of multiple values at once - these are combined with logical OR, so [ευ or φιλ(ο)](http://apps5test.existsolutions.com/exist/apps/lgpn-ling7/index.html?facet-morpheme=%CF%86%CE%B9%CE%BB%CE%BF&facet-morpheme=%CE%B5%CF%85) returns all names which have at least one of these bases
* hierarchical facets (dialect-areal, constituents, classification) only work for "drilling down", which means you cannot select at the same time ευ or φιλ(ο), this will not return any results. You can choose ευ, see available constituent forms and select one of these to narrow your results further

![image](https://user-images.githubusercontent.com/449468/137141710-e682db1a-2650-46cf-adff-646d21ddd8ea.png)

By the way, there are rare cases of XX or YY combinations and I wonder if these are correct?

http://apps5test.existsolutions.com/exist/apps/lgpn-ling7/index.html?facet-classification=complex&facet-classification=truncated&facet-classification=XX

**Comment by Hippodamie** [comment]
Thanks a lot!
Ok, I understand, but have to train with that.
I will test now.

**Comment by Hippodamie** [comment]
Hi Magdalena

could you see the issue I just was writing to you? I could not find it anymore. It was called something like Making run the new version or so on: there were 7 items...
