### ISSUE TITLE
Sort and search options

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#628]
Search by:

![image](https://user-images.githubusercontent.com/449468/135990852-efeb9c9c-34cf-4ef9-a532-7c087992e007.png)

Order by:

* [x] Greek name
* [x] Transliterated name
* [x] Earliest attestation
* [x] Latest attestation
* [x] Frequency (diminishing)
* Dialect

Please note that we can't reasonably sort by Dialect, since multiple Dialects can be selected. For sorting we need a single value to order by. I could sort by primary Dialect but not all of them at once.

![image](https://user-images.githubusercontent.com/449468/135990993-e6de3ecf-58e4-449b-a41f-84e36f98d798.png)

**Comment by Hippodamie** [comment]
could we rather have as filter-list that one:

![image](https://user-images.githubusercontent.com/16923546/136387080-3eff37ef-6fb1-432e-9841-8a4b26e83ca3.png)

**Comment by Hippodamie** [comment]
To answer your remark:
change in the list I just extracted from my last Word file in #156 
Dialect-Areal into:
Dialect-Areal1 (exactly the same label I asked also as a title of the first facet).

**Comment by Hippodamie** [comment]
Could you please tell me whether the new rich Filter list is possible?
I add also a last up-dating to Advanced Search, I would like to simplify.
Many thanks in advance,
Best,
Sophie
