### ISSUE TITLE
wildcard search (was: Truncation)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#63]
I thought I posted a message about Truncation yesterday, but do not see anything.  So I try again. Sorry if I already did it.

Just to say that the function Truncation is important for historians epigraphists & linguists. Not only simple but also double.
For example: _υφ_ which is neither a Root nor a Suffix nor a Prefix but could be useful to search as such.
Epigraphists and linguists use it everyday (it is the way for ex. to understand if the sequence is a Root or a Suffix, looking through the different types of names having it).
Thanks.
Sophie

**Comment by tuurma** [comment]
Sure, wildcard search will be available.

**Comment by Hippodamie** [comment]
Wonderful, Magdalena !

**Comment by tuurma** [comment]
important to allow for patterns starting with * as well as multiple *

**Comment by tuurma** [comment]
wildcard search cases: κλεα, *κλεα, κλεα*, *κλεα*, *κλ*εα*
