### ISSUE TITLE
5 Lexemes with their Names to merge 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#630]
Hi, Magdalena,

here is a file with 5 merging we ask you to do automatically. Would it be possible?
Thank you in advance,
best,
Sophie
[Lexemes to merge asked to Magdalena.docx](https://github.com/eXistSolutions/LGPN-ling/files/7338532/Lexemes.to.merge.asked.to.Magdalena.docx)

**Comment by tuurma** [comment]
no problem, I will do it

**Comment by Hippodamie** [comment]
Thank you!

**Comment by Hippodamie** [comment]
Dear Magdalena,

please, wait a little. I have to think a little more about it.
I come back to confirm later.
Thank you,
best,
Sophie

**Comment by Hippodamie** [comment]
Hi, Magdalena,

here we are. They are only fourn Lexemes with their Names to merge.
See new attachment
[Lexemes (with their names) to merge on LGPN-Ling. Versionbis 4 Lexemes.docx](https://github.com/eXistSolutions/LGPN-ling/files/7352340/Lexemes.with.their.names.to.merge.on.LGPN-Ling.Versionbis.4.Lexemes.docx)
Many thanks for your help.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
Lexemes (with their names) to merge on LGPN-Ling.

* κλεϝεσ [κλε(ϝ)-(εσ)] (472) and κλεϝε [κλε(ϝ)-(ε/ο)] (226) => merge into κλεϝεσ [κλε(ϝ)-(ε)(σ)]  “fame, glory” = 472+226

* θαρσεσ [θαρσ-(εσ)] (15) and θαρσε [θαρσ(ε/ι/ο)] (49) => merge into θαρσεσ [θαρσ-(ε)(σ)]

* κρατεσ [κρατ-(εσ)] (299) and κρατι [κρατ-(ι/ο/ε/αι)] (23) => merge into κρατεσ [κρατ-(ε)(σ)]  “power, strength, might”

* λαμπεσ [λαμπ-εσ] (9) and λαμπε [λαμπ(ε/ο)] (19) => merge into λαμπεσ [λαμπ-(ε)(σ)]  “lightening, shining”.

**Comment by tuurma** [comment]
Done

**Comment by Hippodamie** [comment]
Hi, Magdalena,

many thanks, but could you please, give me the list of ancient κλεϝε, θαρσε, κρατι, λαμπε, since we will have now to check each of the edition.
Thank you for that,
best,
Sophie

**Comment by tuurma** [comment]
Sorry, it would be quite a lot of effort because I'd need to restore an
older version of the database. Are you certain you need it?

**Comment by Hippodamie** [comment]
ok, we will try to do without.
