### ISSUE TITLE
Bis version of what I just have lost. It was my comments about running the new version

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#632]
1. Sorting by Greek Names when I type αγορα* seems erratic.

2. Dialect-Areal: when clicking on Ionian (just followed by Thessalian), sub-categories appear, and then not Thessalian anymore, but Multiareal 23; before I clicked on Ionian, Top50 showed Multiareal 44 (the last label). Why?

> I will explain here to make it easier to follow

* facets show are always the most frequent for a given result set (depending on all the criteria set). So initially we have a list of 5 most frequent dialects and in that group they are sorted alphabetically

![image](https://user-images.githubusercontent.com/449468/137264092-c458d93c-f1e2-40ba-b458-cf4f38fe58d4.png)

* choosing "Ionian" we change the result set, now facets are shown for a given selection, i.e. only Ionian names but they may still have also a different dialect selected. It looks like *multiareal* commonly co-occurs with "Ionian" and this is why it "suddenly" shows in the most frequent dialect list for Ionian names

![image](https://user-images.githubusercontent.com/449468/137264313-31600c50-4609-43f2-a97a-d41d3ddd43ed.png)

3. Classification is wonderful with functions etc.!!! but we currently miss a subcategory (Simple<Compound =XAbbr or YAbbr or Abbr without X, Y):
Complex = 
truncated (X and Y and Abbr in any order, with Abbr once or sometimes twice)
whole (XY and YX and also XY<YX etc.)
vs Simple (no X, no Y, no Abbr).
Where to put it in the more logical order? Rather maybe with Simple? Like Original Simple= Original or Simple<Compound?
Labels to be improved.

4. A detail in running: could it stay at its place when we click, not coming up in the list of the facets? It happens for example when we are in the facets under Lexemes, like Constituents or Classification. 

I prefer to submit now

**Comment by Hippodamie** [comment]
Again about 3:

here is the taxinomy:
Compound (not Complex anymore):
-complete
-truncated
Simple:
-original
-shortened compound
What do you think? Is it clear enough?

**Comment by Hippodamie** [comment]
List of details to correct (appearance, labels improvement):
1. Main Filter LIst: 
- [ ] still missing: Etymological lemma
2. Catalogues to add:

- [ ] Lexemes by letter
- [ ] Lexemes Meanings
3. Among Resources:
- [ ] Bibliography
- [ ] Non-Greek Names by letter
Do you want me to send you Bibliography and the Non Greek Names in A, B, Γ, Δ, Ε? They are ready.
4. How to use Search was almost ready, but will be re-worked once you have fixed the Facets
5. Facets;
- [x] Suffixe + /s/ to add (plural) in both languages
6. Head title of the columns to change:
English/French:
- [x] not Lexicon/Onomastics anymore but Lexemes but Bases in French
- [x] Morphosyntax/ Morphosyntaxe (French)
- [x] References, linked Sources and Onomastics Ref. [add Onomastics before Ref]           (but no change in French)
7. Please, could you 
- [x] move the pages of occurrences line above the Sort + Filter lines just as in LGPN new Search?
That's it for those details.
Good evening and see you tomorrow,
MANY, MANY THANKS!
Sophie

**Comment by Hippodamie** [comment]
Maybe rather write in 3.: Non-Greek Names by letter

**Comment by Hippodamie** [comment]
8. Main filter Lexeme: typing δαμο does not give both δαμο and δᾱμο in the list. In fact, the result is δᾱμο, but we cannot get δαμο without the macron.

9. Ιf I filter by suffix and type ιδ, there will be in facet Suffix a list and if click on ων in this list, I get a name in -ωνίδας, in which ων is as a suffix 3, and is in the same list as ιδ itself, which is a suffix2, and as -ας, which is a suffix1. Whereas -ων is well known also as Suffix1: so it is confusing.

**Comment by Hippodamie** [comment]
The only searches which is missing is Suffix multisearches:

- [x] S4+S3+S2+S1.

**Comment by Hippodamie** [comment]
The last one missing is:
not necessarily Lexeme + Lexeme but rather letters sequences of the names with wildcards like:
not necessarily κλεϝεσ + αγορα but as well: *κλ* + *γορ*. There could coincide with the Constituents. We really need to be able to use even 2 wildcards in the 2 boxes.
We could called that advanced search: Combined Lexemes.

**Comment by Hippodamie** [comment]
I come back to the Classification taxinomy (please keep your ‘whole’ and not my ‘complete’)
Now in French:

- [x] All done

Composés:
-entiers
-tronqués
Simples:
-originels
-composés raccourcis

**Comment by Hippodamie** [comment]
- [x] Or to prefer to ‘originel’ in FRench, rather ‘d'origine’.

Thank you,
good night,
Sophie

![image](https://user-images.githubusercontent.com/449468/137318958-1ff56757-793f-41c7-9a3f-195475a2a85a.png)

**Comment by Hippodamie** [comment]
Hi, Magdalena.

About Semantics: could we have them in English when we have set the Search in English? At the moment we have them in French even when we have selectioned English.

Αbout Homograph Lexemes like hιππο and hιππο2: could you please add the 2 so that in the facets list too we see 2 different items and not what looks as the repetition of the same?
The hιππο2 different from hιππο is right in the Filter list.

**Comment by Hippodamie** [comment]
About design: could we have, please,  the 2 lexemes not too close form each other; we prefer suffixes more tight/squeeze than lexemes. In fact the most of the time they will be not so many suffixes: zero, 1 or 2. So not let too many width for them.

**Comment by Hippodamie** [comment]
If I understand now, we would not need combined suffixes search, since we get it through what I was about to call a mess last evening. Could you confirm?

Th last question is: do we need Combined Lexemes (or letters sequences with wildcards? The test is the case of the reverse compounds like Kleagoras/Agorakles. Could we fin them or others? Very often there are several bases at stake: not only κλεϝεσ + αγορα but maybe κλεϝε + αγορα, κλεϝεσ + αγοραο, κλεϝε + αγοραο. And we are not sure to get every choice we need to explore in the Lexemes facet.

**Comment by tuurma** [comment]
> About design: could we have, please, the 2 lexemes not too close form each other; we prefer suffixes more tight/squeeze than lexemes. In fact the most of the time they will be not so many suffixes: zero, 1 or 2. So not let too many width for them.

We do have it quite tight fight for space. And since it is a table the width will be adjusted to the other suffixes in the column. This is why sometimes it feels wider than absolutely needed in one row, but the situation will be different in another row.

![image](https://user-images.githubusercontent.com/449468/137267843-efffd15c-c4f3-4f5a-9844-eb69d1beca6d.png)

**Comment by Hippodamie** [comment]
Proper Noun main filter does not seem to work. 
Suffix, if I type ιδ gives 17 items, what is very few, since they are so many names in ιδ-ης or ιδ-ας.

**Comment by Hippodamie** [comment]
Coming back to combined Lexemes: we will get it! We have to filter by name, then to type the sequence of letters: for example *μεν*, then we choose δᾱμο, and here are given the reverse couple Μενέδημος/Δημομένης!
Hurrah!
You built a marvel!!! Congratulations and so many thanks!

**Comment by Hippodamie** [comment]
I understand.

**Comment by Hippodamie** [comment]
The 2 last questions are: do we add Etymological lemma and Meaning in Main filter list?

**Comment by tuurma** [comment]
> Th last question is: do we need Combined Lexemes (or letters sequences with wildcards? The test is the case of the reverse compounds like Kleagoras/Agorakles. Could we fin them or others? Very often there are several bases at stake: not only κλεϝεσ + αγορα but maybe κλεϝε + αγορα, κλεϝεσ + αγοραο, κλεϝε + αγοραο. And we are not sure to get every choice we need to explore in the Lexemes facet.

For this we will need an option to have 2 filters at once. This way we could ask for lexeme: κλ* and lexeme: αγ* and get the results you need. A workaround would be to use lexeme: αγ* and facet: κλεϝεσ but as you noted, this will not give us results for κλεϝε, so it is not exactly the same.

**Comment by Hippodamie** [comment]
The only important thing is that when we have 2 lexemes in the table they do not look to tight, whereas for suffixes it is not important.

**Comment by Hippodamie** [comment]
Me should have Lexeme Meaning in the Main filter list, maybe between Dialect Areal and Lexemes.
It is the only way for non specialist public to have access to names they do not already know. For example people who would know if they are names with love in them and what they mean. They would type love and then find all names. It is important.

**Comment by Hippodamie** [comment]
There is now a bug in suffix main filter list: genitives appear.

**Comment by tuurma** [comment]
- [x]  Compound: two lexemes
  - whole
  - truncated (with Abbr)
- [x] Simple: only one lexeme
  - original
  - shortened compound (with Abbr)

**Comment by tuurma** [comment]
Logeion lemma facet:

![image](https://user-images.githubusercontent.com/449468/137318291-b28d45a9-f298-4297-8f65-ac00060386bb.png)

**Comment by tuurma** [comment]
I also added S1-S4

![image](https://user-images.githubusercontent.com/449468/137322842-e282f503-6933-4ba0-b517-606d53782683.png)

**Comment by Hippodamie** [comment]
There are 2 different levels:
etymological lemmas (which would be great in the Main filter list only);
and Greek words, which would be better as a facet.
From a lemma are made many words: here is the hierarchy.

But there is a Name in your list, a star name: Patroklos; it could be also with Logeion links theonyms, names of rivers, of mountains, of heroes, of months. How to call the facet? Lemma is not good. In fact they are words and proper nouns. Lexicon would be great since the only links correspond to our main Greek dictionaries, and the Greek Lexicon LSJ has a proper noun as Patroklos in it! Please, call it simply: Lexicon.

In my idea, Lexicon as facet should take place rather between Dialect-Areal and Bases, since from Bases we have all the more difficult stuff especially concerning linguists. Whereas greek words concern all the Hellenists community.

**Comment by Hippodamie** [comment]
Wonderful for suffixes.
How will it work: not open at the begining, only Suffixes; then clicking on the labels would open the details?

**Comment by tuurma** [comment]
Renamed the facet to Lexicon.

![image](https://user-images.githubusercontent.com/449468/137327891-41f6b25c-1327-48b0-a7ab-678f66bed679.png)

> Wonderful for suffixes.
> How will it work: not open at the beginning, only Suffixes; then clicking on the labels would open the details?

Regarding suffixes: I think it would be best if S1-S4 are hidden initially and we can have a button which says "related/more specific facets" or something like this to open individual suffixes only when necessary. But I will take care of that at a later stage, since this is a bit more "cosmetic".

**Comment by Hippodamie** [comment]
Perfect!

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/137526309-1f6d766e-659c-4bef-844e-8207d71de687.png)

**Comment by Hippodamie** [comment]
Wonderful!

**Comment by tuurma** [comment]
> Main filter Lexeme: typing δαμο does not give both δαμο and δᾱμο in the list. In fact, the result is δᾱμο, but we cannot get δαμο without the macron.

The identifiers of these lexemes are δαμο and δᾱμο but lexemes themselves are δαμ-(α) and δᾱμ(ο) and these can be found, e.g. with query δ?μ* (? represents a single character, while * any number of characters)

![image](https://user-images.githubusercontent.com/449468/137527378-83b7b1c2-83cd-40ac-b95b-0f46d4a21b42.png)


![image](https://user-images.githubusercontent.com/449468/137526976-3013c1ae-0d35-4477-8642-35c04b13810f.png)

**Comment by tuurma** [comment]
Dear Sophie, I either fixed or extracted issues described here so I will close this ticket because it got very long meanwhile

**Comment by Hippodamie** [comment]
So, I did not try the ? (I knew it from your new Name Search): very convient, if it is available too for LGPN-Ling, both Names and Lexemes!
But we will try to solve this kind of problem: it is because sometimes our Lexeme is too different of the identifier. We will work to improve that the next months. I was due in fact to the need we had as editors to see in the table not only the Lexeme but the details of the Constituants themselves, since it was not so convenient to have them hidden (only in the Edition window). So we will be able now to begin to clean that, since we are able to search for Constituants.

**Comment by Hippodamie** [comment]
Would it be solved if we had Id δαμο and Lexeme δαμ(ο/ᾱ)?
Best,
Sophie
