### ISSUE TITLE
A wrong asterisc in suffix to delete: change ω(*ϝ)ς into ω(ϝ)ς 

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#633]
Hi, Magdalena,

could you please remove the asterisc*?
Both in the presentation about LGPN-Ling and in the list of suffixes we use to edit (it seems both forms are in the editor list even if really we do not ‘see’ the wrong one), see screenshots.
It looks awful: a shame for us in fact...
Thanks for your help,
best,
Sophie
![Capture d’écran 2021-10-14 à 14 30 02](https://user-images.githubusercontent.com/16923546/137318492-de20a885-3e01-4419-a9e9-d6f0e4cca12f.png)

![Capture d’écran 2021-10-14 à 14 31 15](https://user-images.githubusercontent.com/16923546/137318540-50774b69-4e4e-4b79-813f-d1c314b1b2fe.png)

**Comment by Hippodamie** [comment]
Sorry: i did not want to submit as soon.
We just would like you delete the asterisc in About LGPN-Ling description, if possible; BUT delete the wrong form of the suffix in the editor list (if it still exists in the list, but I wonder if we did not correct in the list a long time ago; but Florian found it with the asterisc on table). 
But luckily the other (correct) form does already exist (at the end of the list).

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/137531986-412d8e39-bae3-49c2-87f5-849690f41990.png)

**Comment by Hippodamie** [comment]
Thank you very much!
