### ISSUE TITLE
[Menu] Resources

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#634]
Among Resources:
 
- [ ] Bibliography
- [ ] Non-Greek Names by letter

> Do you want me to send you Bibliography and the Non Greek Names in A, B, Γ, Δ, Ε? They are ready.

Yes, please. You can attach these here.

**Comment by Hippodamie** [comment]
Here it is. Only A- Non Greek are temporarely missing (in a few weeks
[Β- Non-Greek and Hybride Names October2021.pdf](https://github.com/eXistSolutions/LGPN-ling/files/7346362/-.Non-Greek.and.Hybride.Names.October2021.pdf)
)
[Γ- Non-Greek and Hybrid Names October2021.pdf](https://github.com/eXistSolutions/LGPN-ling/files/7346366/-.Non-Greek.and.Hybrid.Names.October2021.pdf)
[Δ- Non-Greek and Hybrid Names October2021.pdf](https://github.com/eXistSolutions/LGPN-ling/files/7346367/-.Non-Greek.and.Hybrid.Names.October2021.pdf)
[Ε- Non-Greek and Hybrid Names October2021 .pdf](https://github.com/eXistSolutions/LGPN-ling/files/7346369/-.Non-Greek.and.Hybrid.Names.October2021.pdf)
[Bibliographic References.pdf](https://github.com/eXistSolutions/LGPN-ling/files/7346373/Bibliographic.References.pdf)

.

**Comment by Hippodamie** [comment]
Here are the same files up-dated:
[Bibliographic References 2022-09-12.pdf](https://github.com/eXistSolutions/LGPN-ling/files/9542491/Bibliographic.References.2022-09-12.pdf)
[Β- non_Greek_names_or_hybrides_2022-05-26.pdf](https://github.com/eXistSolutions/LGPN-ling/files/9542496/-.non_Gre
[Γ- non_Greek_names_or_hybrides_2022-01-12.pdf](https://github.com/eXistSolutions/LGPN-ling/files/9542497/-.non_Greek_names_or_hybrides_2022-01-12.pdf)
[Δ- non_Greek_names_or_hybrides_2022-06-16.pdf](https://github.com/eXistSolutions/LGPN-ling/files/9542498/-.non_Greek_names_or_hybrides_2022-06-16.pdf)
ek_names_or_hybrid
[Ε- non_Greek_names_or_hybrides_2022-01-08.pdf](https://github.com/eXistSolutions/LGPN-ling/files/9542499/-.non_Greek_names_or_hybrides_2022-01-08.pdf)
es_2022-05-26.pdf)

**Comment by Hippodamie** [comment]
[Β- non_Greek_names_or_hybrides_2022-05-26.pdf](https://github.com/eXistSolutions/LGPN-ling/files/9542512/-.non_Greek_names_or_hybrides_2022-05-26.pdf)
