### ISSUE TITLE
[Filters]

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#635]
- [x] Etymological lemma

greek words from the ref. field where DELG is set

- [x] Lexeme Meaning

French or English meaning

- [x] Proper noun

all cases where lexeme value (not id) starts with a capital letter

**Comment by Hippodamie** [comment]
In which place in the list? Like that?
![image](https://user-images.githubusercontent.com/16923546/137328630-320c82b5-c0c6-4a23-a66a-8054915cafd4.png)

**Comment by Hippodamie** [comment]
Hi, Magdalena,

how are you?
I was trying to re-write the How to Search, but cannot in fact without the Search available by now.
But a question: why in the filter list to let Name ahead, since after you have the choice between Greek Name and Transliterated? Is it necessary? I do not think it is...
Thank you in advance for your answer,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Hi Sophie

![image](https://user-images.githubusercontent.com/449468/140040175-98922bde-24e8-4208-bc8e-4f266f4b2b6a.png)

Would it be helpful to rename the "Name" as above? At the moment we have 3 options for filtering by name:

* Name (any name form), including variant names
* Greek name - main Greek name form
* Transliterated - transliterated form of the main Greek name form

**Comment by Hippodamie** [comment]
Hi, Magdalena,

do we really need this generic filter?
Would it be possible and correct in your view to have variant names included into Greek name?
And just to have:
Greek name
Transliterated name,
Anyway variants are only accessible in Greek since we did not edit them in transliteration.

**Comment by tuurma** [comment]
I can change the behaviour very easily, just that the same label (Greek name) in sorting will obviously order by the primary version of the name, not the variants.

**Comment by tuurma** [comment]
Sorry to change, but I think that the default sort/filter should be called just Name, because it allows to search through any name form: Greek or transliterated and also through all the variants

Obviously when sorting, choosing "Name" will mean the primary version of the Greek name

![image](https://user-images.githubusercontent.com/449468/140045108-6e5f3262-6c17-4b61-8b5d-7a3cc348ee53.png)

**Comment by Hippodamie** [comment]
but then, we do not need transliterated anymore?

**Comment by tuurma** [comment]
Actually, you're right, it's not really necessary, at least not for filtering. Someone might still want to order by transliterated but I'm not sure it is a realistic scenario. I will remove it for now, 2 minutes to add it back if you later decide you want it.

**Comment by Hippodamie** [comment]
so we could have, only in sorting:
Greek name
Transliterated name?

Then, in filtering, only Name?

**Comment by Hippodamie** [comment]
Maybe rather keep Transliterated in Sorting.

**Comment by tuurma** [comment]
ok
