### ISSUE TITLE
[Facets] user interactions

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#636]
- [x] most logical order of facets
- [x] additional facets initially collapsed (e.g. S1-S4)
- [x] increase the max number of facets to 100? (*more* instead of *Top 50*)
- [x] remove the Top 50 checkbox when there are no more available values
- [ ] bug on hierarchical facets - when choosing top-level category, remove checks for siblings (or better allow for handling of OR queries on hierarchical facets)
- [x] last edited facet hierarchical year-month-day
- [x] keep the location after facet selection

**Comment by Hippodamie** [comment]
Suffixes are 52...
Only Lexemes may have to go up to 100 or the whole.

Could you please also rework also the stopping on the type of facet we are dealing with when we click (and not coming up back to another facet once we have clicked)?

**Comment by tuurma** [comment]
S1-S4 collapsed initially

![image](https://user-images.githubusercontent.com/449468/140056644-fb262e6d-5231-4b55-bab6-46516a445584.png)

![image](https://user-images.githubusercontent.com/449468/140056744-9b320a65-bf11-409a-b9d3-f985e50bd2ad.png)

**Comment by Hippodamie** [comment]
It looks great! Maybe rather: Suffix sequences
I did not understand your collapsed initially....

A question:  if we click on S2 (ί)δ 17, will number and suffixes automatically change in S1 according to this peculiar suffix?

**Comment by tuurma** [comment]
> A question: if we click on S2 (ί)δ 17, will number and suffixes automatically change in S1 according to this peculiar suffix?

yes, other facets automatically adjust to show only values for currently matched names

![image](https://user-images.githubusercontent.com/449468/140064097-0cae99d9-f372-4c13-aa96-960a434f37fb.png)

**Comment by Hippodamie** [comment]
facets are wonderful!

**Comment by tuurma** [comment]
I updated the server version but need to still work on facets so they don't "jump" when changing the selection and to make sure that collapsible facets stay open if the user has selected something in them.

**Comment by Hippodamie** [comment]
ok! Thank you!
