### ISSUE TITLE
False friends: not to forget write the indices/numbers to distinguish hιππο2 from hιππο

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#637]
Same for βοϝ vs βοϝ2     vs βοϝ3: 
3 false friends are very rare, but 2 are several.

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/137524957-89cac3ed-6628-4d26-bea6-fa2e5e5c7efa.png)

![image](https://user-images.githubusercontent.com/449468/137525254-d126ef86-609e-41a5-b964-b2a7b8bbfd2f.png)

**Comment by Hippodamie** [comment]
Hi Magdalena,

thank you for that. But could we please not see both right and lef forms on the line, but like hιππο and hιππο [2] or even hιππο2 like in the ID? Or do you need we edit the numbers at right as in the ID? But we would see them in the table, which would be quite badlooking for users…!
(Maybe it was only for example, but they are really βοϝ, βοϝ2 and βοϝ3).

**Comment by Hippodamie** [comment]
Thank you anyway!
Best,
Sophie

**Comment by tuurma** [comment]
Ok, just added the index in []

![image](https://user-images.githubusercontent.com/449468/137530610-5e498611-84e8-4706-9263-16942ee3e3a1.png)

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/137531059-828ed476-c0a6-4c09-be37-e8bfe84c70ac.png)

**Comment by Hippodamie** [comment]
ok I think it will work like that.
