### ISSUE TITLE
Volume of datas: currently around 25543

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#638]
Dear Magdalena,

I forgot to inform you that we are arrived to 25 543 (the number we see, but with variants, it must be quite more), which is like the end. We will stay around 26 000.
We are almost done (but only primo-edition: to correct everyday, since we had to work too quickly and let errors). 

There will be in the future new names added to up-date (every year, we could have around 100 or exceptionally 200 more, among especially variants).
So we will not in the near future reach 30 000 names, except if we had the aim to expand the project to include also names in other languages. But I think it would be another project in fact.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
Congratulations! To you and the whole team, great effort and well done to you all!

**Comment by Hippodamie** [comment]
Thank you!
