### ISSUE TITLE
Be careful: Segmentation does not let see every letter of the name. It is normal !

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#64]
For example:
 Ἀγασι-κράτης: R1: αγα R2 κρατ. It is normal if -σι- does not appear in the segmentation.

Ex. 2: Ἀγασίας: segmented : R1 : αγα S4: ίας.

Βest,
Sophie

**Comment by tuurma** [comment]
yes, thanks
