### ISSUE TITLE
Headedness classification (was: Puzzling small dash)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#642]
Hi, Magdalena,

do you remember in which  cases (how many) among Classification facets we got the small dash for which I told you I should fin a clear label...
I would like to think about it.
Was it only, if I remember, for truncated we got this probelm or were there others cases?
Thank you in advance for your answer and many thansk for all.
Have a good week-end, a good preparation of you teaching in Berlin!
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
In fact, it was when I asked to change the Classification taxinomy into:
Compound:
-whole
-truncated
Simple:
-original
-shortened compound.

I think that the short dash came in the previous configuration when were mixed both truncated and shortened compounds. It came because there were no X, Y but 1 functional label + Abbr.
So maybe in the improved taxinomy we did together, the problem will be solved by itself.

**Comment by tuurma** [comment]
Dear Sophie,

the dash was representing the situation where no headedness information was present. It is now quite rare for Compound names but rather common for simple names. I could easily change the '--' into a label easier to understand.

![image](https://user-images.githubusercontent.com/449468/139848125-1f59f871-662b-420c-9c9d-15717628cea9.png)


* Compound
  * truncated: 1 case  Κλεόμη http://apps5test.existsolutions.com/exist/apps/lgpn-ling7/index.html?facet-classification=compound&facet-classification=truncated&facet-classification=--
  * whole: 13 cases  http://apps5test.existsolutions.com/exist/apps/lgpn-ling7/index.html?facet-classification=compound&facet-classification=whole&facet-classification=--
* Simple
  * original: 8516 http://apps5test.existsolutions.com/exist/apps/lgpn-ling7/index.html?facet-classification=simple&facet-classification=original&facet-classification=-- 
  * short. compound: 1602 http://apps5test.existsolutions.com/exist/apps/lgpn-ling7/index.html?facet-classification=simple&facet-classification=short&facet-classification=--

**Comment by Hippodamie** [comment]
Dear Magdalena,

thank you very much.
But I do not understand why there are others items than the dash under ‘Simple’ ‘Original’. There should not be...
Could you please give me links towards names corresponding to: X, Y, YX and XY under ‘Original’? I should check.

If there are actually wrong editions and we delete the X, Y labels of those 45+94+61+362 names, and if thus there are only the names with the dash, then we would just need the ‘Original’ category and no sub-category to this peculiar label.
Thank you in advance for links towards those unexpected current subcategories.
Helene Jouguet does still not answer (in France there are 2 weeks vacations at school: is she in vacations?)
Good evening!
With all best wishes,
Sophie

**Comment by Hippodamie** [comment]
could you please work on that subject... if you have enough time?
For example could you find for me some examples among the 362 YX?
Because it looks like a mess: something must be wrong.
Simple Original should be names without XY and without Abbr.

**Comment by Hippodamie** [comment]
Simple names resulting of shortened compounds have:
always Abbr + 1 functional label like V and sometimes X or Y.

Truncated compounds:
always Abbr + 2 functional labels + XY or YX

Original simples have:
1 functional label alone. No X or Y. It could happen they have Abbr but very rarely.

Whole compounds have:
2 functional labels
no Abbr or only very rarely
XY or YX

**Comment by tuurma** [comment]
I will synchronize data from our current system to the test server so you will be able to see for yourself. It will take about 1 hour though, because reindexing the database takes time. I will let you know when it's ready.

**Comment by Hippodamie** [comment]
Thank you. I leave around 5. But be there after dinner.
Best,
Sophie

**Comment by Hippodamie** [comment]
I meant: I will be there after dinner!

**Comment by Hippodamie** [comment]
Finally, just to let you know in case it is useful for you and in case you work, I will not work tonight.
Best,
Sophie

**Comment by tuurma** [comment]
Wish you a nice evening! I will have to stop my work on Ling until Friday now but I uploaded newest data to the test server and you can use Classification facets to check the suspicious names, e.g. Simple names, not shortened but with X http://apps5test.existsolutions.com/exist/apps/lgpn-ling7/index.html?filter=&filterBy=name&facet-classification=simple&facet-classification=original&facet-classification=X

**Comment by Hippodamie** [comment]
Many thanks for all, dear Magdalena,
have nice following days.
I will do it tomorrow and will, when necessar,y write about it on Git.
With all best wishes,
Sophie

We keep up-dated about Helene Jouguet, as soon as she answerts. Vacations end in France on Sunday. People will come back at work the 8th, I guess. It is incredible how many people left Paris for those school vacations. As if they absolutely need to leave the city (a secondary effect of the pandemy and lock-down).

**Comment by tuurma** [comment]
Looking at some of the names, I can see clearly suspicious cases, e.g. Hagylidas has nothing in Root2 except for Abbr mark http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/editor.xhtml?id=Hagylidas

I prepared a script to detect some suspicious cases, you can check the list of names without the lexeme set but with other checkboxes (Abbr or Function etct) http://clas-lgpn4.classics.ox.ac.uk:8080/exist/apps/lgpn-ling/tools/suspiciousNames.xql

Fingers crossed for HJ!

**Comment by Hippodamie** [comment]
Dear Magdalena,
thank you very much for the script: yes, it is a list of mistakes in edition, where Abbr for example was put without Root 1 lexeme  and the lexeme was edited without Abbr in Root2... So we will correct that those following days.
Best,
Sophie

**Comment by Hippodamie** [comment]
2)There are also some foreign names like Abazion, Abauchas etc., that we are not supposed to edit and that do not have to be searchable... But they have been edited for some reason (their suffix only makes them Greek).
What I would say for this type (foreign names): they have only a functional label + a suffix 1. I do not think that we have planed to be able to search those 2 only. So, I guess nobody will find them, and it is not a problem!
Or what kind of trouble could you see?

3) There are also hybrids, like Alexarthos or Albēdōn, with a Latin Root 1 (so we edited the Constituent αλβ, but no root since it is not Greek).
Those are whole compounds. So if we search for the root1 or 2, we will get them. And it is enough. Or we will find them by Gr-Latin or Gr-Iran or Gr-Thr. labels.

4) Finally we have also the case of Timagētos, where we did not edit the root 2, since the form is totally incertain: so we edited it so that the LGPN entry has its equivalent in LGPN-ling, but decide not to edit the root2.

But I confirm that for the most of the names of this list, there are mistakes left to correct.

**Comment by Hippodamie** [comment]
I am now checking Simple, Original, X and AgtN.
I do not understand the presence of some compounds in this list: for example Koroibos, which is a whole compound; Myropnous is a whole compound too, Abdareta, . How is it on this list.

5) it happens we edit  NY without the lexeme, since we are sure it would be such but are not able to identify the lexeme in question, like for Kresphonthēs. Βut it is a full compound, since there are for this name YX NAgtN.

6) There are names with 2 hypotheses, as Palōn: one analysis is AgtN X Abbr, and the other is original simple (juste the label N).

7) eurèka! I understand: I forgot to explain in taxinomy that Prefix + Root 1 or 2 give also whole compound. Those have to go with  whole compound. Like Pronomos, Abrakos.

Next tomorrow afternoon. Taxinomy to precise again a little.
Best,
Sophie

**Comment by Hippodamie** [comment]
Synthesis:
1) Original simple would be by default:
only 1 Lexeme or Prefix + 1 functional label like V, Pro, N Adj VAdj Agt N. Nothing else. But it could happen there will be 2 hypotheses, and the other one sometimes will belong to the following type2.
2) Shortened compound:  only one Lexeme or Prefix+ 1functional label+ 1Abbr. (and sometimes X or Y).
3) whole compound: 2 Lexemes or 1Prefix+1Lexeme+ 2 Functional labels+ XY labels
4) truncated compound: 2 Lexemes or 1Prefix+1Lexeme+ 2 Functional labels+ XY labels+ 1Abbr or rarely 2 Abbr.
Is it enough like that?
Good night,
Sophie

**Comment by Hippodamie** [comment]
Names of the facets to change:
Change Lexicon into: Lexemes/Fr. Lexèmes
Change Lexemes into Root/Fr. Bases.
And at the top of the table: change Lexemes into: Roots.

I am still improving the taxinomy and checking it. Try to finish this week-end..
Best,
Sophie

**Comment by Hippodamie** [comment]
2 more questions+ the improved taxinomy:
1) it seems that the term ‘Base’ be usable both in English and French, So could you please finally set Bases in both languages instead of Roots, everywhere and  at the top of the table of names?

2) Could a name like Peitharatos (=with 2 hypotheses, the one YX NVadj, the other XY VN) be searchable both as YX and as XY?

I hope the categorisation taxinomy will be clear for you. I worked a lot on it, and it seems it is now quite perfect... at least, I hope so... But tell me what you think about it. 

I must say: the search you created is GREAT! All my congratulations about it!
But we will have a lot to do to correct all editions according to the taxinomy (I should have had time to do a long time ago)... but there was so hudge work to do in the same time.
[Improved taxinomy version Magdalena 8 nov2021.pdf](https://github.com/eXistSolutions/LGPN-ling/files/7493101/Improved.taxinomy.version.Magdalena.8.nov2021.pdf)
With all best wishes and so many, many thanks,
Sophie

**Comment by Hippodamie** [comment]
Here is my last version of Taxinomy, the only one to consider!
What do you think about it?
Many thanks in advance.
With all best wishes,
Sophie
[Improved taxinomy last version Magdalena 8 nov2021.pdf](https://github.com/eXistSolutions/LGPN-ling/files/7495101/Improved.taxinomy.last.version.Magdalena.8.nov2021.pdf)

**Comment by Hippodamie** [comment]
I come back again, for the category of Simples B.1., labellized as for example PartXAbbr Menousa or VAdjXAbbr Ainetos, 
I changed, if possible, those into: PartXAbbr(Conv) or VAdjXAbbr(Conv), with Convers. in parentheses, which means optional:
the problem is that for thoses names especially among B.1., the same name Ainetos, according to the person who bears the name, will have to be interpreted sometimes as VAdjXAbbr, if his father is called Eu-ainetos; sometimes as a simple conversion of the VAdj of the Lexicon= VAdjConv.
That is why I tried to improve the label of the previous version, adding here the (Conv).
So, I attache the new version with this only change.
Sorry, but one of the major difficulties about personal names is that for the same name,depending of the person, there could be several analyses, which means they belong to 2 categories: they could be both XAbbr and Conversion. 
Have a nice day, thank you for all.
best,
Sophi
[Improved taxinomy last version Magdalena 8 nov2021.pdf](https://github.com/eXistSolutions/LGPN-ling/files/7495939/Improved.taxinomy.last.version.Magdalena.8.nov2021.pdf)
e

**Comment by Hippodamie** [comment]
Last modification concerning the (Convers.) I added. Lookt at foot-note 3, which I rewrote.
It explains why we have to keep X or Y label for B.1., even if it is in fact obvious: it is the only way to be able to fliter
Menousa PartXAbbr(Conv) different from: Algoumis PartAbbrConv.
Thank you for your patience! It is really the end. I promise!
[Improved taxinomy last version Magdalena 8 nov2021.pdf](https://github.com/eXistSolutions/LGPN-ling/files/7496238/Improved.taxinomy.last.version.Magdalena.8.nov2021.pdf)
Best,
Sophie

**Comment by Hippodamie** [comment]
Mea culpa: sorry again.
It seems we have it.
Originals has come back as title of category B.2.
And I gave precisions about label Conv. presence or absence, and the fact that derivatives are not labellized with that label.
The main types and sub-types are there. I think that now, changes will not change anything for what you build: only sometimes for our editions.
So here is the last version you need to work.
Thank you for all and your patience.
Have a nice week,
best,
Sophie
[Improved taxinomy last version Magdalena 8 nov2021.pdf](https://github.com/eXistSolutions/LGPN-ling/files/7496539/Improved.taxinomy.last.version.Magdalena.8.nov2021.pdf)

**Comment by Hippodamie** [comment]
Dear Magdalena,

please, wait a little more.
We still work with the team and we try to simplify the part B. (simples).
It will be ready, I guess tomorrow, in the afternoon (at the latest).
With all best wishes,
Sophie
