### ISSUE TITLE
Changing the Dialectal double label Theran/Cyrenean into: Theraian

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#643]
Dear Magdalena,

I hope your teaching week was an enriching experience.
Could you please change it into Theraian (not Theran)?
I forgot to ask it but we need it for a long time!
Many thanks in advance.
Have a good week-end,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
No problem, done

![image](https://user-images.githubusercontent.com/449468/138553586-7d7aad86-4c6e-4d8c-91e4-1d9b5b037eb7.png)

Great week in Berlin, I also discussed steps to move LGPN-Ling to Huma-Num with my colleague Joern and we'll be running some tests in the beginning of November to be ready to move on 15th

**Comment by Hippodamie** [comment]
Dear Magdalena,

no it was not exactly that I was asking for: it was really to change the double into the simple: Theraian. Since we are supposed to have removed all Cyrenean Names under the simple Cyrenean label. So we would like now all the rest would be labellized only: Theraian. And if some are both we will clik then on the 2 simple labels. We would like them separate.
Do you understand?
Thank you for your help,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Thanks, I understand. How should it be in French? Google translate says théréen but please confirm.

**Comment by Hippodamie** [comment]
Hi, Magdalena: congratulations! Théréen, very well! Thank you! envoyé : 26 octobre 2021 à 15:51de : Magdalena Turska ***@***.***>à : eXistSolutions/LGPN-ling ***@***.***>cc : Hippodamie ***@***.***>, Author ***@***.***>objet : Re: [eXistSolutions/LGPN-ling] Changing the Dialectal double label Theran/Cyrenean into: Theraian (Issue #643) Thanks, I understand. How should it be in French? Google translate says théréen but please confirm.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
