### ISSUE TITLE
Logos to add to the interface

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#646]
Dear Magdalena,

here are the logos to add to the interface. The order could be: IUF; Ecole pratique; ANHIMA; ANR, then Oxford last, at right.  But it must also look the best: difficult for me to figure out!
Many thanks in advance
With all best wishes,
Sophie
![Logo EPHE-PSL noir](https://user-images.githubusercontent.com/16923546/140301122-d5e8b93e-0d42-484a-b348-10d978663b5f.png)
![ANHIMA-logo-couleurs1](https://user-images.githubusercontent.com/16923546/140301198-73792ec5-6b4a-4c76-a2cb-0d056ca86428.jpg)
![label ANR bleu CMJN](https://user-images.githubusercontent.com/16923546/140301258-ccc960a7-d92b-41e8-b937-76e795e8bd6d.jpg)

![image001](https://user-images.githubusercontent.com/16923546/140301294-12b51300-dbf7-4fae-982c-58f2d189056d.png)

![image001](https://user-images.githubusercontent.com/16923546/140301978-69713ce2-5a2f-4703-bf40-41e05745487c.png)

**Comment by Hippodamie** [comment]
Sorry, I forgot Oxford (and gave IUF twice), for which here is the link Robert gave me this morning:

https://en.logodownload.org/university-of-oxford-logo/

**Comment by Hippodamie** [comment]
In fact change please IUF into this one:
![Logo IUF](https://user-images.githubusercontent.com/16923546/140302505-2e4b824d-ff02-4c9b-8f8e-dc7b7744962b.jpg)

**Comment by Hippodamie** [comment]
Thank you!

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/150143426-ceceb6b9-b544-467b-9cb7-f10b484ccb1a.png)

**Comment by Hippodamie** [comment]
very well!
