### ISSUE TITLE
Transformation of the label Deloc. into Depron.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#648]
Dear Magdalena,

could you please transform the Deloc. label in Complex Structuration into: Depron?
I think we never used Deloc. But we need the other.
many thanks,
best wishes,
Sophie

**Comment by tuurma** [comment]
There are 7 entries for Deloc. I added now Depron.

1
"Emautiōn"
2
"Kissō"
3
"Laprēnos"
4
"Krēthēïs"
5
"Ōpis"
6
"Opholōnidēs"
7
"Ouatillis"

**Comment by Hippodamie** [comment]
Great!
Thank you for all!
