### ISSUE TITLE
Νeeded : macron + brevis sign superposed, as you see below

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#65]
⏓ To be put on α, ε, ο, ι, υ in Roots.
For example: βολ would be perfect with rather than the only macron, ⏓ above the omicron.
For δο(ρ), αlso.
![capture d ecran 2016-01-30 a 14 08 52](https://cloud.githubusercontent.com/assets/16923546/12695874/54bfee48-c75b-11e5-9128-5ffcfebfc46e.png)

Many thanks,
Sophie

**Comment by edouardchiricat** [comment]
ō̆
