### ISSUE TITLE
New title for the column currently called Morphosyntax dealing with 2 different levels of informations

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#650]
Dear Magdalena,

how are you? Are they any news about the transfer on Huma-NUm?
In the new Search, could you please change the current Morphosyntax at the top of the column of the results table into: 
Morphosyntax (+Genetics)
It concerns Classification. Brackets mean this labellisation is optional depending of the personal name. Genetics = those following labels: Convers, Denom, Dev, Deadj, Phrasal and Clausal. They explain the genetic connection between lexicon and each personal name. As we have informations of 2 different levels (morphosyntax concern the form, genetics, the origin), the + is necessary too.
Have a nice week-end,
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
In fact, Morphosyntax is at the Prefix/bases level and Genetics at the PN itself level (=the result of the Morphosyntax).
So I would prefer to be a little more precise and give as a title;
Morphosyntax (+ PN Genetics). And in French... to be as short...: Morphosyntaxe (+ NP génétique). NP= nom de personne.
It is now perfect, don't you think so?
Thank you for that too,
best,
Sophie

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/150138589-d954bfb9-96bd-43ee-98c7-3ba4cb0a4d06.png)

**Comment by Hippodamie** [comment]
Hi, Magdalena,

Could you, please, make a little change into:
Morphosyntaxe = in bold
(+ NP génétique) in normal (not bold).
Many thanks,
best,
Sophie
