### ISSUE TITLE
New Editor

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#652]
Just not to forget:

Titles to change:
complex structuration into: PN Genetics
preroot into Prefix
lexical connections into: Lexical and Onomastical connections

Delete Z everywhere.
Under Prefix: only keep, I assume, Adv.

Add:
ProperNoun [PropN] (under Noun)
ProperAdj [PropAdj] (under Adj)

That is all.
Thank you for all.
With all best wishes,
Sophie

**Comment by tuurma** [comment]
There are 2 cases where Z is present:

Preuklētia and Prothoēnōr

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/150369918-3e67196e-66c1-4881-b4cf-6adbc41faa60.png)

**Comment by Hippodamie** [comment]
Looks well: thank you. I try to remedy to the 2 Z names, which have to disappear very soon!

**Comment by Hippodamie** [comment]
Done: no Z anymore!
Best,
Sophie
