### ISSUE TITLE
Logos: could they look smaller?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#653]
Dear Magdalena,

could we have the logos not so visible= smaller? Currently they are really to visible and take too many place.
Thank you in advance for fixing it.
Have a good week-end!
It was nice to see you.
With all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Could we, please, have the logos only visible on the bottom of the main page?
Thank you in advance.
Best,
Sophie

**Comment by tuurma** [comment]
They are now smaller and sticking to the bottom of the page

![image](https://user-images.githubusercontent.com/449468/150650973-efc66a04-05ad-4d5c-a957-bdb0f0d83db2.png)
