### ISSUE TITLE
Feed-back 3 (Classification)

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#656]
Dear Magdalena,

I think it is now perfect to revise maybe algorythms. I checked everything, especially looking the 2 most complex subcategories:
truncated and shortened compounds. Sorry if I made a mistake last Thursday about truncated.

I will have a look later in the afternoon at the way you already re-ordered facets, like Suffixes.

THANKS for your work!
Bon appétit!
Best,
Sophie
[Feed-back 2022_01_23 Classification).docx](https://github.com/eXistSolutions/LGPN-ling/files/7920333/Feed-back.2022_01_23.Classification.docx)

**Comment by Hippodamie** [comment]
Dear Magdalena,

would it be possible to add a sub-sub category? I mean among the Compounds shortened, could we please distinguish between
shortened
and
shortened derived?
I give you the updated same file with this addition (see Summary, in pink).
What you already did is GREAT (Genetics facet! which is combined with classification!)
THANK YOU!
Good night,
best,
Sophie
[Feed-back 2022_01_23 Classification with the addition.docx](https://github.com/eXistSolutions/LGPN-ling/files/7921425/Feed-back.2022_01_23.Classification.with.the.addition.docx)

**Comment by Hippodamie** [comment]
Others:

1) in my view, to delete:
![Capture d’écran 2022-01-23 à 22 09 16](https://user-images.githubusercontent.com/16923546/150698107-71c5c511-3c24-4450-a112-a5e260adf779.png)

2) Suffixes: to re-order into alphabetical order
![Capture d’écran 2022-01-23 à 22 09 32](https://user-images.githubusercontent.com/16923546/150698161-bb5ba029-4937-4d60-ad6c-26e38e4ef8d9.png)

3) Suffix1 and 2 (not 3, ok)  to re-order into alphabetical order
![Capture d’écran 2022-01-23 à 22 09 56](https://user-images.githubusercontent.com/16923546/150698172-41c3023b-b7e5-4db8-9bfc-ed0a94543460.png)

4) arrows to open or not, like for Constituants are perfect.

**Comment by tuurma** [comment]
Please let's continue this discussion but on Classification facet algorithm *only* in #658

**Comment by Hippodamie** [comment]
Here is the last version of feed-back on Classification with the additional sub-category of shortened Compounds.
I put it alos on #658.
Best,
Sophie
