### ISSUE TITLE
Re-ordering some of the facets lists. I will give you lists reordered on wednesday

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#657]
Dear Magdalena,

In fact, I will have to help you to re-order:
-Bases and Constituants: but maybe the only thing to tell is that when it begins with /h/ like (h)ιππος, we nonetheless sort it as if it began with the vowel, thus here with /i/. So hιππος has to go between θεο and κλεϝεσ.
Αnd for ϝ, it is exactly the same: so ϝανακτ will go at the place of ανακτ exactly as if it did not have an initial ϝ (but only in facets; do not change its place of course in the catalogue. So for that point nothing more, in fact.
Nota bene: a small bug on Constituants arrow: when I click on Constituants plus, I first get the whole closed; then if I click on the arrow, I get them all.

Other necessary reordering for which I will give the model:
**-functions which will have another logic than only alphabetical
-suffixes to reorder (the whole and the positional)**
-classification subcategories, I already gave the order.

So: in bold the priority of my ...homework... for wednesday morning!
Good night!
Sophie

**Comment by tuurma** [comment]
Please note that facets are showing the most frequent items and these are usually ordered alphabetically. I don't think it makes a lot of sense to spend a long time tweaking this order in most cases. I can make certain adjustments to ignore influence of parentheses in suffixes but I do not think it makes any sense for functions.

**Comment by Hippodamie** [comment]
Ok. We keep as it is.

**Comment by Hippodamie** [comment]
Dear Magdalena,

please, note that in Genetics facets
Clausal
Delocutive
Depronominal
are missing.
Could you, please, add them?
Thank you for that too.
Best,
Sophie
