### ISSUE TITLE
Classification facet

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#658]
* Complex
  - primary / primaires
  - derived / dérivés
  - truncated / tronqués
  - shortened / raccourcis
* Simple
  - primary
  - derived 
  - truncated

**Comment by Hippodamie** [comment]
I send it also be email, if you do not like word file on this Git-Hub.

[Feed-back 2022_01_23 Classification with the addition.docx](https://github.com/eXistSolutions/LGPN-ling/files/7926995/Feed-back.2022_01_23.Classification.with.the.addition.docx)

**Comment by Hippodamie** [comment]
Ordering and vocabulary are:
![image](https://user-images.githubusercontent.com/16923546/150830662-ab5c28e7-01a3-4cc9-8ed4-5b653a1125c4.png)

**Comment by Hippodamie** [comment]
Here is the most important of the word file supra (Classification with the addition
![image](https://user-images.githubusercontent.com/16923546/150830825-49e296fd-f690-4486-bb69-d8d3984252dc.png)

**Comment by Hippodamie** [comment]
Here is the whole word file:
![image](https://user-images.githubusercontent.com/16923546/150831163-561df51b-5044-4fee-950a-3f07281d61d7.png)

**Comment by Hippodamie** [comment]
No: it did not work: only a part of the word file has come.
I try again for what follow:
![image](https://user-images.githubusercontent.com/16923546/150831593-e128a4cc-c763-40a6-b07a-8fb81d85ac95.png)

**Comment by Hippodamie** [comment]
![image](https://user-images.githubusercontent.com/16923546/150831790-16c4099d-6d07-4784-a517-1b54e2059195.png)

**Comment by Hippodamie** [comment]
In conclusion: thy were troubles in sorting especially among Compounds between truncated and shortened; I ask for creation of a last category I had forget and that could explain troubles: the derived of shortened, see Summary. I put in pink what is the only difference between shortened and shortened derived. The blue and pink highlight what is discriminant from one category to the other.
Thank you in advance,
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

I paste the new scheme for the algorythms for Classification: I found an error but now I am pretty sure to have found the better way to distinguish each of the the subtypes from the others!
You will see with colours and the legend again the schema I pasted supra, with in pink what I corrected. Then I wrote whitout colours at the end, the better way to rewrite the algorythms, with the only elements distinctive to keep.
I think we definitely get it! What is your opinion?
Have a nice trip if you travel,
with all best wishes,
Sophie

![image](https://user-images.githubusercontent.com/16923546/151407123-1d32d568-4c4b-4a40-8a40-f3f664b04044.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

in fact what I wrote under 1) just above is to understand: I think that suffix has not to be taken in account by you to build the algorythm; but on the other side, for us who edit, I must say that truncated names are supposed to have all a suffix.
Best,
Sophie

**Comment by Hippodamie** [comment]
Sorry: the repetition fo X and X is an error for of course X and Y (see above abour Primary Compounds and Derived compounds).

**Comment by Hippodamie** [comment]
Dear Magdalena,

 a last little improvement of the Classification scheme.
With all best wishes,
Sophie
[Mode d'emploi simplifié Classification 20June2022 .docx](https://github.com/eXistSolutions/LGPN-ling/files/8938722/Mode.d.emploi.simplifie.Classification.20June2022.docx)

**Comment by tuurma** [comment]
## Classification still simplified  20 June 2022

* Compounds/Composés ([X and Y]  et  [X or Y])
  - primary/premiers =   XY + 2 labels fonctionnels                                          (no Suff, no Abbr.)
  - derivated/dérivés    =   XY + 2 labels fonctionnels   + Suff                              (no Abbr.)
  - truncated/tronqués  =  XY   + au moins 1 label Fonct. + au moins 1 Abbr + Suff.
  - shortened/raccourcis = X ou Y  + 1 label Fonct  + 1 Abbr       (no suffixe;genetic  label or not).
  - shortened derived/dérivés de raccourcis = X ou Y + 1 label Fonct + 1 Abbr + Suff.
* Simples (no XY) 
  - premiers = 1funct. label              + 1 label génétique [Conversion]         (no Suff, no Abbr.)
  - dérivés    = 1funct. label + Suff   + 1 label  génétique [Dénom. etc.]      (nos Abbr.)
  - tronqués = 1funct. label  + Abr. + Suff.



N.B.: suffixe = box S1 crossed

**Comment by tuurma** [comment]
@Hippodamie 

Dear Sophie, could you please review the algorithm below. I think I took into account all your remarks.

![ling](https://user-images.githubusercontent.com/449468/174802894-1c6bffc3-126e-418a-bd2f-31708f99d13a.jpg)

**Comment by Hippodamie** [comment]
Dear Magdalena,

are you aware that in the scheme below, in my version, I had crossed out:
+ 1 functional label for the following cases:
- shortened/raccourcis
-shortened derived/dérivés de raccourcis

since it is possible but not necessary.
Now, I try to understand your tree, if really it takes in account my 2 crossed out of yesterday.
Could you please confirm that point?

**Comment by tuurma** [comment]
I confirm that Compound/Shortened and Compound/Shortened derived *may* have a functional label but *do not have to*.

**Comment by tuurma** [comment]
But please have a look at Antikion: it does have 2 functional labels and a suffix, so should be a Compound/Derived but it also has an Abbr, which means there's something missing in the categorization.

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/449468/174812140-2990601d-cef1-4a09-8d24-aa79aab20429.png">

**Comment by tuurma** [comment]
Also look at Amphinnes: no X or Y, so technically simple but then it has 2 functional labels...

<img width="1361" alt="image" src="https://user-images.githubusercontent.com/449468/174814563-bc88def5-e669-4658-a00f-93e372591150.png">

**Comment by Hippodamie** [comment]
This one is a truncated: so the categorization is ok, no?
     truncated/tronqués  =  XY   + au moins 1 label Fonct. + au moins 1 Abbr + Suff. 1

**Comment by tuurma** [comment]
Ah, ok about Amphinnes. What about Antikion?

**Comment by tuurma** [comment]
How about I reindex with the new algorithm and you can review then if it makes sense looking at real data? I think I have it ready.

**Comment by Hippodamie** [comment]
I do not understand what you mean: there are 2 hypotheses (and what seems a bug on the second one [since we see 2 αμφι + αμφ]).
The first hypothesis is allright: we have a truncated compound, with YX Abbr.
The second one wiil have  to be corrected: it is a shortened of compound with only Y, no X.

**Comment by Hippodamie** [comment]
I just answered about it.

**Comment by Hippodamie** [comment]
No, please. I was writing the improvement of your tree.
Just a few minutes more

**Comment by Hippodamie** [comment]
Dear Magdalena,

about the tree:
1) Simples: it seems it is right, but why having set abbr AND suff at first (whereas this Truncated category is especially rare) and not rather:
-Suffix yes: then choice between Abbr (Truncated) and no Abbr (Derived), vs no Suffix (Primary).
I mean Abbr at the end of the rather rather than in the middle.
But maybe you could tell me that it does not change anything for the results.

2) Compounds part of the tree: something is wrong.
Could you please put as first choice, not "2 funct. labels” but X AND X; then:
- choice between yes or no.
a) yes side: suffix and yes Abbr (Truncated) vs Suffix and no Abbr (Derived) ; or no Suffix (Primary)
b) no side:  Suffix yes (Shortened derived) vs suff no (Shortened).

Could you please remake the tree in such a way, send it to me, so that I can check a last time, and then if I say ok, you could implemnt?

Sorry: I am in bad conditions out of my office and cannot rewrite myself the tree and scan.
Thank you for your help,
best,
Sophie

**Comment by tuurma** [comment]
About Simples: order of the algorithm doesn't change anything for the results.

Rewritten tree for Compounds below:

![ling](https://user-images.githubusercontent.com/449468/174822570-0fc73f51-0436-4494-88a4-64dffa85e04f.jpg)

**Comment by Hippodamie** [comment]
Sorry the second hypothesis show a derived of shortened.

**Comment by tuurma** [comment]
I did rework the Simple as you suggest because it is indeed clearer to understand. Thank you!

![lingSimple](https://user-images.githubusercontent.com/449468/174824929-66c4efb5-70c6-49fb-9912-0ce2f4e39eab.jpg)

**Comment by Hippodamie** [comment]
It seems it works, but I still does not understand the logic of this part:
Suff and Abbr: No; and then Suff yes or no.
Is it not contradictory? Same question as previously, I guess

**Comment by Hippodamie** [comment]
Wonderful, so maybe, improve Compounds too, because another point I cannot understand is the first X or Y, followed later  by X and Y? Is it coherent and not a too long way if built in this order?

**Comment by tuurma** [comment]
And following on that, I will also replace the part of algorithm that determines  Truncated/Derived/Primary in Compounds.

But determining between Simple and Compound I need to first check if there is at least 1 X/Y label (if not, then it's a Simple) and then check again if I have 2 or not. It is not a problem and I only do it at indexing time, not every time you make a query.

**Comment by Hippodamie** [comment]
ΟΚ, I understand! It seems to me all is ok. So you can go ahead!

**Comment by tuurma** [comment]
Here with a final diagram, may be useful for us later. I think it's nice and clear now and also easy for me to implement which is a good sign usually that we have it conceptually sound.


<img width="1384" alt="image" src="https://user-images.githubusercontent.com/449468/174831240-454b3615-e2e9-41b7-911a-4ae7474ce070.png">

**Comment by Hippodamie** [comment]
It looks perfect.
There is nonetheless something I must tell you, but at this hour I do not have time enough to think about it more:

in fact, I must confess the system as used by us editors is a little more complex, but that I do not know if it is compatible with your tree.
In fact, some PN are both Simples and Shortened, and it is true also for the Simple derived and Derived of Shortened.
For example, see Polemos, POlemidas and Ainetos and Ainetides.
Look at the way we labellized them. In fact, we mean that they are both by using theadditional  so-called Genetic labels Convers., Denom and Deadj.
I mean that when you see both YAbbr or XAbbr + Convers or Denom or Deadj, it means that we have this indecidable category (being both means that we cannot in fact decide between the one and the other).
What to do with those names?
Can it find its place in your perfect tree or not?

**Comment by Hippodamie** [comment]
In fact it is like create a new category, which would have to be built as such:
Both simple and Shortened (=Simple or shortened): X ou Y + Abbr (+ Suff) + Conv. or Denom or Deadj

**Comment by tuurma** [comment]
Ainetos would now end up as `Compound > Shortened`. Our tree is based on the assumption that a segmentation hypothesis is either of a `Simple` or `Compound` name, but not both. I could introduce another category at this level, therefore:

* Simple
* Compound
* ??? (I don't know how to call it)

At this point, I'd suggest we wait until the indexing finishes (so far it only processed 1/4 of all the names) and you can review it tomorrow. Then you can decide what we should do. It's okay for me to rewrite the algorithm but we need to be certain what we want to achieve.

**Comment by Hippodamie** [comment]
all right. We do as you propose.
The third category would be called:
Shortened Compound or Simple. But has been labellized as if it was Shortened Compounds +  [Conv or Denom or Deadj]

It is like to introduce a new variable  [Conv, or Denom or Deadj], that would connect at the bottom of your tree: Shortened derived (Compounds) and Derived (Simples) and Shortened (Compounds) and Primary (Simples).

I think about it tonight and reviewing your implementation tomorrow morning.

Thank you for your patience,
all best,
Sophie

**Comment by tuurma** [comment]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/449468/174991020-d9fbfcee-f272-4773-a3ca-bf524b706721.png">

**Comment by tuurma** [comment]
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/449468/174993473-5ca884aa-57ca-4b86-aca7-16ca8eaa5060.png">

**Comment by tuurma** [comment]
I can adjust classification to this scheme. What I think it shows is that while "proper" Compounds and Simples are conceptually clear and their subcategorization into Primary, Derivative and Truncated is also neat and consistent, the Shortened category lacks similar clarity. Guess this is exactly what makes it interesting to research ;-) Perhaps, in time, you notice how we could restructure or improve this part, it will be relatively easy to do.

**Comment by tuurma** [comment]
<img width="242" alt="image" src="https://user-images.githubusercontent.com/449468/175023258-f4ee27b6-e40d-427a-a5e6-9f6797b10fcb.png">

<img width="235" alt="image" src="https://user-images.githubusercontent.com/449468/175023419-5ce5d5e8-9691-4e78-926b-48bba1a462a5.png">

**Comment by tuurma** [comment]
Now with requested ordering

<img width="236" alt="image" src="https://user-images.githubusercontent.com/449468/175025799-73dc38d1-823b-48bc-9c7d-3a9f40fcdfe0.png">

**Comment by tuurma** [comment]
Just to let you know I am currently reindexing the data, so search at the moment may return only partial results. All should be back to normal in about 1h

**Comment by Hippodamie** [comment]
Dear Magdalena,

note that it is ‘premiers’, not: ‘premiérs’, thank you!
Thank you for reindexation in progress,
best,
Sophie

**Comment by Hippodamie** [comment]
Yes, many thanks for the pretty diagram: it is a research in progress. The ideal would be at the end... to be able not to have any need of these Undecidable categories. 
When do you think you could implement this final version?
Many thanks,
all best,
Sophie

**Comment by tuurma** [comment]
<img width="242" alt="image" src="https://user-images.githubusercontent.com/449468/195047019-b5ecb632-f5e9-4d1a-bb04-a033bd06d4ae.png">

I have already changed the label to "premiers", please try Shift-Reload if you still see the incorrect accent.

I am not reindexing the database today, so you can work as usual. I am trying to figure out a better way to present facets, please see #702

**Comment by Hippodamie** [comment]
Dear Magdalena,

many thanks. What you propose seems very well (a detail in general: phantom has to come last, after fictitious).
I am busy at the moment, until 3 pm: so I will not work before, and maybe not Gerard.
With all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

GREAT! It looks very clear now!
Sorry not to have tell you directly but in French: fantômes, bilingues, genres need all a final plural /s/ like Fictionnels.
The other point is: we should not have plus, to completely extend the list and also for linked search criteria.
We should rather have now: all
and
more (like it is).
And in French: tout
and
plus (like it is).
Thank you for that too.
Best,
Sophie

PS: I guess you will add a Tm label, which would have almost the same status as GPR (but a link), thus added very near GPR

**Comment by Hippodamie** [comment]
A small bug in Suffix Total twice the same at the top.

![Capture d’écran 2022-10-11 à 15 49 45](https://user-images.githubusercontent.com/16923546/195109269-64a30bf8-9fef-4ad4-956a-46762c3a082c.png)

**Comment by Hippodamie** [comment]
How is that difference in Total possible, look at that (δίδωμι 90, but in facet = 89):
![Capture d’écran 2022-10-11 à 16 03 05](https://user-images.githubusercontent.com/16923546/195112656-f33e419d-4ab6-448a-81fd-63df624c2977.png)

**Comment by Hippodamie** [comment]
Dear Magdalena,

could we have a smoother navigation when moving from one search criterion to another?
Now if I filter by Etymological lemma, and then move to Name or Base, very often there is a bug: for example I type a Name, which appears in the list, but when I click on it, it gives no result. And I have to click on Browse to refresh, which takes time and which wastes the search which was started.
What would be great would be to switch from on type of search to other ones without any bug and without being oblige to refresh = to go out of the search started and to lose all previous steps.
Very often we would have to keep track of all the successives steps: how to do?

But I think we already partly discussed this subject, and maybe it is linked to the up-dated forthcoming ExistDb?

Best,
Sophie

**Comment by tuurma** [comment]
I removed headedness level for Simple names, so no longer this empty -- label to go through. I believe that Classification facet is now right and just as it should be.

**Comment by Hippodamie** [comment]
Υes, I think so. Thank you!
