### ISSUE TITLE
A quick question about the so-called suspicious names of the list you gave

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#659]
Dear Magdalena,

the suspicious names are often interlinguistic names like Greco-Iranian. We are supposed to edit no bases at all, but a Suffix1; or only one base (since one or 2 of them are not Greek).

Could it be a problem for the Search system if we edit those names without any Morphosyntax/PN Genetics labels (giving only comments in Onomastics column), like that example? Because if we edit only labels for one Base, the Classification will not be correct, as if they were Simples even if they are in fact Bilingual Compounds. 

Thank you for your answer.
Good evening,
best,
![Capture d’écran 2022-01-24 à 19 33 36](https://user-images.githubusercontent.com/16923546/150845948-95e2e615-fdbc-4f6d-b1c3-f99de00f9ad4.png)

Sophie

**Comment by tuurma** [comment]
Yes, it will be a problem for the search. I think we will need either:

* a checkbox like we have for "fictitious" or "GPR" to classify such names as "bilingual" and therefore exclude them from classification entirely (or put into separate "bilingual" category)
* a special *placeholder lexeme* e.g. "non-Greek" to use for each non-Greek base, then we could still count how many bases there are and put bilingual names into relevant category

We could also combine both approaches (the checkbox and special lexeme) which would allow people to include or exclude bilingual names as they wish and in the future to extend the database and connect the unedited "foreign" lexemes.

**Comment by Hippodamie** [comment]
Thank you to have answered as quickly.
I have to think about it a little.
Good night,
best,
Sophie

**Comment by Hippodamie** [comment]
How much time would you spend in the first case? And in the second?

**Comment by Hippodamie** [comment]
In fact, what we would choose will be the proposition checkbox, with its alternative= (or put into separate "bilingual" category), so that they are not excluded entirely from classification.
The idea would be to be able to keep edited the same example with all his XY VN labels, as it was.
Could it work?
<img width="810" alt="Capture d’écran 2022-01-24 à 21 49 38" src="https://user-images.githubusercontent.com/16923546/150862545-a7106f0b-39fe-4710-819a-f3f2764fd15c.png">

**Comment by tuurma** [comment]
> The idea would be to be able to keep edited the same example with all his XY VN labels, as it was.
> Could it work?

Yes, the rest would stay exactly the same, just one more checkbox to click. I would like to do the same for the phantom names, see below

![image](https://user-images.githubusercontent.com/449468/150965225-69d9a423-1cfc-42b3-a5a1-a83e081a5a79.png)
