### ISSUE TITLE
Readibility of the form of the 2 bases: not enough distant from each other. Could we save space at the Suffixes level?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#663]
Dear Magdalena,

a short note. I already spoke about that important problem: bases will be difficult for a lot of people, but if they are too close from each other and looking like only one item without separation between them, it will not be friendly at all. It happens especially when the base is quite long.
The solution I see to separate the 2 bases more is to save a little space in width at the level of the 4 suffixes, since the most often suffixes are only 1 or 2. Could you please tighten them all? And also write them smaller than the bases and Prefix?
Thank you.
Best,
Sophie
![Capture d’écran 2022-01-27 à 21 34 01](https://user-images.githubusercontent.com/16923546/151440233-02333ab2-e43f-4916-9dff-2398b906db6c.png)

**Comment by Hippodamie** [comment]
Last point:
the level of grey for the low hypothesis is a little too pale to be easy to read. It should be a little closer to the black of the high hypothesis.
Thank you very much,
good night,
Sophie

**Comment by tuurma** [comment]
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/449468/197720344-29140202-1617-4365-b92a-5365410e4fe3.png">
