### ISSUE TITLE
About contact for users

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#664]
Dear Magdalena,

to contact (me especially), I had put on the pages About, that:
![image](https://user-images.githubusercontent.com/16923546/151509988-c93205f0-8df6-4870-9f98-37447d930ed2.png)
But to get a feed-back or improvement proposed by people, maybe a better solution would be to get it by name, like on the site of AVI dir. Rudolf Wachter Basel, where there is a special link for each item which opens a dialog window, see screenshot.
Thanks you for your answer. No emergency at all.
Best,
![Capture d’écran 2022-01-28 à 09 02 32](https://user-images.githubusercontent.com/16923546/151510471-fd1ddd60-43e2-4c4a-833c-cf31da4e8a7d.png)

Sophie

**Comment by Hippodamie** [comment]
Not contact, rather Feedback: email.

**Comment by Hippodamie** [comment]
Hi, Magdalena,

what do you think about the way to get feed-backs? Maybe the way of a special box corresponding to each name woudl be better than to get directly emails? What is the most simplest and cheapest solution?

**Comment by tuurma** [comment]
Email would be by far simplest, anything else is likely out of budget for the moment.

Longer term, I would like the sources to be available on GitHub, so people could open issues for the data, like you do now for the application. Also this way people could even put in proposals for amendments which you could then accept or not.
