### ISSUE TITLE
Quote button for name instead of last updated facet

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#665]
Dear Magdalena,

why do we have the year of up-dating and statistics at the end of the facets? Who will need it? 
Don't you think it is enough to have, as it is, the most important= the very day when the name has been up-dated, especially to be able to quote, like:
link of the name + (2022-01-28)?
Have a nice trip,
best,
Sophie

**Comment by tuurma** [comment]
citation button now added, closing

**Comment by Hippodamie** [comment]
Sorry, it is on fact useful to keep it too? Is it still possible?
Have a good we, thanks for all, best, Sophie

**Comment by Hippodamie** [comment]
I mean useful only for us editors!
