### ISSUE TITLE
About Functions currently under Constituents: to move around the end of the facets, only available by arrow

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#667]
That facet is not interresting at all since what is very interresting is to get them through Classification, and through headedness for Compounds and (what is not currently the case), directly for Simples.

Thank you in advance,
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

that facet should take place under Classification, and only accessible by the arrow. Before Genetics.
Best,
Sophie

**Comment by tuurma** [comment]
<img width="244" alt="image" src="https://user-images.githubusercontent.com/449468/192017708-bd881f10-bd8d-47ea-9515-ce923e898547.png">
