### ISSUE TITLE
Modification of one suffix: current αινα because of the name Ηierakiaina

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#673]
Dear Magdalena,

could you please change the suffix αινα into: (ί)αινα
It is for the name Ἱερακίαινα Hierakiaina.
Many thanks in advance,
best,
Sophie

**Comment by Hippodamie** [comment]
I mean among Suffixes 2.
Thank you,
best,
Sophie

**Comment by tuurma** [comment]
Hierakiaina has     αιν as suffix 2, and it is used in 24 names in total, e.g.  Ποθαινίς / Pothainis
Would you like me to change all occurrences of it to (ί)αινα?

**Comment by tuurma** [comment]
You can see other names here https://lgpn-ling.huma-num.fr/exist/apps/lgpn-ling7/index.html?facet-suffix2=%CE%B1%CE%B9%CE%BD

**Comment by Hippodamie** [comment]
You are right: do not do anything:  WE are wrong!
Thank you!
Best,
Sophie
