### ISSUE TITLE
A more important space between the 2 Bases/Roots in the tables

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#678]
Dear Magdalena,

as I already told you, the 2 roots/bases are often, especially if they are quite long, so close the one from the other that it is difficult to read and to distinguish. That is not friendly for any kind of user (linguist, historian or everybody else).
How could we improve the visualization of them?
I know you are aware of the problem and already tried to improve by gathering some informations in the same column.
Anyway, suffixes are really less important and very often not more than 2: they could be smaller and be more close from each other. The most important is to clearly separate the roots/bases.
Τhe idea  cannot to add a dash to clearly cut between them. No addition.
Could Prefix be put closer to Dialects, and then Base1, closer to Prefix and thus, not so close to Base2? And/Or even be a little smaller, as Prefix, as the Bases themselves?
Thank you for what you can try for that.
With all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Same visual subject:
could we have for the column Morphosyntax (PN Genetics):
1. Morphosyntax not in bold; PN Genetics as it is = bold, exactly as currently are the results in the column. The whole in a little smaller size (not only title but also content of the column).
The aim is clarity but also gain of space in width.
Thank you.
Best,
Sophie

**Comment by tuurma** [comment]
I introduced the toggle button to hide/show references columns, which helps with the space.

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/449468/197737823-21e05b83-8d05-4966-b679-57e604281422.png">
