### ISSUE TITLE
Page on which the site opens: rather directly browser

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#679]
Rather than the opening on the pages About LGPN-Ling, please, could you make open it directly on the browser?
Thank you in advance (not only for us but for the future user),
best,
Sophie

**Comment by tuurma** [comment]
I will do that in the future, but for the moment it has to open on "About..." page because users who are not yet logged in cannot see any other page

**Comment by Hippodamie** [comment]
Of course!
