### ISSUE TITLE
Position of the Genetics labels like Conversion

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#681]
Dear Magdalena,

how are you?
Could we, please, have a change in the position of the Genetics labels (Conversion, Denom. etc.): they have to be the last of the column. I mean, they have to come after the linked compound (which is itself optional).
See the example of the name Isiades; Denom has to come after the linked compound Isidoros.

Thank you in advance for that.
Have a nice Easter you and all your family,
with all best wishes,
Sophie
![Capture d’écran 2022-04-13 à 21 28 37](https://user-images.githubusercontent.com/16923546/163256609-b7c9db41-2457-4fd2-96ff-5dc545887638.png)

**Comment by tuurma** [comment]
<img width="190" alt="image" src="https://user-images.githubusercontent.com/449468/191981505-68b940fc-9daa-4edd-af4e-af20bfce63a2.png">

**Comment by Hippodamie** [comment]
Wonderful!
