### ISSUE TITLE
Up-dated files for: How to Search; Project( About; Team); Bibliographies.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#683]
Dear Magdalena,
here are the up-dated files to download or to edit.
I re-wrote and simplified a lot About LGPN-Ling in comparison with the current version
[ABOUT LGPN-Ling English May2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8693006/ABOUT.LGPN-Ling.English.May2022.docx)
[About LGPN-Ling French version May2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8693007/About.LGPN-Ling.French.version.May2022.docx)
[Bibliography  English version May 2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/8693008/Bibliography.English.version.May.2022.pdf)
[Bibliography  French version May 2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/8693009/Bibliography.French.version.May.2022.pdf)
[Comment rechercher May 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8693010/Comment.rechercher.May.2022.docx)
[Comment rechercher May 2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/8693011/Comment.rechercher.May.2022.pdf)
[How to search May 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8693012/How.to.search.May.2022.docx)
[How to search May 2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/8693013/How.to.search.May.2022.pdf)
[Team English Version May 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8693014/Team.English.Version.May.2022.docx)
[Team French Version May 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8693015/Team.French.Version.May.2022.docx)
With all best wishes,
Sophie

**Comment by Hippodamie** [comment]
One modification in the files How to Search: please substitute
[Comment rechercher 27 May 2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/8772808/Comment.rechercher.27.May.2022.pdf)
[Comment rechercher May 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8772809/Comment.rechercher.May.2022.docx)
[How to search 27 May 2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/8772811/How.to.search.27.May.2022.pdf)
[How to search May 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8772812/How.to.search.May.2022.docx)
.

**Comment by Hippodamie** [comment]
New updated versions of How to Search in both languages: ready to download
[How to search June 2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/8975211/How.to.search.June.2022.pdf)
[Comment rechercher June 2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/8975212/Comment.rechercher.June.2022.pdf)
!

**Comment by Hippodamie** [comment]
Here are now up-dated the 2 files About LGPN-Ling
[ABOUT LGPN-Ling English June2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8978111/ABOUT.LGPN-Ling.English.June2022.docx)
[About LGPN-Ling French June2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8978118/About.LGPN-Ling.French.June2022.docx)
Ready to reedit.Thank you in advance.
Have a nice week-end,
best,
Sophie

**Comment by Hippodamie** [comment]
Genitive of the Suff -ς added.
[ABOUT LGPN-Ling English June2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8995417/ABOUT.LGPN-Ling.English.June2022.docx)
[About LGPN-Ling French June2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8995418/About.LGPN-Ling.French.June2022.docx)

**Comment by Hippodamie** [comment]
New up-dated How to Search.
Thank you for all,
best,Sophie
[Comment rechercher June 2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/8999610/Comment.rechercher.June.2022.pdf)
[How to search June 2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/8999611/How.to.search.June.2022.pdf)
[Comment rechercher June 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8999613/Comment.rechercher.June.2022.docx)
[How to search June 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8999614/How.to.search.June.2022.docx)

**Comment by Hippodamie** [comment]
Hi, Magdalena,

here are the Team files or rather Credits. 

[Team English Version May 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/9078803/Team.English.Version.May.2022.docx)
[Team French Version May 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/9078804/Team.French.Version.May.2022.docx)
With all best wishes,
Sophie

**Comment by Hippodamie** [comment]
[Team.English.Version.September2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/9542556/Team.English.Version.September2022.docx)
[Team.French.Version.September.2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/9542557/Team.French.Version.September.2022.docx)
Files up-dated.
Thank you in advance,
best,
Sophie

**Comment by Hippodamie** [comment]
[How to search September 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/9542736/How.to.search.September.2022.docx)
[Comment rechercher September 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/9542738/Comment.rechercher.September.2022.docx)
[Comment rechercher September 2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/9542739/Comment.rechercher.September.2022.pdf)

[How to search September 2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/9542737/How.to.search.September.2022.pdf)

**Comment by Hippodamie** [comment]
Here are the  About in both languages up-dated.
Thanks for all,
best,
Sophie
[ABOUT LGPN-Ling English September2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/9542860/ABOUT.LGPN-Ling.English.September2022.docx)
[About LGPN-Ling French September2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/9542862/About.LGPN-Ling.French.September2022.docx)
[About LGPN-Ling French September2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/9542863/About.LGPN-Ling.French.September2022.pdf)
022.docx)
[ABOUT LGPN-Ling English September2022.pdf](https://github.com/eXistSolutions/LGPN-ling/files/9542861/ABOUT.LGPN-Ling.English.September2022.pdf)

**Comment by Hippodamie** [comment]
![image](https://user-images.githubusercontent.com/16923546/189537219-954243f9-c1cf-4138-ab00-4a315078db4c.png)

Here is a picture of the team.

**Comment by Hippodamie** [comment]
![image](https://user-images.githubusercontent.com/16923546/189537433-b1530688-391c-4686-a9cb-6e923e5a6aac.png)

**Comment by Hippodamie** [comment]
The second one without the number of the slide!

**Comment by Hippodamie** [comment]
Dear Magdalena,

I was adding just at the moment this § (in yellow) to How to Search (and could add it in the FRench version too): it is about Statistics, a warning about the fact that numbers are not exact (but approximative) on LGPN-Ling since they do not include the variants, for example.
In my new § I was proposing the way to get the exact numbers: it is easy for number of Persons, since you have created the link to LGPN Database Search.
But if a user need **the exact number of Names made from a Base**, he has to open the LGPN Name Search website. It is what I explain in my new §.

Here is my question: would it be easy for you to  add a link so that we could switch also to the LGPN Name Search, directly when we are on LGPN-Ling? Maybe clicking on the base 1 or the base 2.
<img width="1137" alt="Capture d’écran 2022-09-24 à 09 53 15" src="https://user-images.githubusercontent.com/16923546/192087111-ead82041-0199-4245-8ea9-4c57867d92bb.png">

What do you think?
Thank you for your answer when you can,
best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

please, do not consider the last message on this issue #683.
Could you, please, put on line How to Search in both languages?
Thank you in advance,
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

I just re-wrote slightly (adding Trismegistos, for example) only the page How to read the analysis of a name in both languages and download the new version of both files (only for this very page).
Best,
Sophie
[How to search 25 October 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/9860533/How.to.search.25.October.2022.docx)
[Comment rechercher October 25 2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/9860536/Comment.rechercher.October.25.2022.docx)

**Comment by Hippodamie** [comment]
Dear Magdalena,

here are the files How to Search and Bibliography up-dated.
[Bibliography  English version January 2023.docx](https://github.com/eXistSolutions/LGPN-ling/files/10394217/Bibliography.English.version.January.2023.docx)
[Bibliography  English version January 2023.pdf](https://github.com/eXistSolutions/LGPN-ling/files/10394219/Bibliography.English.version.January.2023.pdf)
[How to search January 2023.docx](https://github.com/eXistSolutions/LGPN-ling/files/10394224/How.to.search.January.2023.docx)
[How to search January 2023.pdf](https://github.com/eXistSolutions/LGPN-ling/files/10394225/How.to.search.January.2023.pdf)
[Comment rechercher January 2023.docx](https://github.com/eXistSolutions/LGPN-ling/files/10394228/Comment.rechercher.January.2023.docx)

Could you please put them online?
Thank you in advance.
With all best wishes,
Sophie
[Comment rechercher January 2023.pdf](https://github.com/eXistSolutions/LGPN-ling/files/10394229/Comment.rechercher.January.2023.pdf)

**Comment by Hippodamie** [comment]
Dear Magdalena,
could you please for the special page How to read the analysis of a name, add the pop-up Constituents. See my addition in pink in the corresponding screenshots (English and French versions).
Thank you for inserting that too.
<img width="1106" alt="Capture d’écran 2023-01-19 à 10 10 25" src="https://user-images.githubusercontent.com/16923546/213401532-250c9dd2-3714-442b-9a8c-679f89172c6a.png">
<img width="1096" alt="Capture d’écran 2023-01-19 à 10 10 40" src="https://user-images.githubusercontent.com/16923546/213401591-abfb80d8-d8f6-48cb-8efd-6eefa7a24de0.png">

**Comment by tuurma** [comment]
All static pages are updated now, ready for review
