### ISSUE TITLE
To fix in the current status of the Search

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#684]
Dear Magdalena,

here is a file where is listed what is still to fix.
In preparation of our meeting.
Good week-end,
best,
Sophie
[To fix in the Search interface May2022.docx](https://github.com/eXistSolutions/LGPN-ling/files/8693038/To.fix.in.the.Search.interface.May2022.docx)

**Comment by tuurma** [comment]
outdated, closing
