### ISSUE TITLE
excessive slowness concerning catalogues

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#685]
Dear Magdalena,

just to remind.
Have a nice week-end,
best,
Sophie

**Comment by tuurma** [comment]
I managed to speed this up quite a lot and also changed the look and added some clearly marked shortcuts via pencil and list icons

In meanings:

<img width="1643" alt="image" src="https://user-images.githubusercontent.com/449468/194120749-93fcbaa7-49a6-4d1f-82a0-0a5b4a45ecc2.png">

In lexemes (please ignore the counts, screenshots are done on a smaller data sample):

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/449468/194121619-b7e05c98-afad-40a9-b39c-f00711a7de6d.png">

**Comment by Hippodamie** [comment]
Dear Magdalena,

it is wonderful all of what you added, including the criteria in the Filtering! Great!
When do you think you could put online the ‘How to Search?’ I mean is it now definitely stable or could the way to search change again, even a little, with for example this new access you just imput to Bases from the Catalogues?
I will have thus to add this new information in the file ‘How to Search’.
Would you like I add it for tomorrow?

Another point: as I wrote you coming back from Bordeaux where I spoke with Yanne Broux, we did not edit the Trismegistos ID for each name. Yanne told me that they could easily import all our ID into Trismegistos. Could we do the same, for the Names which have a file by them, as we did for LGPN Names? And not have to re-edit each name adding this additional  TM Nam ID?

Thank you for all,
with all best wishes,
Sophie

PS: I suppose it is also normal tonight no to be able to save anything and to see the grand total of  Names changing…😉

**Comment by tuurma** [comment]
Yes, sorry about it, but I needed to reindex again. Rest I'll answer
tomorrow

śr., 5 paź 2022, 21:53 użytkownik Hippodamie ***@***.***>
napisał:

> Dear Magdalena,
>
> it is wonderful all of what you added, including the criteria in the
> Filtering! Great!
> When do you think you could put online the ‘How to Search?’ I mean is it
> now definitely stable or could the way to search change again, even a
> little, with for example this new access you just imput to Bases from the
> Catalogues?
> I will have thus to add this new information in the file ‘How to Search’.
> Would you like I add it for tomorrow?
>
> Another point: as I wrote you coming back from Bordeaux where I spoke with
> Yanne Broux, we did not edit the Trismegistos ID for each name. Yanne told
> me that they could easily import all our ID into Trismegistos. Could we do
> the same, for the Names which have a file by them, as we did for LGPN
> Names? And not have to re-edit each name adding this additional TM Nam ID?
>
> Thank you for all,
> with all best wishes,
> Sophie
>
> PS: I suppose it is also normal tonight no to be able to save anything and
> to see the grand total of Names changing…😉
>

**Comment by tuurma** [comment]
Extracted the TM questio to https://github.com/eXistSolutions/LGPN-ling/issues/701

Please, don't update the "How to search" just yet, I may need to edit the English version a bit, and then you can align the French, ok?

**Comment by Hippodamie** [comment]
ok, Magdalena!
Best,
Sophie
