### ISSUE TITLE
Lexemes deletion (function remove) not working

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#686]
Dear Magdalena,

here is one of those I cannot remove.
Is it something I did not understand?
Thank you for your help.
With all best wishes,
Sophie
![Capture d’écran 2022-05-21 à 09 35 46](https://user-images.githubusercontent.com/16923546/169641754-295d9840-1153-4abf-ae10-efcaf16c6945.png)

**Comment by tuurma** [comment]
Fixed
