### ISSUE TITLE
Meanings deletions impossible: Remove function does not work

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#687]
Dear Magdalena,

I hope you are well.
Here is a liste of meanings we would like to remove, but remove function does not work.
If I click on the Meaning ID, boxes are already empty, but the meanings are still visible on the list, with the REMOVE.
So, we do not have the power to  do it by ourselves.
Could you please delete them all and make the function remove working?
Many thanks in advance for that.
With all best wishes,
Sophie
[Meanings à effacer_2022-05-22.docx](https://github.com/eXistSolutions/LGPN-ling/files/8771716/Meanings.a.effacer_2022-05-22.docx)

**Comment by tuurma** [comment]
Please, ID field **must not** contain special characters like `?/.,()*[] ` etc 

All the problematic meanings contained such characters.

<img width="622" alt="image" src="https://user-images.githubusercontent.com/449468/170742493-2809ad06-1b64-494c-b815-103ce86e666c.png">

<img width="988" alt="image" src="https://user-images.githubusercontent.com/449468/170742644-1e4c697e-f69e-4bb3-8487-16467290dcba.png">

Meanings. N’ont pu être effacés (références à la liste en anglais) :

a : 	340 aquilin ?
	341 aquline ?
b :	307 Boïske
	328 Both-
f :	  31  fat ?
	  33 fat- ?
	106 fight, combat
h :	176 high, lofty
	178 highest, loftiest
m :	192 Meriones
	201 Messene
	203 Messina
	209 Midas
r :	127 resourceful
	252 ruminating fish
s :	362 skin (made into a bag)
	530 sparrow- ?
t :	119 The so called Spring ?

**Comment by Hippodamie** [comment]
Totally sorry for that.
We are not supposed to do it again.
Did you repare all, since apparently I cannot delete that to rewrite them.

**Comment by tuurma** [comment]
Yes, all fixed

pt., 27 maj 2022, 18:52 użytkownik Hippodamie ***@***.***>
napisał:

> Totally sorry for that.
> We are not supposed to do it again.
> Did you repare all, since apparently I cannot delete that to rewrite them.
>

**Comment by Hippodamie** [comment]
Thank you so much.
