### ISSUE TITLE
Lexemes deletion

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#688]
Dear Magdalena,

I tried all I can to delete the ones you see: the dublet α_βο̄λια and also α_εργο, but it gave the bug you see.
Could you please fix it?
Many thanks in advance,
with all best wishes,
Sophie
![Capture d’écran 2022-05-25 à 17 58 49](https://user-images.githubusercontent.com/16923546/170306521-330e1790-df1d-4247-9c30-b2d62baf457d.png)

**Comment by Hippodamie** [comment]
No access neither to –(1) at the begining of the lists of lexemes, at the top at left.
![Capture d’écran 2022-05-25 à 21 23 52](https://user-images.githubusercontent.com/16923546/170351509-81ca31db-51b2-47a8-be09-f360c294b510.png)

**Comment by Hippodamie** [comment]
NO deletion possible niether for this one.
Could you please fix it?
Many thanks, best,
Sophie
![Capture d’écran 2022-05-25 à 21 26 06](https://user-images.githubusercontent.com/16923546/170352867-a264b6fd-3118-4c1a-abff-f607b04e6d9c.png)

**Comment by tuurma** [comment]
I fixed removing the lexemes but the page does not yet automatically refresh. I will put that in the summary issue and close this one.
