### ISSUE TITLE
Structure issue not previously told: to switch from facets to main search ‘by name’

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#690]
Dear Magdalena,

I do not know whether it is possible or difficult: but when we search through facets, and then try to call a name by the main search, we see the name in its list and can click on it, but after, we arrive on a window with nothing!
To get this name, we have thus to refresh, which is time consuming.
Could it be improved?
Thank you for that too, if possible.
Best,
Sophie

**Comment by tuurma** [comment]
Could you give me a specific case, i.e. what kind of facet query are you running and then for which name you have no results?

**Comment by Hippodamie** [comment]
For example,
I begin to click on Base hιππο in the facet;
-then,  about Ἄνδριππος name in the table, I would like to know if there is a reverse compound;
-so, I filter Base 2 ανδρο, and get Ἱππανδρίδας, which is great.
-now I de-click hιππο, to focus on ανδρο Βase2,  and it works: I get all!

It seems now it works very well. I think you improved something. Thank you!

The other troubles are in relation with names when we search one through main Menu. Sometimes after going out of the editor and refreshing, when we ask for another name, nothing happen, and we get someting blocked: for example, a few minutes ago, I was looking for Κυπροδάμας, and the Menu showed this very name and also Κυπρόδαμος; when I clicked on Κυπροδάμας, Ι got the blocked screen like. Βut the name exists and normally even if we edit it in the box for LGPN corrections, like here, it appears when we search it.
And once we are so blocked, if I type now Κυπρόδαμος, nothing happens again. And then, the only way is to refresh.
