### ISSUE TITLE
A new genitive for the suffix -ς

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#693]
Dear Magdalena,

we have a new Genitive for this Suff1: there was -(τ)ος, -(δ)ος
and could you please add: -(κ)ος?
Thank you very much.
I make the change too on the About versions,
best,
Sophie

**Comment by Hippodamie** [comment]
Please, wait! I have to check more before.
Best,
Sophie

**Comment by Hippodamie** [comment]
OK: I confirm!
Have a nice day, Magdalena.
All best,
Sophie

**Comment by tuurma** [comment]
Done
