### ISSUE TITLE
Issues to deal with

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#696]
Dear Magdalena,

I hope you are well.
I wrote a list of the issues to deal with.
I up-dated all files to download in the different top Menus. All is up-dated on Github.
Here is the list of issues.
Have a nice day,
with all best wishes,
Sophie
[Issues to deal with_2022-09-19.docx](https://github.com/eXistSolutions/LGPN-ling/files/9596634/Issues.to.deal.with_2022-09-19.docx)

**Comment by tuurma** [comment]
Mostly solved, others extracted into separate issues
