### ISSUE TITLE
Indexation: an error at the top of the ϝ list

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#703]
Dear Magdalena,

how is it possible this lexem comes at the top, with a rho after ϝ? It should be after 277.
Could you please fix it?
Many thanks in advance,
all best,
Sophie

![Capture d’écran 2022-10-12 à 09 36 38](https://user-images.githubusercontent.com/16923546/195279799-cb9ecc75-d2e3-4f9b-8904-0ce0cbdef903.png)

**Comment by tuurma** [comment]
Problem here is that the lexeme is written with regular F, therefore sorts in the beginning. I now change it to `(ϝ)ρο̄-σ(ο)`

<img width="994" alt="image" src="https://user-images.githubusercontent.com/449468/219883954-81019656-542f-4173-ac04-6b2a7c0f137e.png">
