### ISSUE TITLE
Informations pop-up

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#707]
Dear Magdalena,

we do not need in fact the informations pop-up at the top of the Lexis and Onomastics columns: it is clear enough by its title.

For the facets Informations pop-up, the following are unnecessary for the same reasons (they repeat the titles): so you can delete pop-up  and i. labels for:
-Last updated
-Abbreviation and TRuncation
-Bilingual
-Gender
Fictitious.
Thank you for all you already did,
With all best wishes,
all best,
Sophie

**Comment by tuurma** [comment]
done
