### ISSUE TITLE
About Warning mention: please, definitely not in the tables main page, but discrete!

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#708]
Dear Magdalena,

I have a little changed my mind since this afternoon.
I would prefer not to have this warning mention, even if written smaller and more discrete every time in any page when we search or edit! It would be a pity!
So, we have to find another place, more discrete to put it. Its best place would be at the beginning of an introduction: either at the beginning of About LGPN-Ling or at the beginning of the page ‘How to read the analysis of a name’. But the really best place would be at the beginning of About LGPN-Ling.
Or in a pop-up , but not visible at any moment, when we are moving on the main page. Or it could be at the bottom of the last facet (Last updated).
What do you think? Anyway, it cannot stay there.
All best,
Sophie

**Comment by tuurma** [comment]
Ok, moved it to the bottom of the facets. We can also add it to About

<img width="244" alt="image" src="https://user-images.githubusercontent.com/449468/200558964-93abb8f0-1cb7-44a7-b7dc-dd46aad5dfaf.png">

**Comment by Hippodamie** [comment]
Thus, could we please avoid it on the main page and factes band and have it only at the end of About? 

…. next one….
