### ISSUE TITLE
Display of References

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#711]
Dear Magdalena,
here are remarks listed by Matilde (and a screen-shot of a bug, below):
Among FACETS:
-Suffixes 1, 2, 3, 4 pop-up: correct S1 pop-up into Available forms of the inflectional Suffix 1; for the others S2, S3, S4 add. derivational
-BUG: there are many duplicates in the suffixes whenever there is () or /.

About Tables:
-when there are many informations and each is quite long, it is not very clear the separation between 2 different informations, see eg Onomastics of Arsinoē. How to make it clearer? Could we for example have a small indentation on the left for the layout between first line and the others of the same ref./explanation? AND, when we are in the Onomastics cell, could we have a difference of darkness of blue between each of the 3 levels of informations (dictionaries, linked Onomastics and Modern ref.)? 

That is it.
Thank you for all you fix next time,
with all best wishes,
Sophie

<img width="1415" alt="Schermata 2022-10-26 alle 13 43 44" src="https://user-images.githubusercontent.com/16923546/198049327-6a9b6e78-9cd9-475a-8a90-43bc3b85967c.png">

**Comment by tuurma** [comment]
Would this be better for the References? I introduced margin between entries and two kinds of bookmark icons for different types

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/449468/200556676-7172c68d-fc95-4513-8463-2f4da9e4fd95.png">

**Comment by tuurma** [comment]
Suffixes popups are also fixed

<img width="451" alt="image" src="https://user-images.githubusercontent.com/449468/200557517-dfbab14e-4854-45d0-bdab-2dac7dfd7259.png">

Duplicate suffixes I will extract into a separate issue

**Comment by Hippodamie** [comment]
Dear Magdalena,
I only come back now from teaching: thank you for all, but:
1. The idea could be good but the signs used are awfully looking: could we please have something not so visible, smaller and nice-looking? Rather small circles like screen-shot or even smaller? Or only small dashes, like:
+
and then:
-
-
-
We need light signs, almost invisible: to have the eyes which look only at the informations; in the other way we just do not want to look at them, it is totally disturbing!

2. About Warning: it does not work: too long in one only line: could you please put it in a small §? AND could you delete that: (lexical).
Look at the mess! Facets band hide the most of the main informations about Names. And main search is also hidden! Facets has to keep being a quite small band. And there is the superposition into the facets grey band of the white band with the titles of the columns of the table: could you please avoid such a superposition?
Could you please fix all of that? Thank you very much!

I look now at the other messages….

**Comment by tuurma** [comment]
Are these icons any better?

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/449468/200646198-42362ecf-222f-4128-a320-65cafaefccc0.png">

**Comment by Hippodamie** [comment]
Not quite: too visible and not really pleasant to see.
Could you please use something else quite discrete and small like ●/• ?
Or like what I proposed yesterday night:
+
-
-
-
-
Thank you very much,
have a nice day,
all best,
Sophie

**Comment by tuurma** [comment]
Ok, how about just filled or empty circles to signal which type of reference we are dealing with

<img width="570" alt="image" src="https://user-images.githubusercontent.com/449468/200771253-c0f9d9d7-5b6b-44a9-9d04-b2d24699a1cf.png">

**Comment by Hippodamie** [comment]
Quite good now, except the fact that you reverse the 2 types of dots in Lexis vs Onomastics (and perhaps we need 3 icons).
So what I propose is the following:
Lexis column:
at the top, quotation(s): black full dot;
then, dictionaries DELG, LSJ references with their links: empty(= white inside) dot. 
then, the Cf. modern bibliography: empty(= white inside) dot. 

Onomastics column:
Quotations and dictionaries references: the black full dot;
then, there are the Linked sources in Onomastics: what woudl be great would be to have a special sign like a very small and discrete arrow: ↔
below: modern authors bibliographic ref.: empty(= white inside) dot. 

Could you do that?

**Comment by tuurma** [comment]
At the moment there are 4 categories of references in total:

* Lexical and Onomastical Connections
  * Sources
  * References 
* Onomastics
  * Linked sources
  * Modern references

For these 4 categories I can easily use the icons, for the moment Sources and Linked sources get a full dot, while References and Modern references get an empty dot. Please, check on the LGPN-Ling website (with Shift+Reload first to make sure you see the latest version) and let me know if it's okay. If not, please try to make a screenshot of a single entry like Arsinoe and mark which entries should get which icons.

**Comment by Hippodamie** [comment]
Deat Magdalena,
a first question: the very small size of your previous model was perfect (of course not the current one).
The rest is correct: Thank you very much!
All best,
Sophie

PS: I do not work for a while, in case you had time to fix it. But maybe Matilde works.

**Comment by tuurma** [comment]
Please try reloading again, it should look like this:

**Comment by tuurma** [comment]
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/449468/200836748-75b393c1-b8ee-4383-a5c3-ee42d865092f.png">

**Comment by Hippodamie** [comment]
Dear Magdalena,

it is bizarre: I get it with private navigation but not with public. Now, I deteted all my previous navigations and got it also on public!
Thank you anyway! It looks clearer with those icons!
All best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

could you please deal with the so-called bubbles of explanations for Lexis and Onomastics columns, which are not at a good place (to put rather above Lexi and Onomastics Words, when we see them, not to hide the content of columns themselves)?

And why do we have not anymore visible the informations of Morphosyntax and Semantics columns?

Maybe are you currently on it?

Best, thank you for all you do,
Sophie
