### ISSUE TITLE
Greetings and planning

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#713]
Deat Magdalena,

I wish you all the best for you and for your whole family for this new year. Above all, a happy new year, as much as possible!
I juste up-dated files on Git-Hub (How to Search + Bibliography); and sent a few weeks ago a few corrections for the text of About LGPN-Ling.
Could you please set those online?

Last points to fix principally among facets:

- [x] 1. Column Morphosyntax (+ Genetics): could you please re-name it:  Bases Morphosyntax (PN Genetics). And in French: Morphosyntaxe des bases (génétique du NP). It is quite long but we are obliged to have this precise title. The current one keeps ambiguous.

- [x] 2. Could you please move Functions after Constituents? It is not at its logical place. Sorry for that.

> I put it into expanding section under Bases, right after Constituents

3. We currently have double Bases juxtaposed but the = sign and some others signs are missing: for example, we see hιπποhαρμο, hιπποακᾱ, hιπποαρχιᾱ, but we should see: (h)ιππο=(h)αρμο, (h)ιππο=ακ(ᾱ), (h)ιππο=αρχι(ᾱ)
4. Could you please clean all the doblets in suffixes (like: ᾱ/ης 1688 and ᾱης 1688)? So that we only keep the version of those labels with their slash or parentheses.

- [x] 6. Could you please rather write oui vs non in the French version for ‘Suffixe ou non’ AND for ‘Raccourcissement et troncation’?

6a. Εrgonomy: could we keep the ‘All’ clicked all the time we have chosen to use it and until we decide to un-tick it? For each item for which ‘All’ is available.  Currently, if we get all and tick a box, and then un-tick it, we lose the ‘All’ function: the system comes back to the small first selection. In fact in his everyday work, the user will quite often need ‘All’.
6b. A technical point about the opening of those not directly accessible facets: for example, Functions or Constituents: could you please improve in such a way that when we select ‘All’, we do not need to re-open ‘more’ but they keep visible?
6c. If we are  typing  a name through the Main Search, would it be possible to have all cleaned, included the facets, as soon as we have cleaned what we typed in the Main Search box, and to be able to begin another search, without having to refresh by Browse?

The rest is very well: so many thanks for that! 
The plan is to open the website this month: is it possible for you to do those last things in this schedule or not, and when if not?
I must say that we have the hudge control (every 5 years) of our laboratory ANHIMA in February, and it would be essential that they could see the website achieved and open. 
Thank you in advance for your answer,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
I marked the resolved issues in your comment above, remaining are the "Ergonomy" issues and doublets in Suffixes as well as handling of double bases

**Comment by tuurma** [comment]
Furthermore if I could ask you for translation of the warning text (at the bottom of the facets sidebar)

<img width="260" alt="image" src="https://user-images.githubusercontent.com/449468/213510850-494eb594-3ab1-4181-be6c-5cc521e44dec.png">

**Comment by Hippodamie** [comment]
Attention: LGPN-Ling est une recherche en cours. Actuellement (janvier 2023), seule l’analyse des noms de personnes dont les bases (lexicales) commencent par les lettres A à I a été entièrement revue.

Thank you for eveyrything,
best Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

a complementary note with a quick solution to change the (famous) Morphosyntax (+ PN Genetics):
could you please not change the title at the top of the column but rather develop a pop-up comment like you did for the following columns?
And thus, in the pop-up commentary; write: Morphosyntax of the Bases, but Genetics of the Name
French version: morpho-syntaxe des bases, mais génétique du

**Comment by Hippodamie** [comment]
**continuation of the previous message**:
French version: morpho-syntaxe des bases, mais génétique de l'anthroponyme.

Could you create another last pop-up message being able to appear (or not) at the top of the Suffixes column, with written:
English: Personal names suffixes
French: suffixes anthroponymiques
Thank you very much for this improvement,
with all best wishes,
Sophie
