### ISSUE TITLE
7 characters to fix in Suffixes 1 + Genitive List in About LGPN-Ling in both versions

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#716]
Dear Magdalena,

could you please fix the un readable characters in the Suffixes List given in About LGPN-Ling?
Here is the file (yellow marked): those special characters are only in IFAOGrec Unicode available for free online.
Thank you for your help on this subject.
With all best wishes,
Sophie
[Liste S1 + génitifs_About LGPN-LIng_7 characters to fix.pdf](https://github.com/eXistSolutions/LGPN-ling/files/10480747/Liste.S1.%2B.genitifs_About.LGPN-LIng_7.characters.to.fix.pdf)

**Comment by tuurma** [comment]
fixed

<img width="882" alt="image" src="https://user-images.githubusercontent.com/449468/216678002-776ed619-5cdc-4267-9b20-c9d86103b58d.png">
