### ISSUE TITLE
A mess in the presentation page of LGPN-LIng on LGPN site...

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#717]
Dear Magdalena,

would it be possible to remove what has been put online on teh LGPN-LIng page about Team?
Look at that
![Capture d’écran 2023-01-23 à 15 52 26](https://user-images.githubusercontent.com/16923546/214070286-6fd44569-2ee5-4945-bcc4-8846f46e080b.png)
Would it be possible to substitute that:
![image](https://user-images.githubusercontent.com/16923546/214070464-251c1986-6a83-41be-9d9b-93998d6b726c.png)

**Comment by Hippodamie** [comment]
I Mean:
Team, then:
Director, etc.

And in the following next Associates:
![Capture d’écran 2023-01-23 à 15 54 33](https://user-images.githubusercontent.com/16923546/214071022-702c5ec1-77c8-47bd-a917-87539b8f5ca8.png)

to remove people who are already quoted among the Team?
Or whom shall I  ask?

Thank you for your help,
with all best wishes,
Sophie

**Comment by Hippodamie** [comment]
Sorry: the title I meant was not ‘a miss’, but actually ‘a mess’ 😉

**Comment by Hippodamie** [comment]
!!!

**Comment by tuurma** [comment]
Chloe seems to have taken care of it.
