### ISSUE TITLE
Small dots buttons function: giving more space to better separate the 2 lexical Bases?

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#721]
Dear Magdalena,
best,
Sophie

![image](https://user-images.githubusercontent.com/16923546/214821174-3f6f273d-8118-450c-bb7b-7a2330e1a936.png)

**Comment by tuurma** [comment]
full view vs bibliography hidden

I think it's okay now

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/449468/216677339-960cadb9-dc8b-47aa-a84e-7cf43f1634cd.png">

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/449468/216677399-b9bc79e6-cfb3-4268-9620-885e49b302ca.png">
