### ISSUE TITLE
Concerning LGPN Name Search: an idea of improvement

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#727]
Dear Magdalena,

do you plan to make clickable the numbers of each volumes in front of a Name, in LGPN Name Search?
For example, for Diakaiarchos, if we could click also on the number of occurrences of Volume 1 or 2, and being directly redirected to only those persons in Database Search, it would be great!

Best,
Sophie

**Comment by tuurma** [comment]
I will absolutely do that in the new Database Search, but the old version doesn't allow to search by the volume number, unfortunately.

**Comment by Hippodamie** [comment]
When will be the new in service?
