### ISSUE TITLE
A change in the text of the first pop-up about Suffixes in Facets.

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#729]
Dear Magdalena,

could you please change the pop-up message coming about Suffixes in Facets:
currently, we have: all available suffix forms etc.
Could you please change it into:
all available anthroponymic suffixes, regardless of their position

Thank you very much,
all best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

if it is more simple for you, instead, could you please at the top of the Suffixes column, add PN et NP:
=> English: PN Suffixes
French: Suffixes NP

Thank you,
best,
Sophie

**Comment by tuurma** [comment]
Fixed, it will be visible after the server update

**Comment by Hippodamie** [comment]
Thank you very much,
best,
Sophie

PS: if you need I ask to Gérard Genevrois too, I leave in 20 minutes and be back only around 2 pm. Tell me.
