### ISSUE TITLE
Exportable Name record: correlative name place and size of the main name

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#733]
Dear Magdalena,

could you please put the correlative name under the main name in the exportable record?
![Capture d’écran 2023-02-05 à 11 45 13](https://user-images.githubusercontent.com/16923546/216814486-87cd85e3-9249-4c3a-bda4-1e6dff09cbc3.png)
Could you put it, in this example, after Central Greece and before the morphological analysis?
And could the main name be a little bit smaller?
Thank you very much,
all best,
Sophie

**Comment by tuurma** [comment]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/449468/219882857-892466bd-eb97-4c69-8d81-8edbb1a9d0dd.png">
