### ISSUE TITLE
a short warning to add about Geolinguistics Sorting in How to Search

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#734]
Dear Magdalena,

I hope you had a good weekend. 
Coudl you please add the following warning about sorting in the page How to Search.
Here it is.
It is important and we cannot keep silent on the subject. Sorry not to have thought about it before.
Thank you for your help,
all best,
Sophie
[Warning about Geolinguistics sorting.docx](https://github.com/eXistSolutions/LGPN-ling/files/10669177/Warning.about.Geolinguistics.sorting.docx)

**Comment by Hippodamie** [comment]
Dear Magdalena,

congratulations and many thanks for your new explanation about Statistics: perfect! I send you in anther issue the translation in French! I did not change anything! Please add your copyright at this very place!

But the Warning I sent you in this issue is as necessary as your additional words! Since, it is quite confusing too. Of course, because I made the choice ton group several names in only one record....
So, please, find here its improved version.
Could you please add it too? Many thankf in advance.
Best,
Sophie

**Comment by Hippodamie** [comment]
Bizarre, Git-HUb does not accept my file!

![image](https://user-images.githubusercontent.com/16923546/218045253-14d413af-b5a3-4717-a278-78b6df884ce8.png)

**Comment by tuurma** [comment]
Dear Sophie, to be honest, I am not convinced with the wording, even if we move it to the Filtering section, as agreed by email.

Here's the last version you gave me:

>  Warning: the Geolinguistics facet combined with the main filter requires to check the results. 
                Actually, because of the grouping in a single record of the Headname and its variants, the sorting had to 
                be conceived in extension: for example, by searching for the sequence *σσ* combined with 'Boeotian', 
                it produces any record containing a name labelled  'Boeotian', whether or not it contains itself this 
                geminate (e.g. Ἡγησίας, var. Thess. Ἁγείσσας vs Béot. Ἁγεισίας).

I don't think we should write that anything `requires to check the results`, since it suggests a mistake in searching. Myself I had to read it many times before I figured out what you mean ;-) 

I would rather say something like below:

> Warning: when filtering by name, the search pattern is matched not only against its **headname** (the earliest attested form) but against **all variants** of a name. For example, by searching for the sequence *σσ* combined with 'Boeotian', it produces any record labelled 'Boeotian', for which one of the name forms includes the *σσ*, whether or not the variant containing this very geminate is marked as Boeotian itself (c.f. Ἡγησίας, var. Thess. Ἁγείσσας vs Béot. Ἁγεισίας).

**Comment by Hippodamie** [comment]
Dear Magdalena,

ok, I rewrote it in French (juste one modification  in red, in your writing, if you agree):

Avertissement: en filtrant par le nom, la recherche a comme résultat non seulement le nom d'entrée (la forme la plus ancienne attestée) mais aussi toutes les variantes (plus récentes) qui ont été regroupées avec lui. Par conséquent, en cherchant, par exemple, la séquence *σσ* combinée avec 'béotien', il sort toute fiche comportant un nom labellisé béotien, qu'il comporte ou non lui-même cette géminée (e.g. nom d'entrée Ἡγησίας, var. Thess. Ἁγείσσας en face de Béot. Ἁγεισίας).

 

Warning: when filtering by name, the search pattern is matched not only against its headname (the earliest attested form) but against all its variants. For example, by searching for the sequence σσ combined with 'Boeotian', it produces any record labelled 'Boeotian', for which one of the name forms includes the σσ, whether or not the variant containing this very geminate is marked as Boeotian itself (c.f. headname Ἡγησίας, var. Thess. Ἁγείσσας vs Béot. Ἁγεισίας).


Where to put it? It has to be quickly findable…

Thank you for the rest, Iwill have a look to the other issues,
best,
Sophie

**Comment by Hippodamie** [comment]
Have a wonderful week-end, dear Magdalena!!!
All best,
Sophie
