### ISSUE TITLE
Logo Huma-Num

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#735]
Dear Magdalena,

about HUma-Num and Exist logos, why not to put them in this very place (see screen-shot), I mean under the Table of Contents?
Could you please do it?
Thank you,
best,
Sophie
![Capture d’écran 2023-02-07 à 18 01 56](https://user-images.githubusercontent.com/16923546/217312905-ea2b2c05-0849-4e32-b04d-792c4c46ad20.png)

https://www.huma-num.fr/supports-communication/
<img width="475" alt="Capture d’écran 2023-02-07 à 13 21 35" src="https://user-images.githubusercontent.com/16923546/217312549-15302ba1-c0c4-4e39-9921-0f9f0f95eb85.png">

**Comment by Hippodamie** [comment]
Dear Magdalena,

there must be, according to them, not only the logo, but the link to their site:
https://www.huma-num.fr/
Thank you in advance: it is really the most urgent.
All best,
Sophie

**Comment by Hippodamie** [comment]
In fact, could we have the logo also at the bottom, among the others, beside TEI publishers?
And could Exist be put there too?
Look at that.
![Capture d’écran 2023-02-09 à 08 49 55](https://user-images.githubusercontent.com/16923546/217750029-446a5505-23a0-4e82-b664-d66b605e6eba.png)
Best,
Sophie

**Comment by tuurma** [comment]
All done:

below the table of contents with a link, and also added to the strip of logos at the bottom.

I don't think eXist or eXist solutions are that interesting to add, but I did put TEI Publisher there, which is the open source project from which LGPN-Ling application benefitted the most.

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/449468/218139419-45292cf2-8616-456a-8975-e89fc9a6cbd0.png">
