### ISSUE TITLE
Public opening on LGPN-Ling and Huma-Num requirements: questions to you

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#737]
Dear Magdalena,

I hope you are all well. I wrote today again to Huma-Num to ask what was still to do (to answer to their own requirements) by you or me, so that the site be public on the web.
1) I asked you yesterday about their logo to put it visible on the Welcome page, and I asked you whether or not you would like to put also the logo of Exist Solutions.  I think their Logo is the first requirement for HUma-Num, and I regret not to have thought before, but I am like you usually too busy and it happens I forget things. So I would like they see this sign as quickly as possible for you. I think it is necessary to reopen the dialog with them.
2) Another requirement was what I told you a long time ago (Isidore) and I copy here what Helene Jouguet had wrote about it:
«Il n'est effectivement à priori pas satisfaisant de signaler les 30000 fiches de personnes dans ISIDORE. Il faudra voir à la fin de votre projet ce qui est possible, peut être simplement signaler votre site comme une source (et une seule)... Cela pourra se faire plutôt par le **sitemap xml**»
Did you already do that point [sitemap xml] (I mean at the moment when you transfered the site at Huma-Num)?

3) An essential another point is that they have to be confident with our site: and for example the white page Stephane told us yesterday is not a good sign, neither the vanishing Semantics.
So, could I ask you to do all that is necessary to be in accordance with Huma-Num FAIR requirements? Otherwise, the risk is we never are authorized to be public on the web. I think that for each of us, especially you, Gerard, Florian, Enrique, Matilde, Robert and I, it is essential that the result of such a hudge work be visible and usable for all kind of people, colleagues among others, who ask for it since many years now. The aim is to give all kind of people access and not to keep it for us. Even if it keeps a work in progress for years.
I know how you are busy. I am the last person who could forget it.
Could you please answer and help?
All best,
Sophie

**Comment by Hippodamie** [comment]
Dear Magdalena,

is it possible you reference LGPN-Ling on the web or what and how shall I do?
All best,
Sophie

**Comment by tuurma** [comment]
I just added a link to LGPN Name search, which should already help with LGPN-Ling being discovered. I also added the sitemap


<img width="1218" alt="image" src="https://user-images.githubusercontent.com/449468/218145757-9f20eee4-fc33-4155-b0b7-950d71948cc4.png">

**Comment by Hippodamie** [comment]
Wonderful,
thank you very much!
Best,
Sophie
