### ISSUE TITLE
A display problem in the Lexicon facet for the name Thorykanos

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#753]
Dear Magdalena,
I hope you are well.
I did at first a mistake when I typed the Logeion http ling in the wrong box (box details). Then, I fixed it. But the http address is still on display in the Lexicon facet for this name.
Could you please fix it or tell me how I can do it by myself?
Thank you very much in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
I see the link was "doubled", now fixed

<img width="654" alt="image" src="https://github.com/eXistSolutions/LGPN-ling/assets/449468/7b071ca1-7310-4783-a515-0a404de3293d">
