### ISSUE TITLE
Pasithoos to delete, please

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#754]
Ηι, Magdalena,

how are you?
Could you please delete the following file (Pasithoos)?
Thank you very much in advance,
have a nice week-end!
All best,
Sophie
![Capture d’écran 2023-08-25 à 21 57 30](https://github.com/eXistSolutions/LGPN-ling/assets/16923546/4e73235a-f040-4f1b-bcd6-cd95cd83859b)

**Comment by Hippodamie** [comment]
Hi, Magdalena,

could you please delete Konges too?
Thank you,
best,
S

**Comment by Hippodamie** [comment]
Hi, dear Magdalena,
could you please delete Kōris?
Thank you very much,
all best,
Sophie

**Comment by Hippodamie** [comment]
The same, please for Kosōn.
Thank you in advance,
best,
Sophie

**Comment by Hippodamie** [comment]
Hi, dear Magdalena,

Zopyro file is twice. Could you please delete one of them?
Thank you in advance,
with all best wishes,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

I only see one Zopyro. Do you mind checking again? The others are now deleted.

**Comment by Hippodamie** [comment]
Dear Magdalena,
here is what I see right now!
Thank you very much!
All best,
Sophie
