### ISSUE TITLE
A bug on the lexeme καλλυνθο, meaning Kallynthos

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#758]
Dear Magdalena,

I hope your are well. I think Gerard did a mistake in the meanings of the καλλυνθο lexeme: he wrote in the left, a parenthesis, which is forbidden (kal(l)ynthos_    The rest is ok. Thus no meaning comes; but null!
Could you please fix it?
We should have written: Kallynthos_presumed_toponym
Sorry and thank you in advance,
all best,
Sophie

**Comment by tuurma** [comment]
Dear Sophie,

I fixed the problem with meaning.
Gerard's mistake was also to add unnecessary space to the lexeme identifier, this happened for καλλυνθο and 29 others. I fixed that too.
