### ISSUE TITLE
Link beteen root and its structural value

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#80]
Dear Magdalena,
After a discussion with Sophie, it is clear that, after the introduction of the concept of Participle (P) each root will have only one structural value (eg. N, Adv or P) and this will be the same regardless of the name where it appears.
This means that the stuctural value caracterization has to be bound to the root in the same way the 'meaning' is.
Is it possible to add in the small interface where we edit the meanings of a new root the following elements, in order to have the value sticked to the root once for all, as we do with the menings?
Participle Noun Adjective Pronoun Adverb
The interest of doing this is double: We will avoid mistakes and the semantics section will be automaticallly populated when we load a known rooot, as this is already the case with the meanings.

**Comment by tuurma** [comment]
Looking at proper TEI structure for it at the moment.

**Comment by tuurma** [comment]
My first suggestion would be to encode morpheme entries in TEI like this, unfortunately it is not valid TEI:
```
    <category baseForm="huβ" ana="#hump">
        <desc type="function">N</desc>
        <catDesc>(h)uβ</catDesc>
    </category>
```

**Comment by tuurma** [comment]
But just putting @ana on `<catDesc>` should do the trick
```
    <category baseForm="huβ" ana="#hump">
        <catDesc ana="#N">(h)uβ</catDesc>
    </category>
```

**Comment by tuurma** [comment]
still work to be done on the main form & visualization, but function selection added to subform

**Comment by edouardchiricat** [comment]
Thank you so much, Magdalena. You did it!

**Comment by Hippodamie** [comment]
Dear both,

I just discover the work of today and it is incredibly wonderful : it progresses « à pas de géant ». Many very CONGRATLATIONS to both of you, Magdalena and Edouard !!!
I watch it (visualisation and edit interfaces) very carefully and read all your messages tomorrow.
Good night !
Best,
Sophie

**Comment by edouardchiricat** [comment]
Wonderful, Magdalena! Thank you!

Édouard
