### ISSUE TITLE
interface failing to add a second new root (R2)

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#82]
When trying to input a new name whose roots are not yet recorded: 
1. for the first root the input windows opens; data are input, then when saving there is a message: Failed to save data. Nevertheless, the data are saved and the meanings are populated in the main input interface.
2. When trying to input a second new root in the same name, the + button doesnt work; it fails to open the small root editing interface.

**Comment by tuurma** [comment]
thanks for testing, Edouard, will look at it during the afternoon

**Comment by edouardchiricat** [comment]
After several attempts, I managed to enter that name (Againētos). But the second root is not visualized (I had an error when I've tried to save it, but the same thing happened for the first root); no meanings appear on the visualisation, even if the meanings of the first root appear on the input interface.
What might this be?

**Comment by edouardchiricat** [comment]
After several attempts, I managed to enter that name (Againētos). The first root is visualized (I had an error when I've tried to save it, but in the input interface the meanings have been loaded). For the second root, I had the same error saving it as in the case of the first one; the difference is that no meaning has been loaded in the input interface. Only the first root appears in the visualisation interface and no meanings at all.
What might this be?

**Comment by tuurma** [comment]
Looks like there was a hiccup saving the meanings of αιν, I managed to finish the data entry for this name without trouble, but the message that saving of the meaning failed when in fact it succeeded persists and is quite annoying. I'll try to do something about it and will get back.
