### ISSUE TITLE
saving subform results in 'fail' message

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/LGPN-ling#83]
though in fact it succeeds

**Comment by tuurma** [comment]
moving to next milestone as most pressing issue is dealt with

**Comment by tuurma** [comment]
@patczar could you take a look at this perhaps, why is it returning an error when in fact save works without trouble?

**Comment by patczar** [comment]
Do you mean the root/meanings subform?
If so, I can't reproduce it. Maybe it's been fixed (by accident ;)) in the meantime? Or please, write me how you're getting this message.

**Comment by patczar** [comment]
There was a real bug in saveMorpheme.xql - storing new entries where not all 3 translations were provided, fixed it. I also encountered some permission problems - but this is probably more general.
I'm closing this. Open if something is still wrong.

**Comment by tuurma** [comment]
Well spotted the empty @label issue @patczar. Thanks.
