### ISSUE TITLE
Have input a name without any probem; still, the 'meanings' do not show up in Vizualisation

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#84]
I input Agazalos, everything went ok, but there is no meaning in Vizualization.

**Comment by tuurma** [comment]
![screenshot 132](https://cloud.githubusercontent.com/assets/449468/12760659/52e0a47e-c9df-11e5-9a40-b3c8eb526da8.png)

**Comment by edouardchiricat** [comment]
Many thanks indeed, Magdalena

Édouard

**Comment by tuurma** [comment]
some trouble with this on Agasthenēs, meanings for second root are still not displayed
![screenshot 133](https://cloud.githubusercontent.com/assets/449468/12763773/313a9b18-c9ee-11e5-9996-3b0ccc1ef28c.png)

**Comment by edouardchiricat** [comment]
I think the problem comes from the fact that the meanings are not properly
saved.

Édouard

**Comment by tuurma** [comment]
Checked that, they are saved properly, the issue must be just in display.

**Comment by edouardchiricat** [comment]
Good luck in finding the cause, then!

Édouard

**Comment by edouardchiricat** [comment]
Dear Magdalena,
In the entry Ἀγαθοβούλα, neither the root αγαθ, nor the root βολ (with
macron) have theri meanings automaticaly loaded in the input interface. I
have even tried to change the order of the meanings (this time, they are in
the correct order), apparently they have been saved, but even after doing
that, they don't show up in the Input Interf.

Édouard

**Comment by edouardchiricat** [comment]
By the way, I went into Oxygen and I saw that it refuses to validate both
omicron + latin macron and my glyph omicron+Greek macron. Do you think that
this might be the problem?

Édouard

**Comment by edouardchiricat** [comment]
There is still an issue in there. The meanings should be visualized in the order they have been input: will, counsel, Council. But on the visualization page, it's the other way around: Council, counsel, will!

**Comment by edouardchiricat** [comment]
Dear Magdalena,
There is still an issue in there. The meanings should be visualized in the
order they have been input: will, counsel, Council. But on the
visualization page, it's the other way around: Council, counsel, will!

Édouard
