### ISSUE TITLE
How to search when there is a macron (or not) or even both brevis&macron superposed

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#86]
It depends wether the user will be able to enter the letters by himself (truncation function, from the 1st box Greek name of the Advanced Search) or will have an autocompleted menu at his disposal (as, I suppose, in the boxes Constituent & Radical, what would be actually the better solution).

If he types any letters (even corresponding to a Root with macron or such) in the box Name, he will have as answers all the names made with those letters.
If he wants to search by Roots and if there is an autocompleted list, no problem : macron etc. will be already on certain Roots of the List.
The same for the Constituents List.
But if there was no List proposed, he would have to type himself and would of course not know that there is a macron, for ex. on βολ. In this (bad) case, you should create links between "his" βολ and the βο̄λ entered by us in our linguistic Database.

**Comment by edouardchiricat** [comment]
There will be a Google search-like list displaying the possible roots after
one tapes one or two letters in the box.

Édouard
