### ISSUE TITLE
Auto completed Lists of Roots and Constituents

### ISSUE THREAD

**Issue by Hippodamie** [eXistSolutions/LGPN-ling#88]
The idea is that as soon as we identify a new Constituent and a new Root, we would be able to enter/type it (with macron& so on) in the List (once for ever), that will be used then, not only for our whole Edit work (because we will meet the same roots many times during our work), but also for the future Search of the users.

Thanks.
Best,
Sophie

**Comment by edouardchiricat** [comment]
Bien entendu, c'est ce qui est prévu.

Édouard

**Comment by tuurma** [comment]
We have this functionality on Roots in entry form so far. I guess we can add similar one on Constituents there. As for search, of course we can do the same, but please register separate issue for that (as it goes into different milestones).
