### ISSUE TITLE
Trying to acces Ἀγάνωρ 	Aganōr in order to modify it: "failes to load data"

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#95]

**Comment by tuurma** [comment]
Looks like it's caused by the fact that Greek form was entered as Latin and vice versa

**Comment by edouardchiricat** [comment]
​Probably. And I wanted to open it and correct that....​

Édouard

**Comment by tuurma** [comment]
Fixed that one manually, but keep the issue open, need a mechanism to deal with that

**Comment by edouardchiricat** [comment]
Maybe a 'Delete' option next to each entry?

Édouard

**Comment by tuurma** [comment]
Delete option will be surely necessary anyway from time to time! Good point!

**Comment by tuurma** [comment]
Closing now that 'delete' option is in place.
