### ISSUE TITLE
Order of the meanings in visualization is changed

### ISSUE THREAD

**Issue by edouardchiricat** [eXistSolutions/LGPN-ling#96]
The meanings should be visualized in the order they have been input: e.g. will, counsel, Council. But on the visualization page, it's the other way around: Council, counsel, will!
This is a systemic problem, it happens systematically.

**Comment by edouardchiricat** [comment]
Dear Magdalena,
Please reopen this issue. In Agathoboula, the meanings are displayed
as "advice,
will, Council" instead of "will, advice, Council"

Édouard

**Comment by tuurma** [comment]
Did you try to refresh perhaps? Here's screenshot from showcases
![screenshot 136](https://cloud.githubusercontent.com/assets/449468/12856525/45b18af6-cc3d-11e5-964f-edde32a525d7.png)

**Comment by tuurma** [comment]
sorry, you are right, will check

**Comment by tuurma** [comment]
uploaded newest build et voila
![screenshot 137](https://cloud.githubusercontent.com/assets/449468/12856665/e7848658-cc3d-11e5-9b2f-a8097365df9d.png)

**Comment by Hippodamie** [comment]
Well done !
